:PROPERTIES:
:ID:       75e58649-69d0-4161-ada7-5051ce608446
:END:
#+title: 贵州润鑫能源有限公司物资采购人员行为准则

为加强采购管理，规范采购人员行为，提高采购人员素质，特制定本准则。本准则是本公司物资采购人员（包括生产、生活、基建、维修、设备等物资采购人员）必须遵守的准则，是规范物资采购人员言行的依据，是评价物资采购人员言行的标准。全体采购人员应从我做起，从本岗位做起，自觉遵守行为守则，共同塑造本公司良好的企业形象。
* “爱岗敬业”。物资采购人员要热爱本职岗位工作，在本职岗位上尽心尽力、尽职尽责，全身心投入采购工作。认真钻研采购业务，干好本职工作。
* “诚实守信”。物资采购人员做人、做事、干工作要诚实守信、言行一致、做老实人、说老实话、办老实事，不弄虚作假、不欺上瞒下，在具体的采购工作中，严格地履行好自己的权利和义务，自觉地避免各种欺诈、串通、隐瞒等等不法行为的滋生，切实地保障公司权益。
* “廉洁自律”。在采购活动中，物资采购人员要清正廉洁，自觉构筑思想防线，遏止和抵制各种违法乱纪行为。物资采购人员要自我约束、自我规范、自我控制、防微杜渐，自觉树立高尚的觉悟、良知和道德水准，自觉增强抵制不正之风侵蚀的能力．敢于同一切违法乱纪行为作斗争。
* “客观公正”。“客观公正”是采购人员的职业灵魂。物资采购人员在实际工作中，要公平正直，没有偏袒，不搀杂个人的主观意愿，也不被他人的意见所左右；对所有的供应商都一视同仁，在具体的评标活动中，要严格按照统一的评标规则和标准确定中标或成交的供应商，不得有任何主观倾向，以切实维护各供应商的切身利益。
* “坚持原则”。物资采购人员在其采购活动中，要严格依照规定的操作程序和法定的依据进行操作，依法办事，不以自己主观或他人强加的意志所转移。
* “优质服务”。物资采购人员要时刻树立“优质服务”的工作态度，对来自于任何地区的供应商都要做到态度温和、语言文明、尊重事实、谦虚谨慎。在实际工作中，以理服人，尊重事实，心平气和地解释和沟通，为基层单位服好务，为供应商服好务，圆满地完成企业采购任务。
* “热爱企业”。物资采购人员以企业发展为己任，牢记企业宗旨和目标，维护企业利益，信守企业精神和理念，执行企业规章和制度，维护企业信誉和形象，致力于企业改革与发展。
* “竭诚奉献”。物资采购人员要树立职业荣誉感，忠于企业，献身企业，甘愿为企业奉献自己的才华。有压力感、紧迫感和危机感，有强烈的团队意识和群体观念，能够将自己的利益与集体利益紧密联系在一起，将自己的行为和集体行为牢固凝聚在一起。
* “知法守法，依法行事”。在日常生活和工作中，物资采购人员应牢固树立法律意识，注意学习法律，遵守法律、法规，维护法律尊严，做守法、用法的模范。依法制定规章制度，开展工作。
* “公平竞争，维护形象”。同业竞争不应超越法律界定、约束和限制的范围。为确保竞争有序，维护企业诚实守信的形象，物资采购人员应时刻坚持公平竞争的职业道德。物资采购人员任何时候不得利用职权，向供应商提出额外或无理要求，即使供应商出于对员工服务或员工个人的感谢，主动提出以某种形式表达心意，也不得收取供应商任何好处。
* 本准则由供销科负责解释，自经理办公会议审定通过后施行。
