:PROPERTIES:
:ID:       b6ac06e5-fd4f-4789-9069-7622182aca41
:END:
#+title: 锚杆支护工安全操作规程
* 一般规定
** 锚杆支护工必须通过培训考试合格，持证上岗。
** 锚杆的孔深和孔径应与锚杆类型、长度、直径相匹配，在作业规程中应明确规定，金属锚杆的杆体在使用前应平直、除锈和除油。
** 安装锚杆时，当围岩为块状或破碎岩石时，锚杆轴线与巷道的轮廓面的夹角应≥75°；当围岩为层状岩石时，锚杆轴线与岩体主结构面或滑移面的夹角应≥75°；当岩体主结构面与水平面夹角为-15°～+15°时，不在此限。
** 锚杆孔内的积水和岩粉应清理干净。
** 锚杆尾端的托板应紧贴岩面或初喷面，未接触部位应背紧。宜用力矩搬手拧紧螺帽，扭矩应不小于设计规定。作用于同一范围内的各锚杆螺帽的扭矩差，不宜超过设计值的10% 。
** 锚杆的抗拔力最低值不小于设计值的90%。
* 操作注意事项
** 打眼前首先要“敲帮问顶”、检查作业场地的安全状况，如发现顶板破碎有危岩、片帮等不安全因素时，必须先处理完毕后再打眼。
** 锚杆的间距、排距按照作业规程的规定，用尺量标记定位，顶板破碎处，适当加大锚杆密度。
** 打眼时，要严格控制钻孔深度，深度要小于锚杆长度60mm～80mm，防止钻孔过深过浅。钻孔打好后，用锚杆体送到锚杆眼底检查锚杆眼孔是否畅通和孔深是否合格，不合格的钻孔必须重新补打。
** 每个锚杆孔在钻好后，应用压风吹扫干净钻孔内岩屑、煤（岩）粉和积水，以保证树脂胶泥固化后，把岩石与锚杆胶结在一起，起到锚固作用；没有清理的锚杆孔严禁安装锚杆。
** 树脂锚固剂使用前，要进行检查，发现失效（结块或变硬）的锚固剂不能用。
** 安装时，启动安装机升降器，用杆体锚头将锚固剂缓缓送入孔底，待锚固剂前端刚好接触孔底时，启动搅拌器全速旋转搅拌同时启动搅拌计时，升降器匀速将杆体推进到孔底。搅拌时间为8～15秒。
** 待达到搅拌时间后立即停止搅拌，但安装机升降器维持上升状态直到卸下安装机，搅拌结束卸下安装机前应在孔口将杆体楔住，在等待时间10～60秒之前禁止杆体位移和晃动，达到等待时间后即可上紧螺母和托盘。
** 树脂锚杆的安装操作应一次完成，途中禁止停息后二次完成安装。
** 锚固剂表面在使用前不得沾有油垢，若沾染上油垢可用干净布片、纸壳等擦拭干净后再使用。
** 锚固剂在装卸运输过程中，要轻搬轻放，防止摔撞，严禁放在有淋水的地方。对未用完的锚固剂必须装回用塑料桶或箱内封闭好，以保证锚固剂的质量。
