:PROPERTIES:
:ID:       e6b574cc-71c4-4e19-9850-21572043d085
:END:
#+title: 液压支架安装、撤除工安全操作规程
* 一般规定
** 液压支架安装回撤工必须经过培训、考试合格后，方可上岗操作。
** 第一组支架安装位置要根据《综采工作面设备布置图》或测量部门给定的尺寸确定。
* 液压支架的安装程序
** 采用边扩帮边安装的方法进行，从下往上依次逐架进行安装。
** 支架调向与安装：
*** 支架调向之前，调向空间的单体柱必须改好，不允许有任何障碍物，且调向空间必须支护牢固。
*** 支架调向之前，采煤机必须开至离安装点往下10m处，并将采煤机和采面刮板输送机停电闭锁，派专人看守开关。
*** 支架调向之前，离轨道侧面到采面刮板输送机必须有1.2m长的调向空间，若调向空间不够，必须采用单体柱或支架推移板推溜至煤壁。
*** 支架调向时，不得撞倒单体柱。
*** 需要改柱时，必须及时打上临时支柱，严格按照先打后拆的方式进行。
*** 支架调向时，所有人员必须躲开绞车绳及钩子的反弹范围，绳头、滑轮与绞车所形成的三角区内严禁有人。
*** 穿大梁时，必须先打上临时支柱，撑住所抬的大梁。大梁穿好后方可撤换调向空间的支柱。
*** 支架安装好以后，必须检查是否符合安装标准，合格后方可进行下一架的安装。
*** 支架调向安装好后，及时将伸缩梁伸抵煤帮。
* 液压支架的撤除
** 液压支架的撤除顺序：从下往上逐架进行撤除。
** 液压支架的回收方法：
支架在迎头降架及回收面上出口调向过程中，调向绞车和滑轮及支架底座之间形成的三角区域内严禁有人员，必须将回收面迎头和三角区域内的所有作业人员撤到调向绞车往上（外）10米以外的安全位置，且绞车司机前方必须有可靠的防弹网作安全防护，调向过程中指挥人员必须用口哨或电铃信号进行指挥支架调向。
*** 回收第一个支架的工序要求
- 先利用工作面内的调向绞车和远距离操作单体柱互相配合将2#支架拉出调向与煤壁平行以后，在2#支架的原位置上采用2棵4.2米长的工字钢梁和单体柱互相配合支设成“一梁四柱”的形式支护顶板，工字钢梁的间距为750mm，单体柱的柱距为1000mm，单体柱支设迎山有劲，并用8#铁丝绑好防倒绳。
- 待2#支架牵引运输到上出口调向后再调向回收1#支架，回收1#支架之前必须先将下尾巷和下端头原来采用单体柱和铰接顶梁的支护替换搭设成木垛进行加强支护下尾巷的顶板，同时支设在2#支架位置的所有单体柱进行二次注液，保证1#支架能够顺利的抽出调向。
- 1#支架抽出调向后，同样在1#支架的原位置采用2棵4.2米长的工字钢梁和单体柱互相配合支设成“一梁四柱”的形式支护顶板，工字钢梁的间距为750mm，单体柱的柱距为1000mm；在支架前探梁前方的顶板上采用单体柱和2.5m长的工字钢梁互相配合支设成“一梁三柱”的形式支护顶板，与4.2米长的工字钢梁互相交错支护，工字钢梁的间距为750mm，单体柱的柱距为800mm，单体柱支设迎山有劲，并用8#铁丝绑好防倒绳。
- 从3#支架开始往上每回收一个支架，从下往上依次回收2棵工字钢梁支护在已回收的支架位置上，后方的顶板自行下沉。
*** 回收其它支架的工序要求：
- 回收支架前必须先将被回收支架上侧的液压支架和下侧支护的单体柱进行二次注液，保证顶板支护安全可靠。
- 回收支架前首先将被回收支架前探梁上原来支护的半圆木用下侧已支护的2.5m长的工字钢梁从下往上依次逐架回收2棵替换，并对煤帮柱进行供液升起支护工字钢梁。
- 回收支架时先将支架在原位置上缩到最小高度，同时将侧护板油缸和底调油缸收回，并拆除被回收支架与上一架连接的供回液管路，改接成单独的供液操作支架，并堵好上一架的堵头；然后使用回收面上的调向绞车和上一架支架顶梁上吊挂的一台10吨滑轮及支设在被回收支架下侧采用远距离操作阀供液控制的单体柱进行互相配合将支架抽出调向，单体柱支设在被回收支架下侧护板的销轴孔内用双股8#铁丝绑好防倒绳。
- 支架抽出调向后从下方靠近采空区侧依次往上回收2棵工字钢梁和单体柱支护在已回收支架的位置上，工字钢梁的间距为750mm，单体柱的柱距为1000mm，支设成“一梁四柱”的支护形式，单体柱的三用阀和柱把手必须垂直于煤壁方向，后方的顶板自行下沉。
- 支架抽出调向与煤壁平行后先用Φ26×92mm的大链将已调向的支架拴挂在上一架未回收支架的顶梁上防止已调向支架下滑。
- 支架抽出调向后及时连接供液管调整支架的几何尺寸并锁住侧护板以后拆除供液管，用Φ26×92mm的大链和正规连接器将主绞车钢丝绳鸡心环与支架底座龙门架进行连接，准备往上牵引支架。
- 支架牵引运输到上出口平台上停稳后，将主绞车的钢丝绳换绳拴在支架的尾梁上，将装车站上JH-20A型绞车的钢丝绳拴挂在支架的底座上与上出口主绞车相配合将支架调向在上出口往外的巷道内调正，然后拆掉主绞车钢丝绳，用装车站上的JH-20A型绞车将支架拉到装车站上进行装车。
- 待支架牵引到回收面上出口调向稳固好以后方可进行迎头支架的回收工作，严禁回收面上牵引运输支架和迎头调向回收支架工作平行作业。
- 在回收面内支设的单体柱不能影响支架的调向，保证支架调向时有足够的调向空间，若有影响的单体柱必须提前整改处理。
*** 回收最后一架支架工序要求：
- 随着回收面上支架往上回收到最后一个支架时，必须先将上出口的主绞车回收，然后在上出口的抬棚正中央搭设一个木垛，同时用单体柱支护搭在尾架上的抬棚工字钢梁，对上出口支设抬棚的所有单体柱和尾架下侧支护的所有单体柱进行二次注液，保证上出口支护安全可靠，在抬棚下搭设的木垛和支护的单体柱都不能影响尾架的抽出。
- 尾架的回收采用装车站往外的JH-20A型绞车直接从原位置抽出来拉到上出口往外再进行降架锁侧护板，尾架的位置先用工字钢梁和单体柱进行支护，待回收上出口的时候一起回收工字钢梁和单体柱，如果尾架回收后上出口压力大，顶板下沉量明显增大时可搭设木垛进行加强支护。
