:PROPERTIES:
:ID:       692ef7a7-a835-40d8-9193-36669599cb3c
:END:
#+title: “一通三防”专业技术管理制度
* 矿总工程师负责“一通三防” 、瓦斯抽采技术业务管理工作，对防止“一通三防” 、瓦斯抽采事故负技术责任。
* 矿井必须建立健全“一通三防”、瓦斯抽采技术管理体系，设矿总工程师一名，专职通风副总工程师一名，下设通风科、各队组；根据矿井瓦斯治理需要配齐各级工程技术人员；各采掘队组技术员负责本队组“一通三防”技术管理工作。
* 建立健全各级管理人员和技术人员“一通三防”工作责任制，做到各级人员分工明确、到位、不错位、不越位。
* 每月至少召开一次“一通三防”专题会议，矿各有关队组负责人参加。通风例会要做好记录备查。
* 各类“一通三防”、瓦斯抽采的设计、方案、规程、措施、报告、制度、计划等必须严格按程序进行编制和审批，严格执行上级部门安全技术措施审批制度。
* 建立健全具有矿特点的“一通三防”、瓦斯抽采的技术管理规范，明确技术标准，技术管理程序，按既定的程序进行方案、安全技术措施、作业规程、操作规程等技术文件的设计和编制。
* 煤矿生产过程中，必须保证“一通三防”、瓦斯抽采技术工作的独立性，不能用管理代替技术，总工程师要协调、决策“一通三防”、瓦斯抽采的技术工作和“抽、掘、采”衔接工作。
* 根据矿井“一通三防”规划，超前进行矿井通风、抽采能力衔接建设，按照现有的瓦斯治理技术水平和设备能力，留足时间和空间，超前抽采瓦斯，科学合理地确定矿井生产规模，有效降低瓦斯含量和瓦斯压力，预防重大瓦斯事故发生，实现矿井本质安全型生产。
* 对巷道贯通、系统调整、反风演习、阻力测定、瓦斯排放、预防突出、瓦斯鉴定、火区启封、备用主扇、备用抽采泵、备用监测主机系统改造检修等“一通三防”工程，必须成立以矿总工程师为具体负责人的领导协调指挥小组，加强现场的协调指挥。
* 采煤工作面提高单产、采用放顶煤回采工艺、增加采掘工作面数量，必须由总工程师组织技术论证，在通风系统可靠，瓦斯、火灾、煤尘防治技术有保障的前提下实施，严禁超通风能力生产。
* 各类“一通三防”文件、规章、措施、计划、图纸、报告、报表（旬、月、季、年）、记录、台帐、牌板、卡片等技术资料必须按规定及时进行填绘、更新、完善、上报、归档保存或注销，填写内容真实、齐全、准确、清楚。
* 各类 “一通三防”文件、规章、措施、计划、图纸、报告等技术资料按照规程措施要求贯彻学习，各队组、队长负责内人员的贯彻学习。
* 建立健全“一通三防”仪器仪表（光学瓦斯检测仪、便携式瓦斯检测仪、测尘仪、风表等）的保管、发放、维修、调校、鉴定及使用台账。光学瓦斯检测仪、便携式瓦斯检测仪等仪器仪表必须按规定进行检定，保证仪器的正常使用。
* 加强“一通三防”管理人员、工程技术人员和各岗位人员的业务技术学习、培训、考核，开展技术比武、竞赛等，提高工作水平。
* 积极组织进行“一通三防”技术改造、革新和新技术、新装备、新工艺的研究、试验、推广和应用，保证职工的生命和健康安全。监督检查各项“一通三防”规程、措施、计划、方案、制度的执行和落实情况，鼓励工程技术人员、管理人员和职工进行和参与“一通三防”的技术创新、研究和推广应用工作。
* 规程措施的贯彻学习：
** 通风科负责人向职工贯彻学习有关 “一通三防”的规程措施。
** 各生产队组技术负责人负责向职工贯彻学习有关 “一通三防”的规程措施。
