:PROPERTIES:
:ID:       53d713c9-0cc5-4898-bcfc-14c21b89e204
:END:
#+title: 自救器发放工安全操作规程
* 自救器发放工负责管辖范围内自救器的收发、保管、检查和维修。
* 收发自救器时，要轻拿轻放，严禁碰撞；收回的自救器要擦干净，并进行外观检查，放回原处。
* 自救器由矿集中管理，实行专人专用，对号发放。
* 对在用的自救器应逐台建帐、登卡，即记录自救器的出厂日期、编号、检查日期、检查内容、检查结果、使用者的姓名、开启原因，使用效果等。
* 对使用过的自救器要及时注销并补充。凡封条破坏或已开启过的自救器，无论使用时间长短，都应报废；未使用过的自救器，存放时间长达5年以上的，也应予以报废。
* 自救器不得和易燃易爆品放置在同一库房内。自救器库房必须通风良好，整洁干燥，不得有腐蚀性气体或蒸汽。库房中的自救器应避免放在日光直射或其他热源直接辐射的地方。
* 交接班时，要把自救器使用情况、损坏程度交接清楚。分管的自救器帐、卡、物必须相符。
* 各矿收到厂家发来的自救器后，必须在一个月内由自救器工配合供应部门对外观（包括铭牌、出厂日期和标重）气密性和称重（仅指过滤式自救器）进行验收，发现产品不符合标准时，应及时与厂家联系退换。
* 过滤式自救器的称重检查应使用经过校正误差不超过±1克的天平，增重超过10克的自救器应予报废。
* 使用ZJ型气密检查仪检查过滤式自救器气密性时，要求在15秒内压力计水柱下降不得大于8毫米；用60～65℃温水检查时，不得有冒泡漏气现象。否则要更换胶圈或进行维修，以保证气密合格。
* 在60～65℃温水中进行隔绝式自救器气密性检查时，自救器浸入水中出现连续冒泡，或浸入水中一分钟内10秒后开始计数）断续冒泡超过8个的，要及时进行维修。1年内，经检查低于8个泡的，可不进行气密性维修；期满1年时，都要及时维修。
* 用温水检查自救器后，必须把自救器擦拭干净。
* 使用的气密仪必须经过调试、检查，要求仪器系统本身是气密的。
* 气密仪的工作压力范围为（480～520）×9.81帕，检查自救器时，可将压力计水柱提高到540毫米。封压后10秒钟，水柱保持不动时，则认为气密仪调试合格。
* 将被试自救器放入气密仪的工作室中。如果检查过滤式自救器，须预先在工作室里放置随机附带的L形填块。
* 盖上气密仪封盖，扣上封压钩，同时按秒表计时，10秒钟时，记下压力计水柱高度；5秒时，再次记下压力计水柱高度。对于过滤式自救器，如果在最后的15秒钟内压力计水柱下降不超过8毫米，则认为气密合格；超过8毫米或压力计水柱高度未达到470毫米的，则认为气密不合格。对于隔绝式自救器，如果在最后的15秒钟内压力计水柱下降不超过30毫米，则认为气密合格；超过30毫米或压力计水柱高度未达450毫米，则认为气密不合格。为提高检查效率，封压10秒钟后，若压力计水柱停留在480毫米以上某一高度不动，则认为自救器气密合格，不必再观察后15秒钟。
* 气密合格的自救器可以继续使用；气密不合格的自救器必须进行处理。
* 被检查的自救器应处于气密仪检查场所2小时后，才能开始检查，检查时环境温度的波动不应超过2℃。
* 被检查的自救器及气密仪应避免日光直射或靠近暖气热源，检查场所应尽可能避免有过堂风或受抽、排气设备影响。
* 被检自救器上的煤粉和脏物应擦掉，不允许煤粉和脏物等落到密封环和托盘上，以保证气密仪系统的可靠密封。
* 若扣上封压钩后，压力计水柱很快下降到400毫米以下，说明自救器大漏气；如怀疑气密仪系统本身的气密性，可换用库存不漏气的自救器作对比试验，不可冒然调整气密仪。
* 使用气密仪时，加压（扣封压钩）卸压（松开封压钩）均应缓慢地进行，切不可猛扣、快放，以防止水溅到工作室里，使机件受损。
* 检查自救器时，若发现压力计水柱有上升现象，说明橡胶密封环质量不好；如在后15秒钟内压力计水柱上升高度超过4毫米，则橡胶密封环应予更换。
* 压力计刻度管里出现水泡时，表明压力计缺水，应注水后再用。
* 自救器检查完后，应立即取出，不可长时间放在气密仪工作室里加压。
* 对气密处于不合格边缘的自救器，应进行复查。
* 对气密不合格的过滤式自救器，应在经校正误差不超过±1克的天平上称重，增重不超过10克的，密封后可继续使用。
* 为了寻找漏气部位，可用直观方法寻找，也可用毛笔沾浓度适当的肥皂水在自救器被加压30～60秒后涂抹于可能漏气的部位进行检查，冒泡处即是漏气处。此法同样适用于隔绝式自救器。
* 使用气密仪检查隔绝式自救器时，如果在后15秒钟内压力计水柱高度下降，15～30mm属小漏气，仍属气密合格，但应将漏气处用锡焊封闭；如在最后15秒钟内，压力计水柱下降30～50mm属中等漏气，经试验还未失效的，补漏维修后可继续使用。
* 要详细记录修理过的自救器的损坏与修理情况。
* 维修自救器的工作场所应清洁，以避免粉尘、油脂等进入自救器。
