:PROPERTIES:
:ID:       42e19cfd-3243-4b51-acbd-5edaf3b00af8
:END:
#+title: 爆炸物品领退管理制度
* 爆炸物品的领取
** 爆破材料管理必须建立库存台帐；发放、退库台帐；回收废旧的火工品台帐。
** 爆破材料管理人员和放炮员必须严格执行爆破材料领退制度。严格领退手续，做好相应记录。
** 放炮员根据当班生产任务选用雷管炸药，填写在专用的火工品领料单上，经采掘队长签字审批后，持放炮合格证及领料单到矿调度室审批，没有采掘队长签字签字或与生产现场不相符，矿调度员一律不准审批。
** 领取炸药和雷管时，必须有队长、当班负责人审批、签字盖章的或主管部门签字盖章批准的火药领取单到爆破材料发放站领取当班用的炸药和雷管。
** 在有瓦斯或煤尘爆炸危险的煤层中掘进和采煤工作面，只准领取作业规程规定的、取得产品许可证的煤矿许用炸药；严禁领取和使用黑火药、冻结和半冻结的硝化甘油类炸药、含水超过0.5%的铵梯炸药、硬化到不能用手揉松的硝酸铵类炸药及其他不符合安全规程规定的炸药。只准领取经导通、编号、合格的电雷管；采煤工作面只准领取瞬发电雷管或煤矿许用毫秒延期电雷管，严禁领用秒延期电雷管、非电导爆管。
** 放炮员持放炮上岗证、便携仪和审批过的火药领料单在安全员的监督下到地面炸药库领取火工品，否则炸药库发放员严禁发放。库房保管员按照审批数量，如数发放，不得超发或少发。放炮员领取火工品后必须当面核查领取的数量及编号等，否则责任自负。
** 爆破工在领取电雷管时，必须经库房管理员在跟踪卡片上登记雷管段数、编号，后由爆破员、安全员、发放人在跟踪卡片上签字，到作业地点，安全员完成监督任务，由班组长对雷管使用进行监督，并在跟踪卡片上签字，在下班后未用完的，必须退回库房，由收回人核对清点雷管并在跟踪卡片上签字,完成雷管的监督使用任务。
** 爆破工必须在爆破材料库的发放硐室领取爆破材料，不得携带矿灯进入库内，以防矿灯引爆爆破材料。
** 领取炸药和电雷管时，必须当时检查品种、规格和数量是否与领取单上的计划相符，并从外观上检查其质量及电雷管编号是否与申请计划一致。
** 仓库保管员坚持“十不发放制度”：
*** 没有合格证不发。
*** 放炮员不持放炮合格证，无安全员监督，不带瓦斯便携仪，不对号不发。
*** 无安全员监督、签字不发。
*** 不是专用领料单，没有审批不发。
*** 不是双人领料不发。
*** 没有雷管箱不发。
*** 雷管箱没有锁不发。
*** 雷管不导通、不编号不发。
*** 质量有问题不发。
*** 酒后领取爆炸物品不发。
** 放炮员领取的炸药、雷管要及时分别存放入药箱、 雷管箱内，并加锁保管，钥匙随身携带，严禁交与他人保管。
* 爆炸物品的运送
** 领取火工品应有正、副炮工两人领取，有一人休班，由班组长代替，领取爆炸物品时必须穿抗静电衣服,领到火工品应按《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》规定运往工作地点，电雷管必须由爆破工亲自运送，炸药应由爆破工或在爆破工监护下由生产班组，熟悉爆炸材料性能和爆破知识的人员运送。
** 爆炸物品必须装在耐压和抗撞击、防震、防静电的非金属容器内。电雷管和炸药严禁装在同一容器中。严禁将爆炸物品装在衣袋内。领到爆炸物品后，应直接送到工作地点，严禁中途逗留。
** 运送爆炸材料到井下时，根据矿的实际情况，采用人力搬运，并应遵守下列规定：
*** 必须事先通知人车司机，在运送爆炸材料时，严禁非运送人员乘坐人车。
*** 交接班人员上、下井的时间内,严禁运送爆炸材料。
*** 禁止将爆炸材料存放在井口房,井底车场或其它巷道内。
*** 放炮员领取和运输雷管必须在安全员的监督下运到井下使用地点。
*** 一人一次运送的爆破器材数量不得超过24kg。
*** 电雷管与炸药必须分开运输，且间隔距离不得低于25米。
** 爆炸物品运送到工作地点后，必须装入爆炸物品箱内，并加锁，钥匙由放炮员随身携带。爆炸物品箱必须放在顶板完好、支架完整、避开机械和电气设备的地点。
* 爆炸物品的清退
** 当班的放炮工作结束后，与当班班组长一起及时清点剩余的炸药、雷管数量，并写出清返单经班组长、安全员签字，升井后及时退库。
** 不得使用过期或严重变质的爆炸物品。不能使用或剩余的爆炸物品必须交回炸药库。
** 放炮员在将当班的剩余炸药、需管返库时，必须同时持有当班班组长签字清退单。
** 爆破材料管理员在接收放炮员交回的剩余炸药、雷管时，必须认真查对、验收，确认领退数量相符后，方可办理返库手续。
* 相关规定
** 对在领返手续上作弊、有意损坏、偷盗或私藏炸药、 雷管的人员，一经发现后必须立即向上级主管部门汇报。
** 电雷管必须实行专人专号，不得遗失、转借他人使用或挪作它用。不得销毁、扔弃，发现遗失应立即报告班组长。
** 每次爆破工作完成后，爆破工必须认真落实炸药、雷管的来龙去脉。做到“审批、实领、实用、缴回”四个环节爆破材料的品种、规格和数量相一致，使四个环节各负其责、各把其关。
** 各采掘工作面火工品现场用量必须在当班下班之前，经当班安全员核发，在清退单上签字后，放炮员亲自退库，炸药库保管员按清退单查收，在查收后必须给放炮员开一联红单,单中注明清退名称和数量,放炮员收到红单后,将红单交回材料保管,由保管进行保存,争取做到帐与物相符,若发现不按规定办理一次核减薪酬XX元，情节严重者重处。
** 炸药库必须切实抓好火工品班后清退工作，凡放炮员无清退单或清退单填写不符要求的，炸药库值班员必须及时上报安全科，每人次核减薪酬XX元。
** 号召广大职工认真搜捡丢失在煤炭中的雷管，井下拾到的雷管必须交炸药库，由当班炸药库值班员出具证明报安全科，井上捡到的雷管必须及时主动的交炸药库，由当班炸药库值班员出具证明报安全科。上交者必须讲清拾到雷管的地点（最好有证明人），矿对上交雷管个人给予奖励。
** 炸药库对收到的雷管，要做好专项记录台帐，要专箱存放，并查明雷管编号及使用队组。
** 安全科对收到的雷管做好追查处理工作，丢失雷管至少要追查到班组和个人。
** 凡发现私自携带雷管上井的，当一级严重三违处理，三发及以上的除罚款外，交公安部门处理，造成后果的，依法追究刑事责任。对搜捡到雷管不主动上交的，经查实同样按私自携带雷管上井处理。
** 加强井口检身工管理和检查，凡发现携带雷管、炸药出井的，一律开除矿籍，交公安部门处理。
