:PROPERTIES:
:ID:       0de7c4c6-bc2a-42d4-8391-6daec937f6ef
:END:
#+title: 劳动者职业健康监护及其档案管理制度
为规范职业健康监护工作，维护职工合法权益，根据《中华人民共和国职业病防治法》、《职业健康检查管理办法》、《用人单位职业健康监护监督管理办法》，制定本制度。
* 职业健康监护是指劳动者上岗前、在岗期间、离岗时和应急职业健康检查和职业健康监护档案管理。
* 职业健康检查，是指医疗卫生机构按照国家有关规定，对从事接触职业病危害作业的劳动者进行的上岗前、在岗期间、离岗时的健康检查和应急健康检查。
* 职业健康检查，必须与依法取得省卫生行政部门批准的从事职业健康检查资质的医疗机构签定职业健康检查委托协议，由委托单位对从事在有职业危害因素作业场所工作的职工进行上岗前、在岗期间、离岗时职业健康体检和应急健康检查。
** 职业健康检查及诊断机构
明确由取得资质的贵州盘江投资控股（集团）有限公司总医院负责职业健康检查和职业病诊断工作。
** 职业健康检查
上岗前、转岗、离岗人员职业健康检查按照《职业健康监护技术规范》(GBZ188)等国家职业卫生标准的规定和要求，确定检查项目，根据工作需要开展职业健康体检。
在岗期间职业健康体检，按照《职业健康监护技术规范》(GBZ188) 等国家职业卫生标准的规定和要求，确定检查项目和检查周期。人资资源部门根据公司人社部按照职业健康检查周期，明确接触职业危害因素作业人员范围，制定职业健康检查实施方案，开展职业健康检查，需复查时可根据复查要求相应增加检查项目。
接触职业病危害作业人员的职业健康检查周期表
接触有害物质	体检对象	检查周期
煤尘（以煤尘为主）	在岗人员	2年1次
观察对象、Ⅰ期煤工尘肺患者	每年1次
岩尘（以岩尘为主）	在岗人员、观察对象、Ⅰ期矽 肺患者
噪声	在岗人员
高温	在岗人员
化学毒物	在岗人员	根据所接触的化学毒物确定检查周期
接触粉尘危害作业退休人员的职业健康检查周期按照有关规定执行
** 上岗前职业健康检查。为强制性职业健康检查，检查人员包括：拟录用人员、转岗到拟从事接触职业病危害的作业岗位人员。
** 离岗时职业健康检查。检查人员包括：准备调离或脱离所从事的存在职业病危害的作业或岗位前所进行的职业健康检查。如最后一次在岗期间的健康检查是在离岗前90日内的，可视为离岗时检查。
** 应急健康检查。1.接触职业病危害因素的人员在作业过程中出现与所接触职业病危害因素相关的不适症状的；2.作业人员受到急性职业中毒危害或者出现职业中毒症状的。
* 人力资源部门，应根据职业健康检查报告，书面告知职工本人体检结果，同时遵守或采取以下规定和措施：
** 拟录用或转岗到从事接触职业病危害作业岗位人员，未经职业健康查体及与所要从事岗位有职业禁忌症、健康检查其他不符合作业岗位要求的，一律不得录用及转岗。
** 有职业禁忌的职工，不得安排从事其所禁忌作业；不得安排未成年工从事接触职业病危害的作业；不得安排孕期、哺乳期的女职工从事对本人和胎儿、婴儿有危害的作业。
** 对在岗期间职业健康检查诊断有职业病及职业禁忌的职工，立即调离所禁忌的作业；发现与所从事职业相关的健康损害的职工，进行妥善安置。
** 对需要复查的职工，按照职业健康检查机构要求的时间，安排复查和医学观察。
** 对疑似职业病病人，按照职业健康检查机构的建议安排其进行医学观察或者职业病诊断。
** 对应急健康检查发现健康损伤的职工，进行医学观察；对疑似职业病人，应尽快安排职业病诊断。
** 对存在职业病危害的岗位，应改善劳动条件，完善职业病防护设施，为作业人员配备符合国家标准的职业病危害防护用品。
** 职业禁忌，按照《职业健康监护技术规范》(GBZ188-2014)执行，国家有新规定时按新规定执行。
** 对未进行离岗前职业健康检查的职工，不得解除或终止与其订立的劳动合同。
* 职工职业健康体检费用，由职工所在单位承担；职工接受职业健康体检的时间，应当视同正常出勤。
* 人资资源部门，按照一人一档为每名职工建立个人职业健康监护档案，并设立档案室或指定专门的区域存放，明确专门机构和专（兼）职人员管理。职业健康监护档案包括下列内容：
** 职工姓名、性别、年龄、籍贯、婚姻、文化程度、嗜好等情况；
** 职工职业史、既往病史和职业病危害接触史；
** 历次职业健康检查结果及处理情况；
** 职业病历次诊疗资料；
** 需要存入职业健康监护档案的其他有关资料。
* 职工在调离原单位时必须进行职业健康体检。调出公司的，职业健康档案由原单位保管；在公司内部调动时，职业健康监护档案随工作关系移交调入单位，由调入单位建档管理。
* 职工离开单位时，有权索取本人职业健康监护档案复印件，人力资源部门应当如实、无偿提供，并在所提供的复印件上签章。
* 档案管理人员必须维护职工的职业健康隐私权、保密权；相关的卫生监督检查人员和职工本人，有权查阅、复印本人的职业健康监护档案。其他人员不得私自查阅或出现与其相关的其他违反法律规定情形。
* 对已离职人员的职业健康监护档案，在办理完离职后进行封存，以备相关部门查阅。
* 档案管理人员应对职业健康监护档案妥善保管，落实防火、防虫蛀、防霉、防丢失等管理措施，保证档案安全。
