:PROPERTIES:
:ID:       a9135f3f-c965-4c96-9e39-384d747bd92f
:END:
#+title: 瓦斯曲线分析制度
* 矿调度必须24小时值班，发现瓦斯传感器显示值出现大增幅或瓦斯曲线不正常以及临近报警值时，必须及时向通风科值班领导汇报，通风科并立即电话通知瓦检工和监测工，查明原因，采取措施，进行处理，并将原因、措施及处理结果汇报通风科，做好记录。
* 监控系统地面中心站如果出现采、掘工作面瓦斯浓度达到异常报警后，应做好以下几点：
** 若瓦斯浓度当班或上下两个班次平均值浮动达到或超过0.3%，且峰值大于等于0.8%时，应立即通知通风科值班人员和瓦检员查明原因。
** 经瓦检员检查后，现场瓦斯浓度无异常情况，应立即通知监测维护人员，到现场判断传感器是否出现故障，并采取措施及时处理，并将异常报警处理结果汇报给监控人员。
** 经瓦检员检查后，现场瓦斯浓度瓦斯浓度当班或上下两个班次平均值浮动达到或超过0.3%，且峰值大于等于0.8%时，瓦检员应查明原因，并采取措施进行处理。
** 若瓦斯超限时，必须立即采取停电撤人措施。待处理完毕后，监测数值降到《规程》允许浓度内，瓦检员应检查工作面、回风流及上隅角等地点瓦斯浓度，并将检查结果汇报通风科值班人员，由值班人员下达恢复生产命令。
* 瓦检员在检查过程中，发现瓦斯浓度未被有效控制，持续升高，达到超限浓度时，应立即停止该工作面一切作业，切断电源。施工队长及班组长应与瓦斯员一起组织将工作面所有人员沿进风路线逆风流撤退到进风巷内。同时在工作面巷口设置栅栏，揭示警标，由安全员负责设置警戒，同时汇报矿调度值班领导。
* 瓦斯浓度达到1.0%时，必须立即汇报调度、通风科及调度值班领导。调度值班领导在接到汇报后，应立即电话通知该队组各工作面瓦斯员停止该区域内一切作业，由上一级配电室切断电源，将工作面人员沿进风路线逆风流撤出，并在所有能进入的巷道口设置栅栏，揭示警标，悬挂“禁止入内”牌。并做好断电、撤人、设置警戒全过程的监督检查工作。值班领导应立即汇报矿总工程师，由矿总工程师组织有关人员制定处理办法，通风科值班领导入井处理。处理完毕后要汇报值班领导、矿总工程师，调度要做好记录。
* 瓦检员在现场检测过程中，发现瓦斯涌出异常，瓦斯浓度突然增高，应立即通知该工作面人员停止该区域内一切工作，切断电源，撤出人员，汇报矿调度员。调度员在接到汇报后，应立即由通风值班领导和调度值班领导查明原因，制定措施通知就近地点的通风科领导在半小时内赶到现场，进行处理。通风科值班领导现场指挥。处理完毕后要汇报调度值班人员，并做好记录。
