:PROPERTIES:
:ID:       74ca96a5-7423-484e-a972-3ab62fbea797
:END:
#+title: 安全生产标准化管理制度
为持续推进矿井安全生产标准化建设工作，强化各专业安全生产标准化主体责任的落实，进一步改善安全生产环境，夯实安全生产基础，促进矿井安全生产持续安全、健康、稳定发展，根据《[[id:4663f65b-c43d-4e59-b804-905990c44ab5][煤矿安全生产标准化基本要求及评分方法（试行）]]》（以下简称《标准》）及相关规定和要求，结合实际，特制定本办法。
* 安全生产标准化建设目标
持续保持一级安全生产标准化矿井。
* 领导机构及职能
矿成立煤矿安全生产标准化工作领导小组
组  长：矿长
副组长：各分管矿领导
成  员：副总工程师、各科室负责人  各队组负责人
安全生产标准化领导小组下设办公室在安全科和生产技术科，安全科负责安全生产标准化检查考核的日常管理工作，生产技术科负责标准制定、收集上报资料和参与检查考核工作。
领导小组下设安全风险和事故隐患排查治理专业小组、通风专业小组、地质灾害防治与测量专业小组、采煤和掘进专业小组、机电和运输专业小组、职业卫生专业小组、安全培训专业小组、应急管理专业小组、调度专业小组、地面设施专业小组。
** 工作职责
*** [[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]：对矿井安全生产标准化建设工作全面负责，并组织开展检查和督促工作。
*** [[id:21350f90-65e1-46b4-8bb9-c24d0aae7787][安全副矿长]]：对全矿安全生产标准化建设进行监督检查和考核管理，负责矿井安全风险分级管控、事故隐患排查治理和安全培训专业的建设、监督及考核管理工作。
*** [[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]：负责矿井采煤、掘进、调度、职业卫生专业和分管范围内的安全风险分级管控及事故隐患排查治理的安全生产标准化建设及管理工作。
*** [[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]：负责通风、地质灾害防治与测量、应急救援和分管范围内的安全风险分级管控及事故隐患排查治理的安全生产标准化建设及管理工作。
*** [[id:e37d6834-cade-43cc-ac8b-693a0a46d808][机电副矿长]]：负责矿井机电、运输和分管范围内的安全风险分级管控及事故隐患排查治理的安全生产标准化建设及管理工作。
*** 副总工程师：负责协助总工程师及分管矿领导做好矿井安全生产标准化建设及管理工作。
** 成立专业小组
*** 安全风险分级管控和事故隐患排查治理专业小组
组  长：[[id:21350f90-65e1-46b4-8bb9-c24d0aae7787][安全副矿长]]
副组长：副总工程师
成  员：各科室负责人  各队组负责人
职  责：按《标准》组织开展安全风险分级管控和事故隐患排查治理安全生产标准化建设及监督、检查及考核工作。由安全科负责牵头组织开展相关工作，各队组密切配合做好相关工作。
*** 通风专业小组
组  长：[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]
副组长：副总工程师
成  员：通风科科长、生产技术科科长、安全科科长、机运科科长、队组队长
职  责：按《标准》组织开展通风安全生产标准化建设及监督检查工作，由通风科负责牵头组织开展相关工作。
*** 地质灾害防治与测量专业小组
组  长：[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]
副组长：副总工程师
成  员：生产技术科科长、地质及测量组长、机运科科长、安全科科长、队组队长
职  责：按《标准》组织开展地质灾害防治与测量安全生产标准化建设及监督检查工作，由生产技术科负责牵头组织开展相关工作。
*** 采煤、掘进专业小组
组  长：[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]
副组长：副总工程师
成  员：生产技术科科长、安全科科长、队组队长
职  责：按《标准》组织开展采煤和掘进安全生产标准化建设及监督检查工作，由生产技术科负责牵头组织开展相关工作。
*** 机电专业
组  长：[[id:e37d6834-cade-43cc-ac8b-693a0a46d808][机电副矿长]]
副组长：副总工程师
成  员：机运科科长、安全科科长、队组队长
职  责：按《标准》组织开展矿井机电安全生产标准化建设及监督检查工作，由机运科负责牵头组织开展机电相关工作。
*** 运输专业小组
组  长：[[id:e37d6834-cade-43cc-ac8b-693a0a46d808][机电副矿长]]
副组长：副总工程师
成  员：机运科科长、安全科科长、队组队长
职  责：按《标准》组织开展矿井运输安全生产标准化建设及监督检查工作，由安全科负责牵头组织开展运输相关工作，机运科参与和配合。
*** 职业卫生专业小组
组  长：[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]
副组长：副总工程师
成  员：人力资源科科长、机运科科长、通风科科长、队组队长
职  责：按《标准》组织开展矿井职业卫生安全生产标准化建设及监督检查工作，由人力资源科负责牵头组织开展相关工作。
*** 安全培训专业小组
组  长：[[id:21350f90-65e1-46b4-8bb9-c24d0aae7787][安全副矿长]]
副组长：副总工程师
成  员：安培中心主任、相关各科室负责人、队组负责人
职  责：按《标准》组织开展安全培训专业的安全生产标准化建设及监督检查工作，由安培中心负责牵头组织开展相关工作。
*** 应急管理专业小组
组  长：[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]
副组长：副总工程师
成  员：通风棵棵长、安全科科长、队组队长
职  责：按《标准》组织开展应急管理专业的安全生产标准化建设及监督检查工作，由通风科负责牵头组织开展相关工作。
*** 调度专业小组
组  长：[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]
副组长：副总工程师
成  员：矿调度室主任、各相关科室调度室主任
职  责：按《标准》组织开展调度和地面设施专业中调度安全生产标准化建设及监督检查工作，由生产技术科负责牵头组织开展相关工作。
*** 地面设施专业小组
组  长：[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]
成  员：人力资源科科长、队组队长
职  责：按《标准》组织开展调度和地面设施专业中地面设施安全生产标准化建设及监督检查工作，由人力资源科牵头组织开展相关工作。
* 考核标准及方法
** 考核标准
*** 安全生产标准化各专业小组由组长牵头负责按照《标准》的相关规定，结合实际制定各专业验收标准及考核内容，经矿领导小组审核同意后执行。
*** 继续执行“一票否决”制度，凡在检查中存在“一票否决”问题的一律评定为不合格。
*** 矿领导、副总工程师、安全科科长、生产技术科科长、矿调度室主任对全矿各专业及队组的安全生产标准化的考评，具有不合格决定权。
** 考核方法
*** 采用现场验收、检查和抽检的方式，对施工工程质量、图纸、记录和相关资料进行考核。
*** 由分管矿领导组织副总工程师、安全科、生产技术科、矿调度室、机运科、通风科每半月对全矿所有采掘作业工作面及生产系统进行一次通风、采煤、掘进、机电、运输等专业安全生产标准化检查和评定；每月对巷修施工地点进行一次安全生产标准化检查和评定。
*** 每月由分管矿领导组织副总工程师、相关队组及人员进行一次安全风险分级管控、事故隐患排查治理、地质灾害防治与测量、职业卫生、安全培训和应急管理、调度和地面设施等专业安全生产标准化检查和评定。
*** 矿领导、副总工程师、安全科科长、生产技术科科长、矿调度室主任对全矿安全生产标准化情况进行动态抽查。
** 相关规定
*** 各队组必须提高对安全生产标准化工作的认识，扎实开展安全生产标准化建设和检查工作，进一步提高矿井安全生产标准化水平。
*** 现场检查时，被检队组队长负责人或技术员必须参加检查，并准备好检查器具和备查资料。
*** 存在如下“一票否决”项，该专业或队组评定为不合格。
- 被检查单位无分管领导参加、无队组负责人或技术员参加的。
- 未按规程、措施施工和无措施作业的。
- 发生2人及以上群伤事故的，发生重伤及以上生产安全事故的，发生较大及以上涉险事故的。
- 不具备安全生产必备条件被上级部门停产整改的。
- 发生瓦斯超限的。
- 通风设施未按设计进行施工的。
- 电气设备失爆、甩保护的，斜巷断绳、断带跑车的。
- 巷道中、腰线偏差超过规定的。
- 采面上下出口不畅通的，采面两巷高度不符合规定的，采面两巷超前支护不符合规定的，采面支架偏倒严重的。
- 现场文明生产较差的。
- 未按《标准》规定，建立健全相关台账或收集整理牵头组织专业工作资料的。
*** 采面回采、安装、回收前，巷道掘进开口施工前，探放水施工前，输送机及绞车使用前，石门揭煤或防突钻孔施工前及施工完毕后，由队组自检合格后提报验收申请报矿领导和相关单位及部门签字同意后进行验收。以上工程经矿组织相关单位及部门验收合格后方可进行作业。采面回采验收、石门揭煤或防突验收由通风科牵头组织，巷道掘进开口和探放水施工验收由生产技术科牵头组织，采面安装、回收验收及输送机、绞车验收由安全科牵头组织，对验收不合格的，对相关专业或队组安全生产标准化评定为一次动态不合格。
* 考核
** 评分标准
*** 各专业按照《标准》进行检查评分，通风、采煤、掘进、机电、运输专业考核队组，其他专业考核单位。
*** 半月安全生产标准化检查评分80分以下或存在“一票否决”项的评定为不合格，80—89分且无“一票否决”项的评定为合格，90分及以上且无“一票否决”项的评定为优良。
** 奖惩要求
*** 各队组动态抽检、半月检查评定为不合格的专业或队组，对相关队组验收员、带班副队长、队长各进行经济处罚××元/面·次；在一个月内出现两次及以上不合格的专业或队组，对相关队组验收员、带班副队长、队长各进行经济处罚××元/面·次。检查评定为优良的专业和队组，奖励相关队长、验收员、带班副队长各××元/面次。
*** 出现一次动态抽检不合格的专业和队组，扣减相关队组当月结算工资总额的5%；对各专业参检队组半月、全月检查评定为不合格的扣减相关队组当月结算工资总额的10%，核减工资按累加计算。
*** 矿检查中检查评定为安全生产标准化最差的采掘修作业工作面、机电运料队组，对责任队长各进行经济处罚××元/面·次。被上级检查提出现场文明生产较差作业地点，对责任队长各进行经济处罚××元/次。
*** 月检查评定为不合格的专业或队组，对责任队长各进行经济处罚××元/次。
*** 安全科、生产技术科、矿调度室、机运科、通风科等单位必须安排至少1人参加矿半月安全生产标准化检查，参加检查的人员每月奖励××元。严格执行统一投票制度，参加检查的单位及部门必须安排专人参加评定工作。无故不参加、不安排人员参加或不遵守组织纪律影响检查及考核评定工作的，处罚责任人××元/次。
*** 各单位检查考评人员必须严格对标对表检查，按照“谁检查、谁验收、谁签字、谁负责”原则执行，对弄虚作假、敷衍了事的责任者给予经济处罚××元，涉及违纪行为的，严肃责任追究。
*** 每月5日前由矿组织相关科室及队组召开安全生产标准化工作专题会，对各专业、各队组安全生产标准化工作建设、检查情况进行通报，并按标准及相关规定进行考核和评定。因现场施工地质条件或非人为因素影响队组安全生产标准化工作的，经矿领导小组同意后可以不进行处罚。
** 评定结果由安全科汇总，次月5日前报矿审核批准后，由人力资源科负责落实兑现。
