:PROPERTIES:
:ID:       acf10891-93ce-4c6d-baff-2e1323e2edd1
:END:
#+title: ZY－750型液压钻机安全操作规程
* 井下安装
** 在现场安装前，首先清理好施工场地，确认施工场地顶板安全可靠，有足够的施工空间，通风良好，有水源、电源。电源660V，有额定负荷大于18.5KW的防爆开关和电缆，以及足够长的供水胶管和三通。检查各油管连接是否正确；检查个连接螺栓是否拧紧，立柱是否锚固牢固，操作手把置于中位；检查电动机的旋向与齿轮壳体上的标定转向是否一致。检查冷却水及水压是否正常，冷却水流量＞50L/min，水压不小于0.3Mpa。其中压风排渣时，压力不低于0.4Mpa，流量为150—200L/min，并设有灭尘装置和风水切换装置。
** 钻机的安装顺序
*** 钻机运到指定地点后，将各组件按部件进行组装，然后分别将泵站、操作台摆放在既利于安全操作、监视、又便于搬运的位置；
*** 所有接头必须擦干净后方可按照液压系统图进行连接。电动机接线时，注意电压等级变化。检查各部件装配的完整性和可靠性。安装各连接螺栓时，螺栓上应涂抹少量黄油，各连接螺栓应拧紧；
*** 泵站油箱内加46#抗磨液压油，电动机接线，接冷却水管和排渣管路；根据液压系统接通所有胶管，胶管应有标记，以免接错位置，连接前必须检查快换接头，要求清洁无渣屑，并且动作灵活；
*** 接通电源，空车试2min。试车时，先检查手柄的动作是否按规定动作。动力头正反转压力不小于4Mpa，推进油缸反复运动压力不小于2Mpa，总回油压力不小于0.4Mpa，各油管不得有泄漏现象；卡瓦和夹持器卡瓦伸缩平直、钻杆上的夹痕均匀；钻机各部运转平稳，没有异常声响和异常现象，否则应停机检查。
* 钻机操作
** 钻机支设：根据钻孔的位置，调整主机的位置和方位，将操作台上推进用油管接在机架底座平衡阀组对应接头上。操作多路阀正常进退手把调整机座的倾角，并用支撑杆将机架锁定。接通接通排渣水（或压风）和冷却水，试运转钻机。
** 开孔：将动力头推到机架后端，用卡盘夹紧2棵钻杆钻杆后部分用于连接水变轴，在夹持器前端钻杆上上好钻具。操作正、反转手把至正转位，使动力头带动钻杆正转，见到孔口返水（或返风）后，操纵给进手把至前进位，到达开孔位置后慢慢钻进。
** 正常钻进：待孔口位置开出来后，再以正常速度钻进。在钻进过程中，因切屑阻力发生变化时，可调节调速阀来控制推进速度。若发生喷孔、瓦斯增大、水量增大等情况时，立即停止钻进，并向上级汇报，待无隐患后方可作业。
** 钻杆加接：钻进过程中接钻杆时，先停止推进，然后在停止旋转，关闭排渣水。操纵控制夹持器的换向手把，向前推，使夹持器夹紧钻杆后，夹持器手把回到中位。操作正常进退手把到最后位置，操作正转手把然后拉使动力头反转，使水变轴一钻杆旋离。操纵快速进退手把至快退位置，使动力头快速退到机架的后端。将要加接的钻杆接在前一根钻杆上，动力头前进使加接的钻杆接在后一根钻杆上，再边正向旋转边前进，当水变轴梯形锥螺纹与新加接钻杆锥螺纹连紧时，立即松开夹持器，完成钻杆加接。
** 卸钻杆：钻孔施工到设计位置后，关闭排渣水。保持正向旋转，操作正常进退手把使其后退，退到适当位置，并停止后退和旋转。用夹持器夹紧钻杆，操作动力头反转，使卡盘与夹持器之间的钻杆接头拧松，然后打开卡盘，操纵快速进退手把至快进位置，使动力头拉到机架前端，人工卸下动力头后端的钻杆。然后使卡盘夹紧钻杆，夹紧后打开夹持器，保持正向旋转，操作正常进退手把使其后退，退到适当位置，并停止后退和旋转。用夹持器夹紧钻杆，操作动力头反转，使卡盘与夹持器之间的钻杆接头拧松，然后打开卡盘，操纵快速进退手把至快进位置，使动力头拉到机架前端，人工卸下动力头后端的钻杆。如此循环反复，直到卸完全部钻杆。
** 在钻进过程中，注意观察压力表，压力不得超过4Mpa。
* 钻机的保养与维护
** 钻机在使用过程中，必须保持清洁、完好、功能齐全、灵活可靠、必须进行日常维护和检修。
*** 建立正规的使用维护制度，不得在长期不使用的情况下长期停放在井下，以免机器锈蚀损坏。
*** 交接班时必须仔细检查钻机的完好性和工作性能，发现问题记录并及时处理，钻机不得带病作业。
*** 钻机必须有专人负责维修，井下不得随意拆拧动各零、部件。
*** 随时检查油箱油位，当油位低于标定油位时应及时停机加油。一般三个月检查一次油质，若不合格应全部更换新油，并清洗油箱，必要时应升井对液压系统进行全部清洗。
*** 在钻进过程中，随时检查各转动部件及油箱的温升情况，钻机各运动部件及油箱中油温不得超过500°C，否则应及时检查分析，如油温油量、油路阻力，运动过载，元件摩擦损坏、快速接头堵塞，冷却器通水量不足等原因。
*** 钻进时发现油路系统有漏油现象应及时紧固或更换密封圈，发现钻进困难、振动过大时应调节节流阀，降低钻进速度。
** 钻杆放置要保持平直，不得作为其它用途。使用前应在螺纹处涂抹黄油，以取密封和便拆卸的作用。
** 钻机工作前应对运动结合面、注油点涂抹润滑油，对易锈蚀的外表面每周涂抹黄油一次。
** 根据钻机运转工况和响声，及时判断孔内钻头磨损情况，磨损破坏严重应及时更换钻头。
** 液压卡盘、夹持器应经常清洗，保证卡盘移动灵活、可靠，卡盘若有损坏和过渡磨损，应及时更换。
* 钻机的安全使用及注意事项
** 必须进行大、中、小修并加强平时维护及保养。一般规定半年一次大修；三个月一次中修；每班一次小修。
** 钻机各运动部件及油的温度不得超过50℃，否则应停机检查。
** 各进出油口必须保证清洁干净，油箱注油时，环境空气应清新，加油必须经过空气滤清器的过滤网。
** 操作时必须牢记动力头在前面钻杆未被夹持器卡住时不得反转。后退钻杆时应保持继续正转。
** 钻机不得在无冷却水时使用。
** 钻机在使用时不得摔、砸和重力冲击。
** 各液压管路必须连接牢固。
** 加杆人员不得带手套，以防事故的发生。
