:PROPERTIES:
:ID:       41a5bd79-e7de-47b7-a5b9-c97a6b7f1c67
:END:
#+title: 贵州润鑫能源有限公司合同法律风险防范管理制度

为规范公司合同法律风险的防范与管理，根据《[[id:62100299-7e59-449b-af07-fbf25228e480][中华人民共和国民法典]]》，制定本管理制度。
* 总则
** 本管理制度所称合同是指公司及所属部门对外签订的购销合同、加工承揽合同、工程项目施工合同、建筑施工合同等合同。
** 公司对合同风险的防范与管理，实行对经济合同的签订、合同的履行、帐款回收的全过程以及每一个关键的业务环节进行综合性的事先、事中、事后风险预测和控制。
** 公司经理办对公司所属部门与其它单位签订的合同进行法律风险审核。
** 公司经理办对合同进行审核的内容主要包括合同的主体资格和资质、合同文本及其格式的规范性、合同条款的合法性、严密性和可行性等。
* 合同准备与合同条款
** 公司及所属部门对外签订合同，必须充分了解交易对方的主体资格、存续状况、资质、信誉和履约能力等，以此作为是否签约的依据。
** 合同及协议必须采用书面形式，并加盖合同章及由有代理权的经办人签名。
** 合同应当载明以下一般条款，并符合下列要求：
*** 当事人的基本信息条款，包括姓名/名称、法定代表人、住所地、联系方式、银行帐号等。
*** 合同标的条款，包括规格、型号或合作的具体事项等。
*** 数量条款，包括计量单位、计量方法。
*** 验收条款，包括验收的依据、标准，验收的时间、地点，并形成书面验收报告。
*** 质量和品质条款，包括采用的质量标准、质量保证的期限和方式，提出质量异议的期限。
*** 价格条款，包括标的物的单价、总价、计价方法，涉及到运费、保险费、装卸费、清关费的承担和约定等。
*** 履行期限、地点和方式条款，履行合同的时间，期限要有明确的约定，履行地点应约定为我公司所在地。
*** 合同的效力条款，包括合同生效的时间和生效的条件。
*** 违约责任条款，包括违约形态和违约责任等，违约责任的约定应明确约定赔偿的方式和范围，具有可操作性。
*** 解决争议的条款，要明确约定发生争议双方协商解决，协商不成可向威宁县人民法院起诉。
*** 其它需要阐明和约定的条款。
** 公司所属部门应严格按照公司的规定和要求确定合同内容和交易方式。
* 合同订立和履行过程中的注意事项
** 公司所属部门在签订合同时必须准确表达双方谈判确定的意思，做到：条款不漏项；标的物表达清楚，质量有标准，验收有约定；对标的物的名称、规格型号、数量、价款、交提货时间、标的物的安装、验收时间，标的物的价款给付时间和给付条件的约定要准确无误，文字表述严谨、正确、清晰，不可使用模棱两可、含糊不清的词语，条款的约定要严密无漏洞，不留隐患。
** 公司所属各部门要加强档案管理工作，要将主合同、补充合同、技术协议、协议、收货清单、验收报告、售后服务报告等与主合同有关的材料原件及时交合同管理人员登记存档，统一集中管理。
合同管理工作是经营管理中的关键一环，前承客户授信管理，后接收/付款管理,合同也是违约后诉讼过程中的重要依据,故要加强其管理工作。
* 合同的订立与审核
** 买卖合同的概念与特征：买卖合同是出卖人转移标的物所有权于买受人，买受人支付价款的合同。其特征是：买卖合同是转移财产所有权的合同；是财产所有权与价金互为对价的合同；是诺成、双务和有偿合同。
** 承揽合同的概念与特征：承揽合同是指承揽人按照定作人的要求完成工作，交付工作成果,定作人给付报酬的合同。其特征是承揽合同是双务的、诺成的、有偿的合同；承揽人的工作具有独立性；承揽人完成的工作具有特殊性；承揽人以自己的风险完成工作。
承揽工作包括加工、定作、修理、复制、测试、检验等工作。承揽合同的内容包括承揽的标的、数量、质量、报酬、承揽方式、材料的提供、履行期限、验收标准和方法等条款。
** 公司所属部门签订的单笔合同超过50万元（含本数）的合同，经办部门在发布邀请函的同时，向经理办提交招标邀请函并由法律顾问、企管人员参与招标工作,经理办审核同意后，方可对外签订。
** 经理办审查合同的内容为合同是否具备合法性、严密性、完整性、可行性。具体为一是审查对方的信誉和履约能力等资信情况，防止合同欺诈；二是审查合同文本是否合规，合同条款是否齐全，用语是否准确，违约责任是否符合法律规定；三是审查法人资格是否有效，代理人的代理资格是否合格。
** 公司及所属部门对外签订合同，除公司法定代表人之外，其他人对外签署合同必须经过法定代表人的书面授权,授权文件必须阐明委托事项，授权范围和授权有效期间。
** 公司所属各部门要认真执行公司印章使用管理规定，规范合同专用章的使用和管理。
* 合同履行、变更或解除
** 合同订立后，应严格按照合同约定行使权利和履行义务，防止因提前履约、逾期履约、单方违约等造成损失或承担违约责任。
** 公司所属签约单位应指派专人跟踪合同履行过程，关注市场变化和合同相对方履约能力的变化，采取有效措施及时发现和防范各种合同风险,对在履行合同过程中出现的重大意外情况和风险，可能致使合同无法履行或面临经济损失等情况，有关部门要以书面的形式通报给经理办。
** 基于法律规定、合同约定或当事人协商一致可以变更或解除合同，合同变更或解除应当采用书面形式并作为原合同附件存档。
因市场或当事人履约能力等变化导致合同约定的权利义务严重失衡或合同目的无法实现的，合同签订部门应当尽快与对方变更或解除合同，减少和控制可能产生的损失。
* 合同纠纷的处理
** 公司所属部门在履行合同过程中与对方发生纠纷，合同的签订或履行部门应及时将有关情况书面报送经理办及有关部门。
** 通过协商、调解等方式处理合同纠纷的，应当形成书面协议。
** 通过协商、调解等方式无法解决纠纷的应当按照合同的约定或法律规定通过仲裁或诉讼程序及时主张权利。
** 公司所属部门必须强化诉讼时效意识，在诉讼时效期内主张权利，避免丧失胜诉权，给公司造成经济损失。
** 公司及所属部门侵害其它民事主体的合法权益时，应当及时主动协商处理，尽力避免经济纠纷的发生，减少和避免经济损失。
* 其它
** 合同是公司和所属各单位对外经济活动的重要法律依据和凭证，各单位应悉妥善保管，并予以保密。
** 合同履行完毕后，应当按照公司档案管理的规定，予以存档保存。
* 附则
** 本制度由经理办负责解释，自经理办公会议审定通过后施行。
