:PROPERTIES:
:ID:       e7ddf0ad-0852-43eb-bb1a-0293d25c674c
:END:
#+title: 盲巷管理制度
* 临时停工的地点，不得停风，否则必须向矿、上级部门提出申请报批，经批准后，才能按照标准要求进行封闭或设置栅栏。栅栏或密闭内必须切断电源，撤除设备、设施和电缆，并揭示“禁止入内”的警标，栅栏或密闭位置距离全负压通风巷道口不得超过5米。
* 严格按照规程规定的要求处理和管理盲巷。停工停风的巷道和报废的巷道必须及时封闭，封闭前必须将外部连接的钢轨、架线、管路切断，避免杂散电流引爆瓦斯。因停工需要停风的掘进工作面，必须提出申请，报矿总工程师及上级部门审批，并提前一天由矿调度室通知通风科进行处理。
* 设置的栅栏必须牢固可靠，四周用钉子钉牢，栅栏方格网规格200×200mm。停工区内瓦斯或二氧化碳浓度达到3%或其他有害气体浓度超过规程规定，必须在24小时内封闭完毕。
* 盲巷打好栅栏或封闭后，必须建立瓦斯检查点，挂好瓦斯检查牌，揭示明显警标，按规定检查瓦斯。下井管理人员、安全监察人员要加强对盲巷的监察，发现问题及时汇报。
* 停工地点的报废巷道、已采完的工作面必须及时进行回收，在45天之内，必须构筑永久密闭。
* 瓦检员必须按要求对井下所有栅栏和密闭完好情况进行日常检查，发现问题必须及时汇报。
* 已处理的盲巷，必须建立盲巷管理台帐，逐个编号、登记，并填绘到采掘工程平面图和通风系统图上。
* 加强对井下人员，特别是农协工等采掘队作业人员的安全教育，严禁进入盲巷，严禁随意拆除栅栏、密闭等安全设施。要利用班前会、安全学习日加强教育，值班人员班前、班中、班后要及时清点人数，要掌握当班职工的去向。
* 如因工作需要进入盲巷时，必须经通风科同意，制订措施报安监组审查，总工程师批准，排放瓦斯，恢复正常通风后，方可进入。拆除栅栏、密闭只能由救护队进行，其他任何人不得违章拆除栅栏。
* 生产技术科要合理工程布置，尽量减少盲巷、盲硐。因设计或施工造成的盲巷和盲硐，由施工队组技术员编写盲巷处理技术措施和巷道掘进方案，经总工程师批准执行。盲巷盲硐未处理好，严禁另外开口掘进。
* 采矿、地测技术人员必须严格按照规程的要求，认真做好巷道贯通的预测预报工作，保证测量精度，防止误穿盲巷。凡掘进头临近或接近盲巷、废巷以及其他可能存在的空洞也必须提前做出预报。并制定预防事故的措施。
