:PROPERTIES:
:ID:       45457cb5-6202-4a99-bb87-31cb0f81fc55
:END:
#+title: 电力电缆电气试验项目、周期及标准
* 电缆的试验项目和周期
表1.1电力电缆的试验项目和周期
项   目	周   期
1.油浸纸绝缘电力电缆
（1）绝缘电阻测定
（2）直流耐压试验并测泄漏电流
（3）检查相位	（1）新安装和更换接头；（2）运行中一年一次
（1）新安装和更换接头；（2）运行中一年一次
（1）新安装和更换接头；（2）更换电缆
2.胶联聚乙烯绝缘电力电缆
（1）绝缘电阻测定
（2）直流耐压试验

（3）检查相位
（1）新安装和更换接头；（2）运行中一年一次
（1）新安装和更换接头；（2）运行中一年一次
（1）新安装和更换接头；（2）更换电缆
3.橡皮绝缘橡套电缆
（1）绝缘电阻测定
（2）交流耐压试验
（3）检查相位	（1）新安装和修补后；（2）运行中一季一次
（1）新安装；（2）地面修补后
（1）新安装 ；（2）更换接头后
4.聚乙烯绝缘电力电缆
（1）绝缘电阻测定

（2）直流耐压试验

（3）检查相位
（1）新安装和更换接头；（2）运行中一年一次
（1）新安装和更换接头；（2）运行中一年一次
（1）新安装和更换接头；（2）更换电缆
（二）电力电缆的电气试验标准
1.油浸纸绝缘电力电缆试验标准
（1）绝缘电阻试验
表1.2  油浸纸绝缘电缆绝缘电阻标准
名   称	电 压 等 级
＜0.7KV	1～3KV	6～10KV
粘性油浸纸绝缘电缆绝缘电阻，20℃时，（MΩ×Km）	10	50	100
不滴流油浸纸绝缘电缆绝缘电阻，20℃时，（MΩ×Km）	—	100	200
选用的兆欧表规格	1000V
1000MΩ	2500V
2500MΩ	2500V
2500MΩ
良好的电缆吸收比K=R60/R15≥	2	2	2
各项电缆的不平衡系数≤	2.5	2.5	2
（2）直流耐压试验与泄漏电流试验
表1.3  油浸纸绝缘电缆直流耐压试验标准   注：UN为额定电压
电缆额定电压（UN）	试验电压电 压 （KV）
新安装	运行中
1～3KV
35KV	6UN
5UN	5UN
4UN
试验时间（min）	10	5
表1.4  油浸纸绝缘电缆泄漏电流参考值
电缆芯数	工作电压
（KV）	试验电压
（KV）	泄漏电流（μA）
新安装	运行中

85
50
30
20
20
—
120
75
50
50
三芯	35
10
6
3
1	140
50
30
15
5
注：本表适用于长度为250m及以内的电缆，电缆长度超过250m时，其泄漏电流与长度成正比，可适当增加。
测量泄漏电流时，因在直流耐压过程中0.25.0.5.0.75.1.0倍试验电压下，各停留1min试取泄漏电流值。其参考值见表1.4
2.橡皮绝缘电缆的试验标准
（1）绝缘电阻的试验
橡皮绝缘电缆的绝缘电阻：高压应大于12MΩ（用2.5KV 摇表）；低压应大于2MΩ（用1KV 摇表）
（2）耐压试验
耐压试验标准见表1.5
表1.5  橡皮绝缘电力电缆耐压试验电压标准
类  别	额定电压（KV）	试 验 电 压（KV）	试验持续时间（min）
交  流	0.127
0.380
0.660
1.14
6	2.4
2.5
3.0
3.7
15.0	5
直  流	1
6	额定电压的3.5倍	5
3.胶联聚乙烯电缆的试验标准
（1）绝缘电阻试验
表1.6  胶联聚乙烯绝缘电缆绝缘电阻值
额 定 电 压（KV）	电 缆 截 面（m㎡）
16～35	50～90	120～240
绝缘电阻值（MΩ）
6
10
15	1000
2000
3500	750
1500
3000	500
1000
2500
（2）直流耐压试验
胶联聚乙烯绝缘电缆直流耐压参考值见表1.7
表1.7   胶联聚乙烯绝缘电缆直流耐压参考值
电缆额定电压（KV）	试验电压（KV）	试验时间（min）
6
10
35	15
25
85	15
15
15
注：表1.7中数值为换算到长度为1Km、温度为20℃时的绝缘电阻值。
七、电气绝缘安全用具的试验项目、周期和标准
（一）试验周期（见下表）
序号	试品名称	试品试验性质和周期
新品	使用中
1	绝缘手套	使用前	1年1次
2	绝缘胶靴及胶皮绝缘垫	使用前	1年1次
3	绝缘台	使用前	1年1次
4	绝缘拉杆	使用前	1年1次
5	高压验电笔	使用前	1年1次
6	放电棒	使用前	1年1次
7	绝缘类	使用前	1年1次
（二）试验标准
1.绝缘手套、绝缘胶靴及胶皮绝缘垫的试验标准如下：
序号	试品名称	交流耐压试验电压（KV）	耐压时间（min）
新品	使用中
1	绝缘手套	12	8
2	绝缘胶靴及胶皮绝缘垫	20	15
2.绝缘拉杆、绝缘夹、放电棒等的试验标准如下：
电压等级（KV）	试验电压（KV）	试验时间（min）

5-10	40	5
20-35	105	5
35及以上	200	5
注：在做绝缘手套、绝缘靴试验时，手套上口应露出水面50mm；绝缘靴上口应露出水面约20mm。
八、绝缘油的试验项目、周期和标准
（一）绝缘油的试验项目和周期
1.绝缘油的电气击穿强度试验
（1）运行中5600KVA以上的变压器、厂用变压器， 每半年一次。其它35KV及35KV以上的电气设备，每年至少进行一次。
（2）运行中35KV以下的电气设备，每两年至少进行一次。
（3）设备新装和大修前、后，应进行油的电气击穿强度试验。
（4）油断路器多次故障跳闸后，应取油样试验。
2.绝缘油的介质损失角正切值试验
（1）运行中5600KVA及以上的变压器， 每半年一次。
（2）准备注入电气设备的新绝缘油。
（3）充油电气设备在运行中绝缘油显著劣化或介质损失角正切值增大时。
（二）绝缘油的电气试验标准
1.电气击穿强度试验标准
（1）用于15KV以下的电气设备
新油和再生油电气击穿强度应在25KV以上；运行中的油电气击穿强度应在20KV以上。
（2）用于20～35KV的电气设备
新油和再生油电气击穿强度应在35KV以上；运行中的油电气击穿强度应在30KV以上。
（3）用于44～220KV的电气设备
新油和再生油电气击穿强度应在40KV以上；运行中的油电气击穿强度应在35KV以上。
（4）试验方法及注意事项
①绝缘油的电气击穿强度试验用的仪器和用具有升压器、调压器、油杯、电极和温度计等。
②试验温度应接近室温。
③试验前应检查接线是否正确，升压变压器的调压器是否在零位。
④将被试油样接入高压电路中；在被试油和试验变压器的中间串联一个5～10 MΩ的保护水电阻；试验回路应装可靠的过电流保护。
⑤试验时，合上电源；起动调压器（升压速度约为每秒3KV），直至油发生十分明显的火花放电，过流机构跳闸为止。
⑥试验时在相对湿度不大于75%的室内进行，如受条件限制不能在室内进行时，应避免阳光直射而造成击穿电压降低。
⑦为了减少油在击穿时产生的游离碳，在满足一定电压的条件下，尽量采用容量小的试验变压器，并将过流继电器调整到适当数值。
⑧油的击穿电压与作用时间有关，升压时一定要均匀并按每秒3KV左右的速度，否则击穿电压有很大的分散性。
2.介质损失角正切值（%）标准
（1）新油和再生油当温度为70℃时应不大于0.5%。
（2）运行中的油当温度为70℃时应不大于2%。
（3）在常温下测得的数据不大于下列数值（%）时，可不进行70℃时的试验。
20℃测得的tgδ（%）=0.04（新油）；0.11（运行中）；
25℃测得的tgδ（%）=0.05（新油）；0.15（运行中）；
30℃测得的tgδ（%）=0.07（新油）；0.20（运行中）；
35℃测得的tgδ（%）=0.09（新油）；0.27（运行中）；
（4）多油断路器用油，根据需要测量tgδ。
九、电力变压器的试验项目、周期和标准
（一）电力变压器试验项目与试验周期
电力变压器的试验项目与周期见表1.8
表1.8   变压器的试验项目与周期
试验项目	试验周期	备注
绝缘电阻和吸收比测定	1.新装和大修后
2.运行中一年一次
泄漏电流测定	1.新装和大修后
2.运行中一年一次	容量在320KVA及以下者不做此项试验
交流耐压试验	1.新装和大修后
2.运行中按需要进行
（二）电力变压器的试验标准
1.绝缘电阻和吸收比试验标准
测定变压器的绝缘电阻时，变压器的额定电压在1000V以下的用1000V兆欧表，额定电压在1000V以上的用2500V兆欧表，其量程应不低于10000MΩ。测量额定电压为3000V以上的变压器时，也可使用5000V的兆欧表。
对于额定电压为13.8KV或15.7KV的变压器，按3～10KV标准。额定电压为18KV和44KV的变压器，按20～35KV标准。见表2.0
电压在35KV及以下、容量为500KVA及以上的变压器，应测量吸收比R60/R15，当温度在10～30℃的范围内，R60/R15的比值应不低于1.3，电压为35KV以上的变压器，R60/R15的比值应不低于1.5。
表2.0   油浸式电力变压器的绝缘电阻参考值
试验性质	高压线圈电压等级（KV）	温          度（℃）
10	20	30	40	50	60	70	80
新装	3～10
20～35
60～220	450
600
1200	300
400
800	200
270
540	130
180
360	90
120
240	60
80
160	40
50
100	25
35
70
大修	3～10
20～35
60～220	400
540
1080	270
360
720	180
240
480	110
160
320	80
110
210	55
72
140	35
45
90	22
30
60
运行中	3～10
20～35
60～220	360
480
960	240
320
640	150
210
430	100
140
290	70
110
190	50
65
120	30
40
80	20
28
55
2.电力变压器泄漏电流试验标准
电力变压器泄漏电流试验标准见表2.1
表2.1  变压器泄漏电流试验时试验电压标准及泄漏电流参考值
额定电压（KV）	试验电压
（KV）	不同温度下的泄漏电流值
10℃	20℃	30℃	40℃	50℃	60℃
1.2～3
6～15
20～35
35KV以上	5
10
20
40	25
45
72
80	46
72
108
120	65
114
180
200	100
180
290
300	160
300
432
500	260
468
700
800
注：测量未注油变压器的泄漏电流时，其外施试验电压为表2.1中规定的试验电压的50%。
十、隔离开关和母线的试验项目、周期和标准
（一）隔离开关试验项目和周期
隔离开关试验项目和周期见表2.2
表2.2   隔离开关试验项目和试验周期
序号	项   目	周   期	备   注
1	绝缘电阻测定	1.新装和大修后
2.运行中2～4年一次
2	交流耐压试验	1.新装和大修后
2.运行中2～4年一次
3	检查触头情况及弹簧压力	1.新装和大修后

（二）母线的试验项目和周期
母线的试验项目和周期见表2.3
表2.3  母线的试验项目和试验周期
序号	项   目	周   期	备   注
1	绝缘电阻测定	1.新装
2.运行中2～4年一次
2	交流耐压试验	1.新装
2.运行中2～4年一次
3	检查连接部分接触情况	1.新装
2.运行中根据实际需要

（三）试验标准
1.绝缘电阻测定
对于瓷支柱绝缘及可动部分绝缘，用2500V兆欧表测量，所得结果与同类型设备以及以往记录相比较，不应有显著差别。对于有机材料传动拉杆的绝缘电阻不应低于表2.4的规定值。母线绝缘电阻不做具体规定，但各条母线之间与及耐压前后不应有显著的差别。
表2.4  有机材料传动拉杆的绝缘电阻试验标准
试验性质额定电压（KV）	2～15	20～44	60以上
新装和大修（MΩ）	1000	2500	2500
运行中（MΩ）	300	1000	1000
2.交流耐压试验
（1）隔离开关交流耐压试验标准见表2.5
表2.5   隔离开关交流耐压试验标准
试验电压（KV）
额定电压（KV）	2	3	6	10	15	20	35	44	60	110
新装、大修及运行中（MΩ）	16	24	32	42	55	65	95	105	155	250
（2）母线耐压试验
①额定电压在1KV及以上的参照表2.5的标准进行。
②额定电压在1KV以下的交流耐压试验电压为2000V。
3.熔断器试验项目和标准可参照表2.5进行
十一、高爆、低爆开关等试验
（一）高爆开关试验项目
1.交流耐压试验；
2.直流电阻测定；
3.绝缘电阻测定；
4.保护定值的整定。
试验周期：一般每年校验一次。
（二）低爆开关试验项目
1.防爆性能的检查。要求符合煤矿矿用产品安全标志、防爆设备有防爆标志、产品合格证；
2.保护性能的检验与整定；
3.绝缘电阻的测试。
（三）其它
1.信号照明综保试跳一次/天；检漏器试跳一 次/天；煤电钻综保试跳 一次/班。
2.检漏继电器远方人工漏电试验一次/月。
3.低爆开关各种保护试验一次/周。
十二、杂散电流测试
（一）杂散电流测试管理制度
1.测试人员经过培训并取得资格证后方可进行操作和测试。
2.井下使用核相仪器时，必须在瓦斯浓度低于1%以下的地点使用，并且适时监测使用环境的瓦斯浓度。
3.每年对矿井范围内的杂散电流进行测试并且出据相应的试验报告，试验报告保留三年。
4.杂散电流测定仪必须在规定的测量范围内使用
（交流档：0—100mA—500mA—1A—5A）
（直流档：0—100mA—500mA—2.5A—10A—50A）
5.矿井杂散电流测试的要求：小于30mA以下。
（二）杂散电流测定仪使用方法及注意事项
1.测量前，将测试棒接线叉分别旋紧于面板下方两接线柱上，并将连接插两端分别插入面板左方两接线柱中，调节表头指针，使其指示零位。
2.将与接线柱相接的测试棒分别置于待检测的两点（如风管、水管、铁轨和岩石等），将转换开关置于适当档，则表头即指示被测两点之间的杂散电流。
3.当用本仪表测量杂散电压时，可将面板左方两接线柱中的联接插取开。此时表头指示即为杂散电压值（读数时，mA对应mV；A对应V）。
4.测量直流杂散电流时，如表头指针发生反向偏转，拨动面板右上角直流换向开关即可。换向开关拨动方向即是表笔正极方向，
5.在未知杂散电流大小时，应先将转换开关旋至量程最大档，以免误测，损坏仪表。然后在逐步减小量程，直至适当档，读出准确数值为止。测量时，仪表尽量保持水平位置。
6.当被测电流大于5A时，该仪器只宜进行短时测量；当被测电流大于10A时，只能进行瞬时测量。
7.仪表使用完毕后，应将转换开关置于“关”的位置。禁止在野外井下拆开仪表。
十三、远方试跳制度
（一）电检组应根据变电所检修计划的要求，在救护队员、瓦检员、队组电工的协助下对变电所各路总开关进行计划远方试跳工作。
（二）对每一路开关供电最远点的开关进行试跳时，必须首先检查开关周围20米范围内瓦斯浓度，只有瓦斯浓度不大于1%时，方可打开开关大盖。
（三）开关大盖打开后，电工必须对所打开关负荷侧进行验电、放电，确认无电后，方可接入(660V  11KΩ)10W接地电阻。
（四）接地电阻接好后，盖上开关大盖，起动开关，确认变电所总开关跳闸后，说明总开关漏电跳闸，保护灵敏可靠。
（五）在试跳过程中如果出现不动作，必须立即下“通知单”，并监督相关队组整改，及时向领导汇报。
（六）试跳人员应认真做好试跳记录，试跳完毕必须有参加试跳的相关人员签字。
