:PROPERTIES:
:ID:       194f0b2c-536b-48ff-a0a8-13eba71b4236
:END:
#+title: 矿调度室安全生产岗位责任制
* 岗位职责
认真执行党和国家的安全生产方针、法规、政策、规定、指令和文件，严格按照“三大规程”进行指挥生产，安全调度。
* 到位标准
** 参加安全生产检查和矿组织的安全办公会议，根据会议精神，积极落实矿领导交办的安全工作。
** 及时转发上级的安全生产通知、通报和指令，及时向矿领导和上级汇报影响安全生产的重要问题，做到上情下达，下情上报。
** 了解采、掘、机、运、通等生产情况，及时准确向矿领导和上级提供相关的安全生产信息。
** 分析安全生产情况，找出安全生产的薄弱环节，进行重点调度。管理人员定位系统，落实矿长带班下井制度。
** 认真识别安全隐患，督促各科室及现场安全员落实安全措施，并追踪汇报。
** 经常深入现场各作业地点，随时了解掌握生产过程中的各类信息，并反馈给生产矿长和相关领导，便于正确决策，统一指挥、组织好每天的调度会议，坚持按调度会议上的工作安排，抓好具体平衡、督促、落实工作，严格按照生产管理程序，加强对各类生产单位的考核，树立调度统一指挥的权威性。
** 根据矿长指示，负责组织召开调度会，及时督促解决在安全生产中存在的问题。主持召开调度专题会、及时准确下达调度通知、调度命令，按时完成上级调度所要求的各种专题汇报。
** 要熟悉掌握矿井生产各个环节的工艺、布局和设备状况，掌握各作业地点的作业规程或安全技术措施，掌握矿井灾害处理及应急预案的内容，掌握矿井供电、供水、排水、通讯、安全监控等系统的有关情况，当生产环节出现问题和灾变，能立即组织处理抢险救灾。
** 加强调度人员的管理和教育，加强业务培训，加强责任制的落实，努力提高调度人员的技术素质和业务素质，强化调度指挥失误的责任追究制。
** 根据生产情况及时给调度员布置具体工作和重点协调解决的问题，随时检查调度员的工作情况，发现问题及时纠正，规范调度报表，台账和各类纪录，做到记录准确、实事求是，能正确反映采、掘、机、运、通和销售的生产状况和平衡关系。 
** 完善调度室自身建设，做好建章建制和明确业务保安制度，加强现场的安全检查，监督和落实，对重点区域加强防范；严格由下至上的班汇制度和临时交办任务的落实汇报制度；严格按事故报告程序逐级上报矿井发生的各类事故。
* 考核标准
根据《XX单位安全生产岗位责任考核办法》、《XX单位工资管理办法》等相关文件规定，矿调度室安全生产责任制到位标准一项不达标考核XX元。
