:PROPERTIES:
:ID:       b72edae1-0947-451e-8349-52cb014405a8
:END:
#+title: 安全生产岗位责任制考核制度
为进一步规范安全生产管理，强化安全管理人员和从业人员的安全职责，严格执行各项安全管理制度，促进安全生产岗位责任制的落实，杜绝各类违章现象，防止各类事故发生，保障职工生命安全和职业健康，保证矿井安全生产，制定本办法。
* 组织机构
为确保安全生产岗位责任制考核工作顺利开展，矿成立安全生产岗位责任制考核领导小组。
组  长：矿长
副组长: 分管矿领导
成  员：安全科 人力资源科
领导小组下设办公室在人力资源科，人力资源科科长兼任办公室主任，负责安全生产岗位责任制考核日常工作。
* 考核依据
以《[[id:b9ae9739-7d96-4fb7-8f9a-173339c701d5][矿安全生产岗位责任制]]》、《[[id:c538de0c-a879-444c-9f48-74a416c89e2e][矿“三违”处罚办法]]》、《[[id:3a72a033-c900-43fd-88b3-140572619346][矿工资管理办法]]》、《[[id:0bc59331-7132-4e5f-bd03-caaec3b3d983][矿工伤管理办法]]》、《[[id:6b50cd4c-8161-446f-9525-13bab9eb5640][矿安全安全生产标准化管理制度]]》、《[[id:d7c7e1f5-66db-40af-b70d-eef6516f7ab6][矿班组建设考核办法]]》等为考核依据。
* 考核对象及考核方式
** 考核对象：矿属各科室和所有员工。
** 考核方式：每月考核一次。
* 考核内容
** 职能科室安全生产岗位责任制的执行情况；
** 各岗位安全职责的执行情况；
** “三违”行为；
** 责任事故：工伤事故、涉险事故。
* 考核办法
** 职能科室未落实安全生产岗位责任制或执行不到位的，按照相关管理制度考核。
** 各岗位未落实安全生产岗位责任制或执行不到位的，核减个人工资元/次，累加计算。
** 对“三违”人员按照《[[id:c538de0c-a879-444c-9f48-74a416c89e2e][矿“三违”处罚办法]]》规定进行考核。
** 发生责任事故，按照《[[id:3a72a033-c900-43fd-88b3-140572619346][矿工资管理办法]]》、《[[id:0bc59331-7132-4e5f-bd03-caaec3b3d983][矿工伤管理办法]]》的规定进行考核。
* 工作要求
** 队组及各岗位要牢固树立“安全第一”的思想，严格按照《[[id:b9ae9739-7d96-4fb7-8f9a-173339c701d5][矿安全生产岗位责任制]]》的要求逐项做好落实工作，把安全生产责任切实落实到位，确保不发生因安全生产岗位责任制不落实而造成的事故。
** 考核小组必须尽职尽责，客观公正、遵守实事求是的原则。
** 每月考核结束后，领导小组办公室出具奖罚清单报矿领导审批后执行，并将考核结果通报全矿。
