:PROPERTIES:
:ID:       9a6d9967-aeb3-46fc-8eaa-b8d6cb0c799b
:END:
#+title: 安全监测工安全操作规程
* 适用范围
** 本操作规程适用于各类煤矿的井下安全监测工。
** 井下安全监测工应完成下列工作：
*** 负责管理范围内的矿井通风安全监控、装置的安装、调试、维修、校正、监测等工作。
*** 应将在籍的装置逐台建账，并认真填写设备及仪表台账、传感器使用管理卡、故障登记表、检修校正记录。
*** 负责矿井监控系统图、断电控制图的绘制、修正。
* 上岗条件
安全监测工必须经专业技术培训，取得煤矿安全监测监控操作资格证后，持证上岗。
* 对监测工操作规定
监测工每天对监控设备及电缆进行安全检查，对各类传感器的准确性要用光干涉瓦斯检定器进行核实、比较，发现问题及时处理、汇报。安全监控设备必须按规定进行调试、校正，每月至少一次。甲烷传感器、便携式甲烷报警仪等采用载体催化元件的甲烷检测设备，15天必须使用校准气样和空气气样调校1次，采用激光原理的甲烷传感器等，每6个月至少调校1次。
* 操作准备
** 地面检修前的准备工作：
*** 备齐必要的工具、仪表，并备有设备说明书和图纸。
*** 按规定准备好检修时所需要的各种电源、连接线，将仪表通电预热，并调好测量类型和量程。
*** 按规定准备好检修时所需要的各种电源、连接线，将仪表通电预热，并调好测量类型和量程。
** 井下安装前的准备工作：
*** 根据要求确定安装位置和电缆长度。
*** 设备各部件应齐全、完整，电缆应无破口，相间绝缘及电缆导通应良好，并备足安装用的材料。
*** 瓦斯标准气样应采用煤炭工业技术监督主管部门确认甲烷与空气的混合气体，不确定度应小于5%，制备所用的原料气应选用浓度不低于99.9%的高纯甲烷气体。
*** 通电试验下井设备，调试确定各功能指标符合要求，并在地面试运行24h--48h后方可入井使用。
** 传感器调试标校及断电试验前的准备工作：
*** 测试、调校前一天，必须对所需测试、调校地点做出测试、调校申请，并传送相关队组，方便相关队组接到测试、调校申请后，提前安排。
*** 准备调校器材包括：1%--2%校准气体、配套的减压阀、气体流量计和橡胶软管、空气样，并检查器材是否完好。
* 传感器调试标校及断电试验
** 甲烷超限断电功能与标校甲烷传感器时在现场进行，并做好记录。监测工标校甲烷传感器需严格按照标校程序，调校零点、显示值（调校时，应先在新鲜空气中或使用空气样调校零点，使仪器显示值为零，再通入浓度为1%-2%CH4的甲烷校准气体，调整仪器的显示值与校准气体浓度一致，气样流量应符合产品使用说明书的要求），同时观察传感器的报警点、断电点、复电点及控制逻辑。并遵守下列规定：
必须使用按国家有关标准要求配制的标准气样，标准气样的相对误差必须小于5%，所进标准气样必须经气体色谱分析仪校队无误后方可使用。空气可以直接从地面新鲜空气中取。
标校前须提前汇报监测中心值班员，得到许可后方可进行。标校时将气瓶垂直于巷道底板放置好(流量调节阀朝上，瓶体朝下)；将待调校传感器取下放至巷道底板，检查甲烷传感器外观是否完好，并清理表面及气室周围积尘，打开进气罩遮挡片；空气样用橡胶软管连接传感器气室；调节流量控制阀把流量调节到传感器说明书规定；调校零点，范围控制在0.00-0.03%CH4之内；校准气瓶流量计出口用橡胶软管连接传感器气室；打开气瓶阀门，先用小流量向传感器缓慢通入1%-2%CH4校准气体，在显示值缓慢上升的过程中，观察报警值和断电值（气瓶压力表显示压力数值在0～3兆帕之间）；然后调节流量控制阀把流量调节到传感器说明书规定的流量，使其测量值稳定显示,与校准气浓度值一致持续时间大于90s，使显示值与校准气浓度值一致，若超差应更换传感器，预热后重新测试；在通气的过程中，观察报警值、断电值是否符合要求，注意声、光报警和实际断电情况。 当显示值小于1.0%CH4时，测试复电功能；测试结束后关闭气瓶阀门,拔出充气嘴，关闭传感器进气口盖。做好现场记录及地面记录，并核对调校时间是否正常，核对断电是否正常。
** 应按照规定每15天进行甲烷电闭锁试验。进行甲烷电闭锁试验时，试验地点的施工队组必须派电工在开关处观察闭锁情况，试验停电后及时送电确保试验效果，发现闭锁异常配合监测监控工及时进行处理，处理完毕后进行补充试验，确保甲烷电闭锁试验断电可靠。甲烷电闭锁试验必须使用标准气样和空气样进行调试，并有调校记录。为了确保安全生产，试验期间井下各队组严禁使用绞车，采煤机、综掘机等大型设备必须停止运行。
** 每次做甲烷电闭锁试验、标校传感器时，监控中心值班人员必须提前1小时通知上级通风部门和所在县市安全监控中心，同时汇报矿调度，并注意观察断电情况，试验完毕后再次汇报试验情况。
** 除甲烷以外的其它气体监控设备应采用空气样和标准气样安产品说明书进行调校。风速传感器选用经过标定的风速计调校。温度传感器选用经过标定的温度计调校。其它传感器和便携式监测仪器应按使用说明书要求进行调校，所有调校、校准必须都有记录。
** 强制计量检定的设备仪器仪表，必须制定送检计划，按期送检，其它仪器仪表按出厂说明书的要求进行检定。
* 分站、传感器安装操作
** 安装分站时，严禁带电作业，严禁带电搬迁或移动电器设备及电缆，并严格执行谁停电谁送电制度。
** 所停电的高压开关馈电处，必须派专人看管，并挂上“有人工作，严禁送电”的标示牌。
** 停电范围影响到其他队组的，要取得联系，做好协调工作。
** 处理分站高压侧时，严禁一人单独作业（严格执行停送电制度）。
** 安装断电控制系统时，必须根据断电范围要求，接通井下电源及控制线。
** 安全监控设备的供电电源必须取自被控开关的电源侧或专供电源，严禁接在被控开关的负荷侧。
** 传感器在安装或拆除时，高处必须用梯子或木马，扶牢后，再上人安装或拆除。具体安装位置：距顶不大于300mm，距帮不小于200mm。若巷道中有胶带输送机或刮板输送机时，必须和所管辖队组的主要负责人联系安装时间，安装时必须和胶带输送机或刮板输送机司机联系好，停下运输机后，不安装完毕不准开机。严禁输送机运转中安装传感器。
** 传感器或井下分站的安设位置符合《煤矿安全规程》第一百六十八条规定和AQ1029-2019 煤矿安全监控系统及检测仪器使用管理规范要求。安装完毕，在详细检查所用接线、确认合格无误后，方可送电。井下分站预热15分钟后进行调整，一切功能正常后，接入报警和断电控制并检验其可靠性，然后与井上联机并检验调整跟踪精度。
** 分站应放置在便于人员观察、调试、检查及支护良好、无滴水、无杂物的进风巷道或硐室中。
** 分站和过渡电缆及各种传感器之间的接头一定要封闭在接线盒内，以免失爆。
** 分站和分站的电源、蓄电池不能置于地上，使用专用的托架，使其距巷道底板不小于300mm，供电电源必须取自供电电源的电源侧。
** 分站和过渡电缆连接的接线盒固定在分站的托架上，以避免行人将电缆弄乱、拽断等。
** 分站的蓄电池必须保持一定的电量，电网停电后，系统至少能够正常工作两个小时以上。
** 分站由专人负责，每天检查、维护，发现问题立刻解决。
** 瓦斯传感器应垂直悬挂，距顶板（顶架）不得大于300mm，距巷道壁不小于200mm，风速、压差、温度、一氧化碳传感器应悬挂在能正确反映该点测值的地点。
** 装置在井下连续运行不得超过规定。
** 使用过程中应保持传感器清洁，确保仪器正常运行，严禁非工作人员擅自调校和拆开仪器。
** 对需要经常移动的传感器、电缆等由专人负责，按规定移动，严禁擅自移动。
** 当瓦斯浓度超过规定而切断电器设备的电源后，严禁自动复电，只有当瓦斯浓度降到《规程》规定以下时，方可人工复电。
** 严格按分站规定的配接表来接传感器，不得超出配接表规定的数量。
** 各部件的可调整部分，已封胶的不允许拆动，必须做出调整时，要严格按部件说明书要求调整。
** 甲烷传感器报警浓度、断电浓度、复电浓度和断电范围必须符合《煤矿安全规程》第一百六十八条规定。
** 拆除或改变与安全监控设备关联的电气设备的电源线及控制线、检修与安全监控设备关联的电器设备、需要安全监控设备停止运行时，须报告矿技术负责人及调度室，并制定安全措施后方可进行。
* 特殊操作
** 排除故障时应注意以下问题：
*** 应首先检查设备电源是否有电。
*** 可用替换电路板的方法，逐步查找故障，替换电路板时，要切断电源进行。
*** 应1人工作，1人监护。严禁带电作业。并认真填写故障处理记录。
** 瓦斯断电仪投入正常使用后，严禁随意进行试验。若需试验必须提前申请，经矿技术负责人批准后，方准进行试验。
** 断电试验完毕后，要等所断电范围内电源全部恢复正常时，试验人员方准离开现场。
** 传感器和分站出现故障，处理不了的要及时更换。
* 收尾工作
** 安装好后，严格按照质量标准、防爆标准进行检查，确定无误后方准收工。
** 做好记录，汇报工作进展情况。
** 做好交接班的有关事项。
