:PROPERTIES:
:ID:       a22d6629-38f1-4f73-8f9c-1fe2c531fc90
:END:
#+title: 安全教育培训管理制度
为进一步加强安全教育培训管理，切实抓好安全教育培训工作，提高全员安全素质和业务技能，促进安全教育培训工作制度化、规范化，确保安全生产，根据《[[id:08fba9cc-1342-4aaf-a4dd-96f34470aeca][安全生产法]]》、《[[id:a0f5bc0e-ecda-4309-b5d4-c2bd3a35a6f3][安全生产培训规定]]》（国家安监总局3号令）、《[[id:83a86661-34d3-47cf-b121-f100ebea047e][特种作业人员安全技术培训考核管理规定]]》（国家安监总局30号令）《[[id:15b24e7a-5e69-41b3-9b99-9c8983c53888][安全生产培训管理办法]]》（国家安监总局44号令）、《[[id:f58d5433-a5f4-46e5-aeae-fbbb3e734b4d][煤矿安全培训规定]]》（国家安监总局92号令）及煤矿安全生产标准化基本要求和培训大纲规定，结合矿实际，制订本制度。
* 组织领导
为加强对安全教育培训工作的组织领导，确保安全教育培训顺利开展和取得实质性效果，矿成立安全教育培训领导小组和管理小组。
** 安全教育培训领导小组
组 长： 矿 长
副组长：副矿长
成 员：各专业副总工程师
** 安全教育培训管理小组
组 长：安全副矿长
副组长：安全科科长
成 员： 科室负责人 、队组负责人
管理小组下设办公室在安全科，安全科科长任办公室主任，负责全矿安全教育培训日常管理工作。
* 培训机构设置
** 按照《[[id:f58d5433-a5f4-46e5-aeae-fbbb3e734b4d][煤矿安全培训规定]]》，设立矿安全培训中心，配备专职安全培训管理人员和相关工作人员，负责矿安全培训工作。
** 按照《[[id:f58d5433-a5f4-46e5-aeae-fbbb3e734b4d][煤矿安全培训规定]]》，设立或明确负责安全培训工作的机构，配备专职安全培训管理人员和相关工作人员，负责矿安全培训工作。
** 矿安全科负责监督、检查、考核、指导队组安全培训工作。
* 人员配备
** 矿安全科按照《[[id:f58d5433-a5f4-46e5-aeae-fbbb3e734b4d][煤矿安全培训规定]]》、《[[id:7faa94f1-02d9-44f7-9f91-dc336d055808][安全培训机构基本条件]]》要求，配备专职安全培训管理人员专职安全培训工作人员。
** 矿安全科应结合安全培训的需要，按照《[[id:7faa94f1-02d9-44f7-9f91-dc336d055808][安全培训机构基本条件]]》要求，配备专兼职教师。
** 矿安全科负责专兼职教师的聘任、考核和建档工作。各培训机构应根据需求组建结构合理、数量满足的师资队伍。
* 档案管理
** 矿安全科按规定建立健全从业人员安全培训档案，实行一人一档。煤矿企业从业人员安全培训档案的内容包括：
学员登记表，包括学员的文化程度、职务、职称、工作经历、技能等级晋升等；身份证复印件、学历证书复印件；历次接受安全培训、考核的情况；安全生产违规违章行为记录，以及被追究责任，受到处分、处理的情况；其他有关情况。煤矿企业从业人员安全培训档案应按照《[[id:5e1c3313-c352-48d3-81e9-74c1656ac236][企业文件材料归档范围和档案保管期限规定]]》（国家档案局令第十号）保存。
** 煤矿企业除建立从业人员安全培训档案外，还应建立企业安全培训档案，实行一期一档。煤矿企业安全培训档案内容包括：
培训计划，培训时间、地点，培训课时及授课教师，课程讲义，学员名册、考勤、考核情况，综合考评报告，其他有关情况。
实行一人一档煤矿企业从业人员安全培训档案保管期限为30年；对特种作业人员的培训档案应保存6年以上；其他从业人员的培训档案应保存3年以上。
** 每期安全培训考核结束后一周内完成当期培训档案的建立。
** 每期安全培训档案管理人员，负责档案资料的收集、整理和查阅登记等管理工作。
* 安全教育培训范围、内容及规定
** 培训的范围
基层各队组、安全生产业务科室的中层管理人员和从事安全生产经营活动的所有人员。
** 培训内容及规定
*** 煤矿主要负责人、安全生产管理人员必须具备煤矿相关专业大专以上学历，煤矿相关工作3年以上经历并有任职文件，在任职6个月内必须经培训、考核，办理有效证件。
- 培训时间48学时，复训时间16学时。
- 培训考核内容：国家安全生产方针、政策和有关安全生产的法律、法规、规章及标准；安全生产管理、安全生产技术和职业健康基本知识；重大危险源管理、重大事故防范、应急管理和事故调查处理的有关规定；国内外先进的安全生产管理经验；典型事故和应急救援案例分析；伤亡事故报告、统计及职业危害的调查处理方法；其他需要的内容。
- 考核标准：计算机考试不低于80分为合格。
- 主要负责人、安全生产管理人员由矿安全科按照上级部门《[[id:802597a3-bbc6-49e7-8aaf-750ce0a53f04][2022年煤矿主要负责人、安全生产管理人员培（复）训计划表]]》组织到上级培训中心进行培（复）训。
*** 矿特种作业人员的安全培训由矿安全科按照《特种作业人员安全技术培训考核管理规定》的要求和培训大纲的规定及××矿年度安全培训计划组织实施。
- 特种作业人员必须年满18周岁，具有高中及中技以上文化程度，具有煤矿相关工作经历，经过体检合格方可参加培训。
- 培训时间不少于90学时，复训时间24学时。培训内容按照培训大纲规定执行。
- 考核标准：理论、实操考试不低于80分为合格。
*** 从业人员的安全培训由矿安全科按照《[[id:f58d5433-a5f4-46e5-aeae-fbbb3e734b4d][煤矿安全培训规定]]》要求和培训大纲规定及××矿年度安全培训计划组织实施。
- 从业人员必须年满18周岁，具有初中以上文化程度，经过体检合格方可参加培训。
- 培训时间72学时，复训时间20学时。
*** 班组长的安全培训由矿安全科按照《[[id:f58d5433-a5f4-46e5-aeae-fbbb3e734b4d][煤矿安全培训规定]]》要求和培训大纲规定及年度安全培训计划组织实施。重点突出班组长的素质能力培训。
培训时间72学时，复训时间20学时。
*** 其他安全培训按照相关规定和职责分工分别组织实施。
* 矿培训中心职责
** 认真执行国家煤监部门对煤矿安全培训工作所规定的培训大纲和教学计划，全面贯彻国家有关煤矿安全生产的各项方针、政策、法律、法规、指令和决定。
** 拟定培训中心各工作人员岗位职责，不断完善各项管理制度，加强工作人员及教师的德、能、勤、绩考核工作。
** 在上级有关部门的指导下，负责组织培训项目，安排任课教师，确定正常的教学秩序，并做到期期有闭幕，班班有总结，有改进、有提高。
** 负责培训中心的日常事务工作，注意收集和处理煤矿安全培训工作的信息，使培训工作与矿安全生产需要紧密结合。
** 加强师资队伍建设，负责拟定教师的聘请、增补及培训计划，切实保证培训工作的正常教学秩序，努力建设一支即有理论知识又有现场工作实践经验的教师队伍。
** 积极主动搞好安全培训及其办证工作，认真组织开展有计划、常态化、全面化、系统化和规范化的安全教育培训，提供优质的培训服务。
** 负责对各队组安全培训工作情况进行指导、监督、检查、考核，按要求完成矿下发的安全教育培训任务。
* 矿培训计划制定及实施
** 矿主要负责人负责组织制定并签发的年度安全教育培训计划，组织相关科室和人员具体实施。
** 矿安全科负责汇总拟定矿年度安全教育培训计划，矿年度安全教育培训计划以矿发文件形式下发实施。
** 矿主要负责人应根据年度安全教育培训计划积极组织实施。
** 矿安全教育培训的实施
*** 矿安全培训工作由安全科负责培训组织，各专业科室及相关专业专（兼）职教师负责培训，一切培训必须采取脱产培训，坚持“真培训、真考核、真成绩”的原则，切实做好区科安全生产管理人员、特种作业人员、班组长及从业人员的安全培训，尽职尽责组织完成安全培训任务。
*** 按照“干什么学什么、缺什么补什么”的原则，做到培训计划、费用、教材、人员、考核、效果“六落实”，保证培训实效。
*** 领导小组要加强安全教育培训的教学研究，加强“师带徒”等培训，创新培训方法，拓宽培训渠道，构建交流平台，提高安全教育培训的针对性、实效性。
*** 授课教师在接到培训通知后，根据每期培训对象、内容，认真编制教案，培训教案由培训中心存档。同时，要认真做好备课、讲课。备课要突出重点，结合实际，有针对性、实用性；讲课要通俗易懂，条理清晰。每期培训要让参培人员人人持有相配套的复习资料，复习资料由授课老师提供，由培训中心统一印发到职工手中。
*** 授课教师在安排培训内容上，要结合矿安全生产实际和职工文化水平现状，坚持理论与实践相结合、与老工人“传、帮、带”相结合、与安全知识竞赛、与安全技术比武活动等相结合，充分使用好职工实际操作培训基地，使安全培训达到人性化、实效性的要求。
*** 职工培训考试（考核）合格后，上岗前各队组可以采取适当方式进行抽查测验，跟踪考核，不具备上岗能力的不得安排上岗，报矿领导批准后重新培训。
** 各基层队组安全培训的实施
*** 队组队长对职工安全教育培训负总责，队组技术员具体负责，并有计划地认真组织开展职工安全教育培训。
*** 矿组织编制安全教育培训年度计划，建立健全相应的管理制度和培训档案，详细、准确记录培训考核情况。矿举办的各类安全教育培训计划、培训考勤表、课程安排表、考卷、成绩汇总表等档案资料必须完善备查。
*** 矿要有计划地实施培训，在抓好管理人员、职工专业理论知识培训的同时，要结合安全生产工作实际，认真抓好日常安全教育和学习，抓好规程措施的落实、处理安全隐患能力及工作中的安全注意事项等方面的培训。
*** 生产队组要按规定开展好班前会和井下现场班前小会。队长主要负责人在每天的班前会上必须安排安全生产工作，并组织开展“每日一题、每日一问”安全培训活动。各队组根据实际情况，班前小会上安排工作时必须安排安全工作，强调安全注意事项，开展好“每日一题、每日一问”等安全培训活动，认真抓好现场提问培训工作。安全科要对各队组班前会、井下现场班前小会、队长现场提问培训等进行监督检查。
* 安全培训管理考核及奖罚
** 安全培训季度考核
*** 为了让煤矿安全培训工作更好地服务于安全生产管理，使煤矿安全培训工作更加规范管理，经矿安全技术培训每季度后第一个月初对矿各队组的安全培训工作进行专项检查，检查内容为：根据国家及省市、县对安全培训工作检查标准、符合各队组安全培训可行性工作职责范围。
*** 为使安全培训检查季度考核工作公平起见，对矿各队组进行两个组划分来进行综合考核排名。
- 生产组：采煤、掘进队（评选出前二名及最后一名）；
- 辅助组：机电运输、巷修、综合、打钻队（评选出前二名及最后一名）；
** 安全培训奖罚
*** 安全培训季度考核根据评分标准评选出名次给予安全培训做的好的队组奖励，对最后一名给予处罚，具体实施如下：
- 生产组：第一名：奖励该队组XX元；第二名：奖励XX元；
- 最后一名：核减该队组工资薪酬XX元；
- 辅助组：第一名：奖励该队组XX元；第二名：奖励XX元；
*** 最后一名：核减该队组工资薪酬XX元；
*** 矿安全科培训中心组织各类脱产培训时，要提前2天通知相关队组，并建立通知记录。队组认真合理安排好人员参加，不得缺勤。如有无故不参加培训的应培人员，每缺一名核减该队长工资薪酬各X元，累计计算；应培人员当天视为旷工并核减薪酬XX元；缺勤1天取消当期培训资格，矿安全科培训中心将安排重新进行培训，直至培训合格为止。
*** 培训期间，学员必须自觉爱护教室卫生，严格遵守纪律，对迟到、早退、上课睡觉、缺课等行为，每次核减工资薪酬XX元，累加计算。酒后一律不准进入教室，并视为缺课处理。
*** 对班队长实行挂牌上岗管理，着力抓好班队长的教育培训，帮助班队长尽快成长，提高班队长的综合素质，形成班队长教育培养、选聘、使用考核机制。
*** 矿安全科培训中心和各队组职工培训结束后，必须按要求进行考试（每次考试满分为100分，60分为及格），考试不及格的进行补考；补考不及格的，转入下期培训，并经考试合格后方可上岗；第二次补考仍不及格的职工，严禁安排上岗，继续接受强制培训，直到培训考试合格为止。脱产培训期间工资按待岗工资支付。对文化低、无书写能力的职工，可采取口头问答的方式进行考试或考核，并做好记录存档备案。
*** 因重视不够、管理不善、落实不到位，影响安全培训质量和效果，甚至影响安全生产的，严格按照《责任追究制度》追究主要责任人。
