:PROPERTIES:
:ID:       50aea608-445c-47a7-8712-13658727838a
:END:
#+title: 生产安全事故隐患排查治理制度
为认真贯彻“安全第一，预防为主，综合治理”的安全生产方针，有效排查治理生产安全事故隐患（以下简称“事故隐患”），保证矿井安全生产，根据《[[id:4393e9ee-72d3-4f1a-874f-3992117f40b0][中华人民共和国安全生产法]]》、《[[id:e7f7150e-dace-4698-a411-a592c7906663][国务院关于预防煤矿生产安全事故的特别规定]]》（国务院令第446号）、《[[id:1fdcf316-13fd-4080-94b0-189e98f18c2a][安全生产事故隐患排查治理暂行规定]]》（国家安全监管总局令第16号）等法律法规及规章制度要求，强化责任落实，及时消除上级部门及矿排查的隐患，切实实现隐患闭环管理，有效防止事故的发生，确保矿安全、稳定、持续、健康发展，结合矿实际，制定本制度。
* 矿成立事故隐患排查治理领导小组
组  长： 矿 长
副组长：副矿长 总工程师
成  员：副总及各队组负责人
领导小组办公室设在安全科，安全科科长兼任办公室主任。
* 职责范围
** 矿长：
*** 对矿井事故隐患排查治理工作全面负责；
*** 负责组织编制矿井事故隐患年度排查计划；
*** 每月组织分管负责人及安全、生产、技术等业务科室、生产队组相关管理人员开展一次覆盖生产各系统和各岗位的事故隐患排查；
*** 每月组织召开事故隐患治理会议，对隐患治理情况进行通报，分析事故隐患产生的原因，提出加强事故隐患排查治理的措施。
** 安全副矿长：
*** 协助矿长抓好全矿事故隐患排查治理工作，按要求对事故隐患排查治理工作进行监督考核及责任追究；
*** 每旬组织相关管理人员对分管领域进行一次全面事故隐患排查。
** 生产副矿长：
*** 对矿井掘进、巷修及分管范围的顶板管理，矿井掘进工作面开口往里地段、巷修工作面范围内机电运输设备、设施（6KV及以上电压等级除外）等方面的事故隐患排查治理工作负分管责任；
*** 每旬组织相关管理人员对分管领域进行一次全面事故隐患排查。
** 总工程师：
*** 对全矿事故隐患排查治理的技术工作负责；
*** 对矿井一通三防、地质灾害防治与测量、应急救援等方面的事故隐患排查治理工作负分管责任；
*** 每旬组织相关管理人员对分管领域进行一次全面事故隐患排查。
*** 水害防治、技术资料检查。
** 机电副矿长：
*** 对矿井机电设备、运输、供电系统、机电硐室、矿井主运煤（运矸）线路、6KV及以上电压等级的机电运输设备、设施的管理工作、90KW及以上绞车提升运输设备设施、单轨吊及架空乘人装置设备设施等方面的事故隐患排查治理工作负分管责任；
*** 每旬组织相关管理人员对分管领域进行一次全面事故隐患排查。
** 副总工程师：
*** 负责协助总工程师和分管矿领导组织对分管领域内开展事故隐患排查治理工作；
*** 参与事故隐患治理方案、措施的制定。
** 安全科：
*** 负责管理全矿隐患排查治理工作，对矿井事故隐患排查治理工作负责监督、检查及考核，按矿每月事故隐患治理会议要求，编制会议纪要和月度事故隐患统计分析报告；
*** 负责地方安全监管监察部门、矿督察、检查和矿自查查出的隐患整改落实、复查、验收和闭环管理工作；
*** 负责建立矿井事故隐患台账，做好重大事故隐患信息档案和事故隐患排查治理工作相关资料的收集、整理、统计、归档管理和上报工作；
*** 牵头组织开展安全检查和事故隐患排查工作。
** 班组、岗位人员职责：班组每班进行工作场所的隐患排查，岗位人员对本岗位作业场所随时进行事故隐患排查，对排查出的隐患进行整改，不能立即整改的汇报矿调度，落实责任人进行整改，并做好相关记录。
** 办公室工作职责：
*** 负责对各队组安全生产隐患排查与治理的日常管理工作。
*** 负责组织和牵头开展各类隐患排查工作。
*** 负责严格按照“五落实”（即：落实整改责任、措施、资金、时限、预案）要求，对隐患整改情况进行跟踪，实现隐患闭环管理。
*** 负责对重大隐患进行挂牌管理和治理全过程跟踪，随时监控，建立动态隐患监控机制。
*** 负责对上级部门查出隐患，按照隐患的性质、危害程度、管理权限进行分级、分类、汇总、整理、建档、销号管理工作。
*** 负责建立安全生产隐患排查与治理信息管理台账，通过数据分析反映隐患排查与治理现状。
*** 负责整理、上报上级部门隐患排查整改情况。
*** 隐患排查与治理专业组工作职责
- 分管领导对分管专业隐患排查、指导和监督工作负责。
- 矿长每月至少对分管专业进行一次隐患排查治理工作，对存在的隐患全面排查，做到不留死角、不留盲区。
- 各分管领导全面掌握各分管专业存在的安全生产隐患的数量、地点及其现状，及时跟踪整改进展情况。
- 对排查出的隐患严格按照“四定表”（即：定人员、定措施、定时间、定整改情况）和“五落实” （即：落实整改责任、措施、资金、时限、预案）进行汇总和监督整改，并将整改情况报安全科备案存档。
- 上级部门检查出本专业的隐患，必须组织落实整改，制定治理措施。组织召开会议，落实整改措施和解决所需的人、财、物，并确保按照要求整改完毕。
- 对“一通三防”重大安全生产隐患实行挂牌督办，并对整改队组进行业务指导，审核整改方案，分析产生原因和危害程度，针对整改方案的缺陷和漏洞提出改进意见。
- 各隐患排查与治理专业工作组组织对分管专业存在的隐患进行验收和销号处理。
* 事故隐患分类
** 本制度所称的重大隐患，是指矿井的生产、安全系统、安全装备、安全设施、安全制度、安全措施不健全、不落实和违反国家、行业、企业有关法律、法规、规程规定，有可能造成重大事故的隐患。应当全部或局部停产，并经过一段时间整改治理方能排除的隐患，或者因外部因素影响致使责任队组自身难以排除的隐患。矿井重大事故隐患认定依据是《煤矿重大安全生产事故隐患判断标准》（国家安全生产监督管理总局令第85号）。
** 本制度所称的一般事故隐患，是指危害和整改难度较小，发现后能够立即整改、排除的隐患。一般事故隐患按严重程度、解决难易程度分为A、B、C三级。
- A级：难度大，矿井解决不了，必须由上级部门帮助解决的安全隐患。
- B级：难度较大，队组、业务科室解决不了，需由矿井解决的安全隐患。
- C级：为队组、业务科室可以解决的隐患。
** 按事故隐患的种类，事故隐患分为采煤、掘进、巷修、“一通三防”、机电运输、防治水、矸石山、地质灾害、安全管理、地面安全、其它。
** 矿长对重大隐患的排查与治理工作全面负责。总工程师负责重大隐患的排查与整改措施的编制；各分管矿领导负责分管范围内的重大隐患的整改工作；各业务科室负责业务范围内的重大隐患排查与治理；安全生产隐患的排查、治理全面负责，是安全生产隐患的排查和治理工作的直接责任者；安全科负责重大隐患排查与治理工作的监督检查与责任追查。
* 隐患排查要求及报告程序
** 采取有效措施，消除隐患。煤矿对排查出的问题和隐患，企业要建立台账，并按照整改措施、责任、 资金、时限和预案“五落实”的要求，及时消除隐患，对重大隐患要按照规定上报。
** 机运科、通风科等各业务科室每周进行一次业务范围内的隐患排查，并于每周日前报安全科，安全科分类整理呈报分管领导，并将存在隐患分发到责任队组落实整改。
** 安全科每天下午17时以前, 将当天隐患排查和治理情况报安全副矿长签字确认并在调度会进行通报。
** 矿每周组织一次隐患排查，班组每班必须组织一次工作范围内的隐患排查，队组必须建立隐患登记、处理档案，班组必须填写好隐患记录本，同时做好汇报记录。
** 矿每周日必须将自查隐患汇总报安全科，隐患内容必须真实、具体，不得敷衍了事。阐述隐患必须说明隐患地点、造成原因、处理措施、负责人、预计完成时间。安全科严格对监管范围的安全隐患进行排查、统计，督促、追踪落实整改，并分类汇总，逐级上报。
** 对所排查出的重大事故隐患，由安全副矿长负责组织编制整改措施，报矿长办公会议审定后，由各分管副矿长组织落实整改。
** 事故隐患的确认与上报。矿、队在日常安全检查的基础上，每月组织一次矿井事故隐患等级的确认。按级别和类别每月逐级上报，A、B级事故隐患由安全科汇总报上级部门，A级事故隐患同时报上级主管部门。隐患在未整改完成前，必须每次都报，直至隐患整改完成。
** 矿领导严格按照责任分工进行全面隐患排查活动。将查出的隐患按专业分类整理，按照轻重缓急、严重程度。分为停产整顿、边生产边整改和限期整改三类。并以“安全检查四定表”或“整改通知书”下发到责任队组，由责任队组负责人签字组织落实整改。各职能部门随时进行跟踪督查，验收。直到隐患彻底消除，方能组织生产。
** 每月由安全科牵头，对矿井下进行一次全面性的安全生产标准化检查验收工作。重点检查规程、措施兑现情况，有无安全隐患。评定出优胜的采掘工作面和专业，对有重大安全隐患的取消评级资格，并责令停产整改。各专业必须写出书面报告，如实向矿领导报告检查过程中的各种隐患，同时对安全生产系统的安全状况进行综合评价。
