:PROPERTIES:
:ID:       454e6ddc-6292-4e1c-a933-a950352f9b2b
:END:
#+title: 综合防尘管理制度
* 总  则
** 为进一步加强矿井综合防尘管理工作，改善井下工作环境，防止粉尘超限，杜绝粉尘积聚和飞扬，确保矿井安全生产。特制定矿综合防尘管理制度。
** 制定矿综合防尘管理制度的依据：《煤矿井下粉尘综合防治技术规范》、《煤矿安全规程》、《煤矿用隔爆水槽和隔爆水袋通用技术条件》、《煤矿粉尘粒度分布测定方法（质量法）》、《作业场所空气中粉尘测定方法》、《矿综合防尘管理制度》等。
** 矿总工程师对的综合防尘工作全面负责，通风科科长对矿井防尘管理工作具体负责。
生产队组、作业队组、运输队组等的防尘责任和范围必须明确划定，并建立相应的考核办法，严格考核。
入井人员必须按规定佩戴个体防尘用具。
** 煤矿井下所使用的防尘用喷嘴及除尘器等防尘、降尘装置和设备必须符合国家及行业相关标准的要求，并保证其正常运行。
** 矿的防尘系统图应每月进行一次补充完善，并向上级部门报送。
* 一般规定
** 新建矿井所有煤层必须有煤尘爆炸性鉴定资料，生产矿井每延深一个新水平，应进行一次煤尘爆炸性试验工作。
煤尘的爆炸性由国家授权煤矿进行鉴定，鉴定结果必须报煤矿安全监察机构备案。矿井应根据鉴定结果采取相应的安全措施。
** 在编制新建矿井、改扩建矿井、水平延深等设计时，应对综合防尘系统进行设计，并报上级有关职能部门和总工程师批准。
** 编制采、掘工作面的作业规程时，必须对综合防尘作出明确规定。没有铺设防尘供水管路的采、掘工作面不得生产。
** 设计施工的综合防尘系统必须经验收合格后方可移交给生产单位或移交使用队组。
** 防尘用水管路应铺设到所有能产生粉尘和沉积粉尘的地点。管路的安装必须符合安全生产标准化标准要求，管路铺设平直，吊挂牢固，不得出现漏水。
** 按《煤矿安全规程》规定鉴定煤尘爆炸性；制定年度综合防尘、预防和隔绝煤尘爆炸措施，并组织实施。
通风科负责制定年度综合防尘措施。
** 粉尘测定、清洗都必须作好记录。
** 采煤工作面应采取粉尘综合防治措施，落煤时产尘点下风侧10-15米处总粉尘降尘效率应大于或等于85%；支护时产尘点下风侧10-15米处总粉尘降尘效率应大于或等于75%；放顶煤时产尘点下风侧10-15米处总粉尘降尘效率应大于或等于75%；回风巷距工作面10-15米处总粉尘降尘效率应大于或等于75%。
** 掘进工作面应采取粉尘综合防治措施，高瓦斯、突出矿井的掘进机司机工作地点和机组后回风侧总粉尘降尘效率应大于或等于85%；呼吸性粉尘降尘效率应大于或等于75%；其他矿井的掘进机司机工作地点和机组后回风侧总粉尘降尘效率应大于或等于90%；呼吸性粉尘降尘效率应大于或等于75%；钻眼工作地点的总粉尘降尘效率应大于或等于85%；呼吸性粉尘降尘效率应大于或等于80%；放炮15分钟后工作地点的总粉尘降尘效率应大于或等于95%；呼吸性粉尘降尘效率应大于或等于80%。
** 锚喷作业应采取粉尘综合防治措施，作业人员工作地点的总粉尘降尘效率应大于或等于85%。
** 井下煤仓放煤口、溜煤眼放煤口、转载及运输环节应采取粉尘综合防治措施，总粉尘降尘效率应大于或等于85%。
* 综合防尘系统管理职责范围
** 综采队负责综采工作面风运两巷出煤口往里的两顺槽及工作面所有综合防尘设施的安装、使用、维护、设施的标准化及巷道煤尘冲洗等工作。负责综采工作面风运两巷打钻、注水和2寸水管的安装。
** 掘进队负责主要大巷往里整个掘进巷道内防尘设施的安装、使用、维护及回收等。
** 通风队负责（除井下采、掘队管辖范围内的）主要进回风巷和采区巷道的综合防尘工作。并负责井下所有粉尘点的测尘及分散度、SiO2的采样工作。
** 选煤厂负责地面选煤车间，所有皮带走廊及圆筒仓的清扫洒水，确保无煤尘堆积。
** 运销部负责装车点附近20米范围内的煤尘冲洗及防尘设施的安装、使用。
* 粉尘防治
** 矿井必须建立完善的防尘供水系统，并符合下列要求：
*** 永久性防尘水池容量不得小于200立方米，且贮水量不得小于井下连续2小时的用水量，并设有备用水池，其容量不得小于永久性防尘水池的一半；
*** 主要运输巷、带式输送机斜井与平巷、上山与下山、运输巷与回风巷、采煤工作面运输巷与回风巷、掘进巷道、煤仓放煤口、溜煤眼放煤口、卸载点等地点都必须敷设防尘供水管路，并安设支管和阀门；
采煤工作面上下巷、掘进巷道及安装有胶带输送机的巷道供水管路每隔50米安设一个三通和阀门，其它巷道每隔100米安设一个三通和阀门；
*** 防尘用水系统中，必须安装水质过滤装置，保证水的清洁，水中悬浮物的含量不得超过30mg/L,粒径不得大于0.3毫米，水的PH值应在6.0-9.5范围内。
** 井下所有煤仓和溜煤眼都应保持一定的存煤，不得放空；有涌水的煤仓和溜煤眼，可以放空，但放空后放煤口闸板必须关闭，并设置引水管。
** 对产生煤（岩）尘的地点均应采取防尘措施
*** 掘进井巷和硐室时，必须采取湿式钻眼、冲洗井壁巷帮、水炮泥、爆破喷雾、装煤（岩）洒水和净化风流等综合防尘措施；
冻结法凿井和在遇水膨胀的岩层中掘进不能采用湿式钻眼时，可采用干式钻眼，但必须采取捕尘措施；
*** 采煤工作面应有由国家认定的结构提供的煤层可注性鉴定报告，并应对可注水煤层采取注水防尘措施；
*** 炮采工作面应采取湿式钻眼法，使用水炮泥，爆破前、后应冲洗煤壁，爆破时应喷雾降尘，出煤时洒水；
*** 液压支架和放顶煤采煤工作面的放煤口，必须安装喷雾装置，降柱、移架或放煤时同步喷雾；破碎机必须安装防尘罩和喷雾装置或除尘器；
采煤机必须安装内、外喷雾装置，无水或喷雾装置损坏时必须停机；
掘进机作业时，应使用内、外喷雾装置和除尘器构成综合防尘系统；
*** 采煤工作面进、回风巷应各安设两道固定的风流净化水幕，在采面回风巷距采面30～50米处安设1道移动水幕，并宜采用自动控制风流净化水幕；
*** 风流净化水幕的安装要求：
- 矿井及主要进、回风巷应各安设一道风流净化水幕。
- 采煤工作面进、回风巷必须各安设两道风流净化水幕，第一道距工作面30米，第二道距工作面80-100米。 
- 掘进工作面必须安设三道风流净化水幕，第一道距掘进面30-50米，第二道距掘进面80-100米，第三道距回风巷口10-15米。 
- 运输巷道内应设置自动控制风流净化水幕，采煤工作面回风流中应设置自动控制风流净化水幕；井下临时进行巷修的地点下风侧不大于10米处必须设置一道风流净化水幕。 
- 距锚喷作业地点下风流方向100米内应设置两道以上风流净化水幕，且喷浆机下风侧不大于10米处必须设置一道风流净化水幕。 
- 在装煤点下风侧20米内，必须设置一道风流净化水幕。
- 采用风排粉打钻或干式打眼地点下风侧5－10米处必须置一道风流净化水幕。 
- 净化水幕的安设位置应选择在巷道断面规整、无拐弯、避开电气设备、避开通风安全设施且风流保持稳定的地点。
*** 井下煤仓放煤口、溜煤眼放煤口、输送机转载点和卸载点，地面破碎车间、带式输送机走廊、转载点等地点，都必须安设喷雾装置或除尘器，作业时进行喷雾降尘或用除尘器除尘；
*** 在煤、岩层中钻孔，应采取湿式作业。煤（岩）与瓦斯突出煤层或软煤层中瓦斯抽采钻孔难以采取湿式钻孔时，可采取干式钻孔，但必须采取捕尘、降尘措施，必要时采用除尘器除尘；
*** 为提高防尘效果，可在水中添加降尘剂。降尘剂必须保证无毒、不腐蚀、不污染环境，并且不影响煤质。
** 预先湿润煤体
*** 煤层注水
- 注水过程中应进行流量及压力的计量；
- 单孔注水总量应使该钻孔预湿煤体的平均水分含量增量大于或等于1.5%；
- 封孔深度应保证注水过程中煤壁及钻孔不渗水、漏水或跑水。
*** 采空区注水
当采用下行陷落法分层开采厚煤层时，可以采取在上一分层的采空区内灌水，对下一分层的煤体进行湿润，开采近距离煤层群时，在层间没有不透水岩层或夹矸的情况下也可以在上部煤层的采空区内进行灌水，对下部煤层进行湿润。
*** 采煤工作面按《煤矿安全规程》规定采取煤层注水措施，注水设计符合AQ1020规定。
** 采煤工作面防尘
*** 采煤工作面防尘
（1）采煤机割煤必须进行喷雾并满足以下要求：
一是内喷雾压力不得小于2.0Mpa，外喷雾压力不得小于4.0Mpa。无水或喷雾装置损坏时必须停机。喷雾系统应与采煤机联动，工作面的高压胶管应有安全防护措施。高压胶管的耐压强度应大于喷雾泵站额定压力的1.5倍；
二是内外喷雾的喷头不得有堵塞、漏水现象，无水或喷雾装置损坏时必须停机。
（2）自移式液压支架应有自动喷雾降尘系统，并满足以下要求：
一是喷雾系统各部件的设置应有可靠的防止砸坏的措施，并便于从工作面一侧进行安装和维护；
二是液压支架的喷雾系统，应安设向相邻支架之间进行喷雾的喷嘴；喷雾压力均不得小于1.5Mpa；
三是在静压供水的水压达不到喷雾要求时，必须设置喷雾泵站，其供水压力及流量必须与液压支架喷雾参数相匹配。泵站应设置两台喷雾泵，一台使用，一台备用。
（3）有条件时应在采煤机上安装泡沫灭尘装置，割煤时使用泡沫灭尘，提高降尘效果。
（4）采煤工作面进风巷、回风巷必须按规定安设两组净化水幕，距采煤工作面上出口往外30米范围内必须增设一道临时水幕。
2.采煤工作面响炮时防尘
（1）钻眼应采取湿式作业，供水压力为2.0Mpa-1.0Mpa，耗水量为5L/min-6L/min,使排出的煤粉呈糊状；
（2）炮眼内应填塞自封式水炮泥，水炮泥的充水容量应为200mL-250mL；
（3）放炮前应对工作面30米范围内的巷道周边进行冲洗。
（4）放炮时必须在距离工作面10米-15米地点安装压气喷雾器或高压喷雾降尘系统实行放炮喷雾。雾幕应覆盖全断面并在放炮后连续喷雾5分钟以上，应采用高压喷雾等高效降尘措施，采用高压喷雾降尘措施时，喷雾压力不得小于8.0Mpa；
（5）转载点落差宜小于0.5米，若超过0.5米，则必须安装溜槽或导向板，转载点喷雾装置必须使用硬连接，宜采用半圆环上设3个以上喷嘴的水幕。
（6）合理调整风速,防止因风速超限而造成粉尘飞扬。主要进风巷和主要进、回风石门应安设风流净化水幕，在装煤点下风侧20米内，必须设置一道风流净化水幕。
3.其他防尘措施
（1）工作面运输巷的转载点、溜煤眼上口及破碎机处必须安装喷雾装置或除尘器，并指定专人进行管理。
（2）采煤工作面应采取煤层注水防尘措施，有下列情况之一的除外：
①围岩有严重吸水膨胀性质、注水后易造成顶板垮塌或底板变形，或者地质情况复杂、顶板破坏严重，注水后影响采煤安全的煤层；
②注水后会影响采煤安全或造成劳动条件恶化的薄煤层；
③原有自然水分或防灭火灌浆后水分大于4%的煤层；
④孔隙率小于4%的煤层；
⑤煤层很松软、破碎，打钻孔时易塌孔、难成孔的煤层；
⑥采用下行垮落法开采近距离煤层群或分层开采厚煤层，上层或上分层的采空区采取灌水防尘措施时的下一层或下一分层。
（六）掘进工作面防尘
1.综掘工作面防尘
（1）掘进机内喷雾装置的使用水压力不得小于2Mpa，外喷雾装置的使用水压力不得小于4Mpa；
（2）掘进机上喷雾系统的降尘效果达不到本标准十四、要求时，应采用除尘器抽尘净化等高效防尘措施；
（3）采用除尘器抽尘净化措施时，应对含尘气流进行有效控制，以阻止截割粉尘向外扩散；
（4）必须在掘进机上安装泡沫灭尘装置，切割时使用泡沫灭尘，提高降尘效果。
2.炮掘工作面防尘
（1）钻眼应采取湿式作业，供水压力以0.3Mpa为宜，但应低于风压0.1Mpa-0.2Mpa，耗水量以2L/min-3L/min为宜,以钻孔流出的污水呈乳状岩浆为准；
（2）炮眼内应填塞自封式水炮泥，水炮泥的装填量应在一节以上；
（3）放炮前应对工作面30米范围内的巷道周边进行冲洗；
（4）放炮时必须在距离工作面10米-15米地点安装压气喷雾器或高压喷雾降尘系统实行放炮喷雾。雾幕应覆盖全断面并在放炮后连续喷雾5分钟以上。当采用高压喷雾降尘时，喷雾压力不得小于8.0Mpa；
（5）放炮后，装煤（矸）前必须对距离工作面30米范围内的巷道周边和装煤（矸）堆进行洒水。在装煤（矸）过程中，边装边洒水，采用铲斗装煤（矸）机时，装岩机应安装自动或人工控制水阀的喷雾系统，实行装煤（矸）喷雾。
3.其他防尘措施
（1）距工作面20米范围内的巷道，每班至少冲洗一次。
（2）掘进工作面必须安装移动风流净化水幕，且雾化良好，放炮或割煤时应喷雾降尘。移动水幕安设在距离工作面15～20米处，安设在巷道中间部位并固定牢固。
（3）长距离的掘进工作面须在适当位置安设两道固定水幕，且雾化良好，放炮或割煤时应喷雾降尘。
（七）锚喷支护的防尘
1.打锚杆眼宜实施湿式钻孔，采取有效防尘措施后可采用干式钻孔；
2.锚喷支护作业的防尘：
（1）沙石混合料颗粒粒径不得大于15毫米，且应在下井前洒水预湿；
（2）喷射机上料口及排气口应配备捕尘除尘装置；
（3）采用低风压近距离的喷射工艺，其重点是控制以下参数：
输料管长度	小于或等于50m
工作风压	0.12-0.15MPa
喷射距离	0.4-0.8m
（4）距锚喷作业地点下风流方向100米内应设置两道以上风流净化水幕，且喷射混泥土时工作地点应采用除尘器抽尘净化；
（5）喷浆巷道每次喷浆时都必须正常使用除尘风机，除尘风筒末端到喷浆机的距离不得超过3～5米。任何人不得随意拆除或挪用除尘风机上的供水管路。
（八）转载及运输防尘
1.转载点防尘
（1）转载点落差宜小于或等于0.5米，若超过0.5米，则必须安装溜槽或导向板。
（2）各转载点应实施喷雾降尘或除尘器除尘。
（3）在装煤点下风侧20米内，必须设置一道风流净化水幕。
（4）运输系统各转载点喷雾降尘装置检查周期为每周一次。
2.运输巷内应设置自动控制风流净化水幕。
（九）合理调整风速,防止因风速超限而造成粉尘飞扬。主要进风巷和主要进、回风石门应安设风流净化水幕。
（十）采掘工作面回风应安设粉尘浓度传感器进行粉尘浓度连续监测。
* 粉尘清洗制度
** 井下运输机巷道、转载点附近、翻罐笼附近和装车站附近等地点的沉积煤尘进行清洗，清洗周期由矿总工程师确定，煤尘和浮煤必须清除干净。
** 掘进巷道每天冲洗一次，包括掘进巷道的风筒、管线、电缆及巷壁等，电器设备上的粉尘要及时清扫。
** 采煤工作面回风巷距离工作面30米范围内每班冲洗一次，30米以外每天冲洗一次，运输巷每3天冲洗一次。
** 进风石门每20天冲洗一次。回风石门、皮带巷等每7天冲洗一次。未设皮带的上、下山进风侧每15天洗一次，回风侧每10天冲洗一次。
** 进风井筒每月冲洗一次，回风井筒每20天冲洗一次。其它产尘大的地点，则根据粉尘情况随时进行冲洗。
** 及时清扫电器设备及管线的积尘。
** 必须及时清除巷道中的浮煤，清扫或冲洗沉积煤尘，每年应至少进行一次对主要进风大巷刷浆。
** 矿根据实际情况将粉尘冲洗区域划分到相关队组，明确责任，并按有关规定编制粉尘清洗计划，报总工程师批准后实施。
** 粉尘必须冲洗干净,不得有厚度超过2毫米、连续长度超过5米的积尘。
** 冲洗粉尘人员洗尘结束后，及时汇报调度室，通风科根据各队组汇报情况作好记录，严禁弄虚作假。
* 预防和隔绝煤尘爆炸
** 开采有煤尘爆炸危险煤层的矿井，必须有预防和隔绝煤尘爆炸的措施。矿井的两翼、相邻的巷道、相邻的煤层、相邻的采煤工作面间，煤层掘进巷道同与其相连的巷道间，煤仓同与其相连通的巷道间，采用独立通风并有煤尘爆炸危险的其他地点同与其相连通的巷道间，必须用水棚或岩粉棚隔开。
** 矿井每年应制定综合防尘措施、预防和隔绝煤尘爆炸措施及管理制度，并组织实施。
** 预防煤尘爆炸：巷道内设置了隔爆棚，也应按下列规定撒布岩粉。
*** 巷道的所有表面，包括顶、帮、底以及背板后暴露处都应用岩粉覆盖。
*** 巷道内煤尘和岩粉的混合粉尘中不燃物质组分不得低于60%，如果巷道中含有0.5%以上的瓦斯，则混合粉尘中不燃物质组分不得低于90%。
*** 撒布岩粉巷道长度不得小于300米，如果巷道长度低于300米时，全部巷道都应撒布岩粉。
*** 岩粉撒布周期按下式计算：
T = WP
式中：T——岩粉撒布周期，d；
W——煤尘爆炸下限浓度，g/m³；
P——煤尘的沉降速度，g/m³·d。
*** 岩粉（包括岩粉棚的岩粉）的质量，应符合以下规定：
- 可燃物的含有度不超过5%；
- 游离二氧化硅含量不超过10%；
- 不含有任何有害或有毒的混合物（如磷、砷等）；
- 岩粉的粒度必须全部通过50目筛（小于0.3毫米），其中70%以上通过200目筛（小于0.075毫米），一般采用石灰石岩粉。
*** 撒布岩粉的巷道，应遵守下列规定、按规定进行检查：
- 在距离采、掘工作面300米以内的巷道每月取样一次，300米以外的巷道每两个月取样一次；
- 每隔300米为一个采样段，每段内设5个采样带，带间距约50米；每个采样带在巷道两帮、顶、底板周边采样，取样带宽0.2米；
- 每个采样带内的全部粉尘分别收集起来，除去大于1毫米粒径的粉尘；
- 化验室应及时将分析结果报矿总工程师，如果不燃物组分低于规定，则该巷道应重新撒布岩粉。
** 隔绝煤尘爆炸主要采用被动式隔爆水棚（或岩粉棚），也可采用自动隔爆装置。隔爆棚安设应符合下列要求：
*** 主要隔爆棚安设位置：矿井两翼与井筒相联通的主要大巷，相邻巷道之间的集中运输巷和回风巷，相邻煤层之间的运输石门和回风石门等；
*** 辅助隔爆棚安设位置：采煤工作面进、回风巷道，煤和半煤巷掘进巷道，巷道独立通风并有煤尘爆炸危险的其它巷道等；
*** 水棚
- 水棚包括水槽和水袋，水槽和水袋必须符合相关行业规范的规定，水袋宜作为辅助隔爆水棚；
- 水分布特性要求：水槽破碎所需爆炸压力（以静压表示）不得大于16kpa,水袋动作所需爆炸压力（以静压表示）不得大于12kpa；形成最佳水雾的动作时间不得大于150毫秒；最佳水雾持续时间：水槽不得小于250毫秒，水袋不得小于160毫秒；最佳水雾分散长度不得小于5米；最佳水雾分散宽度不得小于3.5米；最佳水雾分散高度不得小于3米；
- 隔爆水棚采取集中式布置方式，必须能覆盖巷道的全断面；
- 水棚应设在巷道的直线段内, 水棚与巷道交叉口、转弯处距离保持50～75米，与风门距离大于25米；
- 首列隔爆水槽（袋）距工作面的距离应为60～200米；
- 主要隔爆水棚的棚区长度不小于30米，辅助隔爆水棚的棚区长度不小于20米。隔爆水棚的排间距为1.2～1.3米；
图2 隔爆水槽吊挂示意图
（7）主要隔爆水棚的水量不小于400L/㎡，辅助隔爆水棚的水量不小于200L/㎡；
（8）水棚安装方式:
①水槽棚既可采用集中横向吊挂式或上托式，也可采用混合式；
②水袋棚安装方式的原则是当受爆炸冲击力时，水袋中的水容易泼出；
③水槽（袋）的布置必须符合以下规定：
断面S＜10㎡时，ηB/L×100≥35%；
断面S＜12㎡时，ηB/L×100≥60%；
断面S＜12㎡时，ηB/L×100≥65%；
式中：η——排棚上的水槽(袋)个数；
B——水棚迎风断面宽度；
L——水棚所在水平巷道宽度。
④水槽（袋）之间的间隙与水槽（袋）同支架或巷道壁之间的间隙之和不大于1.5米，特殊情况下不超过1.8米，两个水槽（袋）之间的间隙不得大于1.2～1.3，棚区长度不得小于20米。
⑤水槽（袋）边与巷道、支架、顶板、构物架之间的距离不得小于0.1米，水槽（袋）底部到顶梁（顶板）的距离不得大于1.6米，如顶梁大于1.6米，则必须在该水槽（袋）上方增设一个水槽（袋）；
⑥水槽（袋）距离巷道轨道面的高度不小于1.8米，水棚应保持同一高度，需要挑顶时，水棚区内的巷道断面应与其前后各20米长的巷道断面一致；
⑦当水袋采用易脱钩的布置方式，挂钩位置要对正，每对挂钩的方向要相向布置（钩尖与钩尖相对），挂钩为直径4-8毫米的圆钢，挂钩角度为60°±5°，弯钩长度为25毫米；
（9）水棚要经常保持水槽或水袋的完好和规定的水量，要挂牌管理。
4.岩粉棚
（1）岩粉棚分为重型岩粉棚和轻型岩粉棚，重型岩粉棚作为主要岩粉棚，轻型岩粉棚作为辅助岩粉棚；
（2）岩粉棚的岩粉用量按巷道断面积计算，主要岩粉棚为400kg/㎡,辅助岩粉棚为200kg/㎡；
（3）岩粉棚及岩粉棚架的结构及其参数：
①岩粉棚的宽度为100-150毫米，岩粉棚的长度:重型棚为350-500毫米,轻型棚为≤350毫米；
②堆积岩粉的板与两侧支柱（或两帮）之间的间隙不得小于50毫米；
③岩粉板面距顶梁（或顶板）之间的距离为250-300毫米,使堆积岩粉的顶部与顶梁（或顶板）之间的距离不得小于100毫米；
④岩粉棚排间距离:重型棚为1.2-3.0米,轻型棚为1.0-2.0米；
⑤岩粉棚与工作面之间的距离，必须保持在60-300米之间；
⑥岩粉棚不得用铁丝或铁钉固定；
⑦岩粉棚的岩粉如果受到潮湿、变硬则应立即更换，如果岩粉量减少，则应立即补充，如果在岩粉表面沉积由煤尘，则应加以清除。
（五）每周至少检查1次煤尘隔爆设施的安装地点、数量、水量或岩粉量及安装质量是否符合要求并做好记录。
（六）在煤及半煤岩掘进巷道中，可采用自动隔爆装置，根据选用的自动隔爆装置性能进行布置与安装。
* 综合防尘设施管理
** 综采工作面：
*** 运输转载处必须安设喷嘴且装置应固定喷嘴对准落煤点的上方。并做到开机开水，无水不开机。
*** 运输巷距胶带大巷30～50米、风巷距工作面50米安设一道净化水幕，每道水幕设喷嘴间隔300～500毫米，水幕喷嘴与巷道垂直方向成45度角。迎风喷射能封闭全断面。
*** 运、风巷距工作面60～200米安装一组隔爆水袋棚，水袋应上架，每排不少于3～4个封闭全断面。安装水量按巷道净断面计算，每平方米需配水200L，并安装隔爆设施说明牌和指定专人负责。
*** 运巷必须敷设洒水管路，每50米设一个1寸三通阀门，皮带机运输巷设消防软管一盘，配有200～300毫米长1寸变6′的短节。
*** 必须实行煤体注水，注水及打钻必须有设计。注水必须安装流量表和压力表，专人看管。
*** 支架上必须安设移架喷雾装置。
*** 风巷必须敷设洒水管路，每50米设一个1寸三通阀门。
*** 风巷距工作面50～100米，运巷在变电列车附近处安设水质过滤器，指定专人负责，并做到每天反冲洗一次。
** 综掘工作面：
*** 运输出煤转载点处必须安设喷雾洒水装置（有自动的必须安装自动喷雾洒水装置），喷嘴装置要固定，喷嘴对准落煤点上方，雾化效果好。
*** 距工作面10～30米处安设水质过滤器，并指定专人负责和每天进行反冲洗。
*** 距工作面60～200米安设一组隔爆水袋棚，水袋必须上架，每排3～4个，封闭全断面。
*** 距工作面50米内安设一道净化水幕，水幕喷嘴间距300～500毫米水幕，与巷道垂直方向成45度角，迎风喷射能封闭全断面。
*** 综掘工作面掘进机无内喷雾时必须安设湿式除尘风机，风机吸风口在掘进机司机前0.5米处。风机安装在皮带机尾架设置的跑道上，并能随掘进机前进、后退。
*** 综掘工作面打锚杆时必须湿式打眼。
*** 掘进工作面巷道内必须安装洒水管路，每50米设一个1寸三通阀门。有皮带运输的巷道要求同综采工作面相同。
** 炮掘工作面：
*** 距出煤口10～15米处安装一台水质过滤器，并指定专人负责和每天进行反冲洗。
*** 各转载点喷嘴装置必须固定喷嘴对准落煤点上方，且雾化效果好。
*** 距工作面60～200米安设一组隔爆水袋棚，水袋标准同综采队相同。
*** 距工作面20米内安装一道冲击波放炮喷雾水幕，在放炮时能自动喷雾洒水，水幕喷嘴间距300～500毫米，与巷道垂直方向成45度角，迎风喷射、长度能封闭全断面，雾化效果好。
*** 距工作面30～50米处安装一个专用冲水泡泥水针，并保持不漏水。
*** 工作面必须采用湿式打眼，放炮前后对工作面30米范围内进行巷道冲洗和洒水。
** 其它地点
*** 皮带巷在回风侧3～5米安设一道净化水幕。
*** 各运输机转载点必须安装喷雾洒水装置，皮带转点实现自动化，喷头装置必须固定，喷嘴对准落煤点。
