:PROPERTIES:
:ID:       3280cc6a-0ad8-4c98-b87c-36f45af774a5
:END:
#+title: 员工招聘及聘用制度
* 总则
** 为配合公司战略目标的实现，最大限度地实现人力资源的优化配置，使招聘工作进一步制度化、流程化，特制定本制度
** 本制度适用于公司一切招聘活动。
** 人力资源部应确保招聘活动符合国家法律法规和公司有关制度。
** 人力资源部负责对内和对外招聘信息的发布形式和内容。
* 招聘范围
** 公司招聘分为内部招聘和外部招聘。内部招聘是指公司内部员工在获知内部招聘信息后，按规定程序应征，公司在应聘员工中选拔人员的过程。外部招聘是指在出现职位空缺而内部招聘无法满足需要时，公司从社会中选拔人员的过程。
** 招聘范围原则上以招聘具有本市行政区域内（城镇）常住户口、大专以上文化程度、有经验的各类人才为主，特殊岗位可面对国内外公开选聘。
** 招聘渠道主要有各地人才市场、劳动力市场、大中专院校的需求见面会及媒体广告招聘等。
* 招聘原则和标准
** 公司的招聘遵循双重考查原则，即所有招聘都需经过用人部门和人力资源部的双重考查，经公司分管用人部门的高层领导批准后由人力资源部发录用通知。
** 所有的应征者应具备良好的职业操守，无不良记录，身体健康，具有大学专科以上学历（含），特殊岗位和经验特别丰富的应征者可以适当放宽要求。
* 招聘计划制定程序
** 人力资源部根据公司未来一年内的人力资源需求状况和公司内外部的人力资源供给状况制定人力资源规划。人力资源规划是人力资源部招聘的依据，人力资源部根据人力资源规划制定计划内的招聘计划。
** 如果有计划外的人员需求或因员工离职需补充人员，用人部门负责人应填写《[[id:e0bcec77-2f39-4c2e-b077-5df61d476aa8][人员需求申请表]]》，反映部门缺员情况、增人要求和理由，由人力资源部审议后制定计划外人员需求计划，并提交人力资源分管副总裁审核、总裁审批后实施。
** 计划内的招聘计划与计划外的招聘计划可合并组成招聘计划。
* 招聘组织程序
** 招聘组织程序可分为内部招聘组织程序和外部招聘组织程序。
** 内部招聘按下列步骤进行：
*** 人力资源部根据招聘计划，发布内部招聘信息。
*** 应聘员工填写《[[id:f636566f-9fb9-4627-83fa-5fa71cd4cd4e][内部应聘申请表]]》。
*** 应聘员工同当前岗位直接上级做正式的沟通，并经当前岗位的直接上级、跨级上级签批《[[id:25354e21-c82e-4355-a17f-36384f914a7f][应聘申请表]]》后，将《[[id:f636566f-9fb9-4627-83fa-5fa71cd4cd4e][内部应聘申请表]]》提交人力资源部。
*** 人力资源部接到《[[id:f636566f-9fb9-4627-83fa-5fa71cd4cd4e][内部应聘申请表]]》后同应聘员工面谈，并在《[[id:f636566f-9fb9-4627-83fa-5fa71cd4cd4e][内部应聘申请表]]》填写相应的内容，签署意见。
*** 人力资源部安排应聘员工和空缺岗位的直接上级面谈，必要时进行其它方式的测试。如果应聘员工当前岗位的跨级上级与空缺岗位的直接上级同属一人，则省略本步骤。
*** 人力资源部将员工的录用信息通知应聘员工本人以及调入、调出的部门负责人。
*** 应聘员工被录用后，薪资水平应根据岗位重新核定，核定方法参见公司薪酬制度。
*** 人力资源部在调动信息发出后督促员工进行工作交接，并给予必要的支持。
*** 人力资源部在应聘员工正式调入空缺岗位前更新员工档案。
*** 如应聘未成功，由人力资源部将结果通知应聘员工。
** 公司岗位之间的调动、升降适用第十四条内部招聘的程序，可根据具体情况进行步骤方面的增删、变动。
** 外部招聘按下列步骤进行：
*** 人力资源部选择适当的招聘渠道发布招聘信息，收集人员资料（应聘人员填写《[[id:f636566f-9fb9-4627-83fa-5fa71cd4cd4e][内部应聘申请表]]》）后进行初步的筛选。初选合格人员由人力资源部通知参加初次面试，初次面试由人力资源部主持，面试完毕，人力资源部应填写《[[id:52a2f43f-6104-4625-ad23-41d99c26597f][面试记录表]]》。
*** 人力资源部通知初试合格人员参加复试，安排空缺岗位的直接上级对初试合格人员进行复试，复试完毕，面试者应填写《[[id:52a2f43f-6104-4625-ad23-41d99c26597f][面试记录表]]》，并根据岗位任职资格确定被录用的人员。
*** 人员聘用过程中，如果人力资源部或空缺岗位的直接上级认为必要，可提请空缺岗位的跨级上级对应聘者进行面试，面试完毕，面试者应填写《[[id:52a2f43f-6104-4625-ad23-41d99c26597f][面试记录表]]》并决定是否录用。
*** 员工在试用期期间的薪酬根据公司薪酬制度确定。
*** 人力资源部根据人员录用名单通知应聘者参加体检，应聘者体检合格后，人力资源部向应聘者发出录用通知，确定报到时间，并将上班报到时间通知空缺岗位的直接上级。
*** 新入职员工应向空缺岗位的直接上级和人力资源部报到，并填写《[[id:3924fd09-e4c8-4638-973e-34f1bcfac09a][员工登记表]]》，由人力资源部归档。
* 招聘费用管理
** 人力资源部在每年末根据公司人力资源需求制定招聘预算，经公司审批后安排在次年使用，预算内招聘费用经财务部核对后予以报销。
* 附表
** 有关招聘的文件和表格清单如下。
*** 《[[id:f636566f-9fb9-4627-83fa-5fa71cd4cd4e][内部应聘申请表]]》
*** 《[[id:25354e21-c82e-4355-a17f-36384f914a7f][应聘申请表]]》
*** 《[[id:17915756-040c-4c76-bb84-b2ed8d41a6e6][年度人员需求申请表]]》
*** 《[[id:3c4644be-255b-4a09-9d23-87de8c6bbddb][计划外人员需求申请表]]》
*** 《[[id:52a2f43f-6104-4625-ad23-41d99c26597f][面试记录表]]》
*** 《[[id:3924fd09-e4c8-4638-973e-34f1bcfac09a][员工登记表]]》

附表一

XX集团有限公司
人员需求申请表
制作部门：                                                     年度        季度
岗位	年初岗位定编	年末岗位定编	岗位定编
调整原因	年初在岗人数	预计离职/转岗人数	需招聘
人员



















人力资源部门意见：

                                            签字：
年   月   日
分管副总裁意见：

                                             签字：
年   月   日
总裁意见：

                                             签字：
年   月   日

附表二
XX集团有限公司
应聘申请表
填表日期：     年    月    日
姓名		性别		出生年月		职称
婚姻状况		健康状况		联系电话		住址
应聘岗位		何时可
入职		期望薪资		能否出差
学历	就读学校	专业	起止时间



工作经历	就职公司	职务	离职原因	起止时间




技能	外语水平：
电脑水平：
其他技能：
性格
证明人	姓名		电话		与本人关系
        姓名		电话		与本人关系
声明：
本人承诺以上内容属实，否则愿承担相应责任。
      签字：

附表三
XX集团有限公司
内部应聘申请表
填表日期：     年    月    日
姓名		性别		出生年月		职称
婚姻状况		健康状况		联系电话		住址
当前岗位		应聘岗位		入职时间		转正时间
学历	就读学校	专业	起止时间



工作经历	就职公司(包括本公司)	职务	离职原因	起止时间



本人
意愿

               签字：
     年     月    日
直接上级意见

               签字：
     年     月    日
跨级上级意见

               签字：
     年     月    日
人力资源部意见

               签字：
     年     月    日
聘用岗位直接上级意见

               签字：
     年     月    日

附表五
XX集团有限公司
面试记录表
应聘者
姓名		应聘
岗位		面试编号
初选意见	人力资源部填写：





                                              签字：
年   月   日
        合格 □        不合格 □
初试意见	人力资源部填写：





                                              签字：
年   月   日
        合格 □        不合格 □
复试意见	应聘岗位直接上级填写：





                                              签字：
年   月   日
        合格 □        不合格 □
复试意见	应聘岗位跨级上级填写：





                                              签字：
年   月   日
        合格 □        不合格 □

附表五
XX集团有限公司
员工登记表
填表日期：     年    月    日
姓名		性别		出生年月		职称
婚姻状况		健康状况		联系电话
住址		其它联系方式
岗位		入职时间		转正时间
学历	就读学校	专业	起止时间



工作经历	就职公司	职务	离职原因	起止时间




家庭成员	姓名	关系	工作单位	职务


技能	外语水平：
电脑水平：
其他技能：
性格

试用期员工管理制度
第八章  总则
第一条	为使新员工尽快熟悉工作，融入所属团队和理解公司文化，明确在新员工试用期间人力资源部、新员工所在部门和新员工本人的职责，加强试用期管理，特制定本制度。
第二条	所有通过外部招聘加入公司和通过内部招聘转入新岗位的员工都要经过新岗位试用期考察。外聘员工的试用期一般为3个月，内聘员工的试用期为1个月。

第九章  试用期管理程序
第三条	部长（不含）以下新员工的试用期管理按下列步骤进行：
（1）	外聘新员工入职当日应签订劳动合同；
（2）	新员工所在部门部长（或其授权人）为新入职员工确定试用期培训计划和目标；
（3）	在员工入职一个月后，由人力资源部和部长（或其授权人）分别与其谈话，评价新员工的工作业绩，并给予指导，了解新员工需要的支持；
（4）	新员工在转正日的前一周，应填写《试用人员转正申请表》中个人总结部分，部长同新员工做转正面谈，填写《试用人员转正申请表》中员工评价、岗位建议、待遇建议部分；
（5）	部长向人力资源部提交《试用人员转正申请表》，由人力资源部进行审核，人力资源部可在必要时同相关部门进行沟通；
（6）	人力资源部填写《试用人员转正申请表》，呈交新员工所在部门的直接上级审批；
（7）	如果转正申请得到批准，人力资源部向该员工发转正通知，抄送员工所在部门负责人，并同转正员工进行转正面谈；如果转正申请未得到批准，由人力资源部安排辞退手续，对于内部招聘新员工，人力资源部可建议返回原部门工作。
第四条	部长及部长以上新员工的试用期管理按下列步骤进行：
（1）	外聘新员工入职当日由人力资源部为新员工安排一小时左右的入职培训，同时签订劳动合同；
（2）	总裁（或其授权人）为新入职员工确定试用期培训计划和目标；
（3）	在新员工入职一个月后，由总裁（或其授权人）与其谈话，评价新员工的工作业绩，并给予指导，了解新员工需要的支持；
（4）	新员工在转正日的前一周，应填写《试用人员转正申请表》中个人总结部分，交人力资源部审核，由总裁同新员工进行转正面谈，对新员工进行评价，审批《试用人员转正申请表》，并确定新员工的岗位和待遇；
（5）	如果转正申请得到批准，人力资源部向该新员工发转正通知，抄送总裁；如果转正申请未得到批准，由人力资源部安排延长试用期、调职或办理辞退手续。
第五条	试用期的员工由人力资源部及员工聘用部门共同负责培训、考查。
第六条	在试用期内，公司或员工如需解除劳动合同，应参照劳动合同相关条款规定，并妥善完成工作交接。
第七条	试用期员工应提供身份证及相关证件、学历、职称及其他应聘时列举的资格或证件的原件和复印件，原件供人力资源部进行审核，复印件由人力资源部存档。如果新员工提供的资料存在虚假、误导等问题，人力资源部可向员工聘用部门通报，同时解除同该员工的劳动合同。
第八条	试用期员工必须严格遵守公司考勤纪律及劳动纪律，并且接受严格的考察措施。

第十章  试用期薪酬福利
第九条	试用期员工工资为所在岗位固定工资的80%，不发放考核工资。

第十一章        附表
第十条	有关试用期管理的文件和表格清单如下。
（1）	《试用人员转正申请表》
（2）	《试用期员工转正通知书》
（3）	《试用期员工辞退通知书》

附表一
XX集团有限公司
试用人员转正申请表
填表日期：     年    月    日
姓名		性别		出生年月		职称
当前岗位		入职时间		转正时间
个人评价	自我评价：



                                                 签字：
                                                 日期：
部长意见	员工评价：

岗位意见：
待遇意见：
                                                 签字：
                                                 日期：
人力资源部意见	员工评价：



                                                 签字：
                                                 日期：
转正员工跨级上级意见	员工评价：



                                                 签字：
                                                 日期：

附表二
XX集团有限公司
试用期员工转正通知书
         ：
你已通过公司的试用期考察，自     年     月     日起，你已成为公司正式员工，现有通知如下：
1.	岗位：                      ；
2.	薪酬：          元，其中        元为基本工资，        元为考核工资；
3.	福利：对于养老保险、失业保险、医疗保险，公司将按照国家有关规定办理；
4.	劳动合同：公司同你签订的1年期劳动合同以及补充协议将继续适用。

XX集团有限公司人力资源部
        年       月      日

附表三
XX集团有限公司
试用期员工辞退通知书
         ：

非常遗憾地通知您，公司认为您不适合目前的工作岗位，请您在      年     月     日之前办理工作交接及离职手续，工作交接按照《员工离职移交手续清单》执行，离职手续的办理遵照您同公司签订的劳动合同及补充协议。
衷心祝愿您能早日找到适合您的工作岗位。


XX集团有限公司人力资源部
        年       月      日

员工考勤及假期管理制度
第十二章        总则
第一条	为规范公司考勤及休假事宜，特制定本制度

第十三章        考勤管理
第二条	公司全体员工必须遵守工作时间，不得迟到、早退。
第三条	工作时间：公司实行定时工作制，每周工作5天，具体安排如下：上午 8：30-11：30， 下午13：30--17：30，
第四条	工作时间离开公司半小时以上者，需向直接上级请假。
第五条	如因工作性质需要，员工无需按时上下班，由所属部门提出人员名单，经人力资源部审核后，报公司总裁批准。
第六条	公司的考勤区间为日历月。
第七条	公司人力资源部负责管理日常考勤及考勤统计工作，并须于每月3日前（遇节假日顺延）将上月公司的考勤情况汇总后，填写考勤汇总表。
第八条	人力资源部在收到考勤汇总表后，进行记录存档，将本月考勤情况于每月5日前（遇节假日顺延）予以公布。人力资源部根据本制度计算员工考勤结果，并于每月16日前（遇节假日顺延）将工资发放表交财务部。
第九条	人力资源部负责考勤情况的公布和考勤工资的计算。

第十四章        加班管理
第十条	公司希望员工在每天8小时工作制内完成本职工作，确因工作需要加班或值班，才予批准。
第十一条	加班时间限制：
（1）	工作日加班每日不超过1小时，特殊情况时不超过3小时；
（2）	每月累计加班上限为36小时。
第十二条	不安排女员工在怀孕期或哺乳未满1周岁婴儿期间加班。
第十三条	凡需加班者，均须填写《加班登记表》申请加班。
第十四条	员工加班需经部长审批，工作日加班超过3小时、节假日加班应由部长审核，分管副总裁审批。
第十五条	加班完毕员工应在加班记录表中填写加班情况，由部长填写意见。
第十六条	部长应在月底汇总本部门全部加班纪录，填写部门加班记录汇总表，送人力资源部存档。
第十七条	人力资源部应在月底汇总本公司全部加班纪录，填写公司加班记录汇总表，报送总裁审批后存档、计算加班费用。
第十八条	加班费用的计算
（1）	平日加班：加班工资 = 本月每小时工资额（本月工资额/20.92天/8小时，以下同）×1.5倍×加班时间
（2）	双休日加班：加班工资 = 本月每小时工资额×2倍×加班时间
（3）	法定节日加班：加班工资 = 本月每小时工资额×3倍×加班时间

第十五章        假期管理
第十九条	病假：员工因病不能正常上班的，须请病假。病假超过1天（不含）者，须提供医院开具的有效证明。公司正式员工1年内可以享受3个工作日（含）的全薪病假，即发放全额日薪；1年内病假超过3个工作日（不含）者，病假超出期间发放日薪的60%；超过5个工作日（不含）者，病假超出期间发放日薪的30%；超过10个工作日（不含）者，扣除病假超出期间的工资。
第二十条	事假：因事而不能正常出勤者，需请事假，经相关领导批准后才能离岗。员工事假期间的工资为月工资扣除事假期间日薪。
第二十一条	婚假：公司正式员工在公司工作期间结婚，可休婚假。婚假为3个工作日，晚婚者（男25周岁，女23周岁）为18个工作日(含工休日)，婚假需在结婚年度使用。婚假不扣工资，也可以和年休假合并使用，婚假期间的路费自理。
第二十二条	丧假：员工亲属（父母、配偶、子女、配偶父母）去世，可休丧假。丧假一般为3个工作日，可给一定的路程假，但累计不超过5个工作日，丧假在亲属丧亡后1个月内使用。丧假不扣工资，但路费自理。
第二十三条	产假：公司女员工生育，可以享受90天（自然日）产假，特殊情况下（难产、剖腹产）可增加15天（自然日）。多胞胎生育的，每多生一胎，增加假期15天（自然日），产假期间只发基本工资。产假期满后无故不到岗者，以旷工论处。女员工怀孕期间，累计享受15天（自然日）的带薪产检假。女员工怀孕不满4个月流产，根据医院开具的相关证明，可以享受15天—30天（自然日）的假期。怀孕满4个月以上流产的，可以享受42天（自然日）产假，超出天数按病假处理，公司承担因流产所发生的医药费用。
第二十四条	哺乳假：产假期满后，本人申请可以休哺乳假，但累计不能超过一年，哺乳期工资发80％。凡有未满1周岁婴儿的女员工在哺乳期间，每天可以享受1个小时的带薪哺乳假，可以分两次使用，也可合并使用。多胞胎生育的，每多哺乳一个婴儿，每次哺乳时间增加30分钟。
第二十五条	年休假：凡是在公司工作满5年的员工，每年可以享受5天（工作日）的休假，之后工作每增加1年，年休假增加1天（工作日），年休假最长不超过15天（工作日）；员工1年内病、事假累计超过了15个工作日或者旷工1天以上，不得享受年休假。员工年休假可在下一自然年度使用，可集中使用，也可分割使用。年休假当年有效。因工作需要，公司有权随时召回正在休假的员工。员工因为工作原因放弃年休假的，则应发给相应的报酬，发放标准为当月日薪的两倍。
第二十六条	工伤假：员工因工负伤的，由所在部门上报人力资源部，经哈尔滨市劳动部门认定后，人力资源部门按医院鉴定报告给予工伤假期。
第二十七条	法定的节假日：员工可以享受国家规定的有薪节假日，具体安排按照国家规定执行。
第二十八条	请假管理：
（1）	员工请假，应提前向人力资源部提交请假申请单。请假天数在3个工作日（含）以内的，应提前1个工作日请假；请假天数在4个工作日（含）以上的，应提前3天请假。确因不可预见的原因没来得及提前请假的，应委托他人代为填写请假单。
（2）	病、事假期限。到岗后的试用期员工事假每月不可超过2个工作日（含），病假每月不可超过3个工作日（含），试用期间的病、事假合计不可超过5个工作日（含），否则终止试用，予以辞退。正式员工1年内事假不可超过15个工作日（含带薪事假），否则公司将保留采取处理措施的权利。
（3）	审批权限。一般员工事假1个工作日以内（含）、其他休假3个工作日以内（含）的，由所在部长审批。事假1个工作日以上、其他休假3个工作日以上由部长审核，员工所在部门分管副总裁审批。部长级（含）以上级别员工请假，无论天数多少，需经过分管副总裁审批。
第二十九条	奖励与处罚：
（1）	全勤奖。凡工作满1年的员工如在全年内没有迟到、早退、旷工、病假、事假及其他休假（除法定节假日），可在年末获得全勤奖金XXXX元。
（2）	迟到、早退在30分钟之内者，每次扣日薪的10%。超过30分钟者，每次扣发日薪的50%。超过1个小时，扣发全天日薪。
（3）	1个月内每旷工1天者，扣发固定月薪的30%，1年内连续旷工达15天或累计旷工30天者，公司予以辞退。
第十六章        附表
第三十条	有关考勤和假期管理的文件和表格清单如下。
（1）	《加班记录表》
（2）	《请假申请表》
（3）	《考勤汇总表》

附表一
XX集团有限公司
加班记录表
填表日期：     年    月    日
加班申请人		审批及审核
加班部门		部长	人力资源部	分管副总
加班日期
加班时间
加班类型	□平日加班       □双休日加班       □法定节日加班
加班事由：
加班特殊事项：
本月加班累计：
加班任务完成状况（加班后填写）：




                                                    加班人签字：
日期：
部长意见（加班后填写）：


                                                    加班人签字：
日期：
人力资源部存档：

附表二
XX集团有限公司
请假申请表
填表日期：     年    月    日
请假人		岗位		请假期间
请假类型	□事假    □病假    □年休假    □婚假    □产假    □丧假
部长意见：

                                                     签字：
                                                     日期：
分管副总裁意见（可选）：

                                                     签字：
                                                     日期：
总裁意见（可选）：

                                                     签字：
                                                     日期：
人力资源部存档：


附表三
XX集团有限公司
考勤汇总表
填表日期：     年    月    日
被考勤人	考勤天数	迟到	早退	离岗	旷工	病假	事假	年休假	婚假	产假	丧假	考勤工资


















注：①离岗指无正当理由离开办公场所半小时以上的行为；
②考勤工资指员工在考勤月由各种考勤行为而被扣除的工资额的总和。
