:PROPERTIES:
:ID:       f812b1be-d873-4e0e-b428-49e6921b575e
:END:
#+title: 采煤工作面文明生产管理制度
文明生产管理是煤矿安全生产的基础，是采煤生产规范化、精细化的主要内容。为规范采煤工作面及巷道文明生产，明确责任范围,提高采煤工作面的工作质量和工作环境，特制定本规定，望各部门认真学习，组织实施；职能部门严格监督、检查，力争使采煤安全生产标准化水平再上新台阶。
* 材料堆放
** 两巷材料堆放的料场要选择在顶板完整，支架完好处，空间位置宽敞，不影响行人、运料、通风地点，并设专人负责管理；
** 所有材料必须分类挂牌留名，码放整齐，数量按作业规程要求配备，同类材料码放应横竖成线，高度不超过1.5m，不同材料之间间隔0.7m。标志牌内容齐全、规范统一。小型材料及黄泥等必须用木板钉制围栏存放。凡不符合要求，一处罚责任管理人××元。
** 备用料的规格、数量、距工作面的距离及备用料的使用要求必须在作业规程中明确规定，码放要求同其它材料一致，挂牌管理并标明规格数量。不按要求执行的，每项罚责任管理人××元。
** 材料分类存放在矿统一加工的材料架上，生产单位负责管理。机电配件堆放要整齐，分层码放，一处不合要求罚责任管理人××元。
** 回收的工字钢、皮带、损坏单体及顶梁等要分类集中堆放在指定地点，码放整齐，否则罚款责任管理人每一处××元。
** 回收的工字钢堆放处不得超过2堆，超过2堆罚责任人××元，过后仍未拿走的要加倍处罚。其它回收物料够一车必须及时运走。对损坏的单体支柱满10支要及时升井，不及时升井的罚运料队责任管理人××元。同时按单体管理规定另行处罚。
** 回收的防尘管、压风管、排水管要分类集中堆放，码放整齐。否则发现一处罚通风科责任管理人××元。够一车要及时运走。
* 管线、电缆管理
** 两巷管线吊挂位置及高度要统一，管线吊挂要平直。严格按标准要求执行。
** 电缆按监测、通讯、信号、低压、高压顺序自上而下分档吊挂，垂度适当，电缆钩固定上下平直，距离一致。高差不超30mm。不合要求的，每一处罚责任管理人××元。
** 风、水管按防尘管、压风管、液压管、排水管自上而下吊挂，吊挂点间距均匀，与巷道坡度一致，杜绝跑、冒、滴、漏现象。不合要求的，一处罚责任管理人××元。
** 风、水管路、液压管路、排水管路的吊挂由队组负责日常管理工作。
** 瓦斯监测线路、通讯线路、电缆的吊挂由通风科负责，队组负责日常管理工作。 
** 以两巷超前棚向外20米为界，20米之外为永久吊挂。超前棚20米至工作面为临时吊挂，由队组负责各类管线临时吊挂，不落地，不用时按规定盘好，否则，每处罚责任管理人××元。
** 转载机机尾到设备列车前10米段的电缆吊挂由队组负责，吊挂要平直。不符合规定要求一处罚队组责任管理人××元。 
* 图牌板管理
** 图牌板由技术员统一管理，技术员负责图牌板内容审查的确定。内容不齐全，一次罚技术员××元。 
** 图牌板内容应与现场施工相符，牌板内容包括精细化管理，工作面布置图、设备布置图、通风系统图、监测通信系统图、供电系统图、工作面支护示意图、正规作业循环图表、避灾路线图等。缺少一块罚技术员××元。
** 牌板制作应规格统一、摆放整齐，牌板存放地点有条件的要设置照明。
** 图牌板应保持清洁无积尘，发现有明显的积尘，一次罚责任管理人××元。内容应根据工作面情况及时进行更换。内容与工作面不符，一次罚技术员××元。
** 施工图牌板移挪、日常保护等由队长安排专人负责。
* 巷道文明卫生
** 巷道底板必须保证平整，安排人员清扫；巷道内不得出现直径大于50mm的矸石。发现一处，罚责任管理人××元。 
** 有水沟巷道，巷道水沟应保持畅通，不得有杂物。否则，每处罚责任管理人××元。 
** 设备工具必须放在专用工具架上或工具箱内，不得随意落地。否则，每次罚责任管理人××元。
** 采煤工作面要做到“三直”、“一平”、“两畅通”。液压支架（柱）实行编号管理，号牌清晰端正，否则一处罚责任人××元；超前支护必须打成一条直线，单体柱三用阀注液口与巷道平行，否则一处罚责任人××元。 
** 超前棚范围内，不得有杂物、多余单体顶梁等，保持清洁、干净、文明。发现一根物料罚责任管理人××元。
* 其它
** 巷道超前棚按规程要求进行执行；不按要求支护，每次罚相关人员每人××元。 
** 支柱初撑力合格率达不到要求，每次罚管理人××元。
** 所有备用物料要分类集中堆放巷帮，不得随意丢放在巷道内，发现一根罚款××元。机、风巷及工作面损坏的单体、顶梁必须及时外运到指定地点，不得随意丢放，否则，发现一根罚款××元。每个工作面只能设一端作为损坏单体指定存放点。
* 监督检查及奖惩
为更好的将文明生产管理规定落实到现场，特制定如下检查与奖惩办法：
** 成立检查小组
 第一组：
 第二组：
每月对各采煤工作面进行两次检查（上下半月各一次），检查分组由生产技术办公室负责，每月5号前各小组将上月的两次检查结果报技术科。
** 奖惩
*** 检查小组依据标准罚款，月度罚款作为奖励基金使用，
由检查小组评定，对执行较好的人员进行奖励。
*** 检查小组根据罚款数目，每月对各采煤工作面进行排名，
划分两个档次，第一、二名分别按××元/月、××元/月进行奖励。
