:PROPERTIES:
:ID:       d7ee9d22-278c-463f-8ddb-ac99a73cfd88
:END:
#+title: 煤层自燃发火预测预报管理制度
为了贯彻落实《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》、《[[id:0c774279-2146-46c9-8c75-09e87dcb9ff8][煤矿防灭火规定]]》及上级有关文件精神，结合矿的实际情况。特制定煤层自燃发火预测预报管理制度。
* 建立自燃发火观测点，自燃煤层巷道每隔40米设置一个，对矿井的自燃危险区进行系统的观测。观测点应选在：采空区回风侧和回采工作面上隅角和回风巷中。观测内容为：一氧化碳、二氧化碳、瓦斯、氧气等气体成份。该项工作由通风科瓦检员负责检查，并将检查的结果填写在观测站记录牌板上和防灭火检查记录本上。
* 矿井自然发火预测预报工作由总工程师负责，具体业务由通风科负责组织实施。
* 预报人员必须收集现场一切资料，确保预报的准确性。预报前必须根据资料认真分析，对其造成的影响加以说明。提前预报必须根据其性质在《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》所规定的安全的前提下进行。预报工作严禁口头说明，必须是书面形式和与其相适应的图纸，并有文字记录。所有资料必须提前由总工程师审查，否则严禁对外预报。预报后必须掌握现场资料，一旦发现与预报情况不符或有其它情况发生，必须及时汇报领导进行补充修改。对于预报的相关资料必须备份存档，以备查阅。
* 回采工作面回采结束45天内必须全部撤出设备，进行永久性封闭。建立永久性防火密闭必须由通风科进行专项设计，专项设计由总工程师签字后，施工队组严格按照设计进行施工。永久性防火密闭必须预留灭火灌浆及防火观察孔门、风窗、风桥等通风设施，也应按防灭火的要求正确选择位置砌筑。
* 防火密闭的气体、温度，每周进行一次检测，同时对流水温度也要进行测定。防火密闭如出现气体温度升高、有CO出现、水温升高等现象，必须立即报总工程师，并采取措施防止自然火灾的发。
* 教育全体员工了解矿井自然发火的征兆，如发现自然发火的预兆时，及时向有关领导和调度室汇报。
* 早期发现煤层自燃发火的初期征兆。煤层自燃的初期征兆，人体感觉气管可以察觉到的现象有：
** 巷道中出现雾气和巷道壁有“出汗”现象；
** 闻到有煤油味、汽油味和焦油味等；
** 出水温度大于25℃，空气与煤壁的温度骤增，气温较常温高出约10℃，皮肤有一种热感，周身不适；
** 人感觉有头疼、闷热、憋气、四肢无力和精神疲乏等现；
* 煤层自然发火原因
根据煤层自燃发火性质,煤的自燃过程实质上是煤氧化逐渐加速的过程,煤急剧氧化放出的热量不能向外散失时,则煤体温度达到着火温度,煤发生自燃。影响煤层自然发火的因素有内在、地质、开采等。
** 内在因素
煤层自然发火性能主要取决于煤层本身的物理化学性质和成分,与煤的变质程度关系很大,变质程度越低,则煤层自燃性能越强。
** 地质因素
*** 煤层厚度。一般情况下,煤层越厚,自然发火危险性越大。
*** 煤层倾角。煤层厚倾角又大时,更易自燃。尤其在急倾斜特厚煤层中,自然发火更为严重。
*** 地质构造。在褶曲、断层带附近,煤层及其顶底板常被挤压、牵引而破碎,煤岩层的裂隙增多,易造成串风供氧,更易发生自燃。
*** 含硫量。煤中含硫越多,越容易自燃。尤其在高硫煤中,若煤层的直接顶含硫量很高,则自燃性能更为严重。
** 开采因素
*** 巷道布置与顶板管理。巷道沿煤层布置时,煤柱多,联络巷多,煤层暴露面积大,封堵困难,易于自燃。采用充填法和垮落法控制顶板时,采空区较为严实,漏风小,故不易自燃。
*** 漏风条件也直接关系到自燃。漏风大,煤在自热阶段的热量不易积聚,不易发展到自燃； 漏风小,供氧不足,即使有自热发生也不易发展到自燃；只有漏风满足煤从自热发展到自燃所需的氧量,又能使氧化过程中产生的热量积聚,这时才易自燃。
* 巡回安全员、瓦检员及工作面现场人员发现上述自燃发火预兆后，必须现场采取有效措施并报调度室。
* 由通风科负责每月对全矿的总回风道、回风道进行一次详细的自然发火征兆观察，从大范围上分析井下有无自燃发火。
* 救护队每天安排专人对井下采煤面的上隅角、回风巷和采空区气体及其它可能发热的地点进行一次全面观测。观测的参数包括：现场的气体成份(CH4.C02.C0.02)、气温、水温、其他火灾征兆等；在防火墙封闭时间长，温度异常和有自燃倾向的区域内的回风风流中要安设CO传感器，CO传感器的报警浓度为24ppm。
* 在采煤工作面上隅角、回风流，掘进工作面的迎头、回风流内安设一氧化碳传感器，进行自燃发火监测。
* 监控值班员发现一氧化碳传感器显示值超过临界值时，必须及时通知有关科室及领导，并采取有效措施。
* 由瓦斯员负责认真观测自燃发火观测点处的观测内容，并及时填写观测数值。
* 由通风科负责及时整理和分析观测结果，并绘制变化曲线，一旦发现某一指标达到临界值，应迅速做出预报，向调度室及有关领导汇报。
* 对于已有发火危险或已出现发火征兆的地点，检查周期缩短到每班一次，及时向有关领导和部门汇报。同时，矿领导应组织专门人员进行火灾灾情的分析并制定处理对策。
* 若出现不按上述制度执行的部门及相关人员给予处罚，处罚金额另订。
