:PROPERTIES:
:ID:       9c3e4034-64ce-44d5-967d-096b0dbadc90
:END:
#+title: 瓦斯监测装置安装、维护、调试、回收管理制度
* 为保证安全监控系统的稳定运行，做好系统的安装维护工作，特制定安全监控系统维护制度。
* 各类传感器安装由通风科出具安装工作单，及安装/拆除位置图。自接到安装/拆除工作单，及安装位置图之日起三日内，由监测队按图安装到位。没有书面安装/拆除工作单不予安装。
* 监测队在接受安装任务时，要弄清安装地点，确定监控设备具体安装位置、电源连接方式、监测量传输方式及控制其它设备方式，并估算通讯线长度。
* 领取、安装仪器时，要检查仪器的各项技术指标和性能是否符合出厂标准，各连接部件是否齐全、完整、紧固，外壳是否变形及锈蚀，隔爆面是否符合要求，在确认无误后，方可领取。
* 监控设备在正式安装使用前，必须按产品使用说明书的要求在地面试验场所进行调试和测试，测试合格并在试验场所试运行至少48小时后方能下井安装使用。对安装所用电缆要做导通及外皮检查，电缆密封圈要合适，档板、三通、悬挂电缆物品等要备齐。
* 安装或搬迁仪器、电缆(本质安全型除外)前必须切断电源，并用与电源电压相适应的验电笔检验。
* 监控设备在正常搬迁中，要防止撞碰、剧烈振动和冲击，搬迁后要检查设备的工作状态是否正常和电缆有无损。
* 井下分站应设置在便于人员观察、调试、检验及支护良好、无滴水、无杂物的进风巷道或硐室中，安设时应垫支架，或吊挂在巷道中，使其距巷道底板不小于300mm，距轨道不小于500mm。
* 隔爆兼本质安全型防爆电源，设置在变电所，严禁设置在下列区域：
** 断电范围内。
** 低瓦斯和高瓦斯矿井的采煤工作面和回风巷内。
** 煤与瓦斯突出矿井的采煤工作面、进风巷和回风巷。
** 掘进工作面内。
** 采用串联通风的被串采煤工作面、进风巷和回风巷。
** 采用串联通风的被串掘进巷道内。
* 模拟量传感器应设置在能正确反映被测物理量的位置，甲烷传感器、一氧化碳传感器、温度传感器应垂直悬挂，距顶板不得大于300mm，距巷道煤壁不小于200mm，不影响行人和行车，安装维护方便，能够正确反映所测地点的浓度或温度；风速传感器应设置在巷道前后10m内无分支风流、无拐弯、无障碍、断面无变化、并应不影响行人和行车，安装维护方便，能准确计算测风断面的地点；粉尘传感器应垂直悬挂，距底板2m处，不影响行人和行车，安装维护方便，能够正确反映所测地点的粉尘浓度。
* 开关量传感器应设置在能正确反映被监测状态的位置。
* 声光报警器应设置在经常有人工作便于观察的地点。
* 煤与瓦斯突出矿井所有井下作业地点的甲烷传感器上限不低于40%CH4高浓甲烷传感器；非突出矿井安设上限不低于10%CH4的高浓甲烷传感器。
* 安装时监控设备、电缆、接线盒以及它们相互之间的连接必须符合井下机电管理的相关规定，安装完毕，应详细检查所有接线，确认合格无误后，方可送电。送电经30分钟预热后可对仪器进行调整，并检查仪器工作是否正常，在确认仪器工作正常后，可投入报警和控制功能，并检查其功能的可靠性，通讯正常经监控机房同意方可离开。
* 安装断电控制时，必须根据断电范围要求，提供断电条件，并接通井下电源及控制线。
* 井下监测分站的交流供电电源取自被控制开关的电源侧，严禁接在被控开关的负荷侧。在交流供电电源停电后，监测分站的后备直流电源在满负载情况下必须保证不小于2小时的连续供电。宜为井下安全监控设备提供专用供电电源。
* 拆除或改变与安全监控设备关联的电气设备的电源线及控制线、检修与安全监控设备关联的电气设备、需要安全监控设备停止运行时，须报告矿调度室，并制定安全措施后方可进行。
* 安全监控设备之间必须使用专用阻燃电缆连接，严禁与调度电话电线和动力电缆等共用。
* 井下工作站同传感器相互连接的电缆，必须严格按照出厂说明书的规定执行。
* 井下监测电缆用非金属耐磨损材料吊挂，每间隔3m 分钩分挂于巷道壁中部，不得落地、埋压，不得有过紧张力，吊挂整齐。监测电缆每间隔100m作标签标志。
* 井下监测分站牌版按矿颁布的《高家庄煤矿通风标准牌板图案》的格式制作和填写。
* 监测工经常擦扫监控设备外壳粉尘和污物，保持仪器清洁，及时更换探头里的防尘罩和清扫探头罩里的污物。
* 监控工必须24小时值班，监测监控装置发生故障，必须及时处理，故障处理不得超过8小时，故障停机期间应采用相应的安全措施。
* 炮采工作面设置的甲烷传感器在放炮前应移动到安全位置，放炮后应及时恢复设置到正确位置。对需要经常移动的传感器、声光报警器、断电控制器及电缆等，由采掘班组长负责按规定移动，严禁擅自停用。
* 监测巡检人员必须每天检查负责区域内所有监控设备及电缆是否正常。如发现显示数据误差、设备损坏、系统运行异常、线缆破损等异常情况，立即汇报监控值班室，并在巡检记录上做好记录备查。
* 瓦检员每班三次将光学甲烷检测仪与甲烷传感器进行对照，并将记录和检查结果报矿调度；当两者读数误差大于允许误差时，先以读数较大者为依据，采取安全措施并必须在8小时内对2种设备调校完毕。
* 井下采掘开巷道及工作面监测设备(线缆、接线盒、传感器、牌板)的使用、悬挂、移动由现场施工的采掘队负责和日常维护；各队组皮带巷、地面皮带走廊内的监测设备由皮带运输部门负责和日常维护；井上下变电所内的监测设备由机运科负责悬挂和日常维护；总回、主井及各主要轨道巷内的监测设备由监测队负责悬挂和日常维护；地面安装监测设备的场所由现场管理部门负责悬挂和日常维护。对监控线路的划分与其电缆线路相同。保持监测设备无灰尘、无淋水、无油污、监测线路整齐有序等。
* 工作面传感器需要延线或收线时，由使用队组通知监测队，监控维修人员与使用队组电工共同进行，使用队组不得私自处理，以防将线接错，损坏仪器。
