:PROPERTIES:
:ID:       f57276fc-9622-428f-8e68-e60381bb1e35
:END:
#+title: 入井检身与出入井人员清点制度
为保障矿井安全生产和职工的人身安全，防止意外事故发生，根据《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》的要求，特制定入井检身制度和出入井人员清点制度。
* 本制度适用于所有出、入井人员。
* 通风科在井口安装人员定位系统和视频监控系统，并装备出、入井闸机系统；每班在井口必须配备一名专职人员，确保24小时有人值班，对每一名出、入井人员进行检身清点，并将出、入井总人数报矿调度室备案待查。
* 人员出、入井时将人员定位卡靠近闸机系统前进行显示，显示为绿色后闸机系统方可打开，实行“一人一杆一通过”，若显示为红色“χ”表示禁止通过，不准人员攀爬或从闸机系统底下通过，严禁损坏闸机系统。
* 地面召开班前会时，班队长要将本班入井人员清点清楚并登记在册，确认职工精神状况，若发现职工精神状况不好、身体不适、喝酒等不准安排入井作业，队组点名登记后，将入井实际出勤人数汇报矿调度备案待查。
* 入井人员必须办理灯牌和人员定位卡，职工入井时必须手持灯牌领取矿灯。灯牌上除必须注明矿灯编号及持有者姓名、工号、工种外，还必须注明灯牌使用注意事项。
* 机运科必须建立、健矿灯使用领退制度、灯房管理制度、灯房岗位责任制度。并严格组织实施执行。
* 通风科必须建立、健全人员定位卡使用领退管理制度。并严格组织实施执行。
* 灯牌、人员定位卡是清点出、入井人员的首要依据。入井人员领取矿灯后，灯房管理人员必须妥善保管灯牌。并统计灯牌总数，报矿调度备案待查，不准遗漏；井下所有人员必须要保护好人员定位卡。
* 矿调度室值班人员在得到井口汇报后必须认真做好记录，并及时进行校对，发现问题立即跟踪追查。
* 每位入井人员必须随身携带自救器，佩戴安全帽及其他劳动保护用品，携带矿灯。严禁携带烟草和点火物品，严禁携带有毒有害药剂和毒品以及化学药品，严禁携带管制刀具及其他凶器，严禁穿化纤衣服，入井前严禁喝酒。
* 井口检身人员要有责任心，发现有外来人员、可疑人员、喝酒人员等情况时，要及时制止，必须及时汇报矿调度室，严禁在井口附近逗留，影响矿井安全生产。
* 井口检身人员必须坚守岗位，不得脱岗、睡觉、早退，严格现场交接班，要将出、入井人员清点记录清楚，班前、班末要将人员出、入井人数汇报调度室，发现人员在规定时间未出井时要及时汇报调度室，随时掌握井下人员活动情况，实现出井、入井人员闭环管理。
* 井口检身人员发现有盗窃矿山物资等行为时，必须立即汇报调度，交人力资源科处理。
* 矿必须认真组织职工学习入井检身与出、入井人员清点制度，学习后签字按手印。入井人员必须佩带人员定位卡，安全科、通风科安排人员在井口对人员定位卡的佩戴进行抽查，井下各头面安全员、瓦检员进行检查，发现一次不携带人员定位卡的处罚XX元/次；人员定位卡损坏或未携带人员定位卡的不得入井作业，否则处罚XX元/人。
* 井口必须有井口检身登记本，所有出入井人员必须在井口登记，未登记入井的处罚XX元/次。
* 检身人员不得离开工作岗位，发现漏检或未清点人数处罚XX元次，除给以严肃的罚款处理外，并立即调离原工作岗位。
* 发现人员定位卡丢失或损坏的，要及时汇报矿调度，矿调度通知通风科要及时安排人员进行更换，更换好后方可允许人员入井作业。
* 机运科灯房人员每班对每位出、入井人员的灯牌进行清理，做到心中有数。
