:PROPERTIES:
:ID:       04dc4c69-a3a0-401d-8382-36c0aa40b39b
:END:
#+title: 员工考勤及假期管理制度
* 总则
** 为规范公司考勤及休假事宜，特制定本制度
* 考勤管理
** 公司全体员工必须遵守工作时间，不得迟到、早退。
** 工作时间：公司实行定时工作制，每周工作5天，具体安排如下：上午 8：30-11：30， 下午13：30--17：30，
** 工作时间离开公司半小时以上者，需向直接上级请假。
** 如因工作性质需要，员工无需按时上下班，由所属部门提出人员名单，经人力资源部审核后，报公司总裁批准。
** 公司的考勤区间为日历月。
** 公司人力资源部负责管理日常考勤及考勤统计工作，并须于每月3日前（遇节假日顺延）将上月公司的考勤情况汇总后，填写考勤汇总表。
** 人力资源部在收到考勤汇总表后，进行记录存档，将本月考勤情况于每月5日前（遇节假日顺延）予以公布。人力资源部根据本制度计算员工考勤结果，并于每月16日前（遇节假日顺延）将工资发放表交财务部。
** 人力资源部负责考勤情况的公布和考勤工资的计算。
* 加班管理
** 公司希望员工在每天8小时工作制内完成本职工作，确因工作需要加班或值班，才予批准。
** 加班时间限制：
*** 工作日加班每日不超过1小时，特殊情况时不超过3小时；
*** 每月累计加班上限为36小时。
** 不安排女员工在怀孕期或哺乳未满1周岁婴儿期间加班。
** 凡需加班者，均须填写《[[id:db8338b1-c084-46f6-baa2-737991a1403b][加班登记表]]》申请加班。
** 员工加班需经部长审批，工作日加班超过3小时、节假日加班应由部长审核，分管副总裁审批。
** 加班完毕员工应在加班记录表中填写加班情况，由部长填写意见。
** 部长应在月底汇总本部门全部加班纪录，填写部门加班记录汇总表，送人力资源部存档。
** 人力资源部应在月底汇总本公司全部加班纪录，填写公司加班记录汇总表，报送总裁审批后存档、计算加班费用。
** 加班费用的计算
*** 平日加班：加班工资 = 本月每小时工资额（本月工资额/20.92天/8小时，以下同）×1.5倍×加班时间
*** 双休日加班：加班工资 = 本月每小时工资额×2倍×加班时间
*** 法定节日加班：加班工资 = 本月每小时工资额×3倍×加班时间
* 假期管理
** 病假：员工因病不能正常上班的，须请病假。病假超过1天（不含）者，须提供医院开具的有效证明。公司正式员工1年内可以享受3个工作日（含）的全薪病假，即发放全额日薪；1年内病假超过3个工作日（不含）者，病假超出期间发放日薪的60%；超过5个工作日（不含）者，病假超出期间发放日薪的30%；超过10个工作日（不含）者，扣除病假超出期间的工资。
** 事假：因事而不能正常出勤者，需请事假，经相关领导批准后才能离岗。员工事假期间的工资为月工资扣除事假期间日薪。
** 婚假：公司正式员工在公司工作期间结婚，可休婚假。婚假为3个工作日，晚婚者（男25周岁，女23周岁）为18个工作日(含工休日)，婚假需在结婚年度使用。婚假不扣工资，也可以和年休假合并使用，婚假期间的路费自理。
** 丧假：员工亲属（父母、配偶、子女、配偶父母）去世，可休丧假。丧假一般为3个工作日，可给一定的路程假，但累计不超过5个工作日，丧假在亲属丧亡后1个月内使用。丧假不扣工资，但路费自理。
** 产假：公司女员工生育，可以享受90天（自然日）产假，特殊情况下（难产、剖腹产）可增加15天（自然日）。多胞胎生育的，每多生一胎，增加假期15天（自然日），产假期间只发基本工资。产假期满后无故不到岗者，以旷工论处。女员工怀孕期间，累计享受15天（自然日）的带薪产检假。女员工怀孕不满4个月流产，根据医院开具的相关证明，可以享受15天—30天（自然日）的假期。怀孕满4个月以上流产的，可以享受42天（自然日）产假，超出天数按病假处理，公司承担因流产所发生的医药费用。
** 哺乳假：产假期满后，本人申请可以休哺乳假，但累计不能超过一年，哺乳期工资发80％。凡有未满1周岁婴儿的女员工在哺乳期间，每天可以享受1个小时的带薪哺乳假，可以分两次使用，也可合并使用。多胞胎生育的，每多哺乳一个婴儿，每次哺乳时间增加30分钟。
** 年休假：凡是在公司工作满5年的员工，每年可以享受5天（工作日）的休假，之后工作每增加1年，年休假增加1天（工作日），年休假最长不超过15天（工作日）；员工1年内病、事假累计超过了15个工作日或者旷工1天以上，不得享受年休假。员工年休假可在下一自然年度使用，可集中使用，也可分割使用。年休假当年有效。因工作需要，公司有权随时召回正在休假的员工。员工因为工作原因放弃年休假的，则应发给相应的报酬，发放标准为当月日薪的两倍。
** 工伤假：员工因工负伤的，由所在部门上报人力资源部，经劳动部门认定后，人力资源部门按医院鉴定报告给予工伤假期。
** 法定的节假日：员工可以享受国家规定的有薪节假日，具体安排按照国家规定执行。
** 请假管理：
*** 员工请假，应提前向人力资源部提交请假申请单。请假天数在3个工作日（含）以内的，应提前1个工作日请假；请假天数在4个工作日（含）以上的，应提前3天请假。确因不可预见的原因没来得及提前请假的，应委托他人代为填写请假单。
*** 病、事假期限。到岗后的试用期员工事假每月不可超过2个工作日（含），病假每月不可超过3个工作日（含），试用期间的病、事假合计不可超过5个工作日（含），否则终止试用，予以辞退。正式员工1年内事假不可超过15个工作日（含带薪事假），否则公司将保留采取处理措施的权利。
*** 审批权限。一般员工事假1个工作日以内（含）、其他休假3个工作日以内（含）的，由所在部长审批。事假1个工作日以上、其他休假3个工作日以上由部长审核，员工所在部门分管副总裁审批。部长级（含）以上级别员工请假，无论天数多少，需经过分管副总裁审批。
** 奖励与处罚：
*** 全勤奖。凡工作满1年的员工如在全年内没有迟到、早退、旷工、病假、事假及其他休假（除法定节假日），可在年末获得全勤奖金XXXX元。
*** 迟到、早退在30分钟之内者，每次扣日薪的10%。超过30分钟者，每次扣发日薪的50%。超过1个小时，扣发全天日薪。
*** 1个月内每旷工1天者，扣发固定月薪的30%，1年内连续旷工达15天或累计旷工30天者，公司予以辞退。
* 附表
** 有关考勤和假期管理的文件和表格清单如下。
*** 《[[id:f24b6cd6-7fd2-4129-a5f3-300374f9ae81][加班记录表]]》
*** 《[[id:b625f480-4ed4-4ad5-9991-78996245b1b4][请假申请表]]》
*** 《[[id:b8301963-b4a8-4fde-99d9-e8d7c1c4b066][考勤汇总表]]》
