:PROPERTIES:
:ID:       7fb4d39c-729e-4d59-965b-d5f264f62843
:END:
#+title: 注氮防灭火的管理制度
矿必须安设一套制氮装置，分别布置在地面工业广场内。注氮主管路为φ100mm的铁管，共敷设注氮管路4趟，注氮管路遍及井下所有采面，能24小时不间断地向采空区注氮。为保证注氮泵正常运转和制氮能够达到要求。特制定本制度。
* 管理职责
** 机运科负责制氮装置的使用、维护和检修，每周对注氮装置的运行情况进行全面检查，确保注氮装置运行正常。
** 队组负责按设计进行注氮管路铺设工作，对注氮管路系统管理、维护和巡视检查，确保注氮管路无积水、无漏气，能正常向注氮地点进行注氮，并做好注氮记录。
** 通风科负责注氮管路设计和注氮地点注氮情况检查，每天对制氮装置的氮气浓度进行检查，确保注氮浓度不小于97%。对注氮地点的注氮量表进行检查和维护，确保计量准确。负责编制注氮管路的安装设计，监督队组严格按照设计进行施工。
* 管理要求
** 在采空区进行注氮防火或在火区进行注氮灭火前，必须编制相应的安全技术措施，并经矿总工程师审批后，方可实施。
** 通风科、机运科应充分发挥其协作配合作用，不得私自拆移、破坏矿井注氮设施。矿井注氮防灭火系统、设施的拆移必须经矿总工程师同意由队组安排人员注氮进行作业。
** 矿井注氮灭火材料、设备、资金应列入矿财务考核、供应和生产计划中，并保证及时、足量供给。
** 通风科、安全科负责监督检查本设计方案的贯彻实施。
** 注氮管路连接好后，采用空压机加载空气进行管路耐压试验，检查泄漏，耐压压力必须达到0.8MPa。
** 注氮设备安装完好后，由通风科指派专人跟班进行首轮注氮试验，试验宽度不小于15m的氧化带宽度。试验期间，查找注氮设备及注氮方法当中存在的问题，提出改进、完善意见，进一步完善修改注氮专项设计。
** 合理设置监测传感器，加强对采空区、工作面和回风巷中O2.N2和CO的监测；同时由瓦检员沿工作面上隅角、回风流不断巡回检查，密切观察各项气体的动态涌出情况，对工作面及其回风巷的O2.CO和CH4浓度进行检查，并记录数值，气体超限时，严禁人员进入，并标明范围，悬挂警标。发现工作面氧气浓度降低，应暂停注氮或减少注氮强度，确保安全生产。
** 第一次向采空区注氮，或停止注氮后再次注氮时，应先排出注氮管内的空气，避免将空气注入采空区中。
** 注入氮气的纯度不得低于97%。
** 在注氮过程中，工作场所的氧浓度不得低于18.5%，否则停止作业并撤除人员，同时降低注氮流量或停止注氮，或增大工作场所的通风量。
** 注氮量的多少，应根据采空区中的气体成分来确定，以距工作面20m处采空区中的氧浓度不大于10%作为确定的标准。如果采空区中CO浓度较高（>50ppm），或者工作面CO浓度超限，或出现高温、异味等自燃征兆，都应加大注氮强度。
** 注氮期间，注氮工作面必须设置救护队员值班，加强采空区的氮气泄漏情况与工作面的氧气浓度检查。
** 每班的氮气注入量不得随意调整，需要调整时由通风科根据推进度、配风量等因素进行计算、经矿总工程师同意后进行调整。
** 注氮作业时，瓦检员对工作面上、下隅角采取打设风幛措施进行封堵，减少向采空区漏风。
** 在管路上安设观察孔，测定注氮管路中的氧气浓度，发现氧气浓度大于3%时，应及时停止注氮，查明原因，进行处理。首次注氮时（含以后每次重新开启制氮设备），应将管路中的空气排空，待注氮管路中的氧气浓度低于3%时，方可开始注氮。
** 注氮作业期间，由通风科组织对注氮工作面进行适度的均压调节，减少采空区的氮气泄漏。
** 注氮期间，救护队派专人检查注氮灭火区及工作面的气体、气温、煤温、出水温度、钻孔气体等情况，并进行每天采气样化验。分析注氮防灭火效果，包括注氮前、后的采空区的三带变化情况、注氮量、注氮扩散半径、注氮口移动步距等。
** 注氮作业过程中，工作面的氧气不得低于20%，否则立即停止作业，撤出人员，同时降低注氮流量或停止注氮。
** 制氮设备的管理人员和注氮操作人员必须经过培训，考试合格，并取得上岗证后，方可上岗。队组注氮小组必须建立操作规程、工种岗位责任制、机电设备维护检修制度。
** 首次注氮试验，通风科指派专人在下端头注氮连接口监控排出空气直到输出氮气的过程，检查输氮管路阀门及注氮支管阀门的密封情况；采空区注氮支管阀门除正常注氮期间，其余时间应处于长闭状态。密切观察工作面风流中的氧气浓度和各项气体，气体浓度异常时，必须及时撤人并调小注氮流量，确保安全生产。
** 下端头注氮连接口必须设置三通调节阀门，并保证连接牢固可靠。检测氧气浓度小于3%时，方可切换至注氮接口。当检测释放口附近巷道风流的氧气浓度低于18%时，必须先关闭输氮出口，并有专人观察输氮管路密封情况。
** 正常注氮期间，救护队员与瓦检员必须沿工作面上隅角、回风流不断巡回检查，密切观察各项气体的动态涌出情况并每半小时记录一次涌出数值。通风科技术室收集首轮注氮期间的各项数据，并绘制变化曲线。
** 第一次注氮期间，每天束管采集采空区气样进行化验、分析。
** 正常注氮期间，救护队员级瓦检员密切观察工作面上隅角氧气浓度情况及各项气体的涌出情况，气体超限时，严禁人员进入，并标明范围，悬挂警标。
** 回采期间一旦工作面因遇地质构造推进速度缓慢停滞不前或监测到自然发火标志气体且呈现快速增长趋势时，则应加大采空区注氮量，同时配合采取均压、堵漏措施，并加强火区监测。
** 瓦检员及其他流动人员必须携带便携式测氧仪器。
** 建立注氮防灭火台帐。
** 注氮防火、灭火区的管理、熄灭标准、注销和启封要求以及防火墙的管理，应按《煤矿安全规程》和《矿井防灭火规范》的规定执行。
