:PROPERTIES:
:ID:       3eb08e35-4dee-402c-91f4-2ecbd206a095
:END:
#+title: 瓦斯地质图管理制度
随着矿井往深部延伸，矿井地质构造、瓦斯、煤与瓦斯突出等灾害越来越严重，为了加强瓦斯地质管理工作，防止重大事故的发生，经矿研究决定开展瓦斯地质工作，特制定本管理办法。
* 瓦斯地质工作职责
生产技术科：是开展瓦斯地质工作的业务主办部门，在矿总工程师的领导下，负责按规范规定的瓦斯地质工作内容开展瓦斯地质工作。
通风科：瓦斯地质工作的协助部门，负责瓦斯地质工作所需各种瓦斯基础数据的提供。
总工程师：对矿瓦斯地质工作负全面技术责任。负责矿瓦斯地质工作的业务指导、监督、检查，领导瓦斯地质工作正常有效开展。
* 瓦斯地质工作内容
** 开展瓦斯地质调查
*** 研究矿地质构造，作出构造应力场分析，并按其分布特点，找出应力集中区。
*** 进行瓦斯构造预测，指导矿井采掘部署，预测瓦斯涌出规律，划定出危险带、过度带、不突出带。
*** 研究煤层厚度变化，确定变化带位置；分析构造变化的原因，对突变部位，诸如煤层分合区界线、构造增厚或变薄带、陷落柱边界等，尽可能占有详细资料。
*** 调查鉴定煤层的各个分层特征，确定煤结构的破坏类型，定出可能共发生突出的松软分层厚度最小值（始突厚度）。
** 编制瓦斯地质图
矿井瓦斯地质图选用l：5000或1：2000煤层底板等高线图（含各类巷道）作底图，分煤层编制。
瓦斯地质图主要内容：
*** 标注瓦斯取样点位置；在各取样点的钻孔旁边注明瓦斯含量、瓦斯压力、见煤标高及距地表垂深；在样点密集处可计算瓦斯变化梯度，绘制出瓦斯含量和瓦斯压力等值线；根据已控制地段的瓦斯含量、瓦斯压力规律，结合地质条件进行瓦斯含量和瓦斯压力等值线的外推。
*** 标注已发生的突出点位置（包括突出时间、突出类型、突出煤量、突出瓦斯量），同时要尽量反映瓦斯含量，瓦斯压力及突出点附近的煤厚变化、构造特征、煤结构的破坏类型等。
在编图过程中和成图以后，均须注意分析瓦斯分布规律、特点及其与地质构造的关系。
图中应当标明采掘进度、被保护范围，煤气赋存条件，瓦斯基本参数及绝对瓦斯涌出量和相对瓦斯涌出量等资料。
** 做好地质预报工作
*** 积极开展区域性地质构造预测预报，为突出危险性区域预测提供依据。
*** 努力搞好采掘工作面地质构造预测预报，以指导采掘布置和防突工作：
- 掘进工作面施工前，应提交地质构造预测剖面及文字说明；
- 石门（包括断层）揭煤，应将地质剖面分别挂在矿调度室和施工现场，并及时填绘施工进度，防止误揭（穿）煤层；
- 保护层如留有煤柱，被保护层进入煤柱前30m必须向下书面通知。
- 采煤工作面开采前，应探明有无隐覆构造、以指导回采工作。
- 地质人员应做到“三勤”，即：眼勤、腿勤、手勤。经常深入现场收集地质资料，不断修正地质预报资料，更好地指导采掘及防突工作。
