:PROPERTIES:
:ID:       aed6a3f5-41df-4ef4-9171-b12982f6b12d
:END:
#+title: 钢丝绳管理制度
为加强钢丝绳购置、使用、回收的全过程管理，保证钢丝绳安全可靠的使用，避免浪费，特制定此管理制度。
* 钢丝绳的采购、验收与保管
（一）钢丝绳必须具有以下证件：生产许可证、产品合格证、煤矿矿用产品安全标志、产品质量证明书。对没有煤矿矿用产品安全标志的进口钢丝绳，须取得相关部门的认定。
（二）钢丝绳必须原始资料齐全，铭牌与实物一致，外观检查无明显缺陷。验收合格后出具验收报告，验收人须在验收报告上签字。
（三）钢丝绳验收合格后入库统一妥善保管，防止锈蚀或损坏。库存备用的钢丝绳，必须放在牢固可靠的支架上，离地300mm以上且不得倾斜。库存备用的钢丝绳，应建立技术档案，妥善保存原始资料及入库前的验收报告。
（四）存放时间超过1年的钢丝绳，在悬挂前必须再进行１次检验，合格后方可使用。
（五）直径为18mm及其以下的专为提升物料用的钢丝绳，有厂家合格证书，外观检查必须无锈蚀和损伤。
* 钢丝绳的悬挂与检验
（一）新绳悬挂前，使用队组必须指定技术人员对新绳进行检查，检查内容包括：“生产许可证、产品合格证、煤矿矿用产品安全标志”、产品质量证明书、钢丝绳规格型号与使用要求是否一致，并对其外观进行检查。
（二）新绳检查合格后，矿井相关人员应截取试样进行检验。
（三）钢丝绳经检验合格，依据检验报告提供的合格钢丝拉断力总和，并结合钢丝绳负荷验算钢丝绳安全系数，安全系数必须符合《煤矿安全规程》规定，规定如下表：
表  钢丝绳安全系数最低值
用途分类	安全系数*的最低值
单绳缠绕式提升装置	专为升降人员	9
升降人员和物料	升降人员时
混合提升时
升降物料时	9
9
7.5
专为升降物料	6.5
摩擦轮式提升装置	专为升降人员	9.2-0.0005H***
升降人员和物料	升降人员时
混合提升时**
升降物料时	9.2-0.0005H
9.2-0.0005H
8.2-0.0005H
专为升降物料	7.2-0.0005H
倾斜钢丝绳牵引带式输送机	运  人	6.5-0.001L***
但不得小于6
运  物	5-0.001L
但不得小于4
倾斜无极绳绞车	运  人	6.5-0.001L
但不得小于6
运  物	5-0.001L
但不得小于3.5
架空承人装置
悬挂安全梯用的钢丝绳
罐道绳、防撞绳、起重用的钢丝绳
悬挂吊盘、水泵、排水管、抓岩机等用的钢丝绳
悬挂风筒、风管、供水管、注浆管、输料管、电缆用的钢丝绳
拉紧装置用的钢丝绳
防坠器的制动绳和缓冲绳（按动载荷计算）	6
6
6
6
5

5
3
 钢丝绳的安全系数，等于实测的合格钢丝绳拉断力的总和与其所承受的最大静拉力（包括绳端载荷和钢丝绳自重所引起的静拉力）之比；
 混合提升指多层罐笼同一次在不同层内提升人员与物料；
    H为钢丝绳悬挂长度，m；
   L为由驱动轮到绳部尾轮的长度，m。
（四）新钢丝绳的使用与管理必须符合《煤矿安全规程》第四百一十条规定。
（五）在用钢丝绳的检验、检查，必须符合《煤矿安全规程》第四百一十一条规定：
1.升降人员或升降人员和物料用的缠绕式提升钢丝绳，自悬挂时起每隔6个月检验一次性能检验；悬挂吊盘的钢丝绳，每12个月检验1次。
2.升降物料用的缠绕式提升钢丝绳，悬挂使用12个月内必须进行第一次性能检验，以后每6个月检验1次。
* 钢丝绳的使用与维护
** 使用队组应配备验绳工（兼职）对钢丝绳进行日常的检查。验绳工应由熟知《煤矿安全规程》对钢丝绳的有关规定，并经技术培训合格者担任。钢丝绳检查人员应保持相对稳定，明确分工。
** 使用队组必须对在用的钢丝绳每天检查一次，安装回收大型设备时，安排验绳工对主提升绞车钢丝绳进行检查。检查质量标准符合《煤矿安全规程》规定。钢丝绳的检查内容应包括：断丝、直径缩小、严重变形、意外损伤和锈蚀等情况，并注明部位。对使用中的钢丝绳，每月涂油一次。
** 验绳的方法及要求：
*** 工作开始前要与提升机司机、监护人员及信号工共同确定好联系信号。检查期间不得同时进行提升机的其它检修工作。
*** 验绳时应采用不大于0.3米/秒的验绳速度，以目测观察和用手捋摸相互配合的方式进行。
*** 验绳时禁止戴手套，应用裸手直接触摸钢丝绳，前边的手作为探知是否有突出的断丝，以免伤手，后面的手抚摸可能发生的断丝和绳股凹凸等变形情况。
*** 验绳时必须使用游标卡尺测量钢丝绳直径，并详细检查绳卡处有无断丝（一般情况下，钢丝绳绳头采用插接方式）。
*** 验绳结束后，要做好钢丝绳检查记录，将检查内容、检查结果详细填入钢丝绳检查记录本。
** 检查中若发现断丝的断面积或钢丝绳直径减小量超过《煤矿安全规程》相关规定，或其他异常情况时，应立即向区科领导汇报，并停止提升。
*** 《煤矿安全规程》第四百一十二条：各种股捻钢丝绳在1个捻距内断丝面积与钢丝绳总断面积之比，达到下列数值时，必须更换：
- 升降人员或升降人员和物料用的钢丝绳为5%。
- 专为升降物料用的钢丝绳、平衡钢丝绳、防坠器的制动钢丝绳（包括缓冲绳）、兼作运人的钢丝绳牵引带式输送机的钢丝绳和架空乘人装置的钢丝绳为10%。
- 无极绳运输用的和专为运物料的钢丝绳牵引带式输送机的钢丝绳为25%。
*** 《煤矿安全规程》第四百一十二条：以钢丝绳标称直径为准计算的直径减少量达到下列数值时，必须更换：
- 提升钢丝绳、架空乘人装置或制动钢丝绳为10%。
- 使用密封钢丝绳外层钢丝厚度磨损量达到50%时，必须更换。
** 钢丝绳在运行中突然停车等猛烈拉力时，必须立即停车检查，发现下列情况之一者，必须将受力段剁掉或更换全绳：
*** 钢丝绳产生严重扭曲或变形。
*** 断丝超过《煤矿安全规程》第四百一十二条的规定。
*** 直径减小量超过《煤矿安全规程》第四百一十二条的规定。
** 使用有接头的钢丝绳时，必须遵守《煤矿安全规程》第四百一十四条规定，即：
*** 有接头的钢丝绳，仅限于下列设备中使用：
- 平巷运输设备；
- 无极绳绞车；
- 架空乘人装置；
- 钢丝绳牵引带式输送机；
*** 钢丝绳接头的插接长度不得小于钢丝绳直径的1000倍。
** 钢丝绳绳头插接长度不得小于钢丝绳直径的30倍。
* 其它补充规定
** 各使用队组加强对钢丝绳的维护保养，每月一次给钢丝绳抹油，延长钢丝绳使用寿命。
** 新绳更换后，旧绳须回收处理。
** 各使用队组必须加强对斜坡轨道地辊管理，地辊位置要安装适当，以不磨绳为原则，发现轴承损坏要及时更换。清理轨道杂物，地辊固定牢固可靠，保证转动灵活。
** 各使用队组在使用钢丝绳时要经常进行检查维护，防止损坏二次投入：
*** 在绞车滚筒上排列要整齐；
*** 钢丝绳拐弯处必须使用滑轮或限位轮，以防钢丝绳摩巷邦造成意外损伤；
*** 反拉矿车或设备、物料时必须使用滑轮导向，严禁用单体柱、工字钢、大链、木料等代替导向轮；
*** 严禁硬拉重物。
** 立井和斜井使用的连接装置的性能指标和投入前的试验必须符合《煤矿安全规程》第四百一十六条规定。倾斜井巷运输时，矿车之间的连接、矿车与钢丝绳之间的连接，必须使用不能自行脱落试验合格的连接装置，并加装保险绳。
