:PROPERTIES:
:ID:       d0a0e984-dc3d-4623-8980-f29f16156e5f
:END:
#+title: 事故监测与预警制度
* 应急信息报告
** 应急信息是指辖区内发生的各类重大突发事件，重要社会动态，紧急灾情、疫情以及其它重要情况，包括如下：
*** 自然灾害。主要包括旱涝灾害；地震灾害；山体滑坡、泥石流、地面塌陷、地裂缝等地质灾害；暴雨、冰雹、大雪、大风、大雾、雷电、沙尘暴、高温、低温等导致重大人员伤亡或财产损失的极端天气气候事件。
*** 事故灾难。主要包括造成人员死亡，或伤3人以上（含3人），或造成重大损失和社会影响的火灾事故、交通事故；工矿企业、建设工程、公共场所发生的重大安全事故；造成重大影响和损失的供水、供电、供气和供热等事故；危险化学品事故；重大环境污染事故、生态破坏事故。
*** 公共卫生事件。主要包括重大传染病疫情；群体性不明原因疾病；食品安全事件；其他严重影响公众健康的事件。
*** 社会安全事件。主要包括造成人员死亡，或伤5人以上（含5人）的刑事案件；伤害身份特殊人员的案件；恐怖活动、恐怖事件；攻击和破坏计算机网络、卫星通信、广播电视传输系统的信息安全事件；绑架、爆炸、投毒事件；大规模非法集资事件；影响民族团结的重要事件。
*** 群体性事件。主要包括到省进京集体上访；影响社会稳定的非法集会、游行、静坐、示威、打横幅、喊口号和罢工（课、市）；聚众堵塞公共交通，冲击围攻党政机关的事件；非法宗教活动；其他规模较大、影响较大的群体性事件。
*** 涉及社会安全以及其他可能对社会稳定造成重要影响的紧急情况；本身较为敏感、已经或可能在社会上形成舆论热点的事件；带有一定苗头性、倾向性、内幕性、预警性、危害性，可能引发重大事件的社会动态。
** 各队组负责人是突发事件应急处置和应急信息报送的第一责任人。
** 遇有一、所列应急信息，事发地责任队组和事涉部门要立即报告，上班期间向矿调度室汇报。
** 应急信息报送的内容要实事求是，主要包括事件的时间、地点、起因、伤亡人数、财产损失和影响范围，事件发生后采取的初步处置措施、存在的问题、需要矿协调解决的事项及未来走势预测，应急信息的报送队组、签发人、联系人及联系电话。
** 对于现场处置特别紧急的重大突发事件，现场有关人员可直接向矿调度室电话报告、请示，之后再按程序报送应急信息。
** 报送应急信息以书面为主，如果情况紧急或尚未完全掌握有关情况，可先口头报告初步情况，然后迅速形成文字材料上报，并跟踪报送事态发展、应急处置、社会舆情和原因分析等详细情况。
** 对于迟报、漏报、瞒报、谎报应急信息的队组和科室，要在矿通报批评，造成较大影响和后果的，要严肃追究责任。
* 应急信息处置
** 要注意信息的时效性，信息传递与反馈要迅速及时，有时要限时完成（如工伤事故等）。重大安全信息，必须按规定时间向上级有关部门报告。
** 信息内容要简明扼要，突出重点。
** 安全信息应分类处理，有处理结果的信息应归档存储。
** 处理原则：能处理的不能推给上级部门，紧急安全信息要求从收集到处理完成不能超过两日；一般信息一周内必须完成。
** 各队组报送的信息，必须填写在规范的表格上，经领导签字并加盖公章后，报送安全部门，情况特殊的，信息员可直接向上级反映信息。
** 召开信息工作会议，总结和发布信息。
* 应急信息预警
** 预警信息发布要准确、及时、客观、全面，最大限度地减少各类突发事件的发生及其造成的危害，保障员工生命健康，维护财产安全，确保安全生产。
** 矿调度室对即将发生或发生的可能性增大，应急根据职责权限和程序要求，发布相应级别的警报，决定并宣布队组、工作面进入预警期，并根据情况变化适时调整预警级别和宣布解除警报。
** 预警信息包括：安全监控监测、束管监测、水位监测等监测系统预警信息、矿井水文、断层、地质构造通知、巷道贯通预透（过）巷通知、现场安全重点，上级发布的恶劣天气（强风、大雨、强降温、冰冻等）、气象灾害（暴雨、台风等）和地质灾害预警信息以及现场人员汇报的预警信息。
** 预警信息应当包括发布队组、发布时间、可能发生的突发事件的类别、起始时间、可能影响范围、预警级别、警示事项、相关措施、咨询电话等。
** 调度员处置所列险情发生时，应立即按照处置要求，向有关队组和人员发布预警信息和处置命令，停止生产，先撤人员，再分析原因。
** 充分利用调度通讯、井下语音广播、无线通讯、广播、闭路电视及电子显示屏、手机短信等传播手段，及时发布预警信息。
** 有关队组和人员接到预警信息后，应当按照有关规定，立即采取应急措施做好防御和处置工作，避免或者降低突发事件造成或可能造成的损害。
** 值班人员要坚守岗位，随时关注预警信息变化情况，密切跟踪灾害发生过程，及时了解现场情况，确保通信联络畅通；及时向应急救援处置相关队组通报情况，加强沟通协调，一旦出现灾情，要立即领导和有关部门报告。
** 全体员工有义务向矿应急管理办公室提供预警信息，瞒报、漏报的将严肃追究。任何队组和个人不得编造、传播虚假预警信息。
** 预警信息发布人员玩忽职守，导致预警信息的发布出现失误，造成严重后果的，对主要负责人、直接责任人给予严肃处理。
