:PROPERTIES:
:ID:       d7fc6248-b0c9-4890-9133-58a6769f7973
:END:
#+title: 专用回风巷巡视及管理制度
为进一步规范专用回风巷管理，使专用回风巷日常检查制度化、规范化、切实落实责任，提高矿通风系统稳定性，结合矿实际，制定本制度。
* 专用回风巷管理制度
** 由生产技术科负责，通风科配合，合理设计专用回风巷的断面，确保断面、风速符合上级要求。
** 专用回风巷内必须使用不燃性材料支护，并应有防止产生静电、摩擦和撞击产生火花的安全技术措施。
** 专用回风巷必须安设瓦斯传感器，瓦斯传感器应悬挂在距专用回风巷口10-15m处，当瓦斯浓度达到0.75%时，能发出报警信号并切断电源，必须停止井下一切工作，撤出人员进行处理。
** 专用回风巷道内不得进行生产作业。
** 若专用回风巷内冲尘或巷道变形、冒顶等需进入处理的，必须制订安全技术措施，经矿总工程师审批后方可执行，并汇报矿调度备案。每次冲尘或巷修前必须报矿调度，经矿调度同意后，方可进入专用回风巷内冲尘或巷修。
** 若专用回风巷内发生冒顶等意外紧急情况，必须经矿调度同意，并停止影响范围内的采掘作业，方可进入处理。
** 专用回风巷内不得有电缆及电器设备，否则，必须制订专项安全技术措施，报矿总工程师审批。
** 任何队组和个人不得擅自进入专用回风巷，否则，按《××矿“三违”管理办法》进行处理。
* 专用回风巷巡视管理制度
** 结合矿生产实际，每旬由通风科进行专用回风巷巡视检查，每次巡视检查时间为8点班，并有巡视检查记录表。
采掘工作面日常的巡视，由各队长及以上管理人员与瓦检员、安全员负责。
巡视人员要认真履行职责。否则，由通风副总负责，根据专用回风巷管理制度规定，对不按时参加检查、不负责任、不按规定巡视、记录、谎报、瞒报、漏报、不报者每次核减薪酬XX元，并对责任队组每次核减薪酬XX元。引起事故者，由安全科调查，按事故责任追查处理。
对所巡视巷道存在的隐患，各队组要及时进行整改，凡是因整改不及时造成风速超限、负压超标的，追究队组责任，安全科负责督促、落实。
** 所有巡视人员进入专用回风系统，必须配备便携式瓦斯检测报警仪，否则按《矿“三违”管理办法》进行处理。
** 在专用回风巷巡视时，最少两人一组，并且一前一后相距不大于5m，并时刻检查顶板支护情况。
** 每次巡视结束后，巡视人员必须作好查记录，安全科制定四定表，由矿总工程师签发，队组严格执行。
* 专用回风巷栅栏管理制度
** [[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]在通往各专用回风巷的入口处设置栅栏及揭示警标，禁止人员进入。
** 采掘工作面回风巷口栅栏以内50m范围的杂物，由队组施工负责回收清理，回风巷其他地点的杂物由巷修队组负责清理回收，其他回风巷执行谁的物料谁清理，谁负责的区域谁清理。
** 通往专用回风巷道口设置栅栏后，采掘爆破作业原则上不再站岗警戒。
** 采掘工作面回风口栅栏的日常管理执行属地管理原则，无确切归属队组的地点归通风科管理。
* 制度如有与上级规定抵触之处按上级规定执行。
