:PROPERTIES:
:ID:       4a18b836-4dec-4c9e-91f2-612064409ea9
:END:
#+title: 四量管理制度
为进一步加强煤炭资源管理，合理开发利用监督，加强对矿井开拓、准备和回采煤量的管理，保证矿井采掘的正常接替，延长矿井寿命。结合矿实际，特制定“四量”管理制度。
* 严格执行《固体矿产资源/储量分类》、《煤、泥炭地质勘查规范》、《煤炭工业技术政策》、《煤炭法》、《矿产资源法》、《生产矿井储量管理规程》及实施细则，按规定的要求进行矿产资源储量的估算、监督和管理。
* 严格按生产矿井地测防治水安全安全生产标准化要求进行日常技术管理，及时填绘各种资源储量图，填写各种台帐，统计各种回采率（包括年度、季度、月度）。
* 严格资源储量增减制度，资源储量变动要按规定的审批权限提出申报，未经上级主管部门批准不得随意自行变动。符合资源储量转入、转出、注销、地质及水文地质损失和报损条件的，生产技术科提出请示，上报主管部门审核批复，没接到批复前不得随意进行破坏性开采，凡未经批准就弃而不采者，按不合理丢煤处理，参加损失率计算，按有关规定进行考核奖罚。
* 回采工作面收尺和地质调查一般要求每旬一次，当工作面推进较快时或构造复杂时应增加观测次数。收尺和地质调查必须深入现场，准确测量，测量的内容包括煤层倾角、厚度、结构、采高、浮煤、丢顶煤厚度、地质构造变化、水文等情况。观测点间距一般10～15米。
* 中厚和厚煤层的工作面要求进行探煤厚工作，探清工作面内丢顶底煤厚度情况，做好原始记录，并做地质素描、建立台帐，将探煤厚资料上图，根据探煤情况提出一次采全高或合理分层、控制采高等建议。
* 加强矿井资源储量业务监督工作，矿资源管理人员要参加水平延深、工作面设计，对设计中违反国家政策和规定的提出建议和意见。对不符合规定、不按设计要求施工或生产，有丢煤可能时，要及时向上级主管领导汇报，并发放“丢煤通知书”。已经造成不合理损失的，按有关规定进行处理，不准出现挂帐煤。
* 按时填绘工作面和队组交换图，矿地质负责人进行认真审核，保证图纸内容准确齐全，无错漏现象。四量每月有地质负责人进行审核，有矿总工程师进行审批，每月25日前将四量报表上报上级部门。
* 矿总工程师要每月组织有关部门对资源储量动态、损失量及回采率指标完成情况进行全面的检查、分析，找出问题，不断改进。
* 四量说明
** 开拓煤量是在矿井可采储量范围内已完成设计规定的主井、副井、风井、井底车场、主要石门、采盘大巷、回风石门、回风大巷、主要硐室和煤仓等开拓掘进工程后，形成矿井通风、排水等系统所圈定的煤炭储量，减去开拓队内地质及水文地质损失、设计损失量和开拓煤量可采期内不能回采的临时煤柱及其它开采量。
** 准备煤量是在开拓煤量范围内已完成了设计规定的采盘主要巷道掘进工程，形成完整的采盘通风、排水、运输、供电、通讯等生产系统后，且煤与瓦斯突出煤层煤巷条带区域无突出危险的煤层中，各区段（或倾斜条带）可采储量与回采煤量之和。
** 回采煤量是准备煤量范围内，已按设计完成工作面进风巷、回风巷等回采巷道及开切眼掘进工程所圈定的，且瓦斯抽采、防突和防治水的效果已达到工作面安全回采要求的可采储量，即正在回采或只要安装设备后，便可进行正式回采的工作面可采煤量之和。
瓦斯抽采、防突和水害防治效果达到安全回采要求的可采储量，可以按工作面推进方向分段计算，分段长度不得小于300米。
** 安全煤量是在开拓煤量范围内已完成了设计规定的采盘主要巷道掘进工程，形成完整的采盘通风、排水、运输、供电、通讯等生产系统后，经抽采达标和消除突出危险后的煤量。且煤与瓦斯突出煤层煤巷条带区域无突出危险的煤层中，各区段（或倾斜条带）可采储量与回采煤量之和。
