:PROPERTIES:
:ID:       150349f6-8a10-41d4-8d1b-8bd391fc17eb
:END:
#+title: 瓦斯仪器检修工安全操作规程
* 瓦斯仪器检修工负责瓦斯检定器的检修、校正、电池更换、药品收发管理工作。
* 保持室内清洁、明亮、干燥，备有常用工具、仪表、材料以及工作台。
* 压力表的装置形式可采用垂直形，要求能任意调压、停压不漏气、操作连接方便，易于观测压力的变化情况。
* 对收回的光学瓦斯检定器，手压气泵5～6次后，其基线应回零。仪器要擦净，各部件应螺丝齐全、连接牢固可靠、松紧适度，转动部分平稳、柔和，不应有卡滞和急跳现象，并有足够的调整范围。
* 对气泵进行检查时，要求在将气泵捏瘪并将胶管折堵后，1分钟内气泵不鼓涨。
* 用水柱计对气路（不包括药管）进行密封性检查时，要求在将水柱计水柱高度加压到700毫米后，1分钟内水柱不下降。
* 电源应开关灵活，仪器条纹清晰。
* 仪器精度通过目镜观测，干涉条纹应符合目力定度要求（0%～7%范围内应有5根条纹），不弯曲。
* 变色吸收剂的变色部分超过二分之一时，要更换。氯化钙有潮解现象时，要更换。
* 检查测微部分时，要求在将基准条纹对准1%、并把小数从“O”调到“1”后，基础条纹应回到零位。
* 正常使用的便携式热催化甲烷检测仪，每7天清理一次网上的煤尘，以保持通气性能良好。
* 为保证仪器可靠工作，使用前必须进行电压检查。在接通仪器电源5分钟后观察欠压指示或电源指示是否正常，如显示欠压或电池电压不足，要重新充电。电池电压不足时，不准投入使用。
* 接通仪器电源开关前，应首先检查电表指示是否在零位，如果不在，应用螺丝刀调整好机械零位。
* 电池电压与机械零位合格后方能进行电零位检查，检查时，先接通电源5分钟，然后在新鲜空气中观察机械指示是否在零位，若有差值，可用螺丝刀轻轻调节仪器的零位电位计使其机械指示为零。
* 对检修的仪器各部分要细致检查，查清故障部位，按检修顺序依电路、光路、气路进行检修。
* 拆装螺丝时要用大小合适的螺丝刀，刀尖与螺丝头应垂直。当一个组合件上有几个螺丝时，不可把其中的一个螺丝先拧松或拧紧，而应将对称的各个螺丝均匀的拧紧或拧松。当螺丝孔有脱扣现象时，不准扩大孔径，要在加铆套重新套丝扣后才能使用。
* 气球组的胶皮球破裂、活塞芯子老化时应更新，气球组的排气嘴、进气嘴与球的接触面老化时，应涂胶水密封或更换新品。
* 检修干燥管组时，应把管组一端胶管折住，将另一端水柱计高度加压到700毫米，要求1分钟内水柱不下降；否则应排除故障。常见的故障和排除方法有：
** 胶管老化、有裂纹，更换新品；
** 干燥管本身有裂纹，更换新品。
更换硅胶时，两端要垫脱脂棉，下端厚10毫米，上端厚5毫米；两端若垫海绵，下端厚15毫米，上端厚10毫米。
* 二氧化碳吸收管组气密性的检查与干燥管组一样。常见的漏气原因和故障排除方法有
** 胶质垫圈老化，更换新品；
** 金属螺盖开焊，应重新焊接；
** 管的端面不平或呈马蹄形，要用钢锉或砂纸研磨，直至密封良好为止；
** 管本身老化，出现裂纹、螺丝滑扣，更换新品。
* 检修气室时，要求气室不漏气、不串气，内表面呈黑色。清洗气室时，将平面玻璃加热后垂直取下，气室的胶装面要作标记；气室腔和弯管要清洗干净；包角螺丝、气室外表要擦干净，安装时胶量要适当，要求既胶装牢固，又看不出多余胶剂。装完后应进行气密性试验。
* 检修调微组时，要检查螺杆与连接座是否紧密柔和，要求每次检修要进行清洗，并检查固定连接座的螺丝是否松动。
* 检修开关组，在出现诸如按钮弹不起、按钮接触片相碰造成灯泡长明或开关座出现裂纹、螺丝滑扣、电接触片锈蚀等情况时，应重整丝扣或打磨、调整弹簧、调整电接触片等进行检修或更换新品。
* 下光源组常见故障及排除方法有：灯泡损坏要更换；灯泡接触环上的螺丝锈蚀或松动，应用砂纸打磨或拧紧；灯泡绝缘圈松动，即便把压紧圈拧到底还不能压紧灯泡，可用粘合剂把灯座绝缘圈粘牢；出现电路短路若是灯泡接触环与灯座连接筒中间有金属屑时，应将其清除干净。
* 目镜组常见故障及排除方法有：保护玻璃划伤严重或破碎，应更换新品，新换的保护玻璃要用虫胶或指甲油粘牢，粘胶时涂胶不可过多，以免影响透光，要待胶干燥后方可使用；当旋转目镜视场中有污点随之转动时，如接目镜、场镜未擦拭干净，有脏物，应分解目镜组，取出接目镜并将其擦拭干净，装配时两镜片的鼓面相对，并且镜头平面要与光轴垂直。
* 在检修分划板时，若旋转目镜头脏点不随之转动，说明分划板上有脏物，是实点，说明脏物在有刻线一面；是虚点，则脏物在另一面。擦拭分划板时，不得用酒精、苯、乙醚等有机溶液擦拭，以免损坏刻线及四周的漆层。当分划板与底座脱落时，应用虫胶或指甲油粘合，粘合时有刻线的一面应朝上，并与底座同心。
* 盘形管组要畅通，气密性要良好。检修时，将气球一端与盘形管连接，压瘪气球，气球若在10s内鼓起，即认为通气性良好。
* 检修各镜片组时，各镜片要擦拭干净，不得有灰尘、指印。擦拭时，可用小竹签卷上脱脂棉轻轻擦拭镜片表面，擦拭的手指只能拿住镜头毛面；不得用金属工具进行擦拭，以免划伤镜面。擦拭中可用脱脂棉沾上少许酒精或苯、乙醚等溶剂进行擦试，然后用脱脂棉擦干。
* 找光谱的方法是，各镜片检修合格并按要求装好后，将粗动手轮拧到底再反转两周左右，使反射棱镜座与壳体平行，接通电源，使光通过聚光镜射向平面镜，调整灯泡、聚光镜光屏、平面镜使平面镜射出的最亮的一束光与瓦斯室螺丝孔右侧相切，其高度与上螺丝孔相平，移动反射棱镜，光谱即可出现在目镜里。检修时应注意以下问题：
** 各镜片不得有影响光谱的划痕、掉块，平面镜、折光棱镜、反射棱镜的镀膜部分必须完好，物镜不得开胶；否则一律更换新品；
** 装配平面镜时，平面镜的下部和后部要与镜座靠紧，固定压板的两螺丝的压力应相同，松紧适度，如果用弹片固定，弹片应位于镜片中部，以免镜片受力不均影响光谱；
** 装配折光棱镜组时，两支柱的高度要相等，弹片位置应在镜片中部，压板的两个螺丝应松紧适度、压力相同。两个偏心垫圈要夹靠住镜片，以使镜片前表面与镜座上的档片靠紧；
** 反射棱镜组的镜座底部由于调零螺杆的长期顶压，会出现麻点、凹坑等，应用平板油石研磨，使之平整。弹簧片弹性减弱或失效时，可将其翻过来再用或更换新品。装配时镜片后面与镜座应靠紧，以防松动；
** 侧微玻璃弹簧片的弹性减弱或失效时，可调整弹簧片的形状以增大弹性，或更换新品；
** 各镜片安装要紧密牢固，方位、角度端正，光线能以正确角度通过。各镜片底座严禁锉磨。干涉条纹宽窄不合适时，可通过调整平面镜组衬垫锡铂纸来解决。
* 基本误差对不同量程的仪器应不超过有关规定。对于回程误差，要求在相同条件下，仪器正反行程在同一示值上的被测量差的绝对值，应不超过有关规定。
* 对于零值误差，在将基准条纹对准零位、并把水柱计水柱高度加压至550毫米后又降到零位的情况下，基准条纹的零位值误差的要求是：甲烷量程为0%～10%的仪器不超过±0.05%；量程为0%～100%的仪器不超过±0.5%。
* 仪器在正常工作时因位置倾斜而产生的指示值变化，称倾斜误差。其值应不超过有关规定。
* 良好的气密性能要求用水柱计分别对仪器的气路系统、压力平衡系统和空气室加压到7000帕时，5分钟内压力下降值不得超过10帕。
* 对仪器的扩散性能进行校验时，将调整好的仪器置于甲烷浓度为2%～3%的试验气体容器中，容器内外气压平衡，要求历时8小时后读取的因甲烷扩散到仪器空气室内而引起的零位移动值的绝对值、对CH4量程为0%～10%的仪器不超过0.05%。
* 通电后的检查要求：外露的动作部件能正常动作；转动调零手轮应能寻找到干涉条纹，且干涉条纹明亮清晰，不得有明显的弯曲和倾斜；基准干涉条纹的宽度、灰度、边界清晰度用眼观察后与厂家提供的干涉条纹卡片对比，符合要求；转动调微手轮应能见到干涉条纹的微移动；主分度板经调节能连续见到分度线和数字；目镜视场内不应有明显的影响测试的锈蚀、汽泡、砂眼、麻点、擦痕、指印和灰尘等。
* 备好浓度在2%～3%之间的甲烷标准气样。校正精度时，接通仪器电源，预热5分钟，通入甲烷气样，流量控制在100毫升/分至300毫升/分（根据仪器的使用说明书确定流量）。如果仪器指示与气样甲烷浓度不相符，用小螺丝刀调整精度（满度），使表头显示数字与甲烷浓度相符。
* 设置报警点时，用稍高于设定点浓度的甲烷气样通入气室，控制气体流量，使指示稳定地停在设定点位置，再调节仪器的报警电位器，使其报警，然后反复通气校验，直到准确报警为止。
