:PROPERTIES:
:ID:       4a484ff2-11c0-4c54-a723-d8bc44d87481
:END:
#+title: 防治煤与瓦斯突出管理制度
* 总则
** 为了加强防治煤（岩）与瓦斯（CH4）突出（以下简称突出）工作（以下简称防突工作），预防煤矿事故，保障从业人员生命安全，根据《[[id:4393e9ee-72d3-4f1a-874f-3992117f40b0][中华人民共和国安全生产法]]》《[[id:4758e44a-c9b1-4508-87ea-8497cb6f1e74][中华人民共和国矿山安全法]]》《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》等，制定本细则。
** 防突制度制定的依据：《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》、《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》、《防突实施细则》等。
** 本制度所称突出煤层，是指在矿井井田范围内发生过突出或者经鉴定、认定有突出危险的煤层。
** 矿设立[[id:a5ca5bb4-2db5-4d37-9b58-221dc00e4c1a][防突领导小组]]和[[id:2b11970c-cd35-453e-a094-c6a8ff6987ea][防突工作小组]]。
** 必须按规定制定区域综合防突措施和局部综合防突措施。
区域综合防突措施包括下列内容：
*** 区域突出危险性预测。
*** 区域防突措施。
*** 区域措施效果检验。
*** 区域验证。
局部综合防突措施包括下列内容：
*** 工作面突出危险性预测。
*** 工作面防突措施。
*** 工作面措施效果检验。
*** 安全防护措施。
** 防突工作坚持“区域综合防突措施先行、局部综合防突措施补充”的原则，按照“一矿一策、一面一策”的要求，实现“先抽后建、先抽后掘、先抽后采、预抽达标”。突出煤层必须采取两个“[[id:6f5e8f2f-fc30-44d2-86ce-0c276bf1007c][四位一体]]”综合防突措施，做到多措并举、可保必保、应抽尽抽、效果达标，否则严禁采掘活动。
在采掘生产和综合防突措施实施过程中，发现有喷孔、顶钻等明显突出预兆或者发生突出的区域，必须采取或者继续执行区域防突措施。
** 防突所需的人力、物力、财力保障安排由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织编制，报[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]审批，矿分管副矿长组织实施。
** 下列防突设计（措施）等由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织编制，报上级部门审批：
*** 新水平编制的《[[id:d758e93b-1879-4ac1-8dfb-c8c457eb9442][防突专项设计]]》；
*** 石门、立井和斜井（巷）揭开突出煤层前编制的防突专项设计。
*** 开采保护层时，采空区内需留煤(岩)柱。
*** 区域预测方案、区域预测结果、区域预测新方法的研究试验、区域防突措施。
*** 保护层和被保护层开采设计依据的保护层有效保护范围等相关参数、保护效果检验、保护范围考察结果等。
* 各级管理人员及相关队组岗位责任制
** [[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]是防突工作的第一责任人，[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]每月进行防突专题研究，检查、部署防突工作；保证防突科研工作的投入，解决防突工作所需的人力、财力、物力；确保“抽、掘、采”平衡；确保防突工作和措施有效落实。
[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]对防突工作负技术责任，负责组织编制、审批检查防突工作规划、计划和措施。
[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]负责开拓、掘进工作面生产过程中的防突工作。负责采煤工作面生产过程中的防突工作。
[[id:21350f90-65e1-46b4-8bb9-c24d0aae7787][安全副矿长]]负责督促防突责任的落实。
[[id:20bd34bb-4ce1-44e3-bb8a-3fe174f78626][生产技术科]]负责施工设计把关，搞清构造和煤层赋存情况。
[[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]负责防突工作的监督，督促落实防突责任。
[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]负责防突工程设计、措施等的编制，并负责上报和落实等工作。
矿其他队组对本职范围内的防突工作负责。
** 矿防突工作领导小组及专业防突队伍，负责防突管理、技术指导、措施实施和新技术的推广应用等工作。
*** 编制防突年度、季度、月度计划并按程序报批。
*** 严格执行区域及局部综合防突措施。
*** 区域防突措施、局部防突措施的实际控制范围与设计不相符时，及时采取补充措施。
*** 认真收集相关资料，分析、总结防突情况，探索矿井突出规律，并制定针对性的防突措施。
*** 负责防突仪器、仪表的使用、维护和送检等工作。
*** [[id:389ea8bc-6491-4765-89d5-589c9434d01c][防突人员]]对所在岗位的防突工作负责。
** [[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]防突工作职责：
*** 监督区域及局部综合防突措施的落实。
*** 负责构筑通风设施、检查有害气体、测定风量等,确保通风系统合理、稳定、可靠。
*** 负责监测监控设备、设施的安设、维护、调校等工作，确保监控有效，并保存相关资料。
*** 对安全防护设施、设备进行巡查，确保设置合理、完好、可靠。
*** 按照《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第二十五条的规定，地质测量部门与防突机构、通风部门共同编制矿井[[id:4f67c15f-8ea1-4ba7-9330-8b0853be14ac][瓦斯地质图]]等。
** [[id:bf6d254c-78bd-4e91-bc30-6b2ca8772824][地质测量部门]]防突工作职责：
*** 负责与[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]共同编制[[id:4f67c15f-8ea1-4ba7-9330-8b0853be14ac][瓦斯地质图]]，图中标明采掘进度、被保护范围、煤层赋存条件、地质构造、突出点的位置、突出强度、瓦斯基本参数及绝对瓦斯涌出量和相对瓦斯涌出量等。
*** 负责提供采、掘工作面的[[id:0983301d-c92f-4271-ae1b-787b40fe4ad5][地质说明书]]，其内容应包括[[id:ce500601-2eaa-4a41-9218-981f398e7dca][地质构造]]、[[id:5b27a5c3-6c0f-40bd-a2a6-6364434e1b99][煤层瓦斯含量]]、[[id:a897fa6c-c8b3-492f-8199-f3e3908dcdf6][煤层瓦斯压力]]、[[id:e482e4cc-25ba-45cf-bf2a-ef52dd7d5aa2][煤层突出危险性]]等。
*** 参与年度、季度、月度防突计划的编制及防突措施的审查工作。
*** 加强突出煤层采掘工作面的地质资料收集和地质预测预报工作，及时将预测预报结果向防突工作领导小组汇报，遇较大变化时，随时通报。
*** 将开采保护层过程中留设煤柱的情况，在[[id:4f67c15f-8ea1-4ba7-9330-8b0853be14ac][瓦斯地质图]]及井下对应位置进行标注等。
** [[id:20a19356-16c8-400e-87b6-2d585aaefd85][物资供应科]]将批准后的防突计划纳入年度、季度、月度生产计划。
** [[id:20bd34bb-4ce1-44e3-bb8a-3fe174f78626][生产技术科]]负责参与防突计划、措施的编制、审批，并监督措施的落实等工作，围绕不掘突出头、不采突出面，完善采掘布署，完善通风系统。
** [[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]负责防突工作的监督检查，督促落实防突责任；负责对职工进行防突知识的教育培训，培训内容必须符合《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》、《防突实施细则》及本制度的相关要求，确保从业人员掌握应知应会知识。
** [[id:8a11ef2a-cf90-451b-a001-c88af1433c7d][队组]]防突工作职责：
*** 对管辖范围内的防突工作负直接责任。
*** 突出煤层采（掘）工作面回采（开工）前，必须由[[id:212bce41-e4cd-4644-a5f4-d688453274ff][防突工作领导小组]]进行防突工程专项验收，验收合格后，方可开工。无专用回风系统或专用回风系统不完善的采（掘）工作面不得回采（开工）。
*** 按照防突管理规定组织生产，严禁超采（掘）。
*** 加强职工防突知识教育培训工作，使其熟练掌握突出预兆及其相关防突知识。
*** 采取强有力的措施，确保工人认真履行自己的岗位防突职责。
* 一般规定
** 突出煤层鉴定
*** 突出煤层的鉴定工作应当由具备煤与瓦斯突出鉴定资质的机构承担。
*** 非突出煤层出现下列情况之一的，应当立即进行煤层突出危险性鉴定，或者直接认定为突出煤层；鉴定或者直接认定完成前，应当按照突出煤层管理：
- 有瓦斯动力现象的；
- 煤层瓦斯压力达到或者超过0.74MPa的；
- 相邻矿井开采的同一煤层发生突出或者被鉴定、认定为突出煤层的。
*** 按照突出煤层管理的煤层，必须采取区域或者局部综合防突措施。
*** 煤矿企业应当将突出煤层的鉴定或者认定结果、按照突出煤层管理的情况，及时报省级煤炭行业管理部门、煤矿安全监管部门和煤矿安全监察机构。
** 开采基本要求
*** 必须根据矿生产发展的需要，不断完善瓦斯抽采系统，确保瓦斯抽采系统满足防突工作和瓦斯治理要求。
*** 必须做好防突工程的计划和实施，将预抽煤层瓦斯、保护层开采等工程与矿井采掘部署、工程接替等统筹兼顾，使矿井的开拓、抽巷道、保护层开采和突出煤层（或被保护层）开采“抽、掘、采”平衡，确保在突出煤层采掘前实施区域防突措施。
*** 突出矿井和按突出矿井设计的矿井，巷道布置设计应当符合下列要求：
- 斜井和平硐，运输和轨道大巷、主要进（回）风巷等主要巷道应当布置在岩层或者无突出危险煤层中。矿井上下山布置在突出煤层中时，必须布置在评估为无突出危险区或者采用区域防突措施（顺层钻孔预抽煤巷条带煤层瓦斯除外）有效的区域；
- 减少井巷揭开（穿）突出煤层的次数，揭开（穿）突出煤层的地点应当合理避开地质构造带；
- 突出煤层的巷道优先布置在被保护区域、其他有效卸压区域或者无突出危险区域。
*** [[id:b8daab54-985f-409c-9c55-548d50a89378][地质测量工作]]必须遵守下列规定：
- [[id:bf6d254c-78bd-4e91-bc30-6b2ca8772824][地质测量部门]]与[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]共同编制矿井瓦斯地质图，作为区域突出危险性预测和制定防突措施的依据。矿井瓦斯地质图更新周期不得超过1年、工作面瓦斯地质图更新周期不得超过3个月。
- [[id:bf6d254c-78bd-4e91-bc30-6b2ca8772824][地质测量部门]]在采掘工作面距离未保护区边缘50米前，编制临近未保护区通知单，并报[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]审批后交专业防突队伍、[[id:8b3b7f54-5496-480a-9d1a-a4b33629d2cd][矿调度室]]、[[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]、[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]和相关采掘队组，同时报送上级部门备案。
- 在突出煤层顶、底板岩巷掘进时，[[id:bf6d254c-78bd-4e91-bc30-6b2ca8772824][地质测量部门]]需提前进行地质预测，编制巷道剖面图，及时掌握施工动态和围岩变化情况，验证提供的地质资料，并反馈给[[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]、[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]、[[id:212bce41-e4cd-4644-a5f4-d688453274ff][防突工作领导小组]]和采掘[[id:8a11ef2a-cf90-451b-a001-c88af1433c7d][队组]]；遇有较大变化时，必须随时通报。
*** 突出矿井开采的非突出煤层和高瓦斯矿井的开采煤层，在延深达到或超过50米或开拓新巷道时，由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织测定煤层瓦斯压力、瓦斯含量及其他与突出危险性相关的参数，并汇报[[id:212bce41-e4cd-4644-a5f4-d688453274ff][防突工作领导小组]]。
*** 突出煤层的采掘作业应当遵守以下规定：
- 严禁采用水力采煤法、倒台阶采煤法或者其他非正规采煤法。
- 容易自燃的突出煤层在无突出危险区或者采取区域防突措施有效的区域进行放顶煤开采时，煤层瓦斯含量不得大于6m³/t。
- 采用上山掘进时，上山坡度在25°-45°的，应当制定包括加强支护、减小巷道空顶距等内容的专项措施，并经煤矿总工程师批准；当上山坡度大于45°时，应当采用双上山掘进方式，并加强支护，减少空顶距和空顶时间。
- 坡度大于25°的上山掘进工作面采用爆破作业时，应当采用深度不大于1.0米的炮眼远距离全断面一次爆破。
- 预测或者认定为突出危险区的采掘工作面严禁使用风镐作业。
- 掘进工作面与煤层巷道交叉贯通前，被贯通的煤层巷道必须超过贯通位置，其超前距不得小于5米，并且贯通点周围10米内的巷道应加强支护。
在掘进工作面与被贯通巷道距离小于50米的作业期间、被贯通巷道内不得安排作业，保持正常通风，并且在掘进工作面爆破时不得有人；在贯通相距50米以前实施钻孔一次打透，只允许向一个方向掘进。
- 在突出煤层的煤巷中安装、更换、维修或者回收支架时，必须采取预防煤体冒落引起突出的措施。
- 突出矿井的所有采掘工作面使用安全等级不低于三级的煤矿许用含水炸药。
*** 在突出煤层顶、底板及邻近煤层中掘进巷道（包括钻场等）时，必须超前探测煤层及地质构造情况，分析勘测验证地质资料，编制巷道剖面图，及时掌握施工动态和围岩变化情况，防止煤层的最小法向距离小于10米时（在地质构造破坏带20米时），必须先探后掘。
在距突出煤层突出危险区法向距离小于5米的邻近煤、岩层内进行采掘作业前，必须对突出煤层相应区域采取区域防突措施并经区域效果检验有效。
*** 在同一突出煤层正在采掘的工作面应力集中范围内，不得安排其他工作面同时进行回采或者掘进。应力集中范围由煤矿[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]确定，但2个采煤工作面之间的距离不得小于150米；采煤工作面与掘进工作面的距离不得小于80米；2个同向掘进工作面之间的距离不得小于50米；2个相向掘进工作面之间的距离不得小于60米。
突出煤层的掘进工作面应当避开邻近煤层采煤工作面的应力集中范围，与可能造成应力集中的邻近煤层相向掘进工作面的间距不得小于60米，相向采煤工作面的间距不得小于100米。
*** 井下和井口房内不得进行电焊、气焊和喷灯焊接等作业。如果必须在井下主要硐室、主要进风井巷和井口房内进行电焊、气焊和喷灯焊接等工作，每次必须制定安全措施，由矿长批准并遵守下列规定：
- 指定专人在场检查和监督。
- 电焊、气焊和喷灯焊接等工作地点的前后两端各10m的井巷范围内，应当是不燃性材料支护，并有供水管路，有专人负责喷水，焊接前应当清理或者隔离焊碴飞溅区域内的可燃物,且工作地点应当至少备有2个灭火器。
- 在井口房、井筒和倾斜巷道内进行电焊、气焊和喷灯焊接等工作时，必须在工作地点的下方用不燃性材料设施接受火星。
- 电焊、气焊和喷灯焊接等工作地点的风流中，甲烷浓度不得超过0.5%，只有在检查证明作业地点附近20m范围内巷道顶部和支护背板后无瓦斯积存时，方可进行作业。
- 电焊、气焊和喷灯焊接等作业完毕后，作业地点应当再次用水喷洒，并有专人在作业地点检查1h，发现异常，立即处理。
- 突出矿井井下进行电焊、气焊和喷灯焊接时，必须停止突出煤层的掘进、回采、钻孔、支护以及其他所有扰动突出煤层的作业。
煤层中未采用砌碹或者喷浆封闭的主要硐室和主要进风大巷中，不得进行电焊、气焊和喷灯焊接等工作。
** 通风系统管理
*** 突出矿井的通风系统应当符合下列要求：
- 井巷揭穿突出煤层前，具有独立、可靠的通风系统。
- 突出矿井、有突出煤层的巷道、突出煤层工作面都有独立的专用回风系统。
- 开采有瓦斯喷出、有突出危险的煤层，或者在距离突出煤层最小法向距离小于10米的区域掘进施工时，严禁2个采掘工作面之间串联通风。
- 突出煤层双巷掘进工作面不得同时作业，其他突出煤层区域预测为危险区域的采掘工作面，其进入专用回风石门前回风严禁切断其他采掘作业地点唯一安全出口。
- 突出矿井采煤工作面的进、回风巷内，以及煤巷、半煤岩巷和有瓦斯涌出的岩巷掘进工作面回风流中，回风巷及总回风巷，应当安设全量程或者高低浓度甲烷传感器；突出矿井采煤工作面的进风巷内甲烷传感器应当安设在距工作面10米以内的位置。
- 开采突出煤层时，工作面回风侧不得设置调节风量的设施。
- 严禁在井下安设辅助通风机。
- 突出煤层采用局部通风机通风时，必须采用压入式。
** 防突管理及培训
*** 矿在编制年度、季度、月度生产建设计划时，必须同时编制年度、季度、月度防突措施计划，保证抽、掘、采平衡。防突措施计划应包括保护层开采、区域预抽、区域效果检验、区域验证、工作面预测、工作面防突措施等。
*** 各项防突措施按照下列要求贯彻实施：
- 施工前，施工防突措施的队组在施工前，负责向本队职工贯彻并严格组织实施防突措施。
- 采掘作业时，严格执行防突措施的规定并有详细准确的记录。由于地质条件或者其他原因不能执行所规定的防突措施的，施工队组必须立即停止作业并汇报矿调度，经[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织相关人员到现场调查后，由原措施编制队组提出修改或补充措施，并按原措施的审批程序重新审批后方可继续施工；其他部门或者个人严禁改变已批准的防突措施。
- 煤矿企业的主要负责人、技术负责人应当每季度至少1次到现场检查各项防突措施的落实情况。矿长和总工程师应当每月至少1次到现场检查各项防突措施的落实情况；
- 煤矿企业、煤矿的防突机构应当随时检查综合防突措施的实施情况，并及时将检查结果分别向煤矿企业主要负责人和技术负责人、矿长和总工程师汇报，有关负责人应当对发现的问题立即组织解决；
- 煤矿企业、煤矿进行安全检查时，必须检查综合防突措施的编制、审批和贯彻执行情况。
*** 防突技术资料管理工作必须符合下列要求：
- 每次发生突出后，煤矿企业指定专人进行现场调查， 认真填写突出记录卡片，提交专题调查报告，分析突出发生的原因，总结经验教训，制定对策措施；
- 每年第一季度将上年度发生煤与瓦斯突出矿井的[[id:23c21054-a9ec-4d97-b247-7169820aafd8][基本情况调查表]]（见附录 B）、[[id:b0f7841a-3003-4264-bce3-a434cbc23daf][煤与瓦斯突出记录卡片]]（见附录 C）、矿井[[id:be04a934-317b-48d8-828e-9a3201fe9289][煤与瓦斯突出汇总表]]（见附录 D）连同总结资料报省级煤炭行业管理部门；
- 所有有关防突工作的资料均存档；
- 煤矿企业每年对全年的防突技术资料进行系统分析总结，掌握突出规律，完善防突措施。
*** 生产现场管理必须符合下列要求：
- 实施防突措施前，工作面附近10米范围内应加强支护，同时，工作面附近20米范围内不得有煤、矸石等杂物，确保后路畅通。
- 队组必须在允许进尺的范围内组织生产，严禁超采（掘）。
- 安全员、瓦检员必须对防突措施实施情况进行监督，并将监督情况向矿调度汇报。
- 突出煤层采掘过程中，发现响煤炮、煤壁外移、瓦斯涌出量忽大忽小、钻孔喷孔、顶钻等突出预兆时，必须立即停止作业、切断电源、撤出人员、设置栅栏，同时向矿调度汇报。只有待矿防突工作领导小组确认无异常，且采取有效措施后方可恢复作业。
*** 发生突出至恢复生产前的相关要求：
- 发生突出后，在后续的事故调查过程中，地测、通风科、专业防突队伍要进行现场调查，收集资料，作好详细记录，并由专业防突队伍填写突出卡片。
- 清理突出的煤炭时，总工程师必须组织制定防煤尘、防片帮、防冒顶、防瓦斯超限、防火源的安全技术措施，并上级部门备案。
突出孔洞应当及时充填、封闭严实或者进行支护，恢复采掘作业前，在其附近30米范围内必须加强支护。
*** 矿每年必须编制突出事故应急预案。应急预案与实际情况不相符时，应及时修改，并贯彻到职工中去。
*** 矿管理人员和井下工作人员必须接受防突知识的培训，经考试合格后方准上岗作业。各类人员的培训应达到下列要求：
- 井下工作人员的培训包括防突基本知识和规章制度等内容。
- 队长、班组长和相关的工作人员的培训包括突出的危害及发生的规律、区域和局部综合防突措施、防突的规章制度等内容。
- 防突员、安全员、瓦检员，属于特种作业人员，必须持有效证件上岗，且每年必须接受一次煤矿三级及以上安全培训机构组织的防突知识、操作技能的专项培训。专项培训包括防突的理论知识、突出发生的规律、区域和局部综合防突措施以及相关防突的规章制度等内容。
- [[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]、[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]应当接受煤矿二级及以上安全培训机构组织的防突专项培训。专项培训包括防突的理论知识和实践知识、突出发生的规律、区域和局部综合防突措施以及防突的规章制度等内容。
* 区域综合防突措施
** 区域综合防突工作程序和要求
*** 突出矿井应当主要依据煤层瓦斯的井下实测资料，并结合地质勘查资料、上水平及邻近区域的实测和生产资料等对开采的突出煤层进行区域突出危险性预测（以下简称区域预测）。经区域预测后，突出煤层划分为无突出危险区和突出危险区， 用于指导采煤工作面设计和采掘生产作业。未进行区域预测的区域视为突出危险区。
*** 突出煤层区域预测的范围根据突出矿井的开拓方式、巷道布置、地质构造分布、测试点布置等情况划定。
*** 对已确切掌握煤层突出危险区域的分布规律， 并有可靠的煤层赋存条件、地质构造、瓦斯参数等预测资料的， 区域预测工作由总工程师组织实施；否则，应当委托有煤与瓦斯突出鉴定资质的机构进行区域预测。
*** 经区域预测为突出危险区的煤层，必须采取区域防突措施并进行区域防突措施效果检验。经效果检验仍为突出危险区的，必须继续进行或者补充实施区域防突措施。
经区域预测或者区域防突措施效果检验为无突出危险区的煤层进行揭煤和采掘作业时，必须采用工作面预测方法进行区域验证。
所有区域防突措施的设计均由矿[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]批准。
当区域预测或者区域防突措施效果检验结果认定为无突出危险区时，如果采掘过程中发现所依据的条件发生明显变化的，煤矿[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]应当及时组织分析其对区域煤层突出危险性可能产生的影响，采取相应的对策和措施。
以下区域在实施区域验证、局部综合防突措施或者采掘作业中，发现有喷孔、顶钻等明显突出预兆或者发生突出的，必须采取或者继续执行区域防突措施。
- 在原有区域预测划分的无突出危险区内发生明显突出预兆或者突出的位置以上20m（埋深）及以下的范围；
- 在实施预抽煤层瓦斯区域防突措施的区域发生明显突出预兆或者突出的位置半径100m范围内。
*** 矿井首次开采某个保护层或者保护层与被保护层的层间距、岩性及保护层开采厚度等发生了较大变化时，应当对被保护层的保护效果及其有效保护范围进行实际考察。经保护效果考察有效的范围为无突出危险区。若经实际考察被保护层的最大膨胀变形量大于3‰，则检验和考察结果可适用于具有同一保护层和被保护层关系的其他区域。
有下列情况之一的，必须对每个被保护工作面的保护效果进行检验：
- 未实际考察保护效果和保护范围的；
- 最大膨胀变形量未超过3‰的；
- 保护层的开采厚度小于等于0.5m的；
- 上保护层与被保护突出煤层间距大于50m或者下保护层与被保护突出煤层间距大于80m的。
保护效果和保护范围考察结果由矿总工程师批准。
*** 突出危险区的煤层不具备开采保护层条件的，必须采用预抽煤层瓦斯区域防突措施并进行区域防突措施效果检验。
预抽煤层瓦斯区域防突措施效果检验结果应当经矿总工程师批准。
** 区域突出危险性预测
*** 区域预测一般根据煤层瓦斯参数结合瓦斯地质分析的方法进行，也可以采用其他经试验证实有效的方法。
根据煤层瓦斯压力或者瓦斯含量进行区域预测的临界值，须由具有突出危险性鉴定资质的队组进行试验考察。在试验前和应用前须经上级部门批准。
区域预测新方法的研究试验由总工程师组织编制，报上级部门批准后，由具有突出危险性鉴定资质的队组进行。
*** 根据煤层瓦斯参数结合瓦斯地质分析的区域预测方法必须遵照《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第五十七条、第五十八条的相关要求进行。
** 区域防突措施
*** 区域防突措施是指在突出煤层进行采掘前，对突出危险区煤层较大范围采取的防突措施。区域防突措施包括开采保护层和预抽煤层瓦斯2类。
开采保护层分为上保护层和下保护层两种方式。开采保护层必须遵守《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第六十条、第六十一条、第六十二条的相关规定和要求。
*** 在没有保护层可开采或未保护区域掘进时，必须采用顶、底板巷穿层预抽煤层瓦斯的区域防突措施。
*** 石门（斜巷）揭煤区域防突措施必须符合下列要求：
- 穿层钻孔预抽石门（含斜巷等）揭煤区域煤层瓦斯区域防突措施必须在揭煤工作面距煤层的最小法向距离7米以前实施（在构造破坏带不得小于10米）。钻孔的最小控制范围是：石门、立井和斜井揭煤处巷道轮廓线外左右各20米，上下（倾向方向）各15米范围，同时还应保证控制范围的外边缘到巷道轮廓线（包括预计前方揭煤段巷道的轮廓线）的最小距离不小于5米，且当钻孔不能一次穿透煤层全厚时，应保持煤孔最小超前距15米。
- 钻孔应均匀布置，钻孔直径为75-120毫米，孔底间距可根据实测的有效抽采半径确定。未实测前，钻孔孔底间距不得大于5米。
- 穿层钻孔、顺层钻孔等预抽钻孔采取“全程套管、两堵一注、带压封孔”封孔工艺，提高封孔质量，确保封堵严密。
- 钻孔的孔口抽采负压不小于13KPa，并保持压力稳定，确保抽采达标和实现消突。
- 所有钻孔投入抽采后，施工效果检验孔对预抽区域煤层瓦斯压力或瓦斯含量进行测定，预抽区域煤层瓦斯压力降到0.74MPa以下或瓦斯含量降到8m³/t以下，通过区域效果检验确认消突后，方可揭煤。
- 石门揭煤工作面在巷道顶板（底板）距离煤层底板（顶板）法线距离5m至巷道底板（顶板）距离煤层顶板（底板）法线距离2m段，严格执行“一炮一验证”，验证结果为无突出危险，方可采取远距离放炮揭煤。
*** 煤巷掘进工作面预抽煤层瓦斯区域防突措施必须符合下列要求：
- 采用顺层钻孔预抽煤巷条带煤层瓦斯作为区域防突措施的，必须满足：
-- 《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》第二百一十条规定的限制条件；
-- 钻孔控制煤巷条带前方有效长度不小于120m；
-- 每次区域措施效果检验有效长度不少于60m，掘进工作面前方保留检验有效长度不少于20m。
- 采用底（顶）板专用瓦斯巷穿层钻孔预抽煤巷条带煤层瓦斯作为区域防突措施的，必须遵循：
①专用瓦斯巷应布置在赋存稳定且有标志层控制的底（顶）板岩层中；
②近距离煤层群或厚度大于0.3m煤层、煤线分布较多的层位，不宜布置专用瓦斯巷，则应在煤层群的底（顶）部选择合适层位布置；
③专用瓦斯巷距煤层的垂直间距应不小于10m（遇地质构造带时，应不小于20m）；
④专用瓦斯巷施工时，采取防止误揭误穿突出煤层的安全技术措施；
⑤采用顶、底板穿层钻孔预抽煤层瓦斯的区域防突措施，其预抽时间不得低于3个月，且预抽范围超前掘进工作面150米以上，确保抽采达标和实现消突；
- 采用岩层定向钻孔预抽煤巷条带作为区域防突措施的，必须满足：
①钻孔开孔位置应选在稳定岩层中，且距煤层的垂直间距应不小于7m；
②钻孔控制预抽瓦斯煤层的有效长度应不小于300m；
③主孔开分支钻孔预抽煤层瓦斯时，分支钻孔进入煤层后的延伸长度应不小于10m；
- 钻孔控制范围：控制掘进巷道及其两侧各15米以上范围内的煤层，其中倾斜、急倾斜煤层巷道上帮轮廓线外至少20米，下帮至少15米。上述钻孔控制范围均为沿层面的距离（以下同）。
*** 采煤工作面预抽煤层瓦斯区域防突措施必须符合下列要求：
- 采用顺层钻孔预抽煤层瓦斯作为区域防突措施的，必须满足：
①在邻近回采巷道沿下一区段回采工作面方向布置预抽区段煤层瓦斯的钻孔，有效长度控制到该区段设计下一回采巷道外侧；
②在邻近巷道沿回采区段方向布置预抽区段煤层瓦斯的钻孔，有效长度控制到回采区段切眼外侧；
③鼓励配套措施：条件适合的煤矿，可采用区段内自下而上接替开采方式，保证钻孔仰孔施工的排水排渣效果；钻孔为俯孔时，可采用钻孔压风吹水排渣工艺，保证钻孔有效施工到设计范围；
④采用顺层钻孔预抽煤层瓦斯方法时，在工作面运输巷、回风巷向工作面施工平行（斜交）钻孔，钻孔应控制区段内的整个开采块段、两侧回采巷道及其外侧一定范围内的煤层。钻孔控制回采巷道外侧的范围是：倾斜、急倾斜煤层巷道上帮轮廓线外至少20米，下帮至少10米；其他为巷道两侧轮廓线外至少各15米。
- 采用顶（底）板穿层网格钻孔预抽煤层瓦斯方法时，钻孔应控制区段内的整个开采块段、两侧回采巷道及其外侧一定范围内的煤层。钻孔控制回采巷道外侧的范围是：倾斜、急倾斜煤层巷道上帮轮廓线外至少20米，下帮至少10米；其他为巷道两侧轮廓线外至少各15米；
- 控制范围内钻孔不得出现“盲区”，孔间距及孔深应根据预抽时间、预抽半径、煤层透气性及采煤工作面斜长等参数确定；
- 厚煤层分层开采时，预抽钻孔应控制开采的分层及其上部至少20米、下部至少10米（均为法向距离，且仅限于煤层部分）；
- 预抽钻孔超前采煤工作面不得小于300米，且确保抽采达标和实现消突。
- 采用岩层定向钻孔预抽煤巷条带或煤层瓦斯作为区域防突措施的，必须满足：
①钻孔开孔位置应选在稳定岩层中，且距煤层的垂直间距应不小于7m；
②钻孔控制预抽瓦斯煤层的有效长度应不小于300m；
③主孔开分支钻孔预抽煤层瓦斯时，分支钻孔进入煤层后的延伸长度应不小于10m。
** 区域措施效果检验
*** 开采保护层的保护效果检验采用残余瓦斯压力、残余瓦斯含量、顶底板位移量及其他经试验（应符合《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第五十七条要求的程序）证实有效的指标和方法。
当采用残余瓦斯压力、残余瓦斯含量检验时，应当根据实测的最大残余瓦斯压力或者最大残余瓦斯含量按《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第五十八条第（三）项的方法对预计被保护区域的保护效果进行判断。若检验结果仍为突出危险区，保护效果为无效。
*** 对预抽煤层瓦斯区域防突措施进行效果检验时，必须符合下列要求：
- 检查预抽区域内钻孔的实际布置是否符合设计要求，不符合设计要求的，不予检验或视为不合格；
- 采用残余瓦斯压力或者残余瓦斯含量指标对穿层钻孔、顺层钻孔预抽煤巷条带煤层瓦斯区域防突措施进行检验时，必须依据实际的直接测定值进行检验，其临界值各矿应根据试验考察确定，在确定前可参照《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第五十八条规定的临界值。其他方式的预抽煤层瓦斯区域防突措施可采用直接测定值或根据预抽前的瓦斯含量及抽、排瓦斯量等参数间接计算的残余瓦斯含量值；
- 采用残余瓦斯压力、残余瓦斯含量或钻屑瓦斯解吸指标对穿层钻孔预抽石门（含斜巷等）揭煤区域煤层瓦斯区域防突措施检验时，必须依据实际的直接测定值进行检验，其临界值由矿根据试验考察确定，在确定前可参照《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第五十八条规定的临界值。
- 其他方式的预抽煤层瓦斯区域防突措施可采用直接测定值或根据预抽前的瓦斯含量及抽、排瓦斯量等参数间接计算的残余瓦斯含量值。
- 检验期间还应当观察、记录在煤层中进行钻孔等作业时发生的喷孔、顶钻及其他突出预兆等。
- 检验孔必须布置在预抽孔中间；
- 采用煤层残余瓦斯压力或残余瓦斯含量的直接测定值进行检验时，若任何一个检验测试点的指标测定值达到或超过了有突出危险的临界值而判定为预抽防突效果无效时，此检验测试点周围半径100米内的预抽区域均判定为预抽防突效果无效，即为突出危险区。
*** 采用直接测定煤层残余瓦斯压力或残余瓦斯含量等参数进行预抽煤层瓦斯区域措施效果检验时，必须符合下列要求：
- 对穿层钻孔或顺层钻孔预抽区段煤层瓦斯区域防突措施进行检验时，若区段宽度（两侧回采巷道间距加回采巷道外侧控制范围）未超过120米，以及对预抽回采区域煤层瓦斯区域防突措施进行检验时若采煤工作面长度未超过120米，则沿采煤工作面推进方向每间隔30米至少布置1个检验测试点；若预抽区段煤层瓦斯区域防突措施的区段宽度或预抽回采区域煤层瓦斯区域防突措施的采煤工作面长度大于120米时，则在采煤工作面推进方向每间隔30米，至少沿工作面方向布置2个检验测试点。检验孔的孔数及位置应根据检验区域的预抽钻孔分布情况确定。
- 当预抽区段煤层瓦斯的钻孔在回采区域和煤巷条带的布置方式或参数不同时，按照预抽回采区域煤层瓦斯区域防突措施和穿层钻孔预抽煤巷条带煤层瓦斯区域防突措施的检验要求分别进行检验。
- 对穿层钻孔预抽煤巷条带煤层瓦斯区域防突措施进行检验时，在煤巷条带每间隔30米布置1个检验测试点。
- 对穿层钻孔预抽石门（含斜巷等）揭煤区域煤层瓦斯区域防突措施进行检验时，至少布置5个检验测试点，分别位于要求预抽区域内的上部、下部、中部和两侧，并且至少有1个检验测试点位于要求预抽区域内距边缘不大于2米的范围。
- 对顺层钻孔预抽煤巷条带煤层瓦斯区域防突措施进行检验时，在煤巷条带每间隔20米至少布置1个检验区域，且每个检验区域不得少于3个检验测试点。
- 各检验测试点应布置于所在部位钻孔密度较小、孔间距较大、预抽时间较短的位置，并尽可能远离测试点周围的各预抽钻孔或尽可能与周围预抽钻孔保持等距离，且避开采掘巷道的排放范围和工作面的预抽超前距。在地质构造复杂区域适当增加检验测试点。
*** 在施工所有区域措施效果检验孔过程中，若出现了喷孔、顶钻、夹钻等明显突出预兆，发生明显突出预兆的位置周围半径100米内的预抽区域措施判定为无效，所在区域仍为突出危险区，必须继续执行或补充区域防突措施。
** 区域验证
*** 区域预测为无突出危险区或者区域措施效果检验有效时，采掘过程中还应当对无突出危险区进行区域验证，并保留完整的工程设计、施工和验证的原始资料。
对井巷揭煤区域进行的区域验证，应当采用本细则第八十七条所列的井巷揭煤工作面突出危险性预测方法进行。
在煤巷掘进工作面和采煤工作面应当分别采用本细则第八十九条、第九十三条所列的工作面预测方法结合工作面瓦斯涌出动态变化等对无突出危险区进行区域验证，并按照下列要求进行：
- 在工作面首次进入该区域时，立即连续进行至少 2 次区域验证；
- 工作面每推进10～50m（在地质构造复杂区域或者采取非定向钻机施工的预抽煤层瓦斯区域防突措施的每推进30m） 至少进行2次区域验证，并保留完整的工程设计、施工和效果检验的原始资料；
- 在构造破坏带连续进行区域验证；
- 在煤巷掘进工作面还应当至少施工1个超前距不小于10m 的超前钻孔或者采取超前物探措施，探测地质构造和观察突出预兆。
*** 当区域验证为无突出危险时，应当采取安全防护措施后进行采掘作业。但若为采掘工作面在该区域进行的首次区域验证时，采掘前还应当保留足够的突出预测超前距。
只要有一次区域验证为有突出危险，则该区域以后的采掘作业前必须采取区域或者局部综合防突措施。
* 局部综合防突措施
** 局部综合防突措施基本程序和要求
*** 工作面突出危险性预测（以下简称工作面预测）是预测工作面煤体的突出危险性，包括井巷揭煤工作面、煤巷掘进工作面和采煤工作面的突出危险性预测等。工作面预测应当在工作面推进过程中进行，经工作面预测后划分为突出危险工作面和无突出危险工作面。
应当采取局部综合防突措施的采掘工作面未进行工作面预测的，视为突出危险工作面。
*** 当预测为突出危险工作面时，必须实施工作面防突措施和工作面防突措施效果检验。只有经效果检验证实措施有效后，即判定为无突出危险工作面，方可进行采掘作业；当措施无效时，仍为突出危险工作面，必须采取补充防突措施，并再次进行措施效果检验，直到措施有效。
无突出危险工作面必须在采取安全防护措施并保留足够的突出预测超前距或者防突措施超前距的条件下进行采掘作业。
煤巷掘进和采煤工作面应当保留的最小预测超前距均为2m。
工作面应当保留的最小防突措施超前距为：煤巷掘进工作面5m，采煤工作面3m；在地质构造破坏严重地带煤巷掘进工作面不小于7m，采煤工作面不小于5m。
每次工作面防突措施施工完成后，应当绘制工作面防突措施竣工图，并标注每次工作面预测、效果检验的数据。
*** 井巷揭开突出煤层前，必须掌握煤层层位、赋存参数、地质构造等情况。
在揭煤工作面掘进至距煤层最小法向距离10m之前，应当至少施工2个穿透煤层全厚且进入顶（底）板不小于0.5m的前探取芯钻孔，并详细记录岩芯资料，掌握煤层赋存条件、地质构造等。当需要测定瓦斯压力时，前探钻孔可用作测压钻孔；若二者不能共用时，则必须在最小法向距离7m前施工2个瓦斯压力测定钻孔，且应当布置在与该区域其他钻孔见煤点间距最大的位置。
在地质构造复杂、岩石破碎的区域，揭煤工作面掘进至距煤层最小法向距离20m之前必须布置一定数量的前探钻孔，也可用物探等手段探测煤层的层位、赋存形态和底（顶）板岩石致密性等情况。
*** 揭煤作业包括从距突出煤层底（顶）板的最小法向距离5m开始，直至揭穿煤层进入顶（底）板2m（最小法向距离）的全过程，应当采取局部综合防突措施。在距煤层底（顶）板最小法向距离5m至2m范围，掘进工作面应当采用远距离爆破。揭煤作业前应当编制井巷揭煤防突专项设计，并报煤矿企业技术负责人审批。
揭煤作业应当按照下列程序进行（井巷揭煤作业基本程序参考示意图参见附录F）：
- 探明揭煤工作面和煤层的相对位置；
- 在与煤层保持适当距离的位置进行工作面预测（或者区域验证）；
- 工作面预测（或者区域验证）有突出危险时，采取工作面防突措施；
- 实施工作面措施效果检验；
- 采用工作面预测方法进行揭煤验证；
- 采取安全防护措施并采用远距离爆破揭开或者穿过煤层。
*** 井巷揭煤工作面的突出危险性预测必须在距突出煤层最小法向距离 5 m 前进行，地质构造复杂、岩石破碎的区域应当适当加大法向距离。
经工作面预测或者措施效果检验为无突出危险工作面时，应当采用物探或者钻探手段边探边掘至距突出煤层法向距离不小于2m处，然后采用井巷揭煤工作面预测的方法进行揭煤验证。若经揭煤验证仍为无突出危险工作面时，方可揭开突出煤层。
当工作面预测、措施效果检验或者揭煤前验证为突出危险工作面时，必须采取或者补充工作面防突措施，直到经措施效果检验和验证为无突出危险工作面。
*** 井巷揭煤作业期间必须采取安全防护措施，加强煤层段及煤岩交接处的巷道支护。井巷揭煤工作面距煤层法向距离2m至进入顶（底）板2m的范围，均应当采用远距离爆破。
*** 揭煤巷道全部或者部分在煤层中掘进期间，还应当按照煤巷掘进工作面的要求连续进行工作面预测，并且根据煤层赋存状况分别在位于巷道轮廓线上方和下方的煤层中至少增加1个预测钻孔，当预测有突出危险时应当按照煤巷掘进工作面的要求实施局部综合防突措施。
*** 根据超前探测结果，当井巷揭穿厚度小于0.3m的突出煤层时，可在采取安全防护措施的条件下，直接采用远距离爆破方式揭穿煤层。
*** 突出煤层的每个煤巷掘进工作面和采煤工作面都应当编制工作面防突专项设计，报矿技术负责人批准。实施过程中当煤层赋存条件变化较大或巷道设计发生变化时，还应当作出补充或修改设计。
*** 在实施局部综合防突措施的煤巷掘进工作面和回采工作面，若预测指标为无突出危险，则只有当上一循环的预测指标也是无突出危险时，方可确定为无突出危险工作面，并在采取安全防护措施、保留足够的预测超前距的条件下进行采掘作业；否则，仍要执行一次工作面防突措施和措施效果检验。
** 工作面突出危险性预测
*** 应针对各煤层发生突出的特点和条件试验确定工作面预测的敏感指标和临界值，并作为判定工作面突出危险性的主要依据。试验由具有突出危险性鉴定资质的队组进行，在试验前和应用前报上级部门批准。
*** 在采用主要敏感指标进行工作面预测的同时，可以根据实际条件测定一些辅助指标（如瓦斯含量、工作面瓦斯涌出量动态变化、声发射、电磁辐射、钻屑温度、煤体温度等），采用物探、钻探等手段探测前方地质构造，观察分析工作面揭露的地质构造、采掘作业及钻孔等发生的各种现象，实现工作面突出危险性的多元信息综合预测和判断。
工作面地质构造、采掘作业及钻孔等发生的各种现象主要有以下方面：
- 煤层的构造破坏带，包括断层、剧烈褶曲、火成岩侵入等。
- 煤层赋存条件急剧变化。
- 采掘应力叠加。
- 工作面出现喷孔、响煤炮、卡钻、夹钻、顶钻等动力现象。
- 工作面出现明显的突出预兆。
出现上述情况之一时，应判定为突出危险工作面，必须立即停止作业并由总工程师组织实施相关防突措施。
*** 石门揭煤工作面突出危险性预测
- 石门揭煤工作面的突出危险性预测应采用综合指标法或钻屑瓦斯解吸指标法或其他经试验证实有效的方法进行。
采用综合指标法预测石门揭煤工作面突出危险性时，其操作程序必须符合《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第九十一条的相关要求。
斜巷揭煤工作面的突出危险性预测按照石门揭煤工作面的各项要求和方法执行。
- 揭开煤层前按下列要求执行：
一是石门揭煤工作面掘至距煤层法向距离7米时，至少打3个钻孔测定煤层瓦斯压力。近距离煤层群应测定各煤层的综合瓦斯压力。
二是采用钻屑瓦斯解吸指标法预测石门揭煤工作面突出危险性，必须符合下列要求：
-- 在与煤层法向距离5米至2米段，每个进尺循环前，必须沿法向方向布置3个孔对工作面进行突出危险性预测，钻孔控制范围：巷道断面两侧轮廓线外2～4米。
-- 在与煤层法向距离2米时（如果岩石松软、破碎，还应适当增加法向距离），必须沿工作面最小法向距离方向布置3个孔和掘进工作面前方布置3个孔进行最后验证，钻孔控制范围：巷道断面两侧轮廓线外2～4米。
-- 预测过程中，在钻孔钻进到煤层时每钻进1米采集一次孔口排出的粒径1～3毫米的煤钻屑，测定其瓦斯解吸指标K1或△h2值，测定时，应考虑不同钻进工艺条件下的排渣速度。
-- 临界值指标应根据矿实测数据确定，尚未确定的，钻屑瓦斯解析指标值临界值暂按0.4mL/g•min1/2.其他指标临界值按《防突细则》表4的规定执行。
如果所有实测的指标值均小于临界值，并且未发现其他异常情况（喷孔、顶钻、夹钻等），则该工作面为无突出危险工作面；否则，为突出危险工作面。
- 揭开煤层后，直至进入煤层顶（底）板法向距离2米的突出危险性预测，按下列要求执行：
-- 钻孔数量不少于4个，分别位于巷道的前方和两侧，钻孔直径为42毫米，钻孔控制范围：巷道断面两侧轮廓线外2～4米。
-- 测试参数及判定指标按《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》表4的规定执行。
-- 只有工作面预测或措施效果检验无突出危险后，方可继续掘进，直至完成揭煤作业全过程。
*** 煤巷掘进工作面的突出危险性预测
煤巷掘进工作面的突出危险性预测可采用钻屑指标法、复合指标法、R值指标法、其他经试验证实有效的方法。
- 采用复合指标法、R值指标法时，必须严格执行《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第九十一条、第九十二条的相关要求。
- 采用钻屑瓦斯解析指标法预测煤巷掘进工作面突出危险性必须按下列要求进行：
-- 在煤巷掘进工作面施工3个（煤层厚度大于3米时，布置5个）孔径为42毫米，孔深8～10米的钻孔，测定钻屑瓦斯解吸指标和钻屑量。
-- 钻孔应布置在软分层中，一个钻孔位于掘进巷道断面中部，并平行于掘进方向，其他钻孔的终孔点应位于巷道断面两侧轮廓线外2～4米处，煤层厚度大于3米时，增补的2个钻孔应控制巷道前方的底（或顶）部。
-- 预测过程中，钻孔每钻进1米测定该1米段的全部钻屑量S，每钻进2米至少测定一次钻屑瓦斯解吸指标K1或△h2值。
-- 钻屑瓦斯解析指标临界值应根据试验考察确定，尚未确定前，钻屑瓦斯解析指标临界值按0.4mL/g•min1/2管理，其他临界值可参照《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》表5规定执行。
如果实测得到的所有测定值均小于临界值，并且未发现其他异常情况（喷孔、顶钻、夹钻等），则该工作面预测为无突出危险工作面；否则，为突出危险工作面。
*** 采煤工作面突出危险性预测
采煤工作面的突出危险性预测，按照本制度七十五、所列的煤巷掘进工作面预测方法进行。除沿采煤工作面每隔10～15米布置一个预测钻孔，深度5～10米外，其他各项操作均与煤巷掘进工作面突出危险性预测相同。
判定采煤工作面突出危险性的各指标临界值应根据试验考察确定，在确定前可参照本《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》煤巷掘进工作面突出危险性预测的临界值。
** 工作面防突措施
*** 工作面防突措施是针对经工作面预测尚有突出危险的局部煤层实施的防突措施。其有效作用范围仅限于当前工作面周围的较小区域。
*** 石门、斜巷工作面揭穿突出煤层的局部防突措施：
- 石门、斜巷工作面揭穿突出煤层必须由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织编制专项防突设计，并报上级部门审批。专项防突设计必须包括下列主要内容：
-- 石门和斜巷揭煤区域煤层、瓦斯、地质构造及巷道布置的基本情况。
-- 建立安全可靠的独立通风系统及加强通风设施管理的措施；
-- 控制突出煤层层位、准确确定安全岩柱厚度的措施，测定煤层瓦斯压力的钻孔工程布置及实施方案。
-- 揭煤工作面突出危险性预测及防突措施效果检验的方法、指标，预测及检验钻孔布置等。
-- 工作面防突措施。
-- 安全防护措施及组织管理措施。
-- 加强过煤层段巷道的支护及其他措施等。
- 石门揭煤工作面的防突措施包括预抽瓦斯、排放钻孔、水力冲孔、金属骨架、煤体固化或其他经试验证明有效的措施。
-- 金属骨架、煤体固化措施，需在采用了其他防突措施并检验有效后方可在揭开煤层前实施。斜井揭煤工作面的防突措施可参考石门揭煤工作面防突措施进行。
-- 对所实施的防突措施都必须进行实际考察，得出符合矿实际条件的相关参数。
-- 根据工作面岩层情况，实施工作面防突措施时要求揭煤工作面与突出煤层间的最小法向距离为：预抽瓦斯、排放钻孔及水力冲孔均为5米，金属骨架、煤体固化措施为2米。当井巷断面较大、岩石破碎程度较高时，还应适当加大法向距离。
- 在地质构造破坏带应尽量不布置石门。如果条件许可，石门应优先布置在被保护区域或先掘出石门揭煤地点的煤层巷道，然后再用石门贯通。石门与突出煤层中已掘出的巷道贯通时，该巷道应超过石门贯通位置5米，并保持正常通风。
- 石门揭煤工作面掘至距突出煤层法向距离10米，施工2个穿透煤层全厚进入顶（底）板不少于0.5米的地质钻孔,如遇地质构造复杂,岩石破碎的区域,石门工作面掘至距煤层法向距离20米之前,必须在石门巷道轮廓线外5米范围的煤层内布置一定数量的钻孔并以探明煤层赋存、瓦斯状况等。地质钻孔的钻孔资料必须准确反映出煤层厚度、煤层层间距离、顶底板岩性及地质构造特征等。
- 石门和斜巷揭煤工作面采用预抽煤层瓦斯区域防突措施后，若预测仍有突出危险，采用预抽瓦斯、排放钻孔等局部防突措施时，必须符合下列要求：
-- 钻孔直径为75～120毫米。
-- 钻孔的控制范围：石门的两侧和上部（或下部）轮廓线外至少15米，下部（或上部）至少10米。立井揭煤工作面钻孔控制范围是：近水平、缓倾斜、倾斜煤层为井筒四周轮廓线外至少8米；急倾斜煤层沿走向两侧及沿倾斜上部轮廓线外至少10米，下部轮廓线外至少8米。钻孔的孔底间距应根据实际考察情况确定，未实测前不得大于2米。
-- 揭煤工作面施工的钻孔应穿透煤层全厚。当不能一次打穿煤层全厚时，可分段施工，但第一次实施的钻孔穿煤长度不得小于15米，且进入煤层掘进时，必须留有5米的超前距离（掘进到煤层顶或底板时不在此限）。
-- 修改抽（排）放钻孔设计必须报矿总工程师审批。
- 石门和斜巷揭煤工作面采用预抽煤层瓦斯区域防突措施后，若预测仍有突出危险，采用水力冲孔、金属骨架、煤体固化等局部防突措施时，必须符合《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第九十八条、第九十九条、第一百条的相关要求。
*** 煤巷掘进工作面防突措施：
- 煤巷掘进工作面施工前必须由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织编制专项防突设计，并报上级上级部门备案，专项防突设计必须包括以下主要内容：
-- 煤层、瓦斯、地质构造、煤层埋深及邻近区域巷道布置的基本情况。
-- 建立安全可靠的独立通风系统及加强通风设施管理的措施。
-- 工作面突出危险性预测及防突措施效果检验的方法、指标以及预测、效果检验钻孔布置等。
-- 防突措施的选取及施工设计。
-- 安全防护措施。
-- 组织管理措施等。
各煤层采用的煤巷掘进工作面各种局部防突措施的效果和参数等都要经实际考察确定。
- 有突出危险的煤巷掘进工作面应优先选用超前钻孔（包括超前预抽瓦斯钻孔、超前排放钻孔）防突措施。如果采用松动爆破、水力冲孔、水力疏松或其他工作面防突措施时，必须经试验考察确认防突效果有效后方可使用。前探支架措施须配合其他措施一起使用。下山掘进时，不得选用水力冲孔、水力疏松等措施。倾角8度以上的上山掘进工作面不得选用松动爆破、水力冲孔、水力疏松等措施。
- 煤巷掘进工作面在地质构造破坏带或煤层赋存条件急剧变化处不能按原措施设计要求实施时，必须首先打钻孔探明煤层赋存条件，然后采用直径为42～75毫米的钻孔抽（排）放瓦斯。若突出煤层煤巷掘进工作面前方遇到落差超过煤层厚度的断层，应按石门揭煤的相关措施执行。
- 煤巷掘进工作面采用超前钻孔作为工作面防突措施时，应当符合下列要求：
-- 巷道两侧轮廓线外钻孔的最小控制范围：近水平、缓倾斜煤层5米，倾斜、急倾斜煤层上帮7米、下帮3米。当煤层厚度大于巷道高度时，在垂直煤层方向上的巷道上部煤层控制范围不小于7米，巷道下部煤层控制范围不小于3米。
-- 超前钻孔在工作面前方必须保证20米以上的超前距离。
-- 钻孔在控制范围内应均匀布置，在煤层的软分层中可适当增加钻孔数。预抽钻孔或超前排放钻孔的孔数、孔底间距等应当根据实测的有效抽采或排放半径确定，未实测前不得超过1米。
-- 钻孔直径应当根据煤层赋存条件、地质构造和瓦斯情况确定，一般为75～120毫米，地质条件变化剧烈地带采用直径42～75毫米的钻孔。若钻孔直径超过120毫米时，必须制定专门的钻进设备和制定专门的施工安全措施。
-- 煤层赋存状态发生变化时，必须重新确定超前钻孔的参数。
-- 钻孔施工前，加强工作面及其附近10米范围内的支护，打好迎面支架（防护拦），背好工作面煤壁。
-- 超前钻孔施工过程中，施工人员必须将孔深及施工过程中出现的喷孔、顶钻、夹钻等异常情况作好详细记录，并汇报矿[[id:212bce41-e4cd-4644-a5f4-d688453274ff][防突工作领导小组]]。
-- 防突专业队伍应针对钻孔施工实际情况，对“盲区”部位必须采取补救措施，保证工作面前方煤体不留抽采或排放“孤岛”，做到均匀卸压。
-- 采用本煤层钻孔抽放方法时，抽放率必须大于30%，单孔抽放浓度必须降到15%以下，其中浓度在10%以下的孔数必须大于抽放钻孔总数的50%。
- 煤巷掘进工作面采用松动爆破、水力冲孔、水力疏松局部防突措施时，必须符合《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第一百零四条、第一百零五条、第一百零六条的相关要求。
- 在局部煤柱应力区未开展区域性预抽范围内掘进时，必须在巷道两帮作钻场采取本煤层长钻孔抽放，孔深大于40米，钻孔数量以控制范围内消除突出危险为原则。
*** 采煤工作面防突措施：
- 采煤工作面回采前必须由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织编制[[id:d758e93b-1879-4ac1-8dfb-c8c457eb9442][防突专项设计]]，并报上级部门备案。[[id:d758e93b-1879-4ac1-8dfb-c8c457eb9442][防突专项设计]]必须包括以下主要内容：
-- 煤层、瓦斯、地质构造、煤层埋深及邻近区域巷道布置的基本情况。
-- 建立安全可靠的独立通风系统及加强通风设施管理的措施。
-- 工作面突出危险性预测及防突措施效果检验的方法、指标以及预测、效果检验钻孔布置等。
-- 防突措施的选取及施工设计。
-- 安全防护措施。
-- 组织管理措施。
各煤层采用的采煤工作面各种局部防突措施的效果和参数等都要经实际考察确定。
- 有突出危险的采煤工作面可采用超前排放钻孔、预抽瓦斯、松动爆破、注水湿润煤体或其他经试验证实有效的防突措施。
- 采煤工作面采用超前排放钻孔和预抽瓦斯作为工作面防突措施时，必须符合下列要求：
-- 措施孔的直径为75-120毫米, 钻孔在控制范围内应均匀布置，在煤层的软分层中可适当增加钻孔数；钻孔的孔底间距应根据实际考察情况确定，未实测前不得大于5米。
-- 遇地质构造带，可选用直径为42毫米的钻孔。
-- 钻孔应优先采伪倾斜布置方式，以便回采时采取充水措施，将孔内瓦斯排除。
- 采用松动爆破防突措施时，必须符合《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第一百零五条的相关要求。
- 采用浅孔注水湿润煤体防突措施时，必须符合《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第一百一十一条的相关要求。
** 工作面措施效果检验
*** 工作面执行防突措施后，必须对防突措施效果进行检验。
在实施钻孔法防突措施效果检验时，分布在工作面各部位的检验钻孔应当布置于所在部位防突措施钻孔密度相对较小、孔间距相对较大的位置，并远离周围的各防突措施钻孔或尽可能与周围各防突措施钻孔保持等距离。在地质构造复杂地带应根据情况适当增加检验钻孔。
工作面防突措施效果检验必须包括以下两部分内容：
- 检查所实施的工作面防突措施是否达到了设计要求和满足有关的规章、标准等，并了解、收集工作面及实施措施的相关情况、突出预兆等(包括喷孔、卡钻等)，作为措施效果检验报告的内容之一，用于综合分析、判断;
- 各检验指标的测定情况及主要数据。
*** 对井巷揭煤工作面进行防突措施效果检验时，应当选择本规定第八十七条所列的钻屑瓦斯解吸指标法或其他经试验证实有效的方法，但所有用钻孔方式检验的方法中检验孔数均不得少于5个，分别位于石门的上部、中部、下部和两侧。
如检验结果的各项指标都在该煤层突出危险临界值以下，且未发现其他异常情况，则措施有效；反之，判定为措施无效。
*** 煤巷掘进工作面执行防突措施后，应当选择本规定第七十五条所列的方法进行措施效果检验。
检验孔应当不少于3个，深度应当小于或等于防突措施钻孔。
如果煤巷掘进工作面措施效果检验指标均小于指标临界值，且未发现其他异常情况，则措施有效；否则，判定为措施无效。
当检验结果措施有效时，若检验孔与防突措施钻孔向巷道掘进方向的投影长度（简称投影孔深）相等，则可在留足防突措施超前距（见本细则第七十六条）并采取安全防护措施的条件下掘进。当检验孔的投影孔深小于防突措施钻孔时，则应当在留足所需的防突措施超前距并同时保留有至少2m检验孔投影孔深超前距的条件下，采取安全防护措施后实施掘进作业。
*** 对采煤工作面防突措施效果的检验应当参照采煤工作面突出危险性预测的方法和指标实施。但应当沿采煤工作面每隔10～15m布置一个检验钻孔，深度应当小于或等于防突措施钻孔。
如果采煤工作面检验指标均小于指标临界值，且未发现其他异常情况，则措施有效；否则，判定为措施无效。
当检验结果措施有效时，若检验孔与防突措施钻孔深度相等，则可在留足防突措施超前距（见本细则第七十六条）并采取安全防护措施的条件下回采。当检验孔的深度小于防突措施钻孔时，则应当在留足所需的防突措施超前距并同时保留有2m检验孔超前距的条件下，采取安全防护措施后实施回采作业。
** 安全防护措施
*** 井巷揭穿突出煤层和在突出煤层中进行采掘作业时，必须采取避难硐室、反向风门、压风自救装置、隔离式自救器、远距离爆破等安全防护措施。
*** 突出矿井必须建设避难硐室，避难硐室必须接入矿井压风管路和供水管路，满足避险人员的避险需要，额定防护时间不低于96h。
突出煤层的掘进巷道长度及采煤工作面推进长度超过500m时，应当在距离工作面500m 范围内建设临时避难硐室或者其他临时避险设施。临时避难硐室必须设置向外开启的密闭门或者隔离门（隔离门按反向风门设置标准安设），接入矿井压风管路，并安设压风自救装置，设置与矿调度室直通的电话，配备足量的饮用水及自救器。
*** 在突出煤层的石门揭煤和煤巷掘进工作面进风侧，必须设置至少2道牢固可靠的反向风门。风门之间的距离不得小于4m。
工作面爆破作业或者无人时，反向风门必须关闭。
反向风门距工作面的距离和反向风门的组数，应当根据掘进工作面的通风系统和预计的突出强度确定，但反向风门距工作面回风巷不得小于10m，与工作面的最近距离一般不得小于70m，如小于70m时应设置至少三道反向风门。
反向风门墙垛可用砖、料石或混凝土砌筑，嵌入巷道周边岩石的深度可根据岩石的性质确定，但不得小于0.2m；墙垛厚度不得小于0.8m。在煤巷构筑反向风门时，风门墙体四周必须掏槽，掏槽深度见硬帮硬底后再进入实体煤不小于0.5m。通过反向风门墙垛的风筒、水沟、刮板输送机道等，必须设有逆向隔断装置。
*** 为降低放炮诱发突出的强度，可根据情况在炮掘工作面安设挡栏。挡栏可以用金属、矸石或木垛等构成。金属挡栏一般是由槽钢排列成的方格框架，框架中槽钢的间隔为0.4m，槽钢彼此用卡环固定，使用时在迎工作面的框架上再铺上金属网，然后用木支柱将框架撑成45°的斜面。一组挡拦通常由两架组成，间距为6～8m。可根据预计的突出强度在设计中确定挡栏距工作面的距离。
*** 井巷揭穿突出煤层和突出煤层的炮掘、炮采工作面必须采取远距离爆破安全防护措施。
井巷[[id:5bb905d8-6901-4658-b880-0d8749f44ce5][揭煤]]采用远距离爆破时，必须制定包括放炮地点、避灾路线及停电、撤人和警戒范围等的专项措施。
井巷[[id:5bb905d8-6901-4658-b880-0d8749f44ce5][揭煤]]起爆及撤人地点必须位于反向风门外且距工作面500m以上全风压通风的新鲜风流中，或者距工作面300m以外的避难硐室内。
在矿井尚未构成全风压通风的建井初期，在井巷揭穿有突出危险煤层的全部作业过程中，与此井巷有关的其他工作面必须停止工作。在实施揭穿突出煤层的远距离爆破时，井下全部人员必须撤至地面，井下必须全部断电，立井口附近地面20m范围内或斜井口前方50m、两侧20m范围内严禁有任何火源。
煤巷掘进工作面采用远距离爆破时，起爆地点必须设在进风侧反向风门之外的全风压通风的新鲜风流中或者避难硐室内，起爆地点距工作面爆破地点的距离应当在措施中明确，由煤矿总工程师根据曾经发生的最大突出强度等具体情况确定，但不得小于300m；采煤工作面起爆地点到工作面的距离由煤矿总工程师根据具体情况确定，但不得小于 100m，且位于工作面外的进风侧。
远距离爆破时，回风系统必须停电撤人。爆破后，进入工作面检查的时间应当在措施中明确规定，但不得小于30min。
*** 突出煤层采掘工作面附近、爆破撤离人员集中地点、起爆地点必须设有直通矿调度室的电话，并设置有供给压缩空气的避险设施或者压风自救装置。工作面回风系统中有人作业的地点，也应当设置压风自救装置。
压风自救系统应当达到下列要求：
- 压风自救装置安装在掘进工作面巷道和回采工作面巷道内的压缩空气管道上；
- 在以下每个地点都应至少设置一组压风自救装置：距采掘工作面25～40m的巷道内、放炮地点、撤离人员与警戒人员所在的位置以及回风道有人作业处等。在长距离的掘进巷道中，应根据实际情况增加设置；
- 每组压风自救装置应可供5～8个人使用，平均每人的压缩空气供给量不得少于0.1m³/min。
* 防突工作程序
** 地质预报。
由技术科根据已有地质资料和钻孔探测资料等进行分析，依据矿作业计划对每个采、掘工作面每月提供相应的平面和剖面图，标明地质构造位置，以便确定防突重点。
** 地质确认。
严格执行“[[id:059d2d99-239d-4fb0-acb9-5ac4d77b18e0][先探后掘]]”制度，通过对探测钻孔的资料分析，然后再与地质预报进行对比分析，确认掘进巷道前方地质构造、煤层赋存、瓦斯、水等情况，确定防突管理的重点位置和需要采取的措施。
** 消突措施。
根据已探明的瓦斯、地质情况，由通风科按照本制度的相关规定制定切实可行的消突措施，确保掘进区域的消突工作符合要求并达到消突目的。
** 现场管理。
严格落实已制定的消突措施，每班安排工程技术人员及以上的管理人员现场跟班，确保钻孔施工和消突措施落实到位。
** 消突评价。
对已实施的消突措施进行评价。由通风科根据《[[id:4ba3bd5b-c5db-4098-b96d-b1fcf13f60be][矿瓦斯抽采达标评价工作体系]]》提报消突评价报告，再由矿长或总工程师组织防突工作领导小组相关人员进行会审，进一步确认消突是否达到目的，[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]、[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]、[[id:21350f90-65e1-46b4-8bb9-c24d0aae7787][安全副矿长]]长必须签字。
** 下达允许进尺（或回采）通知书。
经消突评价确认达到消突目的后，及时下达允许进尺（或回采）通知书。
** 跟踪管理
采、掘工作面正常回采和掘进期间，严格执行本制度两个“[[id:6f5e8f2f-fc30-44d2-86ce-0c276bf1007c][四位一体]]”的综合防突措施，并跟踪现场情况是否出现其他异常，一旦出现瓦斯、煤层、构造、矿压等异常，立即停止作业，由矿重新分析并采取措施。
* 防突工作定期检查制度
** 检查时间。
[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]、[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]应每月至少一次到现场检查防突措施的落实情况，保证防突工作的投入，解决防突所需的人力、财力、物力，确保“抽、掘、采”平衡。
矿[[id:6fdd3569-f00f-44d8-8109-fe1292bf1235][防突队]]应当随时检查区域及局部综合防突措施的实施情况，并及时将检查结果向[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]、[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]汇报。相关负责人应对发现的问题立即组织解决。
矿进行安全检查时，必须检查综合防突措施的编制、审批和贯彻执行情况。
** 检查内容。
*** 通风系统及通风设施：是否具有专用回风系统、通风系统是否合理、进回风系统是否畅通、通风设施是否可靠、防逆转装置是否完善等；
*** 防突措施：区域及局部综合防突措施设计是否符合要求、现场与措施是否相符、措施是否可靠等；
*** 监测系统：瓦斯监测设备安装是否符合设计要求、监控是否有效等；
*** 安全防护：压风自救系统设计是否符合要求、压风自救装置是否与设计相符、压风自救装置是否完好、电器设备是否存在失爆、放炮管理是否符合要求等；
*** 其他检查项目等。
** 检查方式及资料整理。
采取全面检查或抽查、联合或分专业检查等方式对防突工作进行检查。
专业防突队伍应认真收集、分析、整理各种防突资料，并建立防突台帐，各种资料应存档备查。
* 防突例会制度
** 矿每月必须至少召开一次[[id:92847a1e-19bc-441c-99ba-742abf08f872][防突例会]]，并建立日常动态分析制度。
** 防突例会由[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]（或[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]）组织[[id:212bce41-e4cd-4644-a5f4-d688453274ff][防突工作领导小组]]、通风、生产、技术、地测、安全等科室参加，重点分析、总结防突工作现状、存在问题及下一步针对性的防突措施等。
** [[id:212bce41-e4cd-4644-a5f4-d688453274ff][防突工作领导小组]]应随时分析区域及局部综合防突措施是否合理、可靠及存在问题，及时采取有效措施，防范突出事故的发生。
