:PROPERTIES:
:ID:       da52c4cc-c04f-41a7-94fe-1bf3ae9702f7
:END:
#+title: “手指口述”管理制度
为切实推进“手指口述”安全确认工作法，确保现场每道工序、每个环节进行“手指口述”安全确认，进一步规范职工安全操作行为，促进隐患排查治理，提高安全保障能力，有效防范事故发生，根据上级部门相关要求，结合矿实际，制定本管理制度。
* 成立“手指口述”工作领导小组
组  长：矿  长
副组长：副矿长
成  员：副总工程师  各队组负责人
领导小组下设办公室在安全科，由安全科科长兼任办公室主任，负责日常工作。
* 职责划分
** 矿长、安全副矿长对矿“手指口述”工作全面负责。
** 分管矿领导对分管业务及分管队组“手指口述”工作具体负责，对分管业务及分管队组开展“手指口述”工作进行指导、检查和监督，安全副矿长对矿开展的“手指口述”工作负整体组织、协调、监督和考核的职责。
** 矿属各队组是开展“手指口述”工作的第一责任人，负责组织制定“手指口述”考核办法，并报矿审批后执行。
** 矿领导分管科室、队组对分管的业务及分管队组(车间)“手指口述”工作负责，对分管的业务及分管队组(车间)开展“手指口述”工作进行指导、检查和监督。
** 队长（主任）是本队（车间）开展“手指口述”工作的第一责任人，对本队（车间）开展“手指口述”工作进行指导、检查和监督。
** 班组长是本点班职工落实“手指口述”第一责任人，并带头开展好本点班的“手指口述”工作。
** 岗位作业人员是本岗位“手指口述”工作的实施者，必须准确掌握本岗位的“手指口述”操作标准，每道工序开工前和工序发生转换时必须进行“手指口述”安全确认。
* 开展“手指口述”的要求
** 每道工序开工前和工序发生转换时必须进行“手指口述”安全确认。
** 《“手指口述”操作标准》中规定的岗位人员必须严格按其标准执行。
** 各岗位人员或现场安全负责人执行“手指口述”时，必须根据现场涉及隐患的实际情况进行“手指口述”安全确认，做到不喊空话、不指东说西、不慌张、不死记硬背，确保“手指口述”工作真正落实到实处。
* 监督措施
** 矿领导、副总及业务科室管理人员必须把职工落实“手指口述”作为一项日常安全重点工作来抓，广泛宣传“手指口述”工作的目的和意义，对落实“手指口述”工作进行监督和指导。
** 安全员负责当班监管范围内职工“手指口述”监督工作，现场施工人员不做“手指口述”的，要及时汇报矿调度，并有权停止作业，不汇报罚款XX元/次。
** 安全员必须加强业务学习，熟悉掌握“手指口述”操作要领，在监管范围内监督职工做好“手指口述”安全确认工作，对执行“手指口述”不规范、不正确、走形式的要纠偏。
** 井下各点班开工前必须由当班安全负责人或跟班队长对岗位点进行隐患排查，隐患排除后进行“手指口述”安全确认，向矿调度汇报请示能否开工，矿调度根据汇报情况下达开工指令，矿调度做好记录，不汇报严禁开工，否则对当班安全负责人或跟班队长罚款XX元，矿调度记录不到位，罚款XX元/次，矿调度每班必须对当班队组汇报情况向当班安全员进行抽查核实，每个队组抽查不得少于3个队组，抽查时发现弄虚作假的，对汇报人罚款XX元/次，安全员包庇的罚款XX元/次。
** 安全科负责建立各队组执行“手指口述”信息管理台账，每月对全矿“手指口述”工作进行总结分析。
** 每月安全副矿长在矿作业计划会上通报各队组开展“手指口述”工作情况。
