:PROPERTIES:
:ID:       2989bf48-3503-4304-b0b3-988daa865a88
:END:
#+title: 隐蔽致灾地质因素普查制度
为了切实做好矿井隐蔽致灾地质因素普查工作确保矿长治久安，或减小隐蔽致灾地质因素对矿井安全生产的影响，按照《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》，结合《××矿隐蔽致灾地质因素普查报告》和《[[id:2ddc3ace-958e-4b8c-a405-229946a75093][煤矿地质工作规定]]》第四章具体规定，特制定本制度。
* 矿井隐蔽致灾地质因素普查领导小组
组  长：[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]
副组长：各副总工程师
成  员：生产技术科科长、通风科科长、安全科科长、防治水专业人员、测量专业人员、各采掘技术人员。
* 矿井隐蔽致灾地质因素普查领导小组职责、范围
组长：全面负责组织隐蔽致灾地质因素普工作的开展，保证隐蔽致灾因素普查工作开展过程中所需资金、设备、仪器仪表落实到位。
副组长：协助组长工作，负责组织制定整改方案、安全技术措施，重点负责隐蔽致灾地质因素跟踪、督促检查，负责自己专业内隐蔽致灾工作日常业务安排落实。
成员:在组长、副组长的领导下共同开展完成隐蔽致灾地质因素普查工作负责编制专业内的安全技术措施，和整改方案工作，采掘技术人员负责本队隐蔽致灾专业知识培训，专业技术人员负责督促、帮扶队组人员共同提高专业知识。
* 矿井隐蔽致灾地质因素普查范围
** 地表防洪灾害的排查
*** 地测组各专业技术人员对矿内及矿区、周边的地表径流、塌陷裂隙区渗水情况、暴雨过后地表塌陷裂隙区积水情况巡查进行详细的排查勘测并在矿相关图纸上及时准确绘制出具体的位置；
*** 相关部门对矿周围的防洪排水沟每月进行一次全面的排查工作，及时清理防洪沟，保证防洪沟内的清洁，发现有损坏的地方及时进行修复，保证防洪排水沟的完好；
*** 在雨季期间加强防洪沟的巡查工作，对井口较低位置采相应的防水措施，防止强降雨期间，积水涌入井筒内，发生事故。
** 隐蔽致灾因素排查内容
采用调查、走访、物探、化探和钻探等方法进行，查明矿井采空区及邻近采空区分布、形成时间、范围、积水情况、自然发火情况和有害气体等。将采空区相关信息标绘在采掘工程平面图和矿井充水性图上，并建立煤矿和周边采空区相关资料台账。
*** 废弃老窑（井筒）和封闭不良钻孔普查
- 收集井田范围内废弃老窑（井筒）闭坑时间、开采煤层、开采范围，是否开采煤柱和充填等情况。井田内及周边施工的所有钻孔都要标注在采掘工程平面图上，查明并分析每个钻孔的封孔质量。建立井田内废弃老窑（井筒）、水源井、封闭不良钻孔台账。对于钻孔资料不详、模糊的钻孔，必须以“封闭不良钻孔”对待。
- 每月了解相邻矿井的回采情况，调查清楚其废弃井巷及采空区是否积水、是否对矿有影响。
*** 断层、裂隙、褶曲、陷落柱、导水裂隙带等地质构造普查
断层、导水裂缝带等的普查，应采用物探、钻探实测和理论计算等方法确定矿井导水裂缝带高度，合理留设防隔水煤（岩）柱。如果煤层顶板受开采破坏，其导水裂缝带波及范围内存在富水性强的含水层（体）时，在掘进、回采前，应当对含水层（体）进行疏干。
断层、裂隙和褶曲的普查，应查明矿井边界断层和井田内落差大于5米的断层，查明矿井内主要褶曲形态，收集矿井裂隙发育资料、总结规律，编制煤矿地质构造纲要图。其中，断层普查主要包括断层性质、走向、倾角、断距，断层带宽度及岩性，断层两盘伴生裂隙发育程度，断层富水性等。
陷落柱的普查，应查明矿井范围内直径大于30米的陷落柱，主要包括陷落柱发育形态、岩性、周边裂隙发育程度、导水性等。
*** 瓦斯富集区普查
瓦斯富集区普查，应查明煤层厚度、变化规律、煤质和瓦斯含量及赋存状况，系统收集矿井所有的瓦斯资料和地质资料，编制瓦斯地质图，对矿井瓦斯赋存情况进行分区，开展瓦斯防突预测、预报工作。
*** 地下含水体普查
应查明影响矿井安全开采的水文地质条件，各种含水体的水源、水量、水位、水质和导水通道等，预测煤矿正常和最大涌水量，提出防排水措施、建议。
*** 井下火区普查
查明井下火区范围、密闭、气体成分等情况，提出防灭火措施及建议。对井下已采完的工作面的防火密闭进行监控、检测，并及时汇报出现的问题。
*** 古河床冲刷带、天窗等不良地质体普查
应查明井田范围内岩浆岩侵入体分布范围、古河床冲刷带、古隆起、天窗等，将查处的不良地质体标绘在采掘工程平面图上。
* 考核办法
对隐蔽致灾地质因素普查范围出现遗漏或误排查造成损失或者严重后果的追究其责任，并按矿相关制度核减责任人一定比例的薪酬或其他处分。
