:PROPERTIES:
:ID:       c985fa74-3521-4a98-b7f4-b76d1cf70f77
:END:
#+title: 通信设备维护工安全操作规程
* 上岗条件
维护工必须经过安全技术培训，并考试合格取得入井资格证后方可上岗。
* 安全规定
** 严格执行监测监控工岗位责任制，遵守本操作规程和《煤矿安全规程》及矿有关规定、制度。
** 电话通讯信号在入井前，必须经过安全耦合器，严禁直接入井。
** 在作业过程中需在皮带、溜槽上方作业时，须先与司机、调度联系好，待相应皮带、溜槽停稳后，方可进行作业。作业完毕后及时向调度和皮带司机汇报。
** 登高作业时，要有其他人员在下面扶稳梯子，上面作业人员要站稳，上下人员动作应协调一致。高空作业或在煤仓作业时要系安全保险带，同时用细绳系牢自身携带的工器具，以防坠落。
** 在有电机车、卡轨车等运输设备的巷道中悬挂电缆时应安排人员进行警戒，避免作业人员被运行车辆撞伤。
** 严禁带电作业。在设备开盖前必须切断相应设备非本安型电源。
** 维护人员在下井时要携带便携式瓦检仪。作业前先测量周围20米范围内的瓦斯浓度，只有在瓦斯浓度<1.0%CH4时，方可作业。在进入专用排瓦斯巷作业时，必须两人或多人前后相随，当瓦斯浓度超过1.5%CH4时，不得进入瓦排巷作业。
** 如实填写各种记录，妥善保管、存档，不得丢失。
* 作业准备
** 上岗前要按时参加班前会，了解情况，接受任务，熟记相关安全注意事项。并根据工作、任务情况准备好所需的设备、材料、仪表、工器具。
** 作业过程中需停电、拆接火时要提前办理有关停送电和拆接火手续。需要其他队组配合时，须提前一天联系好。
** 使用各种测试仪表前，要先根据被测对象的具体属性，正确选择仪表的各项挡位、设置。
* 作业程序
** 维护工日常巡检作业按以下顺序进行：
*** 按照机电质量标准化要求巡查通讯系统主干线路、分线箱、支路、接线盒、电话机、喊话器、电源箱、小灵通基站等设施。
*** 发现问题要及时处理，因工具、材料、配件、人员等条件不具备不能就地处理的问题，要即时汇报，并作相应的特殊处理。
*** 升井后，根据井下实际作业情况，认真填写《维护记录》和《故障处理记录》。对存在问题的责任人开出五定表；同时对问题严重的进行罚款处理。
** 维护工安装通讯设施作业按以下顺序进行：
*** 根据设备安装现场的实际情况准备相应的设备、电缆、材料，并在地面对通讯设备进行预先检测与调试。
*** 设备、电缆的装车、运输。
*** 根据通讯线路走线情况，事先在地面将通讯信号接续好。
*** 安装前，准备好所需工器具。
*** 选择合适的位置安装设备、敷设电缆。
*** 规范接线，符合质量标准化要求。
*** 安装后的完好检查。
*** 清理现场。
*** 根据实际作业情况，填写《设备安装台帐》。
* 正常操作
** 日常巡检作业
*** 线路巡检。主要包括查看大巷主干通讯电缆、分线箱和各矿井上下山、工作面顺槽巷道中的支路电缆和接线盒有无被拽拉、刮碰等情况发生，同时整理零乱的电缆，重新接续拽脱线的电缆连接头。
*** 设备巡检。检查电话机、扩音电话、小灵通基站功能是否齐备完好；整理接线箱等设备内部线路；紧固松动的螺栓、喇叭嘴、接线端子；更换锈蚀坏损的螺栓、螺母和接线端子。更换已失效的弹垫；清除、擦拭设备表面煤尘，处理隔爆设备防爆面，更换过期、破损的防爆牌、小型电器完好责任牌、设备完好责任牌。保持设备完好，严禁失爆。
*** 造成线路零乱、脱线等问题属看护责任队组责任的，要通知该责任队组，无法就地通知时，立即汇报因工具、材料、配件、人员等条件不具备不能就地处理的问题，并作相应的特殊处理。
*** 发现通讯设备、电缆等设施被损坏，要及时汇报，并就地通知看护责任队组，同时立即采取措施进行修复处理。
*** 发现通讯设施受砸、受水淋、受挤压等威胁时，能就地处理的即时采取措施处理、解决。
*** 发现通讯设施受踢踩、坐卧，要立即制止，并对责任人进行当面教育。
*** 升井后，根据井下实际作业情况，认真填写《维护记录》和《故障处理记录》。对存在问题的责任人开出五定表；同时对问题严重的进行罚款处理。
** 安装设备作业
*** 根据设备安装现场的实际情况准备相应的电缆、电话机、喊话器、小灵通基站等设施，并要仔细核对规格型号和对通讯设备进行预先检测与调试。
*** 设备、电缆的装车、绑扎、运输要符合保养要求。
*** 根据通讯线路走线情况，事先在地面将通讯信号接续好、记录好、测试好，保证信号准确无误。
*** 安装前，必须准备好所需工器具。
*** 安装设备时，电话机、接线箱、扩音电话及电源箱、小灵通基站等安装的位置在符合有关技术要求的同时，还要选择支护稳定牢靠、无滴水、便于检修维护、不易被行人踩踢和来往车辆刮碰的地点。严格按井下防爆电气设备质量标准化进行安装作业，设备安装牢靠，电缆必须悬挂整齐，严禁摔、砸设备或配件。严禁带电搬迁、拆装设备，以防损坏设备、配件及电缆。电缆铺设要顺势平滑地悬挂到电缆钩上，不允许打死弯，不得与动力电缆、风水管路交叉。
*** 所有接线必须规范，符合质量标准化要求。接线箱内接线要按规定色序接续，各接线盒进出线，应标注出用途、线序并画出接线图放置或粘贴于箱内。因作业需要更改接线顺序后，要及时更改箱内相应接线图。接线完毕后，要与地面值班室联系确认所有信号均正常无误且双方通话良好。
*** 安装后的设备，要认真进行完好检查，包括安装位置、设备外观、安全标志、接线嘴、防爆面、紧固螺栓、弹簧垫、垫片等，发现问题就地处理。完好的设备要标贴设备完好及防爆合格证等标志牌，填写内容要准确、清晰。
*** 作业完毕后认真清点工具、配件、材料，不得遗漏。同时清理作业地点周围的杂物。
*** 各种小件、易损设备、配件随身携带上井，并交回工房。需要升井的设备、电缆、空电缆盘要集中到便于运输的地点，电缆、设备不得遗留在密闭巷道内。
*** 根据实际作业情况，认真填写《设备安装台帐》。
* 特殊操作
在巡检、安装过程中，发现的通讯设施存在问题、隐患，都需要就地立即处理，若在现场不能处理时，立即汇报值班室并等故障处理人员到达现场一起处理好后方可离开现场。
* 收尾工作
** 作好当班各种工作记录。
** 将本班作业情况和存在问题向接班人员认真交代清楚。
