:PROPERTIES:
:ID:       4420d299-52e5-4165-97b7-fc33baa9229a
:END:
#+title: 矿井供电管理制度
* 总 则
** 各级供电管理部门及人员的职能。
机运科是矿井供电业务技术综合管理部门，负责供电业务技术管理工作，组织对供电管理制度的落实情况进行督促、检查，对供电事故组织调查、分析并提出处理意见。积极推广节能降耗和安全供电新技术。
矿长是供电安全管理第一责任人，机电副矿长具体负责供电安全管理工作。
** 机电矿长或机电副总工程师负责矿井供电及电气安全技术管理,必须建立健全电气及电（线）缆管理组。
* 矿井高压供电管理
** 矿井的双回路主供电电源线路及矿井高压电网应符合《煤矿安全规程》要求。
** 矿井井下高压供电不宜超过三级(中央变电所为第一级)。
** 矿井高压线路和设备技术管理由机电副矿长负责。具体负责高压供电系统的检查、维护、调整和试验等工作。
** 地面高压架空线路、井上下高压电缆线路、高压配电装置都要统一编号登记、建账，要注明供电设备的型号、容量、电压、电流及电缆(包括架空线)的用途、型号、电压、截面和长度等数据。机运科要有以下图纸及资料并及时更新：
*** 井上下供电系统图。
*** 井上、下高压电缆和高压设备布置示意图。
*** 井下电气设备布置图，地面高压输电线路示意图。
*** 高压供电设备台帐。
*** 高压电气设备预防性试验资料、检修记录。
** 井上下变配电站(所)必须悬挂与实际相符的供电系统图，并按规定及时更新。
** 井下变电所应有两回及以上回路电缆供电，并应引自上级变电所的不同主变压器(母线段)。正常情况下，应采用分列运行，不准随意用联络开关送电。特殊情况下，需要合联络开关送电时，必须由用电队组申请，方可操作。电缆截面的选择，应保证在任一回路停止供电时，其余回路仍可担负全部负荷。中央变电所的高、低压母线宜采用单母线分段。高压母线分段数应与供电电缆回路数相协调。
** 矿井应推广6KV（10kV）下井供电。电缆选择应按现行《煤矿安全规程》要求的有关规定执行。井下变电所应设置进线断路器；双电源进线的变电所、单电源进线但高压负荷超过两个的变电所，也应设置进线断路器。主变电所、变电所的高压馈出线，应设置带真空断路器的专用开关柜或高压防爆开关。变电所内直接向高压电动机配电的回路，应采用高压真空接触器。
** 高压供电线路、设备要进行检查。检查内容主要包括接线螺栓紧固情况、设备灰尘情况、瓷瓶清洁、触头接触、保护整定核对等，并做好记录。地面高压开关柜、变压器由管理队组每季度组织检查一次，内容包括接线有无松动、刀闸接触是否良好、仪器仪表和保护装置是否完好、是否正确使用、柜内有无积尘、油位是否符合要求等。每年雨季前检查一次断路器触头的同期性，并进行一次电动或手动跳闸试验，并做好记录。对达不到要求的应及时处理，对处理不了的问题及时上报机运科。
高压供电线路、设备按规定检修周期和电气设备的检修标准进行检修。检修高压供电线路、设备必须编制检修安全技术措施，经审批后实施。
井下高压开关壳体内必须放置干燥剂，坚持每月检查一次，发现失效的应及时更换。
** 有架空线路的矿井每年至少要在雨季前进行1次蹬杆检查，主要检查绝缘子有无裂纹、污闪损坏，螺丝是否松动、缺失，金具生锈程度等。每月至少进行一次巡视，重点巡视拉线有无缺少、损坏，杆塔有无裂纹、缺件，树木和导线安全距离是否满足要求，并对存在问题及时处理。每年雨季前要进行一次全面检修，遇有大风暴雨和严重结冰等恶劣天气情况要随时巡视检查。
** 井上下高压电缆每月要进行一次检查。在电缆设施处进行施工时，施工队组要制订措施，按措施规定严格进行施工。
** 电气设备使用的绝缘油，要按规定进行试验。对试验不合格者，要及时处理和更换。
** 井上下高压线路和设备的安装必须有合理的设计，并经审批后方可进行施工。
** 防、避雷保护设施要按照《过电压保护规程》进行安装，根据《煤矿电气设备试验规定》进行试验和测定。
** 地面变电所出线上要装设过流和选择性的检漏保护装置，井下变电所高压配电装置，要装设过流及具有延时的欠电压保护装置。上述保护设施要根据《煤矿安全规程》规定进行装设，每年至少进行一次整定、校验和调整。遇有越级跳闸、保护失灵和仪表不准等要立即进行检修或更换。保护整定值不准任意变动。
** 井上、下变电所要按消防规程配备足够数量合格的灭火器材，实行挂牌管理。消防器材应设置在机房和硐室的入口明显处和进风侧，并妥善保管。
** 矿井必须制定详细完整的《停电应急救援预案》,为保证预案的科学性、针对性及可操作性,应根据实际情况随时修订补充内容,并认真贯彻。
* 矿井低压供电管理
** 设有专(兼)职井下低压供电技术负责人员，具体负责低压供电系统、电气设备的检查管理等工作。
** 低压电气设备的安装必须有设计，设计中要包括供电系统图，设备、电缆的选型和校验，设备的型号和主要技术参数，电缆的规格型号、长度，以及过流保护整定值和二相短路电流值等技术数据。在投入运行前要检查过流、漏电、接地三大保护装置是否与设计和《煤矿安全规程》要求相符。
** 井下增设临时电气设备，安装队组必须经专管专职（兼职）电气技术负责人员批准，在指定的地点、部位接线，并队相应的低压防爆开关定值做出相应的调整。
** 对于井上下低压供电系统图要按规范要求进行绘制，标明必要的技术数据，并妥善保管。
** 井下低压防爆开关的过流保护，要根据设计和低压供电系统图中标定的整定值进行过流整定和装设保险，不经主管人员批准，不得任意改动。各种保护由井下各队组专职电工负责，每周检查核对一次。
** 掘进工作面正常工作的局部通风机必须配备安装同等能力的备用局部通风机，并能自动切换。正常工作的局部通风机必须采用三专（专用开关、专用电缆、专用变压器）供电。
** 矿井每月进行一次井上下高低压供电检查，重点检查设备完好情况、电缆吊挂情况、电气防爆情况、保护装置完好情况等。要求防爆电气防爆率达到100%，设备完好率不低于95%，低压电缆完好率不低于95%，小型电器合格率不低于90%。
** 井下低压供电严格执行“十不准”：1.不准带电检修、搬迁、移动电气设备和电缆。2.不准甩掉欠电压、过电流保护装置。3.不准甩掉漏电继电器、信号照明综合保护和局部通风机风电、瓦斯电闭锁装置。4.不准明火操作、明火打点、明火放炮。5.不准用铜、铝、铁丝等代替保险丝。6.停风、停电的采掘工作面，未经检查瓦斯，不准送电。7.有故障的供电线路，不准强行送电。8.电气设备的保护装置失效后，不准送电。9.失爆电气，不准使用。10.不准在井下拆卸矿灯。
* 停送电管理
** 高压停(送)电必须严格执停送电工作票及操作票制度。
** 有计划停(送)电，责任队组必须提前一天写出停(送)电申请单，内容包括：申请队组、申请时间、停(送)电原因、停电范围、影响区域和队组等，报请机电副矿长审批，调度室指挥相关人员按票规定进行停(送)电作业。
** 用电队组在井下临时需要停（送）电时，由用电队组汇报调度室，由调度室协调指挥停送电，并做好停（送）电记录。
** 停电队组根据申请单填写工作票，一式两份，负责停电人一份，另一份交由调度室负责指挥并保存备查。
** 执行停电作业的人员，严格按照操作规程、岗位责任制进行操作。停电检修必须严格按照检查瓦斯浓度、停电、闭锁加机械锁并挂警示牌、验电、放电、挂短路接地线操作程序进行操作，在确认无电后方可进行，带电部位应用栅栏或警示牌标识。
** 在无人值守的变配电点进行停电作业时，停电时应安排专人在现场看护，不准离开现场。停电后将开关进行机械闭锁、加锁后挂上“有人工作，禁止送电”的警示牌，只有执行这项工作的人员才能取下此牌并送电。
** 停(送)电工作必须严格遵守专人专职联系和谁停电、谁送电的原则进行，严禁预约停送电。
** 停电检修时应对开关闭锁并加机械锁，具体要求如下：
高、低压电气设备停送电操作、检修，由专职电工负责，应严格遵守操作规程。要将停电开关的把手闭锁，对电气设备停送电机构进行“加锁”，同时悬挂“有人工作，禁止送电”的警示牌，并专人看管。严格执行“检修必须停电，谁检修谁联系，谁停电谁送电”的停送电管理制度。
检修结束后，检修人员要对各自检修设备、线路进行详细检查，确保无误后方可联系送电。
** 在停送电操作时必须做到：安全技术措施不完善不停送电，作业情况不明不送电，安全隐患不排除不送电，不是专人专职联系不送电。
** 各队组需在自己供电范围内(不影响其它队组供用电的)停电检修，不需要到变电所停(送)电的，其负责人(或检修负责人)必须在检修前向各用电地点人员说明情况，采取必要的措施。当停电检修影响其他队组时，必须办理停(送)电申请单，并做好停(送)电措施后，向调度室汇报，征得调度室同意后，施工队组检修人员方可进行停(送)电操作。
** 紧急情况或事故处理：出现停电事故时，调度室应及时通知值班矿领导、机电副矿长或机电副总和事故影响队组，情况落实清楚后，再负责指挥停(送)电工作。
** 严格执行高压检修“二级停电”制度，即工作点以上必须有两级分断点(断路器断开、手车拉出或隔离刀闸拉开)。
* 防爆电气设备管理
** 矿井配备专（兼）职防爆电气检查人员，负责井下电气设备的防爆检查管理工作。
** 防爆电气设备必须有“生产许可证”、“防爆合格证”、“产品合格证”和“煤矿矿用产品安全标志”。防爆电气设备入井时，防爆检查员应按照防爆标准进行检查，符合防爆要求的做好记录。不符合防爆要求的，严禁入井使用。
** 井下电气设备的防爆性能检查周期：
*** 使用队组负责，每天进行一次外观检查。
*** 专（兼）职防爆电气检查人员，负责每季度对分管区域内的防爆电气设备的防爆性能至少检查，必须覆盖所有队（组）。
*** 机电副矿长（或机电副总工程师）每月对队组的防爆电气设备抽查，并做好记录。
** 队组应建立管辖范围内的电气设备防爆检查记录，防爆检查员应建立井下电气设备防爆检查记录，对检查中发现的问题应及时整改，做好检查记录。井下电气设备发生变化时，防爆检查记录要及时更新。
** 防爆电气设备的防爆性能及检查严格按照《煤矿矿井机电设备完好标准》执行。
* 三大保护管理
** “三大”保护是指：煤矿供电系统中的接地保护、过流保护和漏电保护。矿井必须保证供电系统各种保护装置灵敏可靠，供电系统安全可靠运行。
** 矿井机电副矿长或机电副总工程师负责全矿“三大”保护日常技术管理工作，严格按照《煤矿安全规程》规定，加强“三大”保护使用状况的指导和检查，开展技术培训工作。
** 使用队组应按规程规定的检查、试验周期对“三大”保护进行检查和试验，检查和试验结果报矿电副矿长或机电副总工程师。对存在的问题及不安全隐患要制定整改措施进行整改。
** 新增的电气设备，应按照规程规定装设完善“三大”保护，各项安全保护装置安装试验合格后方可投入运行。
** 过流保护使用管理必须遵守以下规定：
*** 井下低压电网中过电流继电器的整定应按《煤矿低压电网短路保护装置整定细则》进行。
*** 各队组管理的开关要按机运科下达的整定值进行整定，不得随意调整、擅自改变电气继电保护整定值。
*** 各种开关甩掉或短接过流保护的、过载保护超过电机额定电流的、短路保护超过额定电流8倍以上的或整定不合理的，按重大隐患处理。
*** 各种二次保护使用的保险管必须按原配置更换使用，不得替代。
*** 入井使用的馈电开关必须做过流试验，合格后方可入井使用，供配电系统保护装置每6个月至少检查整定一次。
*** 运行中的电气设备的保护装置由负责维护的电工检查，如发现动作有误或整定值有差错时，应及时向相关领导汇报，并根据实际情况作出调整。
** 接地保护使用管理必须遵守以下规定：
*** 保护接地装置必须严格按照《煤矿安全规程》及《煤矿井下保护接地装置的安装、检查、测定工作细则》相关要求进行安装、运行、检查。
*** 矿井中低压电缆严禁使用无接地芯线的电缆。
*** 有值班人员和专职司机的机电硐室，保护接地每天必须进行一次外观检查，其它地方的电气设备保护接地由维修人员每月不少于一次外观检查，发现问题及时处理，并将检查的问题，记入到记录本内。
*** 新安装的接地装置必须经过检查，合格后方可投入运行。
*** 各变电所、机电硐室、副井井底水仓内的保护接地极和接地线，每季度检查和对接地电阻值进行一次测定，并将检查结果和测定结果上报机运科。
** 漏电保护使用管理必须遵守以下规定：
*** 变电所(临时配电点)变压器低压侧出线的总馈电开关和分馈电开关必须安装检漏保护装置，并做到主接地和辅助接地合格、使用正常、动作可靠。
*** 变电所低压供电系统、移动变电站低压总馈电和支路馈电开关每天必须由各责任队组的专职电工对漏电保护装置进行一次跳闸试验，并认真记录。
*** 低压开关的漏电保护试验不合格时，必须立即处理，漏电保护不可靠的开关严禁投入使用。任何人严禁违反规定，明知有漏电情况，强行指挥、操作送电。
*** 每月应组织使用队组负责人对装有检漏继电器的开关进行一次远方漏电试验。
*** 地面变电所和井下变电所的高压馈电线上，必须装设有选择性的单相接地保护装置，供移动变电站的高压馈电线上，必须装设有选择性的动作于跳闸的单相接地保护装置。井下低压馈电线上，必须装设检漏保护装置或有选择性的漏电保护装置，保证自动切断漏电的馈电线路。选择性检漏保护装置必须配套使用(即总开关和所有分支开关必须都装设)，带延时的总检漏保护装置不准单独使用。
*** 运行中的检漏保护装置性能必须可靠，严禁停用或拆除，任何人在任何时间无权停止运行线路的检漏保护装置。当系统出现漏电故障时，严禁采用甩掉检漏保护装置强行送电查找故障的方式。
*** 矿井提升运输系统的信号、照明必须使用设有检漏、漏电闭锁、短路、过负荷保护的照明信号综合保护装置。
* 电缆管理
** 本管理办法所述电缆管理主要指煤矿使用的4mm2及以上动力、照明、通信、监控、信号等各种类电缆的使用管理。
** 各矿井必须成立电缆日常管理部门，对全矿电缆管理、使用、维护等业务进行监管，同时负责电缆管理新技术、新工艺的推广应用等工作。
** 矿井必须建立健全电缆管理制度，严把电缆入井关，对阻燃性能达不到要求的电缆严禁入井，实行建卡建帐管理，做到数量清，状态明。
** 电缆使用队组职责：
*** 电缆使用队组负责人是电缆现场使用管理的第一责任人，对电缆管理、使用、维护和完好状态负责。
*** 电缆使用队组负责管辖范围内电缆的现场管理，并有一名专（兼）职人员负责电缆的领用、回收及移交管理工作。
*** 对电缆管理部门或上级管理人员提出的各种隐患，必须按要求进行整改处理，对电缆在使用过程中存在的不安全隐患或发现有质量问题的，要及时汇报，以便及时采取应对措施。
** 矿井要制定全矿所有地点电缆敷设、使用及维护管理办法，明确职责，实现规范化、统一化和精细化管理。电缆的选用、敷设、连接必须符合《煤矿安全规程》第四百六十二、四百六十三、四百六十四、四百六十五、四百六十六、四百六十七、四百六十八条的有关规定。
** 各矿井应按照下列要求管理好各自管辖范围内电缆的使用、维护，确保电缆的安全运行：
*** 矿井固定敷设的高压电缆每年在雨季前做一次耐压试验。发现电缆隐患或缺陷，责令管理队组及时修复，做好记录，填写电缆试验报告和检修档案。
*** 固定敷设电缆由使用队组每季度做一次绝缘和外部检查，每旬应对其外部和悬挂情况做一次巡回检查。巡查内容包括：线路状态、接线盒、辅助接地极、线路温度等，发现隐患及时申请停电处理，并做好记录。
*** 移动式电气设备的橡套电缆，当班负责人应对其外皮破损情况、悬挂敷设情况等进行一次检查，并做好巡检记录；队（组）负责人每月对电缆做1次绝缘检查，并记录存档。对有顶板冒落或巷道片帮等危险地区，使用队组应及时安排人员对电缆采取保护措施。严禁电缆超负荷运行，发现隐患应立即停电检查处理。在采煤工作面或掘进工作面附近的电缆要采取防护措施，严防炮崩、砸压和受外力拉坏等。
*** 高、低压供电系统中的接线装置应有维护责任人每月进行一次检查，特别是接线端子的连接情况，有无松动、过热现象，发现问题立即整改。因使用电缆不当造成电缆发热，使电缆芯线氧化、绝缘老化报废的，对使用队组进行责任追究。
*** 巷修、开拓等队组在施工作业时，要对作业区间内的电缆采取防护措施，巷道整修完毕后，应及时将电缆悬挂复位。由于电缆防护措施不到位，造成电缆砸伤、放炮崩坏电缆或造成事故的追究有关人员的责任。
*** 任何电缆使用管理队组和个人严禁对带电、备用电缆采用水冲的方式清理电缆上的浮灰和污垢，一经发现对责任队组和责任人进行责任追究。
* 电气试验管理
** 矿井要加强煤矿电气设备试验工作，必须认真执行好《煤矿电气试验规程》，正确判断设备能否投入运行，预防设备故障，保障煤矿电气设备安全运行。
** 矿井变电所(站)及主要电气设备的绝缘、特性试验和电工仪表、继电保护装置检验，按照规程、规范、制度要求进行。
** 各队组是各自辖区内电气设备管理和保护试验的责任队组，负责电气设备及保护的维护、管理和试验工作。
** 局部通风机自动切换装置及风电闭锁装置每天试验一次。低压馈电开关及照明综保的检漏保护装置每天试验一次。低压检漏保护装置每月进行一次远方漏电试验(新安装检漏保护装置投运前必须进行一次远方漏电试验)。
** 每年要对高压开关进行交流耐压试验一次。
** 长期停运的电气设备(井下超过3个月，井上超过6个月)，或移动后的设备投入运行前，必须检查设备防爆性能，合格后方可投入运行，并做好试验记录。
** 每年要对变压器绝缘油进行一次耐压试验，大修的变压器必须经过耐压试验后方可投入运行。
** 每年雨季前，必须对避雷装置及设施进行一次测试。
** 运行中的变压器每年要进行一次绝缘电阻的吸收比的测定。
** 新装和大修后变压器要严格按照《电气试验规程》规定进行性能测试，测试项目包含：直流电阻性能测试、变压比测定、空载试验、绝缘吸收比等，合格后方可投运，并要求出具试验报告存档。
** 高压电缆的泄漏和耐压试验每年一次，主要电气设备的绝缘电阻测试每6个月不少于一次，移动式电气设备、橡套电缆的绝缘测试每月一次。
** 接地电网的接地电阻值每季度测定一次。新安装的电气设备绝缘电阻和接地电阻值在投入运行前必须测定。在钻孔中敷设的电缆不能与主接地极连接时或浅井供电(变电所在井下)应单独形成分区接地网，其接地电阻值都不得超过2Ω。
** 绝缘手套、绝缘胶靴、绝缘台、高压验电笔、放电棒等各种保安用具每6个月试验一次，绝缘杆、绝缘夹每年试验一次，并张贴试验合格证。不合格的严禁使用。
** 大修后和投运前的电动机按试验规程要求进行性能测试。
** 高、低压的各种开关保护功能(短路、漏电、过载、断相等)每年测试调整一次。新到货或检修好后的高、低压开关和照明综合必须进行各种保护功能(短路、漏电、过载、断相等)测试。
** 变电所高压真空配电装置正常工作后，每年应对压敏电阻进行一次预防性试验。
** 电气设备的各种试验应按试验制度和煤矿电气试验规程执行，并做好各种试验记录并保留存档。
** 高压电气设备预防性试验记录统一按照机械动力部下发的试验表格填写，记录填写应准确、规范。
** 矿井应按规定对电气设备和电缆进行检查、调整、试验,认真填写试验报告或记录，并存档备查。电气设备和电缆的检查、调整、试验周期如下：
*** 使用中的防爆电气设备的防爆性能检查低瓦斯每周一次，高瓦斯每周二次，每日应由分片负责电工检查一次外部。
*** 配电系统继电保护装置检查整定每6个月一次，负荷变化时应及时整定。
*** 高压电缆的泄漏和耐压试验每年一次。
*** 电气设备绝缘电阻的检查每6个月不少于一次。
*** 固定敷设电缆的绝缘和外部检查每季一次，每周应由专责电工检查一次外部和悬挂情况。
*** 移动式电气设备的橡套电缆绝缘检查每月一次，每班由当班司机或专职电工检查一次外皮有无破损。
*** 接地电网接地电阻值测定每季一次。
*** 新安装的电气设备绝缘电阻和接地电阻的测定投入运行以前。
*** 局部通风机自动切换装置及风电闭锁装置每天试验一次。
*** 低压馈电开关及照明综保的检漏保护装置。每天试验一次。
*** 低压检漏保护装置远方漏电试验每月进行一次，新安装检漏保护装置投运前必须进行一次远方漏电试验。
*** 高压开关交流耐压试验每年一次。
*** 长期停运的电气设备或移动后的设备(井下超过3个月，井上超过6个月)投入运行前，必须按设备的使用电压进行绝缘性能测试。
*** 变压器绝缘油耐压试验每年一次大修的变压器，必须经过耐压试验后方可投入运行。
*** 避雷装置及设施测试每年雨季前一次。
*** 运行中变压器绝缘电阻的吸收比测定每年一次。
*** 绝缘手套、绝缘胶靴、绝缘台、高压验电笔、放电棒绝缘试验每6个月一次。
*** 绝缘杆、绝缘夹试验每年一次。
*** 大修后和投运前的电动机按试验规程要求进行性能测试。
*** 高、低压继电保护的各种保护功能(短路、漏电、过载、断相等)测试调整每年在试验台上一次，新到货或检修好后的低压继电保护和照明综合保护必须在试验台上进行各种保护功能(短路、漏电、过载、断相等)的测试。
*** 变电所高压真空配电装置压敏电阻的预防性试验每年一次。
* 电工教育培训管理
** 矿井必须建立“三年培训规划，一年培训计划”，电工教育培训必须贯彻“强制培训，岗位培训，经常教育，全员学习”的原则，坚持理论与实践相结合，正规培训与经常教育相结合，脱产培训与岗位培训相结合的要求及“专业化、小型化、常态化”的要求。
** 电工教育培训工作由机电副矿长负责，建立逐级培训管理网络。
** 电工教育培训的对象：全矿所有电工，包括：班组长、安全生产现场管理人员，特殊工种(井下电钳工、机电维护员、配电工、绞车司机、电车司机、人车司机、小绞车司机、信号工、充电工、水泵工、电气焊工等)。
** 电工属特殊作业人员，必须经培训取得合格证后方可上岗。
