:PROPERTIES:
:ID:       05380e9c-aab3-429f-96d5-6c011a2c8f97
:END:
#+title: 停、送电管理制度
* 一般规定
** 停送电操作人员和电气维修工，必须经过相应部门的岗位资格培训，取得合格证后，持证上岗。
** 停送电操作人员必须熟悉作业范围内的电气系统，设备的性能、结构和工作原理，以及停送电的操作方法。
** 电气维修工和停送电操作人员必须掌握验电器具的使用方法，以及验电、放电、挂短路接地线的具体要求和操作要领。
** 电气设备的维护要达到《煤矿机电设备完好标准》规定的要求、各种电气保护齐全，灵敏可靠。
** 进行停送电操作时，必须使用经检验合格的绝缘用具、验电器具、仪表。
** 任何停送电作业，必须由调度统一指挥，停送电工作应严格执行《电业安全规程》操作，停电检修时必须遵守停电、验电、放电、接地、悬挂标志牌等程序。
** 停送电操作应填写“工作票”经批准后执行。应急处理事故时，可不执行“工作票”制度，但需调度室许可，由调度室统一协调指挥。
** 井下不得带电检修和搬迁电气设备(包括电缆)。
** 在电气设备上检修时必须执行工作票制度、工作许可制度、工作监护制度、工作间断、转移和终结制度。
** 高压变配电因检修或工作需要而停电时，要将线路上的隔离开关和跌落保险拉开，并在停电设备可能发生感应电压的部件打接地线。电容器接地放电，对施工设备的进出线各相进行验电，确认设备无电。
** 工作人员必须在停电设备的范围内作业，并与带电部件保持规定的安全距离，并在隔离开关和跌落保险处设专人监护，悬挂警示牌，安全保护用品齐全方可作业。
** 作业现场工作人员除正常检修工作人员外，还要有专人巡回检查和监护，监护人员在未得到命令前不许离岗。
** 作业完毕在恢复供电前，要对工作范围进行全面认真检查，接地线，短路线，及各种安全保护设施要全部拆除，供电线路，变配电设备上无任何遗留材料、工具、杂物等，通知所有作业人员撤离工作地点，由工作负责人检查无误后，方可请示调度室同意后恢复供电。
** 井下高压停送电必须征得矿主管领导或总工程师同意，才能进行停电，停电时要由专人先和地面高压配电室联系，待其它辅助工作安排好后，方可停电，地面配电室要坚守岗位，随时保持通讯联系，并在停电开关上悬挂警示牌，各开关手柄要按规定进行闭锁。井下变电所作业人员要先将检修线路验电、放电、三相短路后接地，至少派一人监护，配备必要的防护用品方可作业。工作完毕，经检查无遗留问题并通知所有作业人员撤离后，要由通知停电的专人与调度联系方可送电。必须坚持谁停电谁送电的原则。
** 停送电应由专（兼）职人员负责，严禁非工作人员任意停送电，停电作业时，穿戴好防护用品，站在专用的绝缘台上操作。操作时要由技术熟练和对本系统设备熟悉的人监护。停电先停负荷侧，送电先送电源侧，严禁带负荷停送电。
** 线路故障和设备检修，需经有关领导、调度室许可方可停电。
** 掘进工作面停风后，未经瓦检员检查，任何人不得送掘进工作面风机电源和动力电源。
** 在一条供电线路同时给予两个（含两个）以上队组供电时，若首先一个队组停电，在此停电时间，其他队组不得私自利用该停电时间进行检修电气设备和其他相关操作，如需检修必须办理停电手续后，方可进行检修。到送电时间，由检修队组持工作票联系送电，并不再通知其他队组。
** 各队组自行施工或检修设备，无涉及其他队组停送电的，由主管人员申请报机电副矿长批准同意后，方可进行停电检修工作。
** 在危及人身和设备安全的紧急情况下，现场人员可紧急停电。事后，立即汇报调度室。
** 外来施工队组需停送电的，由用工单位负责办理停送电手续。
** 各队组在设备故障引起变电所开关跳闸后，作业人员或操作人员需立即上报调度室，并迅速查找原因，排除故障。故障排除后，由队组申请，调度室批准指挥送电。
** 主管机电领导负责日常电力设备、设施的维护、检修和管理工作，确保电力系统安全可靠；并负责办理停送电手续和协调停送电工作。
** 因临时停电或其它原因，局部通风机在恢复运转通风前，必须首先检查巷道内瓦斯，证实停风区域内瓦斯浓度不超过规定时方可人工开动局部通风机，由瓦检员或救护队员负责恢复局部通风机的正常供风。严禁“一风吹”
** 井下因故造成无计划停电停风时，应立即撤出人员，切断电源，并及时向调度室汇报。
** 凡突然发生局扇无计划停电停风的掘进巷道，班组长应立即组织人员将停风工作面打好栅栏，或安排专人警戒，禁止一切人员进入。调度室必须立即查明突然停电停风原因，按照规程进行处理。
** 停电（计划停电、事故停电、系统停电）而影响通风，在恢复送电前，送电区域必须检查瓦斯，只有当瓦斯浓度不超过规定，经现场瓦检员或调度室同意后方可送电。
** 禁止在交接班时间内办理停送电工作（遇有事故时，由交班人处理完毕后方可交班）。
** 矿井因停电，造成主要通风机停止运转，必须制定恢复通风、排除瓦斯和送电安全措施。
** 主通风机停止运行后，按照《主通风机停止运行后停送电的管理规定》执行停送电。
** 停送电除了要执行上述规定外，还要执行“安全管理制度中规定的《井下局部通风机停送电制度》、《系统停电管理制度》、《瓦斯超限停送电管理制度》。
* 停、送电管理
** 维护，检修任何电气设备、线路时必须停电，不准带电作业。确需带电状态进行工作的，必须制定安全技术措施，并报相关领导批准后方可作业。
** 凡须对6KV（10KV）及以上电压等级的设备、线路（包括电缆）进行停电检修时，一律办《第一种停送工作票》，停电范围影响到其他队组时，还需办理《停电停风通知单》与第一种停送电工作票配合使用。须停主通风机和瓦斯泵检修时，还必须同时办理《检修通知书》和《倒机票》与第一种停送电工作票配合使用。凡须对1140V及以下电压等级的设备、线路（包括电缆）进行停电检修时，一律办第二种停送电工作票，须对井下设备、线路（包括电缆）进行停电检修时，还必须同时办理《停电停风通知单》与第二种停送电工作票配合使用。
** 第一种停送电工作票必须由机电副矿长审批（机电副矿长出差或请假时，由矿长指定副矿长审批）。第二种停电工作票由各队组负责人签发。
** 检修通知书必须有相关领导签字，牵涉到一通三防设施由机电副矿长和总工程师同时审批签字。
** 井下局部通风机“三专”设备及线路停电检修时，停电停风通知单除按规定的相关人员签字外，还必须有机电副矿长和总工程师同时签字。在停电检修前，必须制定局部通风机“三专”设备及线路停电检修技术报告并按规定程序审批签字后方可实施检修工作。
** 正常停送电指挥由调度室按停送电工作票执行。故障情况下停送电指挥可不办理停送电工作票，由调度室指挥操作，必须及时向相关领导汇报。
** 供电系统中高低压开关柜出现过流跳闸可指挥抢送一次，抢送一次不成功必须查明原因、排除故障才能联系送电。高低压开关柜出现短路跳闸严禁强送电。
** 停送电操作由变电所、配电点值班员进行操作，无值班员的变电所、配电点由调度室派专（兼）职电工进行停送电操作。
** 凡进行6KV（10KV）及以上电压等级的停送电操作必须执行一人操作一人监护的二人操作制。
** 所有停电检修的电气设备及线路（包括电缆），停电后都必须按规定进行验电、放电、接地、挂停电牌。只有上述安全措施经检查无误后方可进行检修工作。
** 所有停电检修的工作都必须严格执行监护制度和工作许可制度，严禁一人进行电气检修工作。
** 凡涉及到井下瓦斯的停送电工作，恢复送电前必须严格执行瓦斯检查制度，必须得到调度室的指令方可送电。
** 在6KV（10KV）及以上电压等级的设备、线路、变电所进行工作时，必须严格执行两票（工作票、操作票）制度，变电所值班员、维护检修人员按工作票、操作票规定要求进行停电、做好相应安全措施后，应认真填写工作的相关内容。停电工作票执行结束后，工作票由变电所、车间（队）、调度室至少保存三个月。
* 停、送电作业
** 地面变电所和线路（含地面机房各配电部分）
*** 工作票签发人、工作负责人和工作许可人必须熟悉供电系统，并持有相关资格证（如专业技术资格证和电气设备操作资格证），才能从事此项工作。
*** 严格执行“两票制”，停送电由调度室统一指挥，停送电操作必须由变电所值班员执行，无人值守的变电所由调度室指挥专（兼）职电工进行停送电操作。
*** 电话联系停送电时，必须清晰准确，操作人员详细记入操作记录簿中，并向发令人复诵核对一遍，确认无误后，才能进行操作。
*** 按照“工作票”内容，根据供电系统图和现场实际，核对无误后，方可填写“倒闸操作票”，按“倒闸操作票”填写的顺序逐项进行停送电的操作。
*** 停送电操作要严格执行唱票复诵制和一人操作一人监护制度。
*** 停电后，在工作地点施工时，要用与电压等级相适应的验电器验电，确认停电后，用合格的短路接地线充分放电，在做好短路接地措施后方可开始检修作业。
*** 检修工作完成后，确认所有人员已撤到安全地点和所有安全措施拆除，并经复核无误后，方可联系恢复送电。
*** 同一线路上多组施工时，工作票只发给一个总负责人，工作结束后，总负责人核实各组人员，确认人员已全部撤离工作现场后和安全措施已拆除方可联系送电。
** 井下变电所（含井下各个配电点）
*** 所内高压设备停送电
- 按批准的“停送电工作票”执行。
- 严格执行煤矿安全规程和操作规程，专人负责联系停送电。
- 所内的停送电操作必须由变电所值班员执行，其他人员不准进行停送电操作（无人值守变电所除外）。配电点高压设备停送电由专（兼）职电工操作。
- 电话联系停送电时，必须清晰准确，停电负责人将工作任务记入操作记录簿中，并向发令人复诵核对一遍，确认无误后，才能进行操作。
- 停电后，在工作地点施工前，要用与电压等级相适应的验电器验电，确认无误后，用合格的短路接地线充分放电，并将开关手车拉出锁牢，裸露的可能带电体按规定作好短路接地措施，挂好停电警示牌后方可开始检修作业。检修完成后，先拆除所有安全措施，并经复核无误后，方可联系恢复供电。
*** 所内低压设备停送电
- 按批准的“停送电工作票”执行。
- 所内的停送电操作必须由变电所值班员执行，其他人员不准进行停送电操作（无人值守变电所除外）。
- 停送电操作前，要对所停负荷名称根据供电系统图和现场实际核实停送电开关编号，确认无误后，方可进行停送电操作，停电开关闭锁、挂停电警示牌。
- 电话联系停电时，必须清晰准确，停电负责人将工作任务详细记入操作记录簿中，并向发令人复诵核对一遍，确认无误后，才能进行操作。
- 停电后，在工作地点施工时，用与电压等级相适应的验电器（笔）验电，确认无误后，用合格的放电导线放电，裸露的可能带电体按规定做好短路接地措施后方可进行检修作业。
- 检修完成后，拆除所有的安全措施，复核无误后，联系恢复送电。
*** 所外分支高、低压线路检修停送电：
- 按批准的“停电工作票”执行
- 所内的停送电操作必须由变电所值班员（无人值守变电所除外）执行，其他人员不准进行停送电操作，对无人值班的变电所（配电点），必须有专（兼）职电工停送电。
- 值班员停电操作前，要对所停负荷名称根据供电系统图和现场实际核实停电开关编号，确认无误后，方可进行停电操作并闭锁、挂停电警示牌。
- 电话联系停送电时，必须清晰准确，停送电负责人将工作任务详细记入操作记录簿中，确认无误后，才能进行操作。
- 所外检修高、低压开关时，待停电后，对停电开关操作机构闭锁、拆除控制回路保险管或派专人看守开关等安全措施后，再到工作施工地点，用与电压等级相适应的验电器验电，确认无误后，用合格的放电导线放电，再挂短路接地线，之后方可进行检修作业。
- 检修完成后，拆除所有的安全措施，确认无误后，联系调度室恢复送电。
** 其他地点的停、送电
*** 其他地点包括综采、综掘工作面和其他地点的高爆开关、移动变电站；井上、井下变电所外的低压线路及设备。
*** 凡影响到其他队组、用户停电时，填写“停电工作票”，经批准后执行停送电作业。
*** 停送电操作由负责此项工作的电气维修工执行。
*** 停电操作前，要按照所停负荷名称，根据供电系统图和现场实际核实停电开关编号，确认无误后，方可按操作规程操作开关，并闭锁、拆除控制回路保险管或派专人看守开关等安全措施。
*** 检修高、低压开关时，停电后，用与电压等级相适应的验电器（笔）验电，确认无电后，用合格的放电导线放电，再挂短路接地线，之后方可检修作业。
*** 检修完成后，拆除所有的安全措施，复核无误后，联系调度室恢复送电。
* 有关验电、放电和挂短路接地线的具体规定
** 35KV 、6KV（10KV）等级
验电：用电压等级相应而且经实验合格的验电器，在检修设备的进出线的两侧各相分别验电，验电时必须带上绝缘手套，35KV级验电时人体与可能带电体保持1米以上的安全距离，6KV（10KV）级验电时人体与可能带电体保持0.7米以上的安全距离。
放电：当验明无电压后，用有合格绝缘外层的导线或专用器具对地放电。
装设短路接地线：当验明确认无电压后，要立即装设短路接地线。由两人进行，先接接地端，后接导体端，拆除接地线的顺序与此相反。接地线用专用线夹固定在导体上。装、拆接地线时均应使用绝缘棒、戴绝缘手套和穿绝缘鞋。短路接地线用多股裸铜线，其截面应符合短路电流的要求，但不得小于25mm2。
** 1140V、660V、380V以下等级。
验电：用电压等级相应而且合格的验电笔，在检修设备的两侧各相分别验电，人体与可能带电体保持0.2米以上的距离。
放电：用有绝缘外层的导线或者专用器具对地放电。
装短路接地线：先接接地端，后接导体端，接地线用专用线夹固定在导体上。拆卸接地线的顺序与此相反。短路接地线用多股裸铜线，其截面应符合短路电流的要求，但不得小于25mm2。
** 验电器（笔）使用规定
电压等级	验电器（笔）
35KV	35KV
6KV	6-10KV
1140V	1500V
660V	1000V
380V及以下	500V
* 其他相关规定
本规定根据上级有关规程、规定结合矿井实际编制，如在工作中发现与上级有关规程、规定不同，则以上级规程、规定为准。
** 工作票签发人员及权限
*** 机电副矿长：负责全矿第一种停送电工作票的最终审批。
*** 总工程师：负责矿停电停风通知单的最终审批。
** 工作许可人
所有停送电的许可人是调度室的值班人员、现场值班人员（现场检修负责人）。现场值班人员（现场检修负责人）必须经调度室的值班人员同意方可停送电。
* 安全监督
** 调度室负责监督管辖范围停送电的执行情况，调度室负责落实内容包括：询问开关是否已按要求停电；提醒工作人员在工作地点施工前必须验电、放电、接地，必须由工作负责人按要求悬挂停电牌和采取有效的安全措施；提醒工作人员必须做好停送电安全措施；工作结束，恢复送电前，询问工作地点人员撤离情况和安全设施拆除情况，命令工作负责人检查确认各项工作完成后，然后取下停电牌，方可恢复停送电。
** 高压供电系统接线方式改变、多工种多地点停电作业必须由机电副矿长或机电副矿长指定现场安全监督负责人员，但必须由机电副矿长统一负责该项工作。
** 现场安全负责人负责监督现场安全工作。
** 调度室负责监督停送电安全工作，现场负责安全监督人员每次停电检修作业前，须向调度室汇报。调度室须落实停电的开关、线路是否已停电（是否已将开关手车、柜体拉出）、是否已验放电、是否已挂“三相短路接地线”、是否已挂停电牌。恢复送电前，须落实开关、线路短路接地线是否已拆除，线路工作人员是否已撤离。
* 工作票管理制度
** 工作票的意义及种类。工作票是准许在电气设备上工作的书面命令，也是明确安全职责，向工作人员进行安全交底，以及履行工作许可手续，工作期间、转移和终结手续，并实施保证安全技术措施等的书面依据。因此，工作时应按要求使用工作票。
** 工作票应预先编号，填写应清楚，不得随意涂改。工作票中的妥为保管，以供备查。一般保留三个月。
** 一个工作负责人只能发给一张工作票。工作票上所列的工作地点，以一个电气连接部分为限。所谓一个电气连接部分，指的是配电装置的一个电气单元，可以用刀闸和其他电气部分作为截然分开的部分。
施工设备属于同一电压，位于同一楼层、同时停送电、不会触及带电导体时，则允许在几个电气连接部分共用一张工作票。
开工前，工作票内的全部安全措施应一次做完。
** 事故抢修工作可不用工作票，但应记入操作记录簿内。在开始工作前必须做好安全措施，并指定专人负责安全监护。
** 工作票签发人的条件。工作票签发人应由熟悉工作人员技术水平、熟悉设备情况、熟悉安全规程的生产领导或经矿主管生产领导批准的人员担任。
工作负责人和允许办理工作票的工作许可人应由主管领导批准。
** 工作负责人可以填写工作票；工作许可人不得签发工作票。为了使所填写的工作票得到必要的审核或制约，工作票签发人不得兼任工作负责人。
** 工作票中所列人员的安全责任
*** 工作票签发人：
- 工作必要性；
- 工作是否安全；
- 工作票上所填写安全措施是否正确完备；
- 所派工作负责人和工作人员是否适当和充足，精神状况是否良好。
*** 工作负责人（监护人）：
- 正确安全地组织工作；
- 结合实际进行安全思想教育；
- 督促、监护工作人员遵守安全规程；
- 负责检查工作票所列安全措施是否正确完备，值班员所做的安全措施是否适合现场实际操作；
- 工作前对工作人员交待安全措施；
- 工作人员变动是否合适。
*** 工作许可人：
- 负责核对工作票所列安全措施是否正确完备，是否符合现场条件；
- 工作现场布置的安全措施是否完善；
- 负责检查停电设备有无突然来电的可能；
- 对工作票所列内容即使发生很小疑问，也必须向工作票签发人询问清楚，必要时应要求详细补充。
*** 工作人员：认真执行安全工作规程和现场安全操作，互相关心，严格施工措施执行，并监督安全工作规程和现场安全措施。
* 工作许可制度
履行工作许可手续的目的，是为在完成措施以后，进一步加强工作责任感，确保万无一失所采取的一种必不可少的措施，因此，必须完成各项安全措施之后再履行工作许可手续。
** 工作许可人（值班员）在完成施工现场的安全措施后，还应做到：
*** 会同工作负责人到现场再次检查所做的安全措施，检修设备确认无电；
*** 对工作负责人指明带电设备的位置和注意事项；
*** 工作交代清楚后，会同工作负责人在工作票上分别签名。
** 工作负责人、工作许可人任何一方不得擅自变更安全措施，值班人员不得变更有关检修设备的运行接线方式。
工作中如有特殊情况需变更时，应事先取得双方的同意。
* 工作监护制度
执行工作监护制度的目的是使工作人员在工作过程中得到监护人一定的指导和监督，及时纠正一切不安全的动作和其他错误做法，特别是在靠近有电部位及工作转移时更为重要。因此：
** 工作负责人（监护人）在完成工作许可手续并向工作人员交待安全措施和注意事项后，应始终在工作现场，认真做好监护工作。
** 为防止人身触电，在整个工作的始终，工作负责人（监护人）均应负责监护工作。当进行的工作较为复杂、安全条件较差时，还应增设专人监护，专职监护不得兼做其他工作。
** 工作期间，工作负责人若因故必须离开工作地点时，应指定能胜任的人员临时代替，并详细交待现场工作情况，同时通知工作人员。
若工作负责人需要长时间离开现场，应由工作票签发人指派新的工作负责人，两工作负责人应做好必要的交接。
* 工作间断、转移和终结制度
** 工作间断时，所有安全措施应保持原状。当天的工作间断后又继续工作时，无须再经许可；而对隔天之间的工作间断，应交回工作票，次日复工还应得到值班员许可。
** 在未办理工作票终结手续前，值班员不准在施工设施上进行操作和合闸送电。
** 在同一电气连接部分用同一张工作票依次在几个工作地点转移工作时，全部安全措施由工作负责人在开工前一次做完，不需要办理转移手续。但工作负责人在每转一个工作地点时，必须向工作人员交待带电范围、安全措施和注意事项。
** 全部工作完毕时，工作人员应清扫、整理现场。工作负责人应先进行周密的检查，待全体工作人员撤离工作地点后，再向值班人员讲清所修项目、发现的问题、实验结果和存在问题等，并于值班员共同检查设备状况，有无遗留物件，是否清洁等；然后在工作票上填写工作终结时间，经双方签名后，工作方告终结。
** 只有在同一地点、系统的所有工作票结束，拆除所有接地线、临时遮栏和标示牌，恢复常设遮栏，并得到值班调度或值班负责人的许可命令后，方可合闸送电，工作票方告终结。
