:PROPERTIES:
:ID:       088d8149-c38b-42ef-9624-fef65e420760
:END:
#+title: 应急预案管理制度
为充分发挥应急管理机构的职能作用，完善工作机制，创新工作方式，更加规范、有序、高效地开展应急管理各项工作，提高应对和处置突发事件的能力和水平，特制定本制度。
* 应急预案体系
** 集团公司应急预案的编制、评审、发布、备案、修订等相关管理工作，适用本制度。
** 应急预案管理遵循统一规划、分类指导、归口管理、分级实施的原则。
** 应急预案体系由三类组成，包括集团公司应急预案、生产经营单位应急预案、大型活动应急预案。要求覆盖所有行业、专业、单位，形成“横向到边，纵向到底”预案体系。
** 集团公司、子公司制定总体应急预案和专项应急预案。
生产经营单位制定综合应急预案、专项应急预案和现场处置方案；班组制定落实预案的处置措施。
举办集会、庆典、文体、等大型活动，按照谁主办、谁负责的原则，由主办单位负责制订应急预案。
* 预案编制责任分工
根据分析报告、《生产经营单位安全生产事故应急预案编制导则》，由各科室负责组织编制本专业系统应急预案。预案编制行业、专业基本种类及责任分工：
** 生产技术科：顶板、防洪事故预案，矸石山环境事故预案；
** 通风科：瓦斯、煤尘、火灾事故预案；
** 机运科：提升运输、通信设施事故预案，供电事故预案，电力安全事故预案；
** 地质测量组：水灾、地质灾害预案；
** 保卫科：民爆、危化品事故预案，交通事故预案，大型活动事故预案，群体性突发事件预案，地面火灾事故预案；
** 行政科：社区安全事故预案，信息网络安全事故预案，供水安全、突发环境、公共卫生事故预案；
** 安全科：突发事件总体应急预案。
* 应急预案内容
** 综合应急预案内容：总则、生产经营单位危险性分析、组织机构及职责、预防与预警、应急响应、信息发布、后期处置、保障措施、培训与演练、奖罚、附则等11部分。
** 专项应急预案内容：事故类型和危害程度分析、应急处置基本原则、组织机构及职责、预防与预警、信息报告程序、应急处置、应急物资与装备保障等7部分。
** 现场处置方案包括事故特征、应急组织与职责、应急处置、注意事项等4部分。
* 应急预案编制
** 各单位主要负责人牵头成立应急预案编制工作组，安排整体预案编制、评审和修订工作。要落实人员，明确任务、职责分工和工作计划，保证工作顺利实施。
** 收集应急预案编制所需资料（相关法律法规、技术标准、应急预案、国内外同行业事故案例分析、本单位技术资料等）。
** 以危险因素分析和隐患排查治理为基础，确定本单位可能发生事故的危险源、事故的类型和后果，进行事故风险分析，指出事故可能引发的次生、衍生事故，形成分析报告，分析结果作为应急预案的编制依据。
** 要保证预案体系的系统性、衔接性。要保证本单位综合预案、专项预案和应急处置方案之间的衔接；保证与现场实际的适应性，与基层预案相衔接；充分利用社会应急资源，保证与上级单位和地方政府预案相衔接。
* 应急预案修订
各安全专委会负责每三年对应急预案组织一次全面修订。有下列情形之一的，应急预案应当适时修订：
** 应急预案中明确的组织机构、有关责任主体和责任人、工作程序等已经调整的；
** 应急预案中相关部门、单位或人员以及与其他预案的衔接关系发生较大变化的；
** 应急预案依据的法律、法规、规章发生较大变化的；
** 应急预案中涉及的重大危险源情况发生变化的；
** 新建、改建、扩建工程项目完工后；
** 应急预案演练或响应评估报告要求修订的；
** 应急预案制定部门或单位认为应当修订的。
相关单位人员发生变化，要及时更新通讯录。
* 应急预案的评审
预案编制单位、管理部门依据国家安监总局《生产经营单位生产安全事故应急预案评审指南》等规定组织开展预案评审。
** 评审方法
应急预案评审采取形式评审和要素评审两种方法。形式评审主要用于应急预案备案时的评审，要素评审用于生产经营单位组织的应急预案评审工作。应急预案评审采用符合、基本符合、不符合三种意见进行判定。对于基本符合和不符合的项目，应给出具体修改意见或建议。
*** 形式评审。依据《导则》和有关行业规范，对应急预案的层次结构、内容格式、语言文字、附件项目以及编制程序等内容进行审查，重点审查应急预案的规范性和编制程序。应急预案形式评审的具体内容及要求，见附表1。
*** 要素评审。依据国家有关法律法规、《导则》和有关行业规范，从合法性、完整性、针对性、实用性、科学性、操作性和衔接性等方面对应急预案进行评审。为细化评审，采用列表方式分别对应急预案的要素进行评审。评审时，将应急预案的要素内容与评审表中所列要素的内容进行对照，判断是否符合有关要求，指出存在问题及不足。应急预案要素分为关键要素和一般要素。应急预案要素评审的具体内容及要求，见附表2、附表3、附表4、附表5。
关键要素是指应急预案构成要素中必须规范的内容。这些要素涉及生产经营单位日常应急管理及应急救援的关键环节，具体包括危险源辨识与风险分析、组织机构及职责、信息报告与处置和应急响应程序与处置技术等要素。关键要素必须符合生产经营单位实际和有关规定要求。
一般要素是指应急预案构成要素中可简写或省略的内容。这些要素不涉及生产经营单位日常应急管理及应急救援的关键环节，具体包括应急预案中的编制目的、编制依据、适用范围、工作原则、单位概况等要素。
** 评审程序
*** 各生产经营单位应急预案由安全副职和总工程师主持内部评审，分管副总工程师、预案编写人员和预案涉及部门人员参加。安全副职重点从程序、内容上审查，总工程师重点从技术上把关。必要时向上级应急管理机构提出申请，组织相关应急管理人员参加。
*** 内审完毕按专业对口报各上级安全专委会组织外审。各安全专委会要组织应急管理、安全技术等方面专家参加评审。评审结束要形成书面评审意见，经评审人员签字后反馈预案编制单位修改、补充。预案完善符合要求的，由生产经营单位主要负责人签发。
*** 集团公司应急预案由各安全专委会分系统组织专业评审，由应急救援专委会组织综合评审。评审修改完毕报总经理签发。
*** 3月20日前完成预案评审。
** 评审要点
应急预案评审坚持实事求是工作原则，结合实际，按照《导则》和有关行业规范，从以下七个方面进行评审。
*** 合法性。符合上级规定要求。
*** 完整性。具备《导则》所规定的各项要素。
*** 针对性。紧密结合本单位危险源辨识与风险分析。
*** 实用性。切合本单位工作实际，与应急处置能力相适应。
*** 科学性。组织体系、信息报送和处置方案等内容科学合理。
*** 操作性。应急响应程序和保障措施等内容切实可行。
*** 衔接性。综合、专项应急预案和现场处置方案形成体系，并与相关部门或单位应急预案相互衔接。
** 应急预案的备案
应急预案实行分级备案制度。集团公司级预案修订完毕，由应急办报省安监局备案。各二级单位将审定后的应急预案报集团公司应急指挥中心、应急办、专业救援队伍、对口专业部门备案。3月底前完成备案。
应急预案备案应当提交下列材料：
*** 填写并提交《生产经营单位应急预案备案申请表》；
*** 提交事故灾难应急预案评审报告；
*** 应急预案文本、相关图纸及电子文档各1份。
* 应急预案培训、演练
** 每年要对本单位应急预案管理情况进行总结，一月份报上级应急管理部门。
** 预案培训。将各类应急预案有关内容列入每年应急知识宣教培训计划，开展经常性的宣教培训，使员工熟知应急职责、程序和措施。
** 成立应急演习指挥策划小组，根据选定的演习类型制定应急预案演习方案，演习方案包括下列事项：确定演习时间、目标和演习范围，演习方式，确定演习现场规则，指定演习效果评价人员，安排相关的后勤工作，编写书面报告，演习人员进行自我评估，针对不足及时制定改正措施并确保实施。
** 按要求必须3年内完成所有综合应急救援预案和专项应急救援预案演练，至少每半年组织1次生产安全事故应急救援预案演练。
* 应急预案编制格式和要求
** 封面 ：应急预案封面主要包括应急预案编号、应急预案版本号、生产经营单位名称、应急预案名称、编制单位名称、颁布日期等内容。
** 批准页 ：
*** 对应急预案实施提出具体要求。
*** 发布单位主要负责人签字或单位盖章。
** 目录 ：应急预案应设置目录，页码标注准确（预案简单时目录可省略），层次清晰，编号和标题编排合理。
** 评审页：编制单位、评审单位要标明，评审组长、评审人员、编制人员要签字。评审意见附后。
** 印刷与装订 ：应急预案采用A4版面印刷，活页装订。
