:PROPERTIES:
:ID:       9544184f-925f-44d3-959b-16ecdd0d2f99
:END:
#+title: 事故现场处置管理制度
* 基本要求
** 成立事故应急工作领导小组
组  长：矿长
副组长：副矿长
成  员：各队组负责人
应急电话：
** 应急救援工作原则
*** 全面履行安全生产值班工作制度。日常三级管理、矿主管领导和科室两级管理，必须建立和坚持值班工作制度，一旦出现安全生产和应急事故，各级值班工作人员必须在第一时间赶到事发现场，与盯守现场的生产人员、管理人员一同做好应急处置工作。
*** 应急处置统一指挥原则。事故应急工作领导小组各成员必须接受指挥部统一指挥、统一安排，根据应急救援预案的要求，积极参加各类事故的应急处置。
*** 相互补位、自动递补的行动原则。工作小组领导不在岗时，第一成员自动递补，各类事故由相应管理人员主要承担应急工作的领导职责。
*** 应急响应、自动停休原则。事故发生，应急工作领导小组各成员休假的一律停止休假，主动到上级参加应急工作。在家倒班休息的，无论昼夜和疲劳程度如何，必须赶到队组待命或投入救援工作当中。
*** 应急救援坚持奉公尽责原则。事故一旦发生，应急工作领导小组各成员要尽职尽责、拒绝冷漠、传递温暖、无私奉献，不能麻痹大意，全心全意做好应急救援处置工作。
** 适用范围
发生安全生产一般事故及以上安全生产事故时，必须启动安全生产事故应急处置机制。
** 应急处置措施
结合矿企业安全生产实际，制订各类突发伤亡事件和重特大事故应急处置措施和预案，明确组织领导、部门职责、资源调配和使用、处置责任，确保矿井一旦发生生产安全事故时，能够迅速、有效组织协调有关部门人员，依法妥善处置。
** 生产安全事故报告
矿井一旦发生重大安全事故后，企业负责人必须按规定时间、程序、内容向上级主管部门如实汇报。
** 处置流程
*** 启动预案：突发重大生产安全事故发生后，最先接报的部门或人员要第一时间向事故应急工作领导小组报告，工作领导小组立即通过各种途径核实事件性质、伤亡情况、事故地点、事故发生的时间等信息，并迅速召集工作小组所有成员，通报事故现场情况，认真分析、研究、评估事故危害程度，立即启动应急救援预案。
*** 先期处置：应急预案启动后，要迅速派有关人员赶赴现场，会同有关车间、科室、队组人员，全面核查、查实事件性质、发生时间、发生原因、涉及范围、人员损失等基本情况后，及时向工作领导小组报告。根据预案要求做好现场救援工作，尤其做好现场人员的自救、互救和现场急救工作，尽可能消灭初期灾害事故，降低造成的损失。
*** 信息发布：救援工作领导小组根据事态情况，通过电话发布事件信息，向上级组织和主管部门进行汇报。
*** 现场处置：救援处置人员到达现场后，要协调有关部门及时采取控制、救援、保全等措施，防止事态扩大或次生事故的发生，并安排专人对事故伤亡人员进行登记，包括姓名、年龄、工作地点、家庭地址、联系电话等。
*** 善后处理：应急抢险救援行动结束后，由救援指挥部下达解除应急救援的命令，按照预案要求组建事故善后处理领导小组，并分设以下四个组按职责分工开展工作：事故调查组：负责协调有关部门开展事故调查；事故善后处理组：负责事故伤员转院和赔付处理；接待工作组：负责事故伤、亡人员亲属的接待，安抚工作；事故经费保障组：负责事故应急抢救和善后相关费用的经费保障工作。
* 矿井主要灾害事故应急救援程序要点
根据矿山事故及事故抢险工作的特点，做好以下几种危害性较大的事故的应急处理工作。
** 矿山冒顶事故的应急处理
冒顶事故是矿井中最常见、最容易发生的事故，冒顶事故应急处理要点如下：
*** 发生冒顶事故以后，抢救人员首先应以呼喊、敲打、使用地音探听器等与遇险人员联络，来确定遇险人员的位置和人数。
*** 如果遇险人员所在地点通风不好，必须设法加强通风。若因冒顶遇险人员被堵在里面，应利用压风管、水管及开掘巷道、打钻孔等方法，向遇险人员输送新鲜空气、饮料和食物。
*** 在抢救中，必须时刻注意救护人员的安全。如果觉察到有再次冒顶危险时，首先应加强支护，有准备地做好安全退路。在冒落区工作时，要派专人观察周围顶板变化。
*** 在清除冒落岩石时，要小心地使用工具，以免伤害遇险人员。在处理时，应根据冒顶事故的范围大小、地压情况等，采取不同的抢救方法。
*** 顶板冒落范围不大时，如果遇险人员被大块岩石压住，可采用千斤顶等工具把其顶起，将人迅速救出。
*** 顶板沿煤壁冒落、矸石块度比较破碎、遇险人员又靠近煤壁位置时，可采用沿煤壁由冒顶区从外向里掏小洞，架设梯形棚子维护顶板，边支护边掏洞，直到把人救出。
*** 较大范围顶板冒落，把人堵在巷道中，也可采用另开巷道的方法绕过冒落区将人救出。
** 瓦斯爆炸事故的应急处理
瓦斯爆炸表现为在极短时间内大量瓦斯被氧化，造成热量积聚，在爆源处形成高温、高压，然后急剧向外扩散，产生巨大的冲击波和声响。瓦斯爆炸是煤矿事故中破坏力最大的事故之一。瓦斯爆炸事故应急处理程序的要点如下。
*** 以抢救遇险人员为主，必须做到“有巷必有人”，本着“先活者后死者、先重伤后轻伤、先易后难”的原则进行救援。
*** 在进入灾区侦察时要带有干粉灭火器材，发现火源及时扑灭。确认灾区没有火源不会引起再次爆炸时，即可对灾区巷道进行通风。
*** 应尽快恢复原有的通风系统，加大风量，排除瓦斯爆炸后产生的烟雾和有毒有害气体。迅速排除这些气体，既有利于抢救遇险人员，减轻遇险人员的中毒程度，又可以消除对井下其他人员的威胁。
*** 清除巷道堵塞物，以便于救人。
*** 寻找火源，扑灭爆炸引起的火灾。
*** 做好灾区侦察、寻找爆炸点、灾区封闭等工作。
*** 救护队在处理瓦斯爆炸事故时应注意的问题：
- 问清事故性质、原因、发生地点及出现的其他情况；
- 切断通往灾区的电源；
- 进入灾区时须首先认真检查各气体成分，待不再有爆炸危险时，再进入灾区作业；
- 侦察时发现明火或其他可燃物引燃时，应千方百计立即扑灭，以防二次爆炸；
- 有明火存在时，救护队员的行动要轻，以免扬起煤尘，发生煤尘爆炸；
- 救护队员穿过支架破坏地区或冒落堵塞地区时，应架设临时支护，以保证队员在这些地点的往返安全。
** 煤尘爆炸事故的应急处理
煤炭粉末悬浮于空气中遇高温迅速被干馏而产生可燃气体，这些气体与空气混合而燃烧并放出大量热量，传给附近悬浮的煤尘使燃烧循环下去以致形成煤尘爆炸。发生煤尘爆炸事故应急救援程序的要点：
*** 发生煤尘爆炸事故时，首先由发现人利用附近电话汇报上级，说明灾害地点、性质、范围及波及面。同时设法通知灾区回风侧人员由基层管理人员带领，按规定的避灾路线退到新鲜风流地点待命或撤出矿井。
*** 此时所有人员都应戴上自救器。如果估计在自救器的有效使用时间内撤不出灾区时，应利用现场一切可用的材料构筑临时避难硐室，等待救护队抢救。为了避免冲击波的伤害，发生事故时要背向冲击波方向，用湿毛巾保护面部和口鼻，躺在水沟的一侧。
*** 矿调度室接到事故报告后应按应急计划通知有关领导及矿山救护队，立即组织抢救。
*** 应急指挥部应迅速查清灾害地点、性质、遇难人数、位置、通风设施等的破坏程度，并制定出救灾实施方案，保持与救护队不间断地联系。
*** 救护队长应根据救灾方案安排行动计划。指挥部还应及时命令后勤部门准备救灾物资和设备，做好下井人数的统计工作，组织好医务、家属及治安等项工作。
*** 灾区救护人员应注意的是，集中力量抢救遇险人员，应多带自救器或备用呼吸器，以保证遇险者安全脱险，立即切断灾区电源，注意停电操作应由灾区以外配电点进行，以防断电火花引爆煤尘或瓦斯，对灾区进行全面侦察，发现火源立即扑灭，防止二次爆炸。
*** 恢复通风，清除堵塞物，迅速排除有害气体。
** 井下火灾事故的应急处理
根据热源不同，矿内火灾可分为两大类：一是外因火灾，是由外来热源引起的；另一类是内因火灾，是矿物等可燃物本身受到某些化学或物理作用引起的。处理井下火灾的程序的要点为：
*** 通风方法的正确与否对灭火工作的效果好坏起着决定性的作用。火灾时常用的通风方法有正常通风、增减风量、反风、风流短路、隔绝风流、停止风机运转等。不论何种通风方法，都必须满足：
- 不使瓦斯聚积，矿尘飞扬，造成爆炸；
- 不危及井下人员的安全；
- 不使火源蔓延到瓦斯聚积的地域，也不使超限的瓦斯通过火源；
- 有助于阻止火灾扩大，压制火势，创造接近火源的条件；
- 防止再生火源的发生和火烟的逆退；
- 防止火风压的形成，造成风流逆转。
*** 为接近火源，救人灭火，应及时把弥漫井巷的火烟排除。
*** 扑灭井下火灾的方法有直接灭火法(用水灭火、惰气灭火、泡沫灭火等)、隔绝灭火法(封闭火区)、综合灭火法(注泥和注砂、均压、分段启封直接灭火等)。
*** 用水灭火最方便有效。要求有充足的水量，保证不间断供给；有正常的通风，使火烟和水汽顺利排出；灭火时应由火源边缘逐渐向中心喷射，以防产生大量水蒸气而爆炸；要经常检查火区附近的瓦斯，防止引发爆炸。
*** 惰气灭火是把不参与燃烧反应的窒息性气体，利用一定的动力送入火区，使火区的氧量降到抑燃值以下，从而抑制可燃物的燃烧和爆炸。最常用的惰性气体是氮气。当不能接近火源或用其他方法直接灭火具有很大危险或不能获得应有效果时可用惰气灭火。
*** 高倍数泡沫能隔绝火源并覆盖燃烧物，产生水蒸气而大量吸热，阻止火场的热传导、热对流和热辐射的作用，其灭火威力大，速度快，因而也被广泛应用于扑灭井下火灾。
*** 隔绝灭火法是在通向火区的巷道中构筑密闭墙，断绝火区的供氧源，使火区中的氧含量逐渐减少，二氧化碳含量逐渐增高，使火灾自行熄灭的方法。这种方法适用于难以接近火源，不能直接灭火或直接灭火无效时。采用隔绝法灭火的密闭材料，取材广泛，易于就地解决，便于建造也便于启封。
*** 注浆防灭火是一种较简单的综合灭火方法。它是利用地面和井下的高差产生的压力，加上泥浆本身的压力，把事先搅拌好的泥浆注入火区，以达到灭火的目的。注浆灭火兼有直接灭火和隔绝灭火的优点，且取材方便，经济有效，因而在矿井中被普遍应用。
*** 均压通风防灭火是通过改变通风系统的压力分布，降低漏风风路两端的风压差以减少漏风，通过降低火区供氧量来加速火灾的熄灭。均压通风防灭火适用于火源位置不明确，人员难以接近，采用直接灭火或隔绝灭火都较困难的场合。
*** 分段启封直接灭火是救护队经常采用的灭火方法。当火源范围大，蔓延速度快而被封闭了的火区火势减弱之后，可采用逐段启封直接灭火的方法。
** 井下水灾事故的应急处理
当矿井水的水量超过矿井排水能力或发生井下突然涌水时，会造成水灾，轻者局部巷道被淹，重者全井充水，矿毁人亡。矿井发生水灾后，常常有人被困在井下等待救助，这是救护工作的重点对象。井下水灾应急处理的一般程序要点是：
*** 必须了解突水的地点、性质，估计突出水量，静止水位，突水后涌水量，影响范围，补给水源及有影响的地面水体。
*** 掌握灾区范围、事故前人员分布，矿井中有生存条件的地点，进入该地点的可能通道，以便迅速组织抢救。
*** 按积水量、涌水量组织强排水，同时堵塞地面补给水源。
*** 加强排水和抢救中的通风，切断灾区电源，防止将空区积聚的瓦斯引爆或突然涌出其他区域。
*** 排水后侦察、抢险中，要防止冒顶、掉底和二次突水。
*** 搬运和抢救遇险者，要防止突然改变伤员已适应的环境和生存条件，造成不应有的伤亡。
*** 抢救长期被困在井下的遇险人员时应注意：发现遇险人员时，严禁用头灯光束直射其眼睛，以免在强光刺射下瞳孔急剧收缩，造成眼目失明。正确的方法是用衣片等罩住头灯，使光线减弱，或蒙住遇险人员眼睛，待瞳孔逐渐收缩直至恢复正常时，才可以见到强光。发现遇险人员时，不可立即抬运出井，应注意保护体温。应在井下安全地点进行初步处置(如包扎、输液、注射等)并待其情绪稳定以后，才送到医院进行特别护理。在治疗初期，避免亲友探视，以防过度兴奋影响遇险人员的健康或造成死亡。遇险人员长期不进食，消化系统功能极度减弱，急需补充营养，应以少量多餐的方法，以稀软的、高营养、高蛋白的食物为宜。
