:PROPERTIES:
:ID:       1ca779b8-adc4-44ff-b4cb-60a8bc7e750e
:END:
#+title: 爆破工安全操作规程
* 上岗条件
* 爆破工必须通过培训考试合格，方能持特种作业操作证上岗。
* 领退雷管炸药的规定
** 必须按规定，持符合要求的手续到炸药库领、退雷管、炸药。在同一工作面不准使用不同型号的雷管。
** 运送途中“七不准”：
*** 不准将雷管炸药混装（或混拿）；雷管与炸药应分别用非金属器盛装。
*** 不准随身携带雷管、炸药去乘坐乘人器或坐矿车。
*** 不准在上下班人流高峰时运送雷管、炸药。
*** 不准将雷管、炸药放在刮板输送机、皮带机上传送。
*** 不准将雷管交非放炮人员代运、代拿。
*** 运送雷管、炸药人员不准与旁人打闹、嬉戏。
*** 不准在途中逗留。
** 运到工作地点附近，应将雷管炸药放在无垮塌、碰撞、挤压以及无电缆、金属物（防杂散电流）的安全、通风、干燥处，并分别入箱上锁，专人看守。
** 当班未用完的以及失效的雷管、炸药，应全部退交库房，不准随身携带回家、更不准私自借用或隐藏在库房以外的任何地方；失效的雷管炸药严禁私自处理。
* 装配引药
*** 装配引药必须在离工作面30米以外、顶板完好、支架完整、通风干燥、避开电器设备、导电体和放炮地点的安全地点进行。
*** 装配引药的数量以当班用完为准，不得多做。
*** 先检查炸药，如含水量超过0.5%或硬化成块，手捏不散的，不能用。用细木棍在符合要求的炸药一端扎一小孔，然后将雷管轻轻全部送入孔中，不准用雷管代替木棍扎孔，不准斜插或裸露部分在药卷外，不准在药卷中腰部扎眼，不准将雷管捆在药卷外面，装好后将雷管脚线轻轻缠绕在药卷外，并将脚线端头短路扭结。
*** 从成捆的雷管中抽取单个雷管时，应先将脚线打散、理顺，然后手持雷管体依次轻轻抽出，严禁手拉脚线硬拽管体；也严禁手拉管体硬拽脚线，防止折断雷管脚线和损坏其绝缘层。
* 装药
** 不准边打眼边装药，待工作面人员全部撤退后才能装药。
** 先用挖耳掏尽或用扫眼器吹出炮眼中的煤（岩）粉，待检查瓦斯后，再用木棍将炸药轻轻推入炮眼，不准不掏粉末，严禁用金属物硬顶、捣实。使用扫眼器吹出炮眼中的煤（岩）粉时，人员应避开被吹炮眼。
** 炮眼内药卷与药卷之间必须紧密接触。
** 装药时，要将雷管脚线悬空而扭接短路，严禁脚线触及电缆或金属物体。
** 炸药装好后，再装水炮泥，最后封粘土炮泥，严禁用煤粉、浮渣、块状材料或其他可燃性材料代替粘土炮泥，无封泥、封泥不足或不实的炮眼严禁放炮。封炮泥的长度应符合下列要求：
*** 炮眼深度小于0.6米，不得装药放炮。
*** 炮眼深度在0.6～1.0米时，封泥长度不得小于眼深度的1/2。
*** 炮眼深度在1米以上，封泥长度不小于0.5米。
*** 炮眼深度超过2.5m时，封泥长度不得小于1米。
*** 深孔爆破时，封泥长度不小于孔深的1/3。
*** 工作面有两个或两个以上的自由面时，在煤层中的最小抵抗线不得小于0.5米，在岩层中  的最小抵抗线不得小于0.3米，浅眼装药爆破大岩块时，最小抵抗线和封泥长度都不得小于0.3米。
*** 严禁放糊炮。
* 放炮
** 放炮前要把放炮地点的设备、支护材料、电缆等搬开或作妥善的遮掩，使之不被破坏。再次检查瓦斯符合要求后，瓦检员将发爆器（处于非工作状态）的钥匙带在身上，不准交给他人。
** 班组长安排专人在能进入放炮地点的所有通路上布置好警戒点，设置警戒标识，警戒人员必须忠于职守，未接到放炮结束的通知，不得擅离警戒点或打瞌睡。
** 临时铺设带绝缘的放炮母线应远离电缆和金属导电物。不准使用固定母线，严禁用电缆、钢轨、刮板输送机或大地作回路。特殊情况下，在采取安全措施后，可使用固定母线。
** 将放炮母线端头扭结短路后，分别连上需要放炮的各炮眼的雷管脚线，接头必须悬空，再由爆破工逐个检查一次联通情况，保证接触良好、导通，爆破工要最后离开放炮地点。
** 一切就绪后，由班（组）长清点人数，待全部人员搬离至安全距离，经班（组）长、瓦检员、爆破工三方确认清点无误后（直线100米以外，曲线80米以外），由班（组）长向爆破工和警戒人员发出明显的放炮信号。爆破工将母线联在发爆器桩头上，发动发爆器，检查导通情况，再等待10秒钟后，并分3次提醒现场人员“放炮啦”，才用钥匙旋转发爆器放炮。严禁不清点人数放炮；严禁边撤人边连接母线在发爆器上；严禁不用钥匙，以其他物件拨弄发爆器（除操作放炮外，不准将钥匙留在发爆器匙孔中）；严禁用发爆器以外的任何电源放炮。
** 当班装的炮眼，应当班放完。如放不完，应由班（组）长和爆破工向下一班的班（组）长和爆破工现场逐一交代。
** 操作发爆器后，炮不响，可再发动发爆器，如再不响，爆破工应将钥匙取下，从发爆器桩头解下放炮母线，将其短路联接，再等15min后，才能沿母线查找原因。
** 放炮后，爆破工和班（组）长会同瓦检员进入放炮作业点，检查通风、瓦斯、煤尘、顶板、支架、瞎炮、残爆等情况，如有危险，必须立即处理（如及时恢复放炮崩倒的支柱等）。
** 工作面放炮后15min以上，待炮烟吹散、隐患排除后，才能由布置警戒的班（组）长下达撤回通知，作业人员方可进入工作面工作。
* 瞎炮和残爆的处理
** 处理瞎炮和残爆必须在班（组）长直接指导下进行，并应在当班处理完毕。如果当班未能处理完毕，爆破工必须同下一班的班（组）长．爆破工在现场交接清楚。
** 由于连接线不良的瞎炮，可以重新连线放炮。
** 在距瞎炮至少0.3米处另打同瞎炮眼（残爆眼）平行的新炮眼，重新装药放炮。
** 严禁用工具挖、刨或从炮眼中取出原放置的引药，或从引药中拉出电雷管；严禁将炮眼残底（无论有无残余炸药）加深；严禁用打眼的方法往外掏药；严禁用压缩空气吹这些炮眼。
** 处理瞎炮的炮眼爆炸后，爆破工必须详细检查，从炸落的煤矸中收集未爆的雷管。
** 在瞎炮处理完毕以前，严禁在该地段从事与处理瞎炮无关的作业。
* 放炮“五不准”
** 掘进工作面的支护不符合作业规程的规定不准放炮。
** 放炮地点附近20米内，风流中瓦斯浓度达到1%及以上时，不准装药，不准放炮。
** 在放炮地点20米以内，有未清除的煤、矸、矿车或其他物体阻塞巷道断面的三分之一时，不准装药、不准放炮。
** 炮眼内发现异状、温度骤高骤低、有显著瓦斯涌出、煤岩松散、透水、透老空等现象时，凡有上述情形之一者，必须立即报告班（组）长，逐级上报，及时处理，未处理前停止作业，不准装药，不准放炮。
** 无发爆器不准放炮，发爆器无钥匙不准放炮。
