:PROPERTIES:
:ID:       818418b9-a919-404e-a330-c73b79bb174e
:END:
#+title: 顶板管理制度
* 目的
** 杜绝顶板事故和未遂事件。
** 矿井安全生产标准化等级达到一级。
** 提升各类巷道和工作面矿压监测手段，抓好矿压监测、数据分析和应用。
** 开展好掘进及回采巷道支护状况和顶板管理资料的建档工作。
** 积极开展职工现场操作技能培训，进一步提高顶板管理水平。
* 组织机构及职责
** 为确保本规定的严格执行，矿成立顶板管理领导组，负责组织、协调顶板管理的各项工作，检查、落实、考核本规定的执行情况。
组  长：矿 长
副组长：总工程师 安全副矿长 生产副矿长 机电副矿长
成  员：各专业副总工程师 生产技术科科长 安全科科长 通风科科长 物资供应科科长 机运科科长 人力资源科科长 矿调度室主任  队长
领导组下设日常管理办公室，办公室设在生产技术科，负责顶板管理的具体事宜。
** 生产技术科负责巷道支护设计及顶板支护管理工作，负责采掘工作面地质构造的预测预报、探放水及顶板岩性鉴定工作。
** 生产技术科、安全科负责井下巷道支护及矿压的监督管理，同时，贯彻执行矿和上级主管部门有关巷道支护设计、规定，并结合矿实际，指导施工巷道各类作业规程、补充措施的编制工作，监督检查其执行情况，协调解决执行中的支护问题。
** 安全科、通风科、队长负责无人区巷道的支护、变形等情况的检查汇报。
** 安全科负责监督检查顶板管理措施的贯彻执行，并组织各职能部门每月进行一次专项检查，对顶板事故进行分析和责任认定。
* 顶板管理一般规定
** 生产技术科、安全科及队长在巷道支护设计时应采用工程类比法。首先根据相邻巷道的情况、巷道的断面以及服务时间等进行设计，然后根据相关设计进行施工。在施工中观测巷道的变形情况、进行巷道的围岩稳定性分类、探测巷道顶板的分层情况等，根据观测情况及时进行修改设计。
** 加强雨季期间和采、掘工作面地质构造期间构造带的顶板监测和管理。队组要及时制定相关措施报矿审批，安全科负责监督落实。
** 安全科每月牵头组织一次对井下所有巷道、采掘工作面顶板管理、工程质量安全大检查，对检查过程中查出的问题进行考核、通报，并监督队组落实到位。每旬至少组织进行一次对井下所有作业地点进行隐患排查，对顶板管理存在严重隐患的地点，要在醒目位置悬挂警示牌板；在未采取有效措施前，不允许人员通行或在附近区域作业。
** 安全科、生产技术科要组织队组对存在严重安全隐患的地点进行研究分析，制定预防顶板事故发生的安全技术措施，并责成队组进行处理。
** 各队长井下各作业地点的队长是队组顶板管理第一责任者。跟班队长、班长、安全员负责当班顶板管理方面的安全隐患排查，发现顶板事故隐患，必须立即采取相应措施，预防事态扩大，并及时向相关负责人汇报。出现顶板事故预兆时，要及时发出预警信号，并组织现场人员撤离。
** 井下采掘修工作面要配备足够数量的支护器材，包括单体液压单体柱、坑木、锚杆、锚索、钢带、垫片、工字钢、金属网等。同时配备一定数量的铁锹、镐、大锤、撬棍等救援工具，以备应急救援之用。
** 试验涉及安全生产的新技术、新工艺必须经过论证并制定安全措施；新设备、新材料必须经过安全性能检验，取得产品工业性试验安全标志。
** 对专用回风巷道支护质量的检查必须两人以上，并且事先联系好通风科，由瓦检员陪同。
* 顶板管理的具体内容及要求
** 提高认识，加强对顶板管理的组织领导和实施
*** 高度重视顶板管理工作，摆正生产与顶板管理的关系。各队组要进一步落实顶板管理责任，完善规章制度，把责任落实到个人。
*** 要正确对待随着矿井开采深度的不断延深，顶板条件的日趋恶化的现状，切实加强现场管理。同时，各队组要结合现场工作的实际情况，针对性地将顶板管理和预防措施细化、量化到每一个环节，相应制定出顶板管理和预防措施，定人员、定时间、定资金、定责任。
*** 队组要加强井下顶板动态观测，各业务科室加强动态监督检查，严格落实整改、严格考核。
** 加强生产技术的动态管理，完善有关规章制度和规程措施，严格现场兑现，提高支护设计和规程措施的严密性和可操作性，科学地指导生产。
*** 各业务科室要对采、掘、修作业规程 (安全技术措施 )进行严格审查，重点对顶板管理部分进行审查 ，进一步完善规程(措施)中的有关内容，做到规程严密，措施得当。
*** 采掘工作面遇有特殊地质构造，必须重新修订作业规程或补充完善措施，及时改变和加强支护。
*** 巷道采用锚网(锚喷)支护，要依据巷道围岩强度、地应力、松动圈等测定结果，进行严密的支护设计。并结合生产实践，做好支护设计的补充和完善，确保锚杆支护技术得以安全可靠的应用。
*** 队组要搞好日常的顶板监测和预报，建立健全矿压观测资料，做到记录齐全可靠，分析及时准确，从技术上加强对顶板管理的指导。
*** 队组要对矿井的各类巷道进行普查，实行建档管理，并根据巷道的使用情况、失修情况等进行分类，对影响安全生产，急需修复的巷道，要尽快制定修巷措施及时安排修复。特别要加强对系统巷道和盲区巷道的日常管理和修复。
*** 物资供应科加强对各种新购、修复和加工改造的支护材料的管理，完善管理制度和检测手段，加大入井支护用品的检查验收力度，不符合要求的不许下井使用。
*** 加强工作面端头（尾）空档顶板管理，补充完善机头尾顶板管理措施，使用好端头支架，使端头支护方案更严密、更可靠。
*** 积极开展科技攻关技术研究，进一步提高顶板管理水平，消除顶板管理方面的安全隐患，促进安全生产。
** 加强现场支护监测管理，完善各类顶板管理手段，推广应用智能化监控系统
*** 回采工作面必须安设智能化矿压观测仪器进行顶板动态连续监测，并要有矿压观测记录和分析预报，月终要有分析报告，从技术上加强对顶板管理的指导。
*** 回采工作面要加强两端头、三角区及超前支护段的顶板管理。端头管理要符合作业规程要求，高度达标，清洁整齐，安全畅通，三角区管理要严密接顶，有效控制，超前段严禁出现断梁折柱，单体柱要编号管理，并有压力测定和防倒措施。
*** 回采工作面的液压支架倾斜等要提前预防，防止倒架。乳化液配比达到要求，确保浓度达标，液压系统无“跑、冒、滴、漏”与自动卸载现象，确保初撑力达要求。
*** 回采工作面采高和三直一平达规定要求，单体柱接顶严密，人员进入机道防范措施落实到位。
*** 回采工作面安装、初采、收尾、回收，掘进开口、贯通及遇地质构造时，要制定严密的顶板管理措施，安全科负责监督落实。
*** 掘进工作面要使用好临时支护、及时进行永久支护，严禁空顶作业，防止空顶时间长造成顶板离层致使支护失效或压力超前传递影响其他巷道。
*** 加强锚网(索)支护管理，建立完善锚杆材料检查手段，积极推进锚杆规范化和系列化工作，重点要解决锚杆预紧力和锚杆角度方面存在的问题，确保支护安全，对所有锚网(索)巷道必须按规定进行锚杆抽检和矿压观测。
*** 采掘工作面以及巷修和回撤巷道中架设与回收各类支护时，必须制定有严密的安全技术措施，并严格遵照执行。
*** 突出重点地段、时段的现场顶板管理。做到安全技术措施严密合理，临时支护有效，安全防范到位，确保顶板安全。
** 强化职工现场操作技能培训，提高职工自觉管理顶板的能力
*** 要组织各队组以及职工进行顶板管理知识培训，重点培训、学习锚网支护技术理论、架棚支护技术理论、“煤矿安全规程”、“作业规程措施”和煤矿安全生产标准化基本要求及评分方法，并结合各岗位作业标准化标准，对职工进行全方位的理论培训，解决认识上存在的问题。
*** 队组要结合煤矿生产实际和安全生产标准化基本要求及评分方法，开展针对性的操作培训和竞赛。通过加强工作面标准化动态达标管理，树立“质量就是任务，上一循环为下一循环服务”的理念，全面实现动态达标。通过建立岗标和现场的配套应用机制，实现理论和实践的统一，提高职工的实践适应能力和管理顶板能力。
* 采掘工作面顶板管理规定
** 掘进工作面顶板管理
1.临时支护管理
（1）掘进工作面必须使用临时支护，严禁空顶作业。
（2）作业规程中必须对工作面控顶距做出明确规定。
（3）作业规程中必须对采用的临时支护方式、数量和操作要求做出明确规定。
2.掘进工作面顶板管理
（1）巷道的施工管理及工程质量验收和考核由安全科、生产技术科组织检查实施。每一条巷道施工完毕，必须组织验收，验收合格后才能准许掘进队将设备拆除倒装。对每一条巷道的施工情况及验收情况要有记录，并存档备案。
（2）巷道遇断层、陷落柱等地质构造及巷道开口、切巷刷大、整巷、扩巷、处理较大范围的冒顶以及其它特殊情况时，必须制定专项安全技术措施，并严格检查监督执行情况。
（3）“双锚”支护巷道，因地质构造、煤层松软等因素造成巷道规格超过规定，要对超宽、超高部分进行补强支护，并对高冒区用材料进行充填。
（4）巷道压力大，煤层松软、顶板破碎时，应及时编制加强支护措施，所有支护必须紧跟迎头。
3.锚杆、锚索支护巷道顶板管理
（1）螺母拧紧力矩不小于350N•m，顶锚杆锚固力不小于70kN，帮锚杆锚固力不小于50kN。
（2）锚杆（索）间排距误差不超过设计值的±100mm，锚杆外露长度为螺母往外10-100mm，锚索外露长度为150-250mm。
（3）锚杆（索）的托板必须紧贴岩面，锚杆与井巷轮廓线切线的角度不小于75°，锚索与井巷轮廓线切线的角度不小于80°。
（4）必须使用锚杆钻机、风动扳手、电动扳手等机械工具安装锚杆。
（5）锚杆锚固力每班必须检查，并留有详细记录；锚杆螺母必须使用气扳机或力矩扳手拧紧，保证力矩符合有关要求。
（6）锚杆支护巷道，掘出后，顶板有效支护距迎头最大空顶距不超过200mm，且临时支护的距离必须符合作业规程规定，空顶的时间不得超过1h。
（7）巷道交岔点优先选用锚索加强支护。
（8）锚索长度应根据巷道顶板岩层情况确定，使锚索锚固到稳定的岩层中，当稳定岩层与巷道顶板距离过大时，锚索长度应超过自然平衡拱2m以上，并满足锚固段长度不小于2m，自由段长度不小于3m，张拉端长度要保证张拉工艺要求的长度，一般不小于150mm。
（9）锚索各组件的材质和规格符合设计要求。托梁安设位置、方向符合设计要求，紧贴岩面。
4.架棚巷道顶板管理
（1）架设棚子前，当班跟班队长或班长必须指派有经验的工人按操作规程严格执行敲帮问顶制度，并有专人监护，将危岩活矸清理干净。
（2）放炮前，靠近掘进工作面10m范围内的支架必须加固。放炮后，必须先对放炮崩倒、崩坏的支架进行修复，修复支架时必须先检查顶、帮，并由外向里逐架进行；迎头作业时必须在可靠的超前支护或临时支护下作业。
（3）支架间必须用牢固的撑木或拉杆连接起来。支架必须使用支拉杆，并用机械力矩扳手拧紧卡缆，卡缆拧紧扭矩不得小于350N·m。支架和顶帮之间的空隙必须刹背接顶，并保证刹背严实。
（4）坚持对煤或松软围岩进行松帮卸压，减少支架变形，降低复修工程量，对确实需要修复的巷道，要及时编制措施进行修复。
5.过断层、裂隙带、石门揭煤和岩性突变地段巷道顶板管理
（1）必须加强掘进地段的地质调查工作，根据所掌握的地质资料，及时制定具体的施工方法和安全措施。
（2）在破碎带中掘进，必须一次成巷，尽可能缩短围岩暴露时间，减小顶板出露后的挠曲离层，提高顶板的稳定性。穿煤层或遇地质构造时，应采用架棚支护，并喷浆封闭。
（3）施工中要严格执行操作规程、交接班和安全检查制度。要经常观察围岩稳定状况的变化，一旦发现异常必须及时处理。
（4）掘进工作面临近断层或穿断层时，巷道支护应采用架棚加锚网喷或锚索的复合支护，并缩小棚距。
（5）采用小循环掘进，减小空顶距离，及时进行支护，永久支护紧必须跟工作面迎头。
（6）采用钻爆法破煤（岩）时，必须少打眼、少装药、放小炮，尽量保持围岩的稳定性。若放炮中顶板难以控制与管理，有冒顶危险，应改用手镐挖掘方法掘进。
（7）巷道支架背板要严实，提高支架对围岩的支护能力，防止掘进中漏顶或漏帮。
（8）在顶板岩性突变地段，要及时打点柱支护突变带顶板。对离层伞檐状围岩要及时敲掉并加强支护。
** 回采工作面顶板管理
*** 回采工作面端头支护和顺槽超前支护
（1）采煤工作面上下顺槽，必须保证规定的断面和高度，距工作面30m范围内必须加强支护，确保安全出口巷道高度必须达到1.8m以上。
（2）应经常检查采煤工作面上下端头的支护情况，支护方式、支护密度必须符合作业规程的规定，运输机机头部位必须采取加强支护措施，作业的方式方法必须在作业规程中明确规定。
（3）相邻采空区工作面或二次动压巷道靠采空区侧压力大且底软时，工作面超前支护距离必须达到100m以上，并应加大支护密度。具体支护的距离、形式、密度、柱鞋的种类及规格和材质等，必须在作业规程或专项措施中明确规定。
*** 回柱放顶
（1）加强回采工作面两端头回柱管理，特别是初采期间的回柱管理，确保落山顶板及时垮落。
（2）上、下端头必须按要求支设好密集柱和戗柱。
（3）回拆锚网必须在密集柱往外的空间内进行，严禁任何人员进入密集柱以里空顶区进行作业。回柱放顶工作不得与移转载机、推移机头机尾、拉移端头架平行作业。
（4）回拆锚杆卸压前，必须在所在锚杆退后200～300mm处，至少支设一根单体柱加强支护。
*** 初、末采顶板管理
（1）回采工作面初、末采必须制定专项安全技术措施，并明确顶板控制方法，加强顶板管理。初采期顶板垮落难度大的，要在切巷推进3m范围内采取强制放顶措施。
（2）工作面初采时，端头要加强支护，必要时在落山支设木垛、密集柱或戗棚。使用的单体柱必须完好，支设要迎山有力。
（3）初采阶段超前支护范围内不得有缺棚少柱现象，失效的支架要及时更换。
（4）末采工作面若有失效支柱等不安全隐患时，必须及时更换和处理。
（5）工作面初、末采若发生冒顶事故，必须制定专项安全技术措施，严格按规定进行顶板维护，严禁人员在无支护的空间下违章作业。
*** 工作面顶板管理
**** 回采工作面必须按作业规程规定及时支护，人员进入煤帮作业时，必须严格执行人员进入机道作业的安全技术措施。
**** 采煤工作面必须保证一定数量的备用支护材料，其数量、规格、存放地点和管理方法，必须在作业规程中明确规定。开工前班组长必须对工作面进行全面的检查，确认无危险后方可开工。严禁使用折损的坑木、损坏的金属顶梁、失效的摩擦支柱和失效的单体液压支柱，摩擦支柱和失效的单体住在入井前必须逐跟进行压力实验；摩擦支柱和失效的单体住在工作面回采结束后或使用时间超过8个月必须进行检修，检修后的支柱必须进行压力实验，经检验合格后方可投入使用。
**** 采煤工作面严禁空顶作业。所有支柱必须架设牢固，并有防倒柱措施，严禁在浮煤或浮矸上架设支柱。工作面的排柱距要在作业规程中明确规定，使用木支护工作面的坑木规格要在作业工程中明确规定，碰倒或损坏的支柱必须立即恢复或更换。单体液压支柱的初撑力，柱径100mm的不得小于11.5MPa。
**** 工作面柱、梁必须编号，不许缺梁少柱；外观缺损的柱、梁严禁使用。支护强度必须达到设计的支护强度要求。
**** 工作面安装结束，要经过职能部门组织的联合验收，验收合格后方可开始生产。
**** 工作面初采必须制定专项初采安全技术措施，矿上应成立专门机构，坚持跟班制度。在工作面初采措施中，对工作面初采领导小组、工作面初采期间的支护管理和加强支护的特殊支护措施等内容，必须做出具体规定。
**** 工作面初次来压前后，要有专人观测顶板压力变化情况，及时采取加固措施。
**** 回柱时若出现工作面大面积来压有推棚危险时，应立即停止工作并加强支护，情况紧急时立即撤出人员并向调度室和值班人员汇报。
**** 为保证支柱有足够的初撑力，泵站压力不能低于设计值，液压管路不能有窜、漏液现象。
**** 采煤工作面支架初撑力不能低于24MPa，采煤工作面超前支护单体支柱初撑力不能低于11.5MPa。生产期间要保证支柱稳固，坚持循环测压及循环注液制度。
**** 根据上下两巷顶板情况合理确定超前支护形式，并在作业规程中明确规定，巷道高宽尺寸规定：超前托棚30m范围内，巷道净高不低于2.0m，净宽不低于3.0m。两巷有片帮时，必须采取防片帮措施。
**** 工作面上、下安全出口必须设专人维护，保证支护安全可靠、行人畅通。安全出口高度不低于1.8m，人行道宽度不小于0.8m。
**** 工作面生产时要严格执行《采煤安全安全生产标准化标准及考核评级办法》，落实采煤工作面工程质量责任制，严格执行质量验收制度及敲帮问顶制度；分析支护质量存在问题，制定改进的具体措施。
**** 上下巷单体柱确需穿柱鞋时，柱鞋的规格、尺寸、材质等必须在作业规程中明确规定和说明。
**** 矿要建立采煤工作面顶板管理统计分析表和顶板事故档案，严格实行日常的事故分析制度。
**** 采煤工作面因片帮造成最大控顶距超过规定距离时要采取安全措施；倾角在25°以上的回采工作面要采取防止大面积顶板垮落的措施。
**** 要加强采煤工作面矿压观测工作。要通过矿压观测成果，对开采的煤层进行顶板分类，及时制定相应的顶板管理措施。
**** 回采工作面处理冒顶时，必须制定专项安全技术措施。工作面发生冒顶事故时，必须先停止生产，待顶板维护好后，方可恢复生产。处理过程中必须明确负责人，队长、跟班队长现场指挥，安全员现场监察，停电闭锁工作面刮板输送机，并确保退路畅通。
**** 回采工作面因故停产前，必须使采面支护满足最小控顶距要求。端面距超过规定时，要支设贴帮柱，停产期间安排专人巡回检查，发现顶板隐患及时处理。
* 井下敲帮问顶管理规定
（一）井下“敲帮问顶”领导小组
组  长：安全副矿长
副组长：生产副矿长 总工程师  机电副矿长
成  员：副总工程师 安全科科长 生产技术科科长 通风科科长 物资供应科科长 机运科科长 人力资源科科长 矿调度主任
领导组下设日常管理办公室，办公室设在安全科，负责日常“敲帮问顶”工作具体事宜。
（二）职责划分
1.矿领导职责
（1）生产副矿长负责矿范围内采煤、掘进、巷修工作面“敲帮问顶管理”工作，督促采煤、掘进、巷修工作面严格落实“敲帮问顶”制度。
（2）总工程师负责生产技术科、通风科及救护队井下作业地点作业过程中“敲帮问顶管理”工作，督促相关队组落实“敲帮问顶”制度的执行。
（3）机电副矿长负责机运科井下作业地点“敲帮问顶管理”工作，督促相关队组落实“敲帮问顶”制度的执行。
（4）安全副矿长对矿井下作业地点“敲帮问顶”管理工作负监督管理责任，组织各相关科室对“敲帮问顶”制度落实情况进行跟踪落实。
2.安全科职责
（1）每班队组分头面安排安全员对井下所有作业地点“敲帮问顶”工作进行监督落实。
（2）每旬由安全科科长统计汇报各队组“敲帮问顶”制度责任落实及处理情况。
（3）每月安全生产办公会由安全科统计通报各相关队组“敲帮问顶”制度落实及处理情况。
3.队组职责
（1）队组成立相应的“敲帮问顶”领导小组，划分职责，明确分工。
（2）各队组由队长总体负责“敲帮问顶”制度落实，每班设“敲帮问顶”负责人，具体负责落实小班“敲帮问顶”工作。
（3）队长每天对分管范围内作业地点“敲帮问顶”工作进行跟踪落实。
（三）井下作业地点“敲帮问顶”管理规定
1.工具加工要求：钎杆由φ20mm钢管或钢钎加工而成，一端为尖钎，另一端为扁钎。
2.每次进入作业点，开工前，班组长或安全负责人必须实施敲帮问顶,对工作面安全情况进行全面检查，确认无隐患后，方可允许作业人员进入工作面。敲帮问顶时，其他无关人员不得进入工作面。现场敲帮问顶工作由安全员进行督促检查。
3.采掘修工作面敲帮问顶工作由班队长负责或指派有经验的专人负责。
4.工作面必须备有敲帮问顶专用工具：采煤工作面上下端头，超前支护20米范围内必须始终有1.8m、2.5m的找顶钎杆各一棵；掘进工作面必须配备1.8m、2.5m专用找顶钎杆各一棵（设计巷道高度超过3.5m时必须配备不少于3m长的专用找顶钎杆），炮掘工作面摆放在距迎头不超过10m范围内（响炮时拿到后方的安全位置），综掘工作面专用找顶钎杆放置在迎头后20m范围内，不用时靠帮吊挂；巷修工作面，找顶钎杆（不小于1.5米及2.5m专用找顶钎杆各一棵）要始终放在施工现场5米范围内，不用时靠帮吊挂。
5.敲帮问顶时，工作面顶板出现离层、断裂，又不能立即挑下时，必须立即进行支护或采取临时支护的措施，临时支护必须牢固可靠。
6.掘进工作面，超前空顶距不超过《作业规程》规定。
7.掘进巷道在挖腿脚窝、支护棚梁、钢筋网及铺铁丝网等工作之前进行敲帮问顶；炮掘工作面打眼、放炮、清货前必须进行敲帮问顶，发现问题，及时处理，确认安全后再进行施工。
8.掘进工作人员必须经常认真检查工作地点的顶板、煤壁及两帮、支护情况等，当发现顶板和煤壁有松动时，必须立即采取措施进行处理。
9.敲帮问顶要求达到标准、清除顶帮伞檐及所有松动煤（岩）块，无煤（岩）块明显裂缝出现和煤（岩）层离层情况出现。
10.敲帮问顶工作必须在有可靠支护的条件下进行，禁止空顶作业。敲帮问顶时使用专用敲帮问顶工具操作。
11.如发现有活矸，应及时进行处理，如有冒顶危险，处理后方能继续进行工作。
12.采煤工作面顶板破碎、煤壁发生片帮时，先拉移超前支架，护好顶帮，停止工作面采煤机，运输机，再执行敲帮问顶制定。
13.采煤工作面上下端头作业、回柱前，必须先检查周围支架、顶板的完好情况，进行敲帮问顶。确认无隐患后，方可按回柱的程序和要求进行回柱作业。
14.巷修点的敲帮问顶：人员在施工过程中，必须始终坚持经常性敲帮问顶工作。
15.井下相关作业的队组以及井下其他工种、岗位的人员，都必须随时检查工作地点附近的围岩活动情况，发现问题，立即处理。有关敲帮问顶的基本知识，要求队组管理人员对全体职工进行讲解和培训。
16.在井下现场隐患排查记录本中，必须对敲帮问顶负责人、敲帮问顶情况进行详细记录。
（四）敲帮问顶方法
1.敲帮问顶工作应有两名有经验的人员担任，一人找顶、一人负责监护观察顶板和退路。敲帮问顶人员应站在安全地点，监护人应站在敲帮问顶人员的侧后面，并保证退路畅通。
2.敲帮问顶应从有完好支护的地点开始，由外向里先顶后帮，依次进行，敲帮问顶期间敲帮问顶范围内严禁其他人员进入，敲帮问顶人员严禁进入空顶区域。
3.敲帮问顶人员找顶时，要防止煤矸顺杆而下伤人。
4.顶帮遇有大块断裂煤矸或煤矸离层时，应首先设置临时支护，保证安全后再顺着裂隙、层理慢慢地找掉，不得硬刨强挖。
5.斜巷敲帮问顶时，敲帮问顶人员站在敲帮问顶位置上方顶板支护完好区域由上向下方向进行找顶，敲帮问顶位置下方严禁站人。
6.敲帮问顶后由当班安全负责人或安全员确认敲帮问顶区域安全可靠后，方可允许人员进入施工。
7.施工中发现帮顶有浮煤活矸时及时停止作业，撤出危险区域人员，进行敲帮问顶，敲帮问顶完毕确认安全后方可继续施工。
8.逆风敲帮问顶时，敲帮问顶人员必须佩戴防护眼镜。
（五）责任追究
各队组要高度重视，认真落实责任，矿生产技术科要常态进行效能监察，对在工作中严重渎职、失职而造成不良后果的队组和个人，将严肃追究责任。
* 矿压观测管理制度
（一）成立矿压观测领导小组
组  长：总工程师 生产副矿长
副组长：副总工程师
成  员：各队组队长及各队组采掘技术员
矿压观测办公室设在生产技术科，下分设各技术室为办公地点。
（二）职责划分
1.矿总工程师是矿压观测工作的技术管理负责人，负责矿压观测设计的审批，组织开展矿压观测技术分析，优化支护技术方案。
2.生产副矿长是矿压观测实施负责人，负责矿压观测设计及支护技术方案的落实。
3.副总工程师负责矿压观测设计的编制、审查及协助生产副矿长实施现场矿压观测，负责矿压观测信息的阅示、分析等日常管理工作，并提出整改意见。
4.各队组技术员负责日常管理，保证矿压观测正常运行，出现问题及时解决落实。
5.各队组采、掘技术员负责各系统的日常管理及矿压分析，对现场存在的问题及时通知队组，指导生产。
6.队组验收员负责真实、准确的采集矿压数据，及时交给队组技术员，对于现场存在问题及时汇报，积极组织整改。
（三）采煤工作面矿压观测
1.矿压观测方法
（1）观测仪器
①回采工作面支架安设工作阻力检测仪表，每1个支架安装一块支架工作阻力记录仪（1#、2#、3#、4#、……）。
②上、下端头及超前支护采用单体柱测压表
③上、下巷超前支护30m段每隔10米，其余地点每隔50m设置一个观测站，采用“十字”布点方法布置观测基点。
（2）观测项目
综采工作面支架初撑力、支架工作阻力、端面顶板冒落高度、遇构造情况、工作面煤壁片帮。
（3）观测方法
①观测方法从回采工作面开切眼推进开始至第一循环周期来压，每点班连续观测回采工作面矿压基本参数，以后每个圆班观测一次。
②上、下巷的观测方法与掘进工作面的矿压观测方法相同。
2.矿压观测分析报告编制
（1）矿压分析报告编制时间规定
回采工作面矿压观测分析报告每月编制一次，回采工作面回采结束后要对该工作面的矿压显现规律进行总结、存档。
（2）观测的目的、内容及方法
矿压分析报告包括矿压观测的主要任务、内容、采用的矿压观测仪器、测点及测站的布置、观测和记录的方法及日常数据整理方法等；分析回采工作面矿压显现规律，包括直接顶初次垮落步距、老顶初次来压步距、老顶周期来压步距和来压强度。
（3）采面地质及生产技术条件
①说明工作面的地质条件、煤层名称、采高、顶底板岩层组成、各层厚度、岩石强度、裂隙及构造发育程度、倾角、采深等。
②说明观测工作面的生产系统、开采要素、工作面周围的开采情况及与采空区的相对位置关系等。
③说明观测工作面支架型号及参数、支架规格及工作方式。
（4）观测结果分析
观测成果根据观测计划、观测工作组织与实施情况分析回采工作面的矿压显现规律。
（5）结论和建议
结论和建议的主要内容是：工作面矿压参数；回采工作面矿压规律；支架选型与参数的改进建议；对顶板控制的建议；以及其他需要说明的问题。
（四）掘进工作面矿压观测
矿压观测应从宏观和微观两方面收集矿压与支护的信息。
1.微观观测
（1）巷道表面位移量（底鼓量、顶板下沉量）、两帮移近量；
（2）锚杆（索）受力、支护受力。
2.宏观观测
（1）围岩状态：包括围岩岩性、稳定性类别、层位、淋水、地质构造、动压影响等；
（2）巷道支护状况：巷道支护的变形、支护参数等；
（3）工程质量状况。
3.矿压观测规定
（1）新掘巷道至迎头200m重点观测；
（2）巷道开掘至竣工的观测按照规定时间观测；
（3）正常服务巷道抽点观测；
（4）受动压巷道在动压结束三个月内重点观测。
4.观测点布置方法
（1）均点布置与随机布置相结合
（2）均点布点：每隔50m设置一个观测点，观测点距离迎头不大于50m。
（3）随机布点：巷道条件发生变化如支护参数、支护形式、围岩条件、遇构造地带、淋水等特殊地段必须随机增加观测点或加大布点密度。
5.观测点设置方法
（1）煤巷锚杆支护可安设顶板离层仪；
（2）可采用“十字”布点方法，在围岩的表面钻孔，孔内打设木桩，安设测钉，作为测量基点。
（3）观测时间
①新掘巷道一个月内每2天观测一次；之后每7天观测一次。
②正常服务巷道每月观测一次；
③受采动影响巷道每2天观测一次。
（4）观测方法
①顶板离层仪和巷道表面位移同时布置（巷道每50m安装一组），安装地点附近安设一块牌板记录显示值。顶板离层仪显示情况，蓝色表示正常，黄色表示警告，红色表示危险。若出现危险情况，应及时将信息反馈给相关部门。
②位移量采用钢卷尺测量“十字”布点0A、OB、OC、OD、OE、OF与初始数值对比得出顶板下沉量、底鼓量、两帮移近量等。
③锚杆锚固力抽测：锚杆巷道每施工300根锚杆，一组抽查至少10根锚杆的锚固力。手动泵加压时顶锚杆大于100KN即为合格，煤巷帮锚杆大于40KN、岩巷大于60KN即为合格。
④锚杆预紧力矩监测：用扭矩扳手从正反两个方向测试扭矩，大于350N•M即为合格，抽查率不低于30%。
6.资料管理
（1）健全技术档案，做到一条巷道一档，要建立健全各巷道的观测数据或信息。
（2）矿压观测分析
根据矿压观测显现的特点、结合矿压观测的数据，分析矿压显现的原因，分析支护参数的合理性、支护存在的问题，提出巷道支护参数的调整及优化支护的建议，形成综合分析图表。
7.矿压观测报告的编制
工作面矿压观测报告内容可分为四个方面。
（1）观测的目的、内容及方法
说明本次矿压观测的主要任务、内容、采用的矿压观测仪器。测区及测点的布置、观测和记录的方法及日常数据整理方法等。
（2）测区地质及生产技术条件
①说明观测工作面的地质条件、煤层名称、采高、顶底板岩层组成、各层厚度、岩石强度、裂隙及构造发育程度、倾角、采深等（附综合柱状图）。
②说明观测工作面的生产系统、掘进要素、工作面周围巷道布置情况、工作面周围的开采情况及与采空区的相对位置关系等（附巷道布置图）
（3）观测结果分析
分析掘进工作面矿压的显现规律。
（4）结论与建议
结论和建议的主要内容是：工作面矿压参数；支护形式选择与支护参数的改进建议；对顶板控制的建议；以及其他需要说明的问题。
* 考核
根据矿发《安全生产标准化管理制度》规定，根据矿每月安全生产标准化检查情况，对照《安全生产标准化管理制度》中相应项目，对队组现场存在的问题进行处罚。
