:PROPERTIES:
:ID:       e7788d0d-82e5-4613-b4ca-b1a941741d64
:END:
#+title: 安全监督检查制度
为了加强安全生产监督检查，确保党和国家的安全生产法律法规和《煤矿安全规程》、《作业规程》和《安全技术操作规程》在生产过程中得以认真贯彻落实，确保矿的安全生产，特制定本制度。
* 日常安全检查
安全副矿长负责日常生产过程中的安全监督检查，矿根据生产实际需要配备足够数量的安全员，做到采、掘工作面专人监督检查，通风、机运每班有专人，全面监督检查生产过程的各个环节，确保安全生产。现场严格按三大规程规定作业。对存在隐患的作业地点，必须督促先消除隐患，才能作业，坚决做到“三不生产”。
* 专项检查
** 每旬由总工程师组织安全科、通风科、生产技术科及打钻队对矿“一通三防”工作进行全面检查，重点检查“一通三防”的装备及管理情况，对生产过程中存在的“一通三防”隐患进行彻底的整改。
** 每旬由生产副矿长组织安全科、生产技术科及相关负责人对矿采掘工作面及巷道顶板支护情况进行全面检查。
** 每旬由机电副矿长组织对全矿机电、运输安全情况进行全面检查，重点检查井下电气的防爆和完好状况，斜井、立井提升的设备及安全管理，地面、井下机电机房、硐室的安全安全生产标准化状况。
* 综合检查
** 每月由安全副矿长牵头，组织安全科、生产技术科、通风科、机运科等队组对矿进行一次全面的安全检查，并根据检查结果，对矿安全生产进行评估。对不具备安全生产条件的工作面必须停产整改，并督促有关队组进行彻底整改，直到隐患消除，并经验收符合规定要求后方可恢复生产。
** 矿人力资源科每月组织对地面岗位点人员遵章守纪情况和各队组值班人员上岗情况进行一次督查。
* 监督检查内容
** 安全检查的内容主要是查思想、查管理、查制度、查安全设施、查隐患、查事故处理。
** 检查各作业地点检查生产过程中的作业条件、生产设备以及相应的安全设施和工人的操作行为是否符合安全生产的要求。
** 主要是对照党和国家有关安全生产的方针、政策及有关文件,检查各单位领导和职工群众对安全生产工作的认识。
** 主要检查各单位领导是否把安全生产工作摆到议事日程；
** 各单位主要领导人是否负责安全生产工作；
** 各职能部门在各自业务范围内是否对安全生产负责；
** 工人群众是否参与安全生产的管理活动；
** 矿安全技措经费是否按规定提取和使用。
** 检查各单位的安全教育制度
** 作业规程和各工种的安全操作规程、岗位责任制等的执行情况。
** 检查生产单位的劳动条件、生产设备以及相应的安全设施是否符合安全生产、文明生产的要求。
** 检查矿井“一通三防”的装备、管理情况以及矿井水灾、火灾、瓦断、煤与瓦斯突出和煤尘等灾害的预防措施是否齐全有效。
** 要害部门和重点设备如:变电所、火药库及各种有毒有害、易燃易爆等物品的仓库和使用场所都要进行严格检查。
** 检查各单位对伤亡事故是否及时报告、认真调查、严肃处理,如发现单位未按“四不放过”的要求分析处理事故,要严肃处理。
** 在开展安全检查工作中矿及各单位可根据具体的情况做到每次检查的内容有所侧重,采取有效措施,防止类似事故重复发生。
* 现场安全检查监督管理
** 安全员是分管范围内本班安全质量监督检查的第一责任者，必须认真检查分管范围的安全质量问题，指出并督促施工队组组织整改；对危及人身安全的重大隐患，要立即组织撤出人员，停止生产，及时向矿调度汇报；认真搞好安全质量班评估工作，对当班出现的安全质量问题，要立即督促整改，当班处理不完的，要亲自交给下一个点班的安全员，直到监督整改合格。
** 安全科是班队安全质量监督检查管理的第一责任人，负责监督检查本班瓦检员、跟班班队长、放炮员等特殊工种履行岗位职责和生产现场落实施工标准、安全措施的情况。
*** 协调并督促施工队组解决安全员检查出的隐患及问题；
*** 对本班所有的施工地点巡视检查一遍，督促并协调组织整改存在问题，保证安全质量隐患得到及时整改落实；
*** 对当班出现的安全隐患要及时汇报矿调度，并协调组织处理，对危及人身安全的重大隐患，要立即组织人员撤到安全地点，及时汇报矿调度，采取初步应急措施进行处理。
** 安全科科长是分管范围内安全质量监督检查管理的第一责任人，负责分管业务范围内各工作地点安全措施的落实和现场的监督检查。必须经常深入井下现场监督检查安全措施的落实整改情况，发现安全质量问题，及时向矿调度汇报，并督促整改。
** 安全科科长是矿安全质量监督管理的第一责任人，负责协调组织安全生产标准化现场落实的监督检查、隐患问题的整改落实工作。督促安全员加强现场落实安全生产标准化的监督检查，消除隐患，保证工程质量达到合格。
** 各工作面凡未按规程、措施和操作程序进行作业的，安全员或其他人员检查发现后，必须责令其立即停止作业，并通报矿调度，立即进行整改，并对责任人进行处罚。
** 井下所有工程开工前，必须由安全科牵头组织验收，符合开工条件的方可施工。
** 对检查出的问题及时下发“四定表”，由安全科限定整改时间、落实措施责任人，并对落实整改情况进行复查验收。
** 上级领导、部门所检查出的问题，由安全科负责落实责任人进行整改，并对落实整改情况组织复查验收。
** 安全科负责将矿隐患整改落实情况进行详细登记、汇总。
* 安全监督检查结果处理
对各类检查中检查出来的问题和隐患，必须按五落实进行整改处理，并将处理结果进行通报及存档备案，对拒不落实处理的个人，按矿《××矿责任追究办法》进行处罚。
