:PROPERTIES:
:ID:       5350005b-bdb3-489d-a6c2-2ed84b418d50
:END:
#+title: 矿长（总经理）安全生产岗位责任制
* 岗位职责
** 是煤矿安全生产的第一责任人，对全矿安全生产工作负主要领导责任。
** 贯彻执行党和国家安全生产方针政策、法律法规和标准规定，组织制定安全生产责任制，明确各岗位的责任人员、责任范围和考核标准，组织制定班子成员和分管部门负责人安全生产责任制，组织制定并督促落实矿领导带班下井制度。
** 带头执行安全生产法律法规，严格履行法定职责。要强化风险管控和重大灾害治理，每年不少于1次向煤矿安全监管监察部门报告重大风险管控、重大灾害治理情况。
** 向监管监察部门如实报告安全生产有关情况。
** 向煤矿安全监管监察部门及时、如实报告生产安全事故，负责组织事故抢险救援。
* 到位标准
** 建立健全安全责任体系
*** 健全安全生产责任制。按照“党政同责、一岗双责、齐抓共管、失职追责”要求，建立健全覆盖煤矿企业各层级、各部门、各岗位的安全生产责任制，明确党政主要负责人、分管负责人，安全、生产、技术、经营、规划、财务、人事及党委工作部门、工会等各部门的安全生产职责，形成人人有责、各负其责、权责清晰的安全生产责任体系。建立并公示岗位安全生产责任清单，实现“一岗一清单”。
*** 完善安全生产管理制度。煤矿企业应建立健全各项安全生产管理制度，至少包括安全生产责任制管理考核制度、安全目标管理制度、安全承诺制度、安全技术措施审批制度、安全办公会议制度、安全投入保障制度、生产安全设备采购制度、劳动用工制度、安全教育培训制度、安全监督检查制度、安全风险分级管控制度、事故隐患排查治理制度、事故报告与责任追究制度、安全生产标准化管理体系检查考核制度、事故应急救援制度、安全生产责任奖惩制度、应急值班制度、复工复产和重大隐患整改现场验收制度等。管理制度内容应做到责任清晰、有针对性，能够对照执行和考核。
*** 健全安全生产组织机构。要结合本矿灾害特点，建立健全相应的管理、技术、监督等职能部门，配齐配强治理各类灾害的专业技术人员和管理人员。针对煤矿实际情况，特别是风险灾害情况，选优配强管理人员，健全灾害治理机构、配备施工装备，防止违规劳务承包。
*** 强化内部监督。建立内部考核机制，制定安全责任考核办法和标准，对照安全生产责任清单，开展安全目标考核，并将考核结果纳入相关人员绩效管理，对于连续2次考核不合格的，及时调整岗位。建立完善并严格执行事故煤矿“一票否决”制度。每月组织开展安全生产检查，及时发现煤矿在安全理念、工作目标、制度执行、风险管控、灾害治理等方面存在的问题。建立责任倒查机制和问题反思机制，对存在的重大隐患和突出问题，倒查各级管理人员责任，分析深层次原因，完善管理制度，改进工作机制，防止问题重复发生。严格执行复工复产和重大隐患整改现场验收制度。
** 严格落实主要负责人法定职责
*** 落实安全生产第一责任人责任。要及时学习贯彻落实习近平总书记关于安全生产重要指示批示精神和党中央、国务院关于安全生产的重大决策部署，每年不少于2次组织研究安全生产重大问题，并形成会议纪要。支持、指导和督促领导班子其他成员落实安全生产主体责任。强化风险管控和重大灾害治理，每年不少于1次向煤矿安全监管监察部门报告重大风险管控、重大灾害治理情况。严格兑现安全承诺。
*** 严格履行法定职责。要带头执行安全生产法律法规，严格履行法定职责，依法建立健全安全生产责任制、安全生产规章制度。组织制定并实施安全生产教育和培训计划，保证安全生产投入有效实施。督促、检查安全生产工作，及时消除事故隐患。组织制定并实施事故应急救援预案，及时、如实报告生产安全事故。督促分管矿长、总工程师坚持“一岗双责”，履行好分管范围内的安全职责。
*** 实施安全公开承诺。每年向全体员工和社会公开作出安全承诺：保证严格落实安全生产责任制和安全管理制度；保证有效管控重大安全风险、治理重大灾害，及时消除事故隐患；保证安全投入所需资金；保证不超能力下达生产任务和经营指标；保证不违规安排使用劳务派遣工和采掘工程外包队伍等。每年将安全承诺兑现情况纳入年度述职内容和工作报告。
* 夯实安全生产基础
*** 强化安全生产标准化管理体系建设。组织开展安全生产标准化管理体系建设，制定年度创建目标，建立激励约束机制，加强监督检查，按月组织现场检查、动态抽查，严格考核兑现。所有生产煤矿必须达到三级以上标准化等级，大型煤矿力争达到一级、中型煤矿至少达到二级标准化等级。
*** 强化风险防控和隐患排查治理。要建立完善安全风险辨识评估、管控和警示报告机制，科学制定风险辨识程序和方法，按月组织开展重大风险辨识。制定重大风险管控方案，确定管控重点，明确管控责任，监督落实到位。每年向煤矿安全监管监察部门报送风险清单。以风险辨识管控为基础，加强隐患排查治理，定期对存在重大风险的场所、环节、岗位开展隐患排查，分析隐患成因、制定消除措施，着力从根本上消除事故隐患。
*** 加快智能化建设。要建立健全技术装备淘汰更新机制，不断提高装备可靠程度和安全生产保障能力，加快推进智能化建设和危险岗位机器人替代，推进互联网、大数据、人工智能同煤矿安全生产的深度融合。
*** 持续提升从业人员素质。要研究制定职工素质提升中长期规划和年度计划，选优配强师资力量，保障培训工作经费，杜绝培训造假行为。严格准入和劳动用工管理，矿领导、副总工程师必须具备煤矿相关专业大专及以上学历，新上岗的特种作业人员必须具备高中及以上文化程度，员工至少具备初中学历。取消井下劳务派遣工。
*** 大力推进“一优三减”。要加强统筹协调，合理安排专业技术力量，以通风系统可靠、运输系统简化、危险岗位替代为重点，对所属煤矿开展生产系统、开拓布局、作业环节和劳动组织优化，减少生产水平，减少采区，减少作业头面，减少作业单元人员数量。科学确定采掘接续，降低开采强度，建设“一井一面”“一井两面”示范矿井。
*** 切实保障安全投入。要建立健全安全投入保障机制，落实企业主要负责人、分管经营、财务负责人和经营、财务等职能部门的安全投入责任，保证足额提取、按规定使用安全生产费用，保证灾害治理、装备升级、人员培训等工作所需资金。
*** 加强重大灾害治理。建立由主要负责人负责的煤矿重大灾害治理管理体系和以主要技术负责人（总工程师）为首的灾害治理技术保障体系。科学制定治灾计划，合理安排灾害治理工程，保障治理资金。加强灾害治理调度，合理调整煤矿生产经营指标，防止生产系统不健全、灾害治理不到位，盲目组织生产。
*** 提升应急救援能力。健全事故响应机制，针对煤矿灾害特点，编制生产安全事故应急救援预案，加强应急救援队伍建设，配备必要的应急救援物资，加强与地方政府沟通和衔接，提升应急救援能力。建立灾害性天气应急预警机制，在相应灾害性天气情况下及时停产撤人。严格落实应急值班制度，实行24小时值班值守。
* 考核标准
根据《XX公司安全生产岗位责任考核办法》、《XX公司工资管理办法》等相关文件规定，矿长（总经理）安全生产责任制到位标准一项不达标考核XX元。
