:PROPERTIES:
:ID:       a04d76d5-dc70-4383-85bf-61214f5d6575
:END:
#+title: 全事故报告、调查、分析处理制度
为加强安全生产监督管理，规范安全生产事故的报告，应急救援和调查处理，落实安全生产事故责任追究制度，防止和减少安全生产事故，根据《[[id:4393e9ee-72d3-4f1a-874f-3992117f40b0][中华人民共和国安全生产法]]》、《[[id:4758e44a-c9b1-4508-87ea-8497cb6f1e74][中华人民共和国矿山安全法]]》、《[[id:a58a6a98-fc39-452a-bb3c-57d8b084528f][中华人民共和国突发事件应对法]]》、国务院《[[id:fdeee6f5-f63e-4d90-b371-fc9b662f1b9a][生产安全事故调查报告和调查处理条例]]》、国家安监总局《生产安全事故信息报告和处理办法》等法律法规和有关规定，结合矿生产安全管理实际，制定本制度。
* 事故汇报
** 发生轻伤及以上事故或其它安全生产事故时，必须立即向矿安全调度汇报，矿安全调度接到汇报后，按程序、按事故类别、按事故级别分别向相关矿领导报告，并通知相关部门；相关部门接到通知后，必须立即通知科领导到待命，并做好应急救援准备工作。
** 事故信息报告应及时、准确和完善，任何科室和个人不得迟报、漏报、谎报或者瞒报事故；信息处置应当遵循快速、协同配合、分级负责的原则。
** 事故信息报告范围包括已经发生的煤矿生产安全事故（特别重大、重大、较大、一般生产安全事故）和较大涉险事故的信息。
较大涉险事故的信息是指：
*** 涉险10人以上的事故；
*** 造成3人以上被困或者下落不明的事故；
*** 其他较大涉险事故。
** 事故信息报告时限
*** 发生一般生产安全事故，应当在1小时内报告上级。
*** 发生较大生产安全事故或者发生重大、特别重大生产安全事故的，立即汇报上级部门。
*** 事故信息报告后出现新情况的，应当按规定及时续报。较大涉险事故、一般事故、较大事故每日至少续报1次；重大事故、特别重大事故每日至少续报2次。续报工作直至事故抢险救援工作结束。
** 事故信息报告应当包括下列内容：
*** 事故发生的时间、地点以及事故现场情况；
*** 事故的简要经过（包括应急救援情况）；
*** 事故已经造成或者可能造成的伤亡人数（包括下落不明、涉险的人数）和初步估计的直接经济损失；
*** 已经采取的措施。
* 事故汇报程序图
* 事故处置
** 调度室在接到事故信息时，应当立即启动应急预案规定的应急响应，立即向矿长及领导班子成员汇报，组织开展应急救援工作，并按照程序向上级调度汇报，同时通知安全科，由调度室和安全科共同做好事故信息的核查、跟踪、处置、督导等工作。
** 发生轻伤事故，矿调度接到汇报后，必须及时通知医院。车队接到矿安全调度通知后立即安排救护车辆和医务人员到井口接送受伤人员到医院检查治疗。严重轻伤，救护队安排救护车辆和救护队员到井口接送受伤人员到医院检查治疗；发生重伤及其以上安全生产事故，矿调度接到汇报后，必须及时通知救护队和医院。救护队接到矿调度通知后立即安排救护车辆和医务人员到井口接送受伤人员到医院检查治疗或组织救护队员到井下对现场受伤人员进行现场施救。
** 发生重伤及其以上安全生产事故时，矿调度接到汇报后，应在10分钟内时向上级总调度室报告。
** 发生死亡事故时，必须按要求及时向有关部门报告，并积极配合有关部门按程序进行事故调查。
** 发生安全生产事故后，相关矿领导接到矿调度的报告后应及时赶赴调度室指挥，并组织应急救援。
** 发生安全生产事故，矿必须严格按照事故应急救援体系中相关制度要求，及时将受事故威胁地点的人员撤离至安全地点，并积极组织救援工作，防止事故扩大，造成人员伤亡或增加伤亡数量。
* 事故调查处理
** 发生一般安全生产事故后，必须按事故的类别由矿分管领导组织相关部门进行调查处理，并按下列要求进行。
*** 发生安全生产事故使矿井停工、停产或采掘工作面停产24小时的，由生产副矿长组织，安全副矿长、分管副矿长或专业人员参加进行调查分析和处理。
*** 由于采掘工作面瓦斯治理力度不够，造成回风流瓦斯浓度超过1%或局部瓦斯达到2%及以上的，由矿总工程师组织，安全副矿长及专业人员参加进行调查分析和处理。
*** 采掘、巷修工作面发生片帮、冒顶，巷道、石门或采煤工作面冒顶长度超过5米（含5米），掘进巷修工作面冒顶长度达3米及以上的安全生产事故，由生产副矿长组织，安全副矿长、分管副矿长、总工程师及专业人员参加进行调查分析和处理。
*** 出现煤与瓦斯突出动力现象，或大面积瓦斯超限的安全生产事故，由总工程师组织，安全副矿长及专业人员参加进行调查分析和处理。
*** 发生水灾使一个采掘工作面被淹停产的，由总工程师组织，安全副矿长、分管副矿长及专业人员参加进行调查分析和处理。
*** 停电、触电、斜井跑车、刮板输送机断链伤人、皮带断带伤人的安全生产事故，由机电副矿长组织，安全副矿长及专业人员参加进行调查分析和处理。
*** 通风系统不合理，通风设施不可靠，损坏通风设施的，由总工程师组织人员参加进行调查分析和处理。
*** 发生放炮崩人类型安全生产事故，由生产副矿长组织，安全副矿长、分管副矿长、总工程师及专业人员参加进行调查分析和处理。
*** 不按要求排放瓦斯的，由总工程师组织专业人员进行调查分析和处理。
*** 发生其他意外造成重伤的，由安全副矿长组织人员进行调查处理。
** 安全生产事故发生队组有关人员必须积极配合事故调查工作，如实提供有关情况。
** 安全生产事故调查处理应当按照科学严谨、依法依规、实事求是、注重实效的原则，及时、准确地查清事故经过、事故原因、事故损失，查明事故性质，认定事故责任，总结事故教训，提出防范和整改措施，并对事故责任者提出处理意见。
* 事故责任分析及处理
** 事故责任分析
*** 根据事故调查所确认的事实，通过对直接原因和间接原因分析，确定事故的直接责任、间接责任者。
- 直接责任：凡是导致事故发生直接原因的人员责任属直接责任。
- 间接责任：产生人的不安全行为、物的不安全状态、管理缺陷的间接原因的人员责任属间接责任。
*** 事故责任人员一般分为四类责任：直接责任者、主要责任者、重要责任者、一般责任者。
直接责任者主要是指因违章操作或违章指挥直接导致事故发生的人员。主要责任者、重要责任者、一般责任者属于间接责任，主要是指各级管理人员、矿级领导。其中领导责任又分为：主要领导者、重要领导责任者、一般领导责任者。
** 事故责任追究及处罚
按照《事故调查报告》做出具体的处罚决定。
** 对事故隐瞒不报、谎报或拖延不报，阻碍、干涉事故调查处理，故意破坏事故现场，拒绝接受调查以及拒绝提供真实情况和资料的科室和个人，根据情节轻重，做出处理。
** 《事故调查报告》下达后由安全科按标准进行落实，罚款纳入矿安全基金。
** 对于事故调查组提出的事故调查处理意见和防范措施，由安全科负责跟踪落实。
