:PROPERTIES:
:ID:       261754d8-0994-4275-88fe-b3337f7716fc
:END:
#+title: 生产管理制度
* 总则
** 本制度规定了生产管理的职责与内容、检查与考核。本制度适用于公司属各单位。
* 管理职责
** 生产管理实行公司统一管理，分级负责的管理体制。
** 生产安全部是生产管理的主管部门，负责公司的生产组织协调工作。
** 各二级单位负责本部门的生产计划实施工作。
* 管理内容
** 生产管理就是运用组织、计划、控制的职能，把投入生产过程的各种要素有效地组织起来，形成有机整体，按最经济的方式，生产出满足社会需要的优质、低耗、高附加值的产品。
** 生产管理要求合理地组织公司的生产活动，合理配置资源，有效地进行生产控制，提高生产效率，保证按品种、按质量、按期限和成本目标完成公司的生产任务。
** 制定公司生产经营计划。
*** 原燃料分公司根据年度原燃料平衡计划及库存情况编制每月《大宗原燃料输入计划》，并于每月20日前报生产安全部。
*** 销售分公司根据市场形势、公司主要产品生产及库存情况编制每月《销售资源需求计划》，根据炼钢厂生产需要，编制每月《废钢（含生铁块）资源平衡计划》，并于每月20日前一并报生产安全部。
*** 机动部根据公司年度设备检修计划，生产经营形势以及设备运行状况，编制每月《主要设备检修计划》，并于每月20日前报生产安全部。
*** 技术中心根据公司年度双高产品开发计划，编制每月《双高产品生产计划》，并于每月20日前报生产安全部。
*** 生产安全部根据公司生产经营总体目标、年度经济责任制协议书及以上部门（即原燃料分公司、销售分公司、机动部、技术中心）上报的计划，并考虑市场、库存、资源、生产能力、设备检修等因素，制定公司生产经营计划，并报请公司主管领导审批后，于每月26日前下发给公司属各单位。
*** 各二级单位根据公司生产经营计划制定本部门的生产计划。
** 组织生产经营计划的执行和实施
*** 生产管理是实现生产经营计划的重要手段，在执行生产计划过程中，会出现一些预想不到的情况和矛盾，必须及时监督和检查，发现偏差及时调节和校正，生产作业控制以超前管理为主，时时受控，要抓好生产准备工作，防止不协调现象发生。
*** 生产安全部（公司总调）是生产作业控制中心，生产安全部（公司总调）发布的生产调度指令，下级生产部门和同级管理部门必须无条件地执行。
*** 各二级生产单位必须严格执行公司生产经营计划，制定切实可行的保产措施。
*** 各分（子）公司必须履行为集团公司系统生产组织服务的义务，当系统生产组织与分（子）公司生产发生冲突时，一律以保系统生产为重。
*** 各相关管理部门都要围绕公司生产经营计划，各自抓好自身工作。
*** 各工序之间要顾全大局、互相支持、团结协作，上道工序必须无条件保证下道工序需求，使生产过程能均衡、稳定、高效，产品优质，以保证公司全年生产经营目标的顺利实现。
* 管理措施
** 二级单位负责对本单位的生产计划执行情况进行检查与监督，并建立相应的检查及考核制度。
** 生产安全部根据该制度对二级单位进行巡查、监督和月度考核。对影响生产严重的责任单位，实行及时考核制度，避免类似情况的重复发生，重复事故加倍考核。
*** 各二级生产单位必须严格执行公司生产经营计划，对不按品种进度计划组织生产的责任单位，根据经济责任制考核办法，按未完成的比例进行考核。
*** 各二级单位要加强设备的维护和点检定修以及计划检修工作，对非计划停产检修（≥4小时）的责任单位，根据影响生产所造成的损失程度，每小时扣罚2000～5000元，累计计算。
*** 因外部原因造成炼铁高炉非计划休风，单座高炉每休风1小时（不足1小时视同1小时）考核责任单位10000元，累计计算。因炼铁厂内部原因造成高炉非计划休风（工艺性休风除外），考核其6000元／单座高炉·小时，累计计算；单座高炉的工艺性休风时间（月累计）不得超过9小时，否则视同非计划休风予以考核。
*** 因外部原因造成高炉减风（减风量低于正常风量的85%），单座高炉减风1小时（不足1小时视同1小时）考核责任单位6000元，累计计算；  因炼铁内部原因造成高炉悬料、减风等（减风量低于正常风量的85%），单座高炉减风1小时（不足1小时视同1小时）考核其4000元，累计计算。
*** 各主体单位之间不能相互影响生产，各辅助单位要为主体单位的生产保驾护航。凡工序之间相互影响生产的责任单位，根据影响生产所造成的损失程度，每次扣罚责任单位5000～10000元，累计计算；如造成三个以上单位受损，加倍考核。
*** 如果出现二级单位（包括分、子公司）各自为政、无视公司生产大局的现象，影响系统生产一次，扣罚责任单位50000～100000元，累计计算，并且所造成的损失由责任单位承担。
*** 对不执行公司生产组织协调相关会议纪要（或精神）的责任单位，每次扣罚责任单位5000～10000元，并且所造成的损失由责任单位承担；对违反生产管理相关会议纪律的责任单位，按《调度会、生产例会管理规定》相关条款进行考核。
*** 对上报生产安全部的数据、报表、计划无故拖延，每次扣罚责任单位1000元，累计计算；对影响生产的信息反馈不及时以及数据失真的责任单位，每次扣罚1000～5000元，累计计算。
*** 凡因内部管理不严、执行标准不力、违反工艺纪律、操作规程等因素造成生产事故的责任单位，按《生产事故管理办法》相关条款进行考核。
*** 对违反公司调度纪律及不执行（或执行不到位）公司总调指令的责任单位，按《调度管理办法》相关条款进行考核。
*** 对影响公司物流畅通的责任单位，按《大宗物料平衡管理办法》相关条款进行考核。
*** 如因生产安全部（总调）生产组织不当或指挥失误，给公司的生产经营造成损失，按《公司年度经济责任制》相关条款进行考核。
*** 对因生产形势发生变化而出现的其它问题的考核，由生产运输处对责任单位提出考核建议，提请“公司月度效益工资平衡会”上审议。
* 附则
** 本制度由生产安全部起草并负责解释。
** 本制度自发布之日起执行，Q/SGG  0601-2008《生产管理》同时废止。
