:PROPERTIES:
:ID:       29b2ae42-40a8-4200-aa5f-fe8cfe62b4cf
:END:
#+title: 雨季期间重点部位巡视检查制度
为切实做好矿雨季“三防”工作，确保安全生产，防范水害事故发生，特制定雨季期间重点部位巡查制度。
* 牢固树立“安全第一、生产第二”的思想，进一步提高雨季“三防”工作的认识，立足防大汛、抗大洪，认真抓好雨季防洪物资的储备和防洪措施的落实。
* 加强雨季期间矿井地表水系、塌陷、积水区和周边环境及输电线路的巡查、排查。特别是雨中、雨后巡查工作，发现问题，及时汇报处理。
* 加强汛期矿井涌水量观测、各类防水设施和防水煤柱的排查，做好疏水与排水系统检修维护，责任落实到人，并纳入专人管理。对矿井水害隐患威胁的地点，要严格遵循“预测预报、有疑必探、先探后掘、先治后采”的防治水原则，确保矿井安全渡汛。
* 加强井下防水设施及施工区域积水的管理工作，要责任到人。由总工程师负责，每月组织一次矿井全方位的水情水害专项排查，排查出的问题要定人员、定措施、定标准限期整改；每月至少进行一次井上、井下全面水患排查自检，并严格落实治理责任制，对重大水害隐患的整改完成情况要由总工程师负责组织验收。
* 根据矿实际情况，由总工程师负责制定完善的防汛措施及预案，坚决做到大雨不淹井，暴雨不伤人，雨季受水威胁严重的区域要严禁生产或有人员进入。
* 制定灾害性天气停产撤人等应急处置措施。要对防汛预案组织学习，成立防汛队伍。
* 根据矿井实际做好雨季机电安全工作，对矿区供电系统、排水系统、通讯系统进行全面检查和测试，并配备充足的备品配件。机运科负责对各井下水仓设备检修以及排水系统（含临时水仓、截流水仓）的联合试运转工作，确保处于完好状态，X月X日前完成，由机电副矿长负责实施。
* 对所管辖的高压线路逐一排查，对存在影响线路安全运行的问题进行处理，特别是对线路安全通道内的树木、建筑等障碍，要进行彻底清除，确保矿井电源线路及其它一类负荷的可靠供电。
* 按时完成井下水仓的清挖工作，对井上下排水沟要及时清理疏通。
* 地面建筑物、变配电所、供电线路等设施的防雷装置必须进行检查试验，做到齐全有效；主变压器、主电缆等要按照规定做好预防性试验、整定校验，保证灵敏可靠。由机电副矿长负责。
* 泵房、变电所等重要场所要配齐值班人员，持证上岗，及时报告和反馈有关情况。
* 严格落实灾害天气停产撤人制度，当连续降雨达到100mm以上或气象预报为“暴雨”天气时，矿主要负责人、分管安全生产的矿领导、机运科、调度室、通风科、安全科、生产队组等队组相关负责人必须在岗在位，立即停产撤人。
* 暴雨期间安排专人巡查各井筒范围外排水情况，发现问题及时处理。
* 雨季前要完善“三条线”检查，对压风管路、防尘管路、通讯线路进行检修、清查。
* 雨季“三防”期间，24小时必须有矿领导带班、值班，及时矿调度协调有关事宜，并做好记录。各队组管理人员的手机必须24小时不得关机，随时保持联系。
* 确保矿井主排水系统、供电系统正常运转，水仓、吸水井清挖及水泵联合试运转按期完成。
* 严格按照矿防汛值班表安排值班。
