:PROPERTIES:
:ID:       0ba0a75f-f7fa-4f7e-b083-04bc14d8d7ce
:END:
#+title: 水害预测预报管理制度
为进一步做好煤矿水害预测预报工作，预防水害事故，根据《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程2022版]]》第二百八十三条“煤矿企业应当建立健全各项防治水制度”和《[[id:c3c897d4-b900-4119-8034-e51f6b312c80][煤矿防治水细则]]》第六条“煤矿企业、煤矿应当建立健全水害防治岗位责任制、水害防治技术管理制度、水害预测预报制度和水害隐患排查治理制度”等规定，制定本制度。
* 煤矿企业、矿井的主要负责人（含法定代表人、实际控制人，下同）是防治水工作的第一责任人，总工程师（技术负责人）具体负责防治水的技术管理工作。地测组是煤矿防治水业务科室，必须按照业务责任制度和有关规程规定有计划地开展水文地质工作，为煤矿预防水害事故提供详实可靠的基础成果资料，提出预测预报。
* 地测组应根据年、月采掘生产计划，分析预测各采掘工作面及周围受水害威胁情况，及时提供相关水文地质资料，下发年度、月、临时性水文地质预报。年报应于年初签发，月报应于上月末签发。在采掘施工过程中，当井下水文地质条件发生变化、出现突（涌）水征兆、接近可疑水区和可疑老空区时，地测组必须及时发出临时性水文地质预报，提出水害防范对策措施和处理建议，且必须有文字和图纸。
* 预报内容应包括地点、范围、对生产的影响，应采取的措施等，预报结果应保证煤矿正常安全生产，不出现因预报错误而造成透水事故。
* 水情水害预报应包括年预报、月预报、临时性预报。预报应图表相符，内容齐全，描述准确，定性，定量，措施有针对性，签字齐全。矿井总工程师组织相关专业技术人员对水害预测报告进行认真审查。对预报进行周分析，月底、年末总结，不断提高预报的准确性，并按年装订成册。
* 若当月生产计划变更，要及时进行补充水害预报。
* 在施工过程中，应对预测预报图表逐月进行检查，不断补充和修正。在施工至含水层时，应提前20m发出水文预测预报单，报告调度室。
* 水文技术人员应做好预测预报资料整理、报送、档存等工作。
* 每月召开一次水情分析会议，由煤矿总工程师负责主持（特殊情况下可由指定人员代替），参加人员包括地测、技术、机运、安全等科室有关人员，地测人员负责会议的记录，形成正式的文字资料。
