:PROPERTIES:
:ID:       544615d9-2610-454c-8abb-925925f887ac
:END:
#+title: 爆破材料储存及运输管理制度
五、爆破材料储存及运输管理制度
一、地面爆炸材料库采取的安全措施
（一）地面爆炸材料库位于距工业场地0.4km以外的地方，并由当地公安部门组织通过验收，爆炸材料库占地面积0.30ha,库内储存各种爆炸材料的数量不得超过矿井3个月的计划需要量。经计算，炸药不得超过3t，雷管不得超过0.5万发。
（二）矿井下不设爆炸材料库及爆炸材料发放硐室。
（三）矿井所有爆破材料的运输，除遵守民用爆炸物品管理条例外，还遵守《煤矿安全规程》第339、340、341和342条等有关规定。
（四）地面爆炸材料库房为砖混结构平房，有发放爆炸材料的专用套间或单独房间。发放室内木地板上应铺设胶板，在炸药发放套间内,可临时保存爆破工的空爆炸材料箱和发爆器；在雷管发放套间内发放雷管时，必须在铺有导电的软质垫层并有边缘突起的桌子上进行，并设有防爆灯具照明，硐室内设有与地面调度室的直通电话。
（五）地面爆炸材料库有发放爆炸材料的单独房间，发放雷管时，在铺有导电的软质垫层并有边缘突起的桌子上进行。
（六）地面爆炸材料库周围，设铁刺网，其高度不低于2.2m，距库房的距离不小于6.0m，并有警卫昼夜看守。
（七）库房中均采用C15混凝土铺底，铺底厚度为100mm，在存放炸药和雷管的木架及木地板上必须铺有一层3mm厚的胶皮板。
（八）按照有关规定及要求配备足够的消防器材，详见下表。
地面爆炸材料库消防器材及材料表
序号	名    称	单  位	数  量	备  注
1	10L泡沫灭火器	个	2
2	8kg干粉灭火器	个	2
3	砂子	m³	3
4	粘土	m³	3
5	灭火岩粉	kg	500
6	水龙带	条	3
7	水泥	t	1.0
8	消防桶	个	2
9	铁锹	张	5
（九）为了防止直击雷，地面爆炸材料库设独立的避雷针保护，其冲击接地电阻不大于10Ω；为避免雷电波沿电力线传入，地面爆炸材料库的照明使用带绝缘套的矿灯。在地面爆炸材料库设有固定电话。
二、爆破材料运输的安全措施
（一）电雷管和炸药分装分运；
（二）用车辆运送硝化甘油类炸药或电雷管时，装车高度低于车厢上缘100mm。用车辆运输雷管时，雷管箱不得侧放或立放，层间垫软垫；
（三）在装有爆炸材料的矿车内，除爆破工或护送人员外，不得有其他人员；
（四）交接班、人员上下井的时间内，严禁运送爆炸材料；
（五）禁止将爆炸材料存放在井口房、井底车场或其他巷道内；
（六）爆破工把炸药、电雷管分开存放在专用的爆炸材料箱内，并加锁；严禁乱扔、乱放。爆炸材料箱放在顶板完好、支架完整、避开机械、电气设备的地点。爆破时把爆炸材料箱放到警戒线以外的安全地点；
（七）建立爆炸材料领退制度、电雷管编号制度和爆炸材料丢失处理办法；电雷管在发放爆破工前，用电雷管检测仪逐个做全电阻检查，并将脚线扭结成短路。电阻不合格的电雷管不发放；
（八）按民用爆炸物品管理条例的规定，建立爆炸材料销毁制度；
（九）所有爆破人员，包括爆破、送药人员，熟悉爆炸材料性能和《煤矿安全规程》。
