:PROPERTIES:
:ID:       d006f5ca-5b0b-45f5-8bcc-8d1f3d75aeba
:END:
#+title: 火区管理制度
* 井下火区未直接扑灭而予以封闭的区域称火区。
每个火区必须根据发火时间及时编号，建立火区管理卡和绘制火区位置关系图，由矿通风部门永久保存。火区管理卡片包括以下内容：
** 火区基本情况登记。
** 火区位置示意图。
** 灌浆、注氮或其他方式灭火记录。
** 进回风防火墙及观测记录。
火区位置关系图以通风系统图为基础绘制，即在通风系统图的基础上标明所有火区的边界，防火墙位置、火源点位置、漏风路线及灌浆、注氮系统布置、火区编号、发火时间、封闭时间、火区注消时间等内容。
* 当井下无法直接灭火或直接灭火无效时，必须采取封闭措施灭火。封闭时应遵循以下原则：
** 在确保安全的前提下，尽量缩小封闭范围，特别应缩短进风侧密闭与火源之间的范围；
** 进、回风密闭在施工顺序上采取进、回风侧同时封闭或先进后回的封闭方法。采取先做进风侧密闭时，应留有通风孔，使其既能控制火势又可防止火源上风侧发生瓦斯超限和积聚。因约定好时间，使进回风防火墙在同一时间封闭结束。封闭有爆炸危险的火区必须采用防爆墙；
** 必须指定专人每隔10分钟检查一次进回风流中瓦斯浓度、一氧化碳和氧含量，随时判别爆炸危险性。必须根据具体情况采取防止瓦斯、煤尘爆炸和人员中毒的安全措施。有爆炸危险而无有效防爆措施时必须将人员撤到安全地带，然后排出爆炸危险；
** 火区封闭结束后应进快将人员撤离灾区。
* 火区封闭后应积极采取措施加速火区熄灭进程。火区灭火方案由矿通风部门负责编制,经矿长、总工程师批准后执行。灭火方案应包含以下内容:
** 火区基本情况及现状分析。
** 火区周围地质情况及开采情况。
** 灭火方法、灭火工程、劳动组织及安全措施。
** 灭火方案图。
* 当火区范围较大,火源是否已经完全熄灭难以确认时,可以采用缩封措施,来解决部分冻结煤量和封闭物资,并通过在封闭状态下将密闭逐段逼近火源地点,以便提高灭火效果,加速火区熄灭。实施缩封火区必须编制缩封计划和安全措施,报上级部门审批,并由矿山救护队负责完成，缩封计划与安全措施可参照火区启封计划和安全措施编制。
* 封闭的火区必须经取样分析符合下列熄灭条件,经矿长和矿总工程师组织有关部门鉴定确认火区已经熄灭时,方可注销火区:
** 火区内空气温度下降到30℃以下或达到灾前日常温度。
** 火区内空气中氧浓度降到5%以下。
** 火区内空气中不含有乙烯、乙块,CO浓度在封闭期间逐渐下降,并稳定在0.001%以下。
** 火区的出水温度低于25℃或与灾前水温相同。
** 上述4项指标持续稳定达1个月以上。
注销火区时,必须将火区注销鉴定及结果报上级部门备案,未经注销的火区密闭严禁打开。
* 启封火区必须谨慎从事,要做好一切应急准备。事先必须编制启封计划和安全措施报上级部门审批。启封计划和安全措施应包含以下内容:
** 火区注销时间及火区注销鉴定材料。
** 启封方法、火区侦察顺序及防火墙启封顺序。
** 启封时防止人员中毒、防止火区复燃、防止瓦斯爆炸的通风安全措施及应急准备工作。
* 启封火区，通常应采用锁风法,即启封过程中使火区始终处于封闭隔绝状态的启封方法,启封火区时,火区回风流所经过巷道内人员必须全部撤出，应逐段恢复通风，且必须随时测定火区气体及回风流中有无一氧化碳，一旦发现复燃征兆,必须立即停止向火区送风并重新封闭火区。
启封火区及恢复火区初期通风的工作矿申请由矿山救护队负责完成。火区启封后三天内,每班必须由救护队检查通风情况,并检测水温、气温和空气成分,只有在确认火区已完全熄灭且通风正常后方可转入其他工作。火区启封工作结束,应予以总结并将启封报告报知上级部门。
* 在火区附近进行采掘工作必须遵守下列规定:
** 在火区同一煤层同一水平的相邻区域进行采掘工作,必须留有足够火区隔离煤柱，并编制专门设计及安全措施报矿总工程师批准。
** 在火区同一煤层的上下区段及上下临近煤层一般不得回采。但当煤层倾角小于35°且火区下部留有足够高度的煤柱，能有效隔离火区时,应编制专门设计和安全措施报上级部门批准后方可回采。在火区下部掘进时必须有防止冒顶、冒透火区的安全措施。
** 在火区下方的邻近煤层进行回采，只要有防范措施能够保证回采后不影响火区灭火工作和火区对回采没有威胁,应将专门开采设计报上级部门批准。
* 每周对防火墙、火区密闭和其它密闭进行检查，分析测定其内外气体成分,内外温度、进回侧密闭内压差及墙体与围岩支护情况，并记入防火专用记录本备查。通风科队长应及时审查,发现密闭墙封闭不严。或有发火异常现墙体裂缝等必须采取措施及时处理，并报告矿总工程师。
