:PROPERTIES:
:ID:       9db01e38-3921-4bdb-9610-65a6a4e24f3b
:END:
#+title: 职业病危害防治宣传、教育和培训制度
为切实加强和提高职工职业病危害防范意识和技能，有效预防、控制和消除职业病危害，保障职工身体健康，根据《中华人民共和国职业病防治法》、《煤矿作业场所职业病危害防治规定》、《国家安全监管总局办公厅关于加强用人单位职业卫生培训工作的通知》等法律法规和有关规定，制定本制度。
* 安全副矿长是职业病危害防治宣传教育和培训工作的第一责任人；各单位是职业病危害防治宣传教育工作的责任主体。
* 有职业危害因素作业场所的单位，必须将职业病危害防治宣传教育培训工作纳入本单位年度工作计划，并保证所需工作人员和经费。
* 在职业危害因素作业场所作业的职工，必须接受职业卫生教育培训，熟悉有关职业病防治的法律、法规、规章、职业卫生标准和操作规程，增强预防和控制职业病危害意识及应急处理能力。
* 有职业危害因素作业场所的单位，要充分利用广播、报纸、公告栏等宣传手段，进行职业卫生法律、法规、规章和职业病危害防治知识的宣传教育工作。
* 有职业危害因素作业场所的单位，在每年四月的最后一周要举办一次《职业病防治法宣传周》活动宣传活动，开展职业病危害防治宣传教育活动。
* 矿培训中心要按规定组织单位主要负责人、安全生产管理人员参加专业机构组织的职业危害防治工作培训，培训课时、培训内容以上级有关培训机构为准。
* 专职职业卫生管理人员以及职业病危害因素监测人员初次培训不得低于16学时，继续教育不得低于8学时。培训内容：国家职业病防治法律、行政法规和规章以及标准、职业病危害防治知识、主要职业病危害因素及防控措施、职业病防护设施的维护与管理、职业卫生管理的要求和措施。
* 职工上岗前，培训时间不少于8学时；在岗期间，每年培训不少于4学时。培训应包括以下主要内容：国家职业病防治基本知识、职业卫生管理制度和职业卫生岗位操作规程、所从事岗位的主要职业危害因素和防范措施、职工职业卫生保护权利和义务等、职业病危害事故案例分析、职业病危害防治设备、设施及个人防护用品的使用和维护、自救、互救、疏散和现场紧急情况的处理。培训资料包括：培训计划、培训通知、培训内容、培训记录、培训签到、考试试卷、宣传图片等纸质和摄录像资料。
* 实习生到矿下井实习必须接受职业病危害防治培训，培训时间不少于8学时。
* 主要负责人、安全生产管理人员、专职职业卫生管理人员以及职业病危害因素监测人员的培训考试由相应的培训机构实施，考核合格后，颁发培训合格证；接触职业病危害的职工培训考核由矿培训中心或基层单位实施，考核合格后出具相应的证明材料。
* 因变更工艺、技术、设备、材料或岗位调整导致职工接触职业病危害因素发生变化时，重新对职工进行职业卫生培训，经培训合格后方可上岗。
