:PROPERTIES:
:ID:       d5549e7f-49f6-4705-8da6-cad7f7039e5a
:END:
#+title: 安全风险分级管控工作制度
根据《[[id:4663f65b-c43d-4e59-b804-905990c44ab5][煤矿安全生产标准化基本要求及评分方法（试行）]]》要求，为全面辨识、管控矿井生产建设过程中可能存在的安全风险、危害因素以及重大危险源，将风险控制在事故隐患形成之前，提升矿井安全风险分级管控水平，保障安全生产，结合矿实际，建立安全风险分级管控责任体系。
* 组织领导
建立矿井安全风险分级管控责任体系工作领导小组，负责相关工作的统筹安排及部署。
组  长：[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]
副组长：副矿长  [[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]
成  员：副总工程师  各科室科长  各队组负责人
领导小组下设办公室在[[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]，安全科科长兼任办公室主任，负责日常管理工作。
* 工作职责
** [[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]：对矿井安全风险分级管控工作负全面管理责任，负责组织各分管矿领导、副总工程师、相关业务科室人员对风险分级管控工作落实情况进行检查、督导工作。
** [[id:21350f90-65e1-46b4-8bb9-c24d0aae7787][安全副矿长]]：对全矿安全风险分级管控工作进行监督、检查和考核工作。
** [[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]：负责业务及分管范围内的生产组织管理、采煤、掘进、巷修、调度信息、职业卫生等方面的安全风险分级管控工作。
** [[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]：负责业务及分管范围内的矿井生产技术、重大技术方案、“[[id:eff5ca66-6f86-4513-b296-faba138024a2][一通三防]]”、应急管理及安全生产证照管理等方面的安全风险分级管控工作。
各大系统及巷道管理安全风险分级管控责任范围：[[id:e3da0fc4-7222-4c13-92ad-fcd5648c24f9][矿井通风系统]]、[[id:e02c4d8b-1d86-477c-8391-b3fa040f5689][安全监测监控系统]]、[[id:8deab42b-606b-45d7-8ee8-57455c81cc88][防灭火、防尘系统]]、[[id:b7761b13-0fa0-497a-b02d-c16f7ba3a61e][人员定位系统]]、[[id:c0114249-7c3f-40b6-b568-34cead49cfef][井下瓦斯抽采系统]]及井下炸药库管理。
地面设备设施管理安全风险分级管控责任范围：负责地面瓦斯发电管路及进气管路、矿井采煤影响区域的地质灾害管理。
** [[id:e37d6834-cade-43cc-ac8b-693a0a46d808][机电副矿长]]：负责业务及分管范围内的矿井主运煤（运矸）线路、6KV及以上电压等级的机电运输设备、设施等方面的安全风险分级管控工作；负责90KW及以上绞车提升运输设备、设施管理，架空乘人装置设备、设施管理等方面的安全风险分级管控工作。
各大系统及巷道管理安全风险分级管控责任范围：[[id:657760aa-8f65-4c80-b89c-9894e4b2428b][矿井供电系统]]、[[id:12e124e1-9542-4ef8-8fa9-ed22c0d767ac][主提升系统]]、[[id:df8389eb-7f10-4c47-8cd5-f76f1639926a][主运输系统]]、[[id:6b4cf7e8-dec5-4455-95b7-c7f562da0e5b][主压风系统]]、[[id:4812a127-85c4-4d53-b685-087267368bc9][主供水系统]]、[[id:8864ef4e-c79d-4f88-bc3c-66af2aff2a62][主排水系统]]、[[id:90fb36e2-1c15-44d5-a2f1-6b5ae03c0d4b][通信联络系统]]及矿井水仓、水泵房、变电所等机电硐室的巷道巡查管理的安全风险分级管控工作。
地面设备、设施管理安全风险分级管控责任范围：负责地面35KV及6KV变电所、主要通风机房、地面注氮泵、地面瓦斯气柜、地面民用瓦斯气管路及供水管路。
** 副总工程师：负责协助[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]和分管矿领导，抓好分管技术业务范围内的安全风险分级管控工作。
** 矿属各业务科室按照工作职责划分，认真抓好管理及业务责任范围内的安全风险分级管控工作，抓好风险分分级管控措施的落实工作。
矿属各队组队长是本队安全风险分级管控工作的第一责任人，对本队安全风险分级管控负全面管理责任；班队长对本班队生产作业场所安全风险分级管控措施的落实负直接责任；职工对本岗位作业场所安全风险分级管控措施的落实负直接责任。各队组负责本队安全风险分级管控管理工作，做好相关资料的收集、归档管理和上报工作。
安全科负责建立矿井安全风险分级管控台账，做好安全风险分级管控工作相关资料的收集、整理、统计、归档管理和上报工作。
* 安全风险辨识范围及方法
** 辨识范围
风险辨识范围包括：矿井各大生产系统、采煤掘进巷修顶板管理、瓦斯、水、火、煤尘、爆破、机电运输、设备设施、地质灾害、矸石山、消防、瓦斯气管路、危化品、食品卫生、道路交通、地面设施、人员密集场所等。
** 辨识方法
通过组织召开安全风险辨识专题会，结合安全生产情况、图纸资料等进行安全风险辨识。各岗位人员，对照安全风险清单、管控措施要求，对现场“人、机、环、管”等方面进行安全风险辨识，落实安全风险管控措施。
* 安全风险辨识评估
** 年度辨识评估
每年底由矿长组织各分管矿领导、副总工程师和相关业务科室、队组进行年度安全风险辨识、评估，结合矿生产系统、设备设施、作业场所等部位和环节，重点对矿井瓦斯、水、火、煤尘、顶板、爆破、机电运输、提升运输系统等容易导致群死群伤的危险因素开展安全风险辨识、评估；根据辨识、评估结果，由矿组织生产技术科、安全科、机运科、通风科等单位相关人员，编制年度安全风险评估报告和重大安全风险清单，并制定相关管控措施；将辨识评估结果应用于确定下一年度安全生产工作重点，并指导完善下一年度生产计划、灾害预防处理计划、应急救援预案。
** 专项辨识评估
*** 新水平、新采区、新工作面设计前，由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]组织有关业务科室开展1次专项辨识，重点辨识地质条件和重大灾害因素等方面存在的安全风险。根据辨识、评估结果，指导生产工艺选择、生产系统布置、设备选型、劳动组织确定等。
*** 生产系统、生产工艺、主要设备设施、重大灾害因素等方式重大变化时，由分管矿领导组织有关业务科室开展1次专项辨识。重点辨识、评估主要环境、生产过程、重大灾害因素和设备设施运行等方面存在的安全风险。根据辨识、评估结果，补充完善重大安全风险清单并制定相应管控措施，指导重新编制或修订完善作业规程、操作规程。
*** 启封火区、排放瓦斯、突出矿井过构造带及石门揭煤等高危作业实施前，新技术、新材料试验或推广新应用前，连续停产1个月以上的采掘工作面复产复工前，由分管领导组织副总工程师、业务科室、队组等开展1次专项辨识，重点对作业环境、工程技术、设备设施、现场操作等方面存在的安全风险，根据辨识、评估结果，补充完善重大安全风险清单并制定相应管控措施，作为编制安全技术措施依据。
*** 矿发生死亡事故或涉险事故、出现重大事故隐患和省内发生重特大事故后，由矿长组织分管矿领导、副总工程师和业务科室、队组相关人员开展1次针对性的专项辨识，识别安全风险辨识结果及管控措施是否存在漏洞、盲区。根据辨识、评估结果，补充完善重大安全风险清单并制定相应管控措施，指导修订完善设计方案、作业规程、操作规程、安全技术措施等技术文件。
*** 专项安全风险辨识评估报告，由分管矿领导指定相关队组人员收集、整理，并形成专项安全风险辨识评估报告，并交安全科备查。
* 检查分析
** 月度检查分析
每月矿[[id:6eb1b561-9672-4f49-8e57-51adf34fde91][矿长]]组织对重大安全风险管控措施落实情况和管控效果进行一次检查分析，针对管控过程中出现的问题调整完善管控措施，并结合年度和专项安全风险辨识评估结果，布置月度安全风险管控重点，明确责任分工。安全科负责对检查分析情况进行收集、整理，形成矿井月度安全风险管控措施落实情况的分析报告，制定安全风险管控重点。
** 旬检查分析
各分管矿领导每旬针对分管范围内月度安全风险管控重点实施情况进行一次检查分析，检查管控措施落实情况，不断完善和改进管控措施，并由分管矿领导指定相关队组编制成安全风险管控检查分析报告。
* 安全风险分级管控流程
** 安全风险等级标准
根据《[[id:d631ad17-62b5-4b22-94e1-9049861b847d][煤矿安全风险预控管理体系规范]]》、《[[id:17e148e8-8f3f-4a57-acc3-21bef7ccf63d][煤矿安全风险分级管控标准化评分表]]》及国家标准、规范，结合矿实际，采用LEC评估法（LEC评估法附后）对找出的风险点进行评估定级，将安全风险等级从高到低划分为重大风险、较大风险、一般风险和低风险四个风险等级，分别用红、橙、黄、蓝四种颜色标识。
*** 重大风险（红色）：是指可能造成人员伤亡和主要系统损坏的。
*** 较大风险（橙色）：是指可能造成人员伤害，但不会降低主要统损坏的。
*** 一般风险（黄色）：是指不会造成人员伤害，但会降低主要系统性能或损坏的。
*** 低风险（蓝色）：是指可能造成现场存在隐患及一定经济损失的，但不会造成人员伤害和主要系统损坏的。
煤矿LEC评价法，对辨识出的安全风险进行逐项评估，该方法用与系统风险有关的三种因素指标值的乘积来评价操作人员伤亡风险大小，这三种因素是：L为发生事故的可能性大小，E为人体暴露在这种危险环境中的频繁程度，C为一旦发生事故会造成的损失后果。采取半定量计值法，给3种因素的不同等级分别确定不同的分值，再以3个分值的乘积D来评价危险性的大小，其简化公式为：D=L×E×C。
根据乘积D来评价危险性，将风险等级分为红、橙、黄、蓝四级预警颜色，其中D≥160为重大风险，对应红色；70≤D＜160为较大风险，对应橙色；20≤D＜70为一般风险，对应黄色；D＜20为低风险，对应蓝色。
分值标准量化见下表：
事故发生的可能性（L）
| 分数值 | 事故发生的可能性   |
|     10 | 完全可以预料       |
|      6 | 相当可能           |
|      3 | 可能，但不经常     |
|      1 | 可能性小，完全意外 |
|    0.5 | 很不可能，可以设想 |
|    0.2 | 极为不可能         |
|    0.1 | 实际不可能         |
暴露于危险环境的频繁程度（E）
分数值	暴露于风险环境的频繁程度
10	连续暴露
６	每天工作时间内暴露
３	每周一次，或偶然暴露
２	每月暴露一次
１	每年几次暴露
0.5	非常罕见地暴露
发生事故产生的后果（C）
分数值	发生事故产生的后果
100	10人以上死亡或50人以上重伤或直接经济损失5000万元以上。
40	3-9人死亡或10-49人重伤或直接经济损失1000-5000万元。
15	1-2人死亡或10人以下重伤或直接经济损失1000万元以下。
7	伤残（严重、重伤、或造成一定财产损失。
3	重伤（致残、或造成较小财产损失）。
1	轻伤（需要救护、或造成财产损失）。
风险分值（D）
风险分值	风险等级	预警颜色
≥160	重大风险	红
70≤D＜160	较大风险	橙
20≤D＜70	一般风险	黄
D＜20	低风险	蓝
** 安全风险管控要求
*** 年度安全风险辨识、评估及专项辨识结束后，分别由矿长和各分管矿领导组织相关队组及人员进行安全风险等级划分，建立一整套安全风险数据库、重大安全风险清单，并按照风险等级进行分类管理。
*** 安全风险辨识评估、定级结束后，要组织编写安全风险综合评估书，明确辨识的时间和区域、存在的风险和等级、管控措施和建议等内容。
*** 根据辨识、评估存在的安全风险制定管控措施，必须从制度、管理、措施、装备、应急、责任、考核等方面逐一落实管控措施，由矿长、分管副矿长亲自组织实施，按照“矿、队、班组、岗位”逐级分解落实责任，并根据现场实际情况，及时修订完善管控措施，确保风险管控有效、措施落实到位。
*** 对现场辨识出的不同类别安全风险，必须明确应急处置程序和措施，划定为重大、较大安全风险的区域必须设定作业人数上限。经评估存在不可控风险的，必须立即停止区域作业或停止设备运行，撤出危险区域人员，督促责任单位制定措施进行整改，整改完毕后再重新进行评估并进行实时监控。
*** 矿领导按照《[[id:149bc76b-2a8b-4a4a-8e0e-f88f2167b860][煤矿领导带班下井及安全监督检查规定]]》，严格执行煤矿领导带班制度，跟踪重大安全风险管控措施落实情况，发现问题及时整改。
*** 各业务科室要突出管控重点，对重大危险源和存在重大安全风险的生产系统、生产区域、生产工艺、岗位点等实行重点管控，有针对性地开展日常管控工作。
*** 建立安全风险公告制度。在井口或存在重大安全风险区域的显著位置，公告存在的重大安全风险、管控责任人和主要管控措施,由安全科具体负责。
** 工作要求
*** 各队组必须按上级部门和矿要求，统筹兼顾，明确职责，精心组织，细化具体工作要求和措施，做到部署到位、责任落实到位、安全风险辨识、评估到位、防范措施到位。强化重点领域或关键环节安全风险分级管控，做到排查全覆盖、不留死角，确保取得实效。
*** 严格按照“谁主管、谁分管、谁负责”和“谁辨识评估、谁签字、谁负责”的要求，加强各队组工作开展情况的监督检查和考核奖惩工作，对消极应付、工作落后和管理不到位的按矿有关规定进行责任追究，建立长效机制，持续推动安全风险分级管控工作深入开展。
*** 各队组要探索采用信息化管理手段，实现对安全风险的记录、跟踪、统计、监测和预警等全过程的信息化管理。加强信息共享和协调联动，及时将安全风险区域的有关信息及应急处置措施告知受风险影响的相邻作业区域队、班组、岗位。
*** 由矿安培中心负责，每年至少组织一次安全风险辨识评估技术专项培训；各科室每年对全矿所有入井人员和地面关键岗位人员进行以年度和专项安全风险辨识评估结果、与本岗位相关的重大安全风险管控措施为主的教育培训，使其熟悉掌握矿井风险类别、危险源辨识和风险评估方法、风险管控措施，提升安全风险管控能力。
