:PROPERTIES:
:ID:       160ce87e-597c-4066-b0f6-e6a58334ef02
:END:
#+title: 防爆设备入井安装验收管理制度
* 防爆电气设备的领用
** 防爆电气设备的领用（包括五小电器），矿使用队组必须配置专（兼）职的防爆电气设备管理员，设备管理员应由责任心强、熟悉防爆电气设备完好性能的人员承担。
** 严格执行岗位责任制，使用队组防爆电气设备管理员到矿物资供应科库房或设备组库房领用防爆电气设备时，必须和库管员、电检组、设备组等有关人员一起对领用的设备进行验收；到矿机运科（防爆电机车）领用防爆电气时，必须和机运科质量检查员、电检组、设备组等有关人员一起对领用的设备进行验收。
** 防爆电气设备的验收，严格按照《煤矿安全规程》、《煤矿矿井机电设备完好标准》及有关规定和标准进行。做到入井前的防爆电气设备必须有“产品合格证”、“防爆合格证”、“煤矿矿用产品安全标志”和安全性能可靠。
** 防爆电气设备的发放，设备验收合格后，由电检组组织参加验收的人员在防爆设备检修验收单上签字和签发入井许可证，使用队组设备员办理设备领用手续。
* 防爆电气设备入井
** 防爆电气设备领回后，设备员通知安装人员按照防爆标准配齐安装时所需的零部件，并将领回的设备记入台帐管理，汇报机电负责人落实入井运输责任人。
** 防爆电气设备的入井必须有入井许可证，入井许可证应注明设备的名称、规程、型号、编号、使用队组和电检员姓名，入井许可证应贴置于设备的合适位置。
** 防爆电气设备在入井运输过程中，运输责任人必须做到轻拿轻放，做好设备的防染尘、防进水工作，确保安全无损地运到安装地点。
** 防爆电气设备运到安装地点，确定完好无损，防爆性能符合要求后才准予安装。
* 防爆电气设备的安装
** 防爆电气设备验收合格后，安装责任人必须严格按照《煤矿井下机电设备完好标准》进行安装，按技术员核定的整定值整定，确保设备安全保护装置齐全、灵敏可靠，安全防护装置齐全、牢固可靠，做到不失爆。
** 防爆电气设备安装工作完成后。属日常生产补充或更换的设备，由机电技术员组织安装责任人和使用责任人进行移交验收。属安装工程由矿指定有关队组组织移交验收，确定防爆性能符合要求后才准予投入使用。
* 防爆电气设备使用维修
** 防爆电气设备验收合格在安装完毕投入使用前，要对设备进行挂牌管理，标志牌应填写设备型号、设备用途、设备容量、设备整定值、设备责任人。做到实际整定值与标志牌整定值相符，开关、五小设备要按照标准化的规定，做到上架上板。
** 责任人的职责范围和工作质量要求：
*** 防爆电气设备的使用维修由经过培训考核合格的矿井井下电钳工承担，并持证上岗，负责设备的维护检修，熟悉掌握防爆电气设备的结构、性能、完好标准和检修标准，做到每天对设备检查维护一遍，按轮修计划的要求，在每月底提出下月的检修计划，使之经常保持安全完好的状态，消灭电气设备失爆。
*** 负责防爆电气设备过流保护、接地保护、漏电保护的整定，保证电气三大保护完整、灵敏、可靠。
*** 有计划地对设备进行巡回检查，严格执行日检、周检、月检、季检计划，并认真做好检查、检修记录，发现问题主动汇报处理。
*** 在检查中发现失爆或重大问题时，必须责令被检查队组当场处理，检查员在现场监督直至处理完后方可离开。
*** 遵守各项规章制度，特别是停送电制度，严格按照安全技术操作规程管好用好防爆电气设备。坚守工作岗位、按时保质保量地完成各项电气维护、检修任务，使之安全正常运行。
