:PROPERTIES:
:ID:       33f90fdd-ce17-4799-a433-c634dbf575bf
:END:
#+title: 瓦斯异常情况分析报告制度
* 瓦斯异常情况汇报处理程序
** 瓦检员、安全员、现场施工人员及其他人员，发现施工地点瓦斯异常时，立即停止该区域内及回风系统内一切作业，撤离人员，及时查明原因，并向矿调度室汇报。
** 监控系统地面中心站值班室必须24小时有监控员值班，发现瓦斯传感器显示值出现大增幅、瓦斯曲线不正常及临近报警值时，及时向矿调度室汇报，矿调度员立即电话通知该工作面瓦检员，查明原因，采取措施，进行处理，并将瓦斯异常原因、处理措施及处理结果汇报矿调度室，并矿调度室做好记录。
** 监控系统地面中心站如果出现采、掘工作面瓦斯浓度达到1%后，矿调度室必须立即电话通知该工作面瓦检员、安全员停止该区域内及回风系统内一切作业，撤离人员、查明原因，采取措施，进行处理。
** 监控员做好报警记录的同时，应立即汇报矿调度室，矿调度室在接到通知后，立即通知该工作面瓦检员、安全员对停工及处理全过程进行监督检查。
** 瓦检员在停工处理完毕，检查工作面、回风流及上隅角等地点瓦斯浓度降到《煤矿安全规程》规定范围内，汇报矿调度室，由矿调度室下达恢复生产命令。
** 瓦检员处理过程中，发现瓦斯浓度未被有效控制，持续升高，达到超限浓度时，应立即停止该工作面一切作业，切断电源，汇报矿调度，矿调度汇报值班矿领导。安全员与瓦检员一起组织将工作面人员沿进风路线撤退到进风巷道内，同时在工作面巷道口设置栅栏，揭示警标。
** 矿值班领导立即会同通风科领导制定措施，并电话通知通风科队长，在半小时内赶到现场，指挥处理，处理完毕汇报矿调度，并做好记录。矿调度领导确认隐患排除后，方准下达撤除警戒、恢复送电、人员进入工作面生产的命令。
** 矿井总回风巷瓦斯浓度达到0.75%时，必须立即汇报通风科及矿值班领导。矿值班领导在接到汇报后，应立即电话通知该队组各工作面瓦检员、安全员停止该区域内一切作业，由上一级配电室切断电源，将工作面人员沿进风路线撤出，并在所有能进入巷道口设置栅栏，揭示警标，悬挂“禁止入内”牌。安全员做好断电、撤人、设置警戒全过程的监督检查工作。矿值班领导应立即汇报矿总工程师，由矿总工程师组织相关人员制定处理办法，通风科副科长入井处理。处理完毕后要汇报矿值班领导、总工程师，矿调度要做好记录。
** 瓦检员在现场检测过程中，发现瓦斯涌出异常，瓦斯浓度突然增高，应立即同安全员停止该区域内一切工作，切断电源，撤出人员，汇报矿调度。矿调度接到汇报后，应立即由通风科值班领导和矿调度值班领导查明原因，制定措施，通知通风科队长在半小时内赶到现场，进行处理。矿值班领导现场指挥。处理完毕后要汇报矿调度值班人员，并做好记录。
* 主扇、局扇异常情况汇报处理程序
** 监控系统井上监测员发现主扇、局扇停风等异常情况时，必须立即通知矿调度值班领导。矿调度值班领导应立即召集相关人员，进行排查解决。
** 矿调度员应立即通知停电、停风区域瓦检员、安全员迅速将工作面人员沿进风线路撤退到进风流或撤退出井。
** 当主扇10分钟内不能恢复正常时，立即由当班调度值班员按一下顺序通知到人头，作好记录，机电副矿长、矿总工程师、安全副矿长、矿长、其他矿领导、机运科、通风科、安全科、物资供应科，同时作好原始记录。
** 故障排除后，恢复主扇、局扇启动时，必须严格执行以下程序：
*** 恢复主扇排放矿井瓦斯时，主扇启动前，先打开回风井口安全硐室风门，采用风流断路方法进行排放。
*** 在主扇出口瓦斯浓度小于2%时，（必须保井下的风流瓦斯排出后）再逐渐将风门关闭。
*** 通风系统正常后，主扇出风口瓦斯浓度降到1%以下时，方可由通风科值班领导指挥瓦检员入井检查通风瓦斯情况，矿井回风流瓦斯浓度降到0.75%时，向矿调度汇报，调度员报告相关领导。
*** 矿值班领导确认回风流瓦斯浓度降到0.75%以下时，命令地面变电所向井下送电，（按高压操作程序操作）变电所值班员接到矿调度值班领导向队组井下配电室送电命令后，向队组井下配电室送电，队组井下配电室值班员接到矿调度值班领导向队组局扇送电命令后，方准送局扇专用电。
*** 局扇恢复通风前，瓦检员必须首先检查局扇及其开关附近10m风流中的瓦斯浓度小于0.5%的情况下，方可人工启动局扇，局扇由外向内逐台启动，只有排完一个巷的瓦斯后方准启动下一台局扇，启动局扇后，控制风量进行排放，严格检查局扇外部的风量，严禁“循环风 ”、“一风吹”排放，确保排出的瓦斯和二氧化碳浓度与全风压风流汇合处小于1.5%。
*** 瓦检员只有检查排放巷内瓦斯浓度与全风压风流汇合处小于1.0%时方准进入巷内，进入巷内时两人一组，缓慢前进，一前一后保持10m距离，不断测定瓦斯浓度，只有检测瓦斯浓度小于1.0%时，方准继续前行。
*** 瓦斯排放完毕，瓦检员经检查巷内瓦斯浓度小于1.0%，二氧化碳浓度小于1.5%，且稳定30min后，局扇方可正常供风，同时向矿调度汇报，矿调度向值班领导汇报，并记录在案。
*** 全部掘进巷道排放完毕，恢复正常通风后，由电工检查巷内电器设备，当局扇供风巷电器设备检查完毕，证明完好后，方可汇报调度室，由值班领导下达恢复队组内一切电器设备电源。
*** 安全员负责排瓦斯与复电全过程的监督检查，确保万无一失。
*** 瓦斯排放完毕，队组生产恢复正常后，调度应及时汇报通风科科长、矿值班领导、总工程师。
** 监控系统井上监测员发现主扇负压传感器数值变化超过30Pa时，应立即汇报通风科值班领导及调度值班人员，调度值班人员联系机运科风机房确认水柱计变化是否超过30Pa，当风机房水柱计变化超过30Pa时，汇报调度值班领导、通风科、机运科值班人员，调度值班人员组织人员采取措施，进行处理。
** 当水柱计变化为+30Pa，通风科、队组派人查看井下主要通风巷道，是否有冒落、塌死情况。
** 当水柱计变化为-30Pa，通风科派人查看井下巷道，是否有风流短路情况。
* 一氧化碳异常情况汇报处理程序
** 现场瓦检员发现一氧化碳有异常情况后必须及时汇报矿调度。
** 矿调度室接到报告后，立即向主要负责人报告。
** 矿值班领导或主要负责人应迅速采取措施，查明原因，落实相应的防范措施。
** 现场瓦检员检测出一氧化碳浓度超过10PPm，及时通知矿调度，由矿调度通知矿救护队派人查明原因，采取措施进行处理。
** 现场瓦检员检测出检测出一氧化碳浓度超过20PPm，及时通知矿调度，矿调度通知值班领导，值班领导下令立即撤出井下所有人员。矿总工组织相关人员分析原因，采取措施，进行处理。
** 井下任何一个地点的一氧化碳浓度超过24ppm，必须立即撤出井下所有人员，通知矿救护队派人查明原因，进行处理，处理完毕后方可组织井下作业。
