:PROPERTIES:
:ID:       01a37201-6023-4cdb-9459-488334b59c05
:END:
#+title: 通风系统管理制度
为了认真贯彻落实“系统合理、设施完好、风量充足、风流稳定”的要求，确保通风可靠。特制本制度。
* 矿成立以总工程师为组长的通风系统管理领导小组，明确各级管理人员及相关部门的职责，并严格落实。
* 矿井通风系统必须合理、稳定、可靠；风量、风速满足《煤矿安全规程》的相关要求。
* 矿井必须有完整的独立通风系统。新水平延伸、开拓新巷道或改变一翼、一个水平等矿井通风系统时，必须编制通风设计及安全措施，报上级部门批准后实施。
* 矿井开拓新水平和准备新巷道的回风，必须引入总回风巷或主要回风巷中。在未构成通风系统前，可将此种回风引入生产水平的进风中；但矿为瓦斯喷出或有煤（岩）与瓦斯（二氧化碳）突出危险的矿井，开拓新水平和准备新巷道时，必须先在无瓦斯喷出或无煤（岩）与瓦斯（二氧化碳）突出危险的煤（岩）层中掘进巷道并构成通风系统，为构成通风系统的掘进巷道的回风，可以引入生产水平的进风中。上述2种回风流中的瓦斯和二氧化碳浓度都不得超过0.5%，其他有害气体浓度必须符合规程的相关规定，并制订安全措施，报矿总工程师审批。
* 生产水平和矿井必须实行分区通风。
准备矿井，必须在矿井构成通风系统后，方可开掘其他巷道。采煤工作面必须在矿井构成完整的通风、排水系统后，方可回采。
高瓦斯矿井、有煤（岩）与瓦斯（二氧化碳）突出危险的矿井的必须设置至少1条专用回风巷。瓦斯矿井开采煤层群和分层开采采用联合布置的矿井，必须设置1条专用回风巷。
矿井进、回风巷必须贯穿整个巷道，严禁一段为进风巷、一段为回风巷。
* 采、掘工作面应实行独立通风，严禁2个采煤工作面之间串联通风。
开采有瓦斯喷出或有煤（岩）与瓦斯（二氧化碳）突出危险的煤层时，严禁任何2个工作面之间串联通风。
煤矿井下内1个采煤工作面与其相连接的1个掘进工作面、相邻的2个掘进工作面，布置独立通风有困难时，在制定措施后，可采用串联通风，但串联通风的次数不得超过1次。
构成新区段通风系统的掘进巷道或采煤工作面遇地质构造而重新掘进的巷道，布置独立通风确有困难时，其回风可以串入采煤工作面，但串联通风的次数不得超过1次；构成独立通风系统后，必须立即改为独立通风。
采用串联通风的工作面，必须在进入被串联工作面的风流中安设瓦斯传感器，且瓦斯和二氧化碳浓度都不得超过0.5%，其他有害气体浓度都应符合规程的相关规定。
采用串联通风的工作面必须制定安全技术措施报矿总工程师审批。
* 有突出危险的采煤工作面不得采用下行通风。
* 采掘工作面的进风和回风不得经过采空区或冒顶区。
无煤柱开采沿空送巷和沿空留巷时，应采取防止从巷道的两帮和顶部向采空区漏风的措施。矿井在同一煤层、同翼、煤矿井下相邻正在开采的采煤工作面沿空送巷时，采掘工作面严禁同时作业。
* 采空区必须及时封闭。必须随采煤工作面的推进逐个封闭通至采空区的连通巷道。回采工作面开采结束后45天内，必须在所有与已回采相连通的巷道中设置防火墙、封闭巷道。采煤工作面回采结束后，必须在45天内永久封闭完毕。否则，追究队组负责人的责任。
* 控制风流的风门、风桥、风墙、风窗等设施必须可靠。不应在倾斜运输巷中设置风门；如果必须设置风门，应安设自动风门或设专人管理，并制定专门的安全技术措施，防止矿车或风门碰撞人员以及矿车碰坏风门。开采突出煤层时，工作面回风侧不应设置风窗。
* 矿井通风阻力测定每3年至少进行1次。矿井转入新水平生产或改变一翼通风系统后，必须重新进行矿井通风阻力测定。
* 必须加强巷修工作，严格落实巷道维修制度，确保矿井通风阻力符合规程相关规定。
* 进、回风井之间和主要进回风巷之间的联络巷内，必须砌筑永久性风墙；需行人、过车的联络巷内，必须安设两道联锁的正向风门和两道反向风门。
* 尽可能避免出现角联通风巷道，特殊情况下，须在角联通风巷道内安设风速和瓦斯传感器。
* 对井下不用的巷道或废弃巷道应及时封闭，以简化和优化通风系统。
* 矿主要通风机为轴流式风机，能进行反转反风，但必须确保能在10分钟内改变巷道中的风流方向；当风流方向改变后，主要通风机的供给风量不应小于正常供风量的40%。
每年应进行1次反风演习；矿井通风系统有较大变化时，应进行1次反风演习。
矿总工程师每季度至少组织1次反风设施检查，发现问题必须及时整改，并作好详细记录。
矿井必须建立测风制度，每10天进行一次全面测风。对采掘工作面和其他用风地点，应根据实际需要随时进行测风，每次测风结果都应写在测风记录牌上。应根据测风结果采取措施，进行风量调节。
* 矿井必须按月绘制通风系统图、通风系统立体示意图和矿井通风网络图，并及时修改。图中标明风流方向、风量和通风设施的安设地点。多煤层同时开采时，必须绘制分层通风系统图。
* 矿井每月必须编制风量计划报告，报矿总工程师审批。报告应包括矿井总风量、采掘工作面风量、硐室及其他地点风量等内容。
生产过程中，若采掘工作面瓦斯涌出量变化较大，应按实际瓦斯涌出量重新核定风量，编制风量调整报告，报矿总工程师批准后实施。
* 矿总工程师每月至少组织一次通风系统审查。审查应包括下列主要内容：
** 审查矿井、采掘工作面及硐室专用回风系统是否符合要求、是否存在角联通风巷道、通风系统是否合理、进回风系统是否畅通、通风设施是否可靠等；
** 审查井下巷道的风量、风速、瓦斯浓度、温度、一氧化碳浓度、二氧化碳浓度等是否符合规程规定；
** 审查采、掘工作面的布置是否合理；
** 审查井下巷道断面是否满足通风要求、巷道状况是否完好；
* 矿井通过日检、周检或旬检、月检、专项检查等方式检查通防系统，确保通风系统合理、符合规定。
* 矿井通风系统巡视检查时间应符合下列要求：
** 回风巷道（包括硐室）、角联通风巷道由瓦检员每班至少巡视检查一次。
** 掘进工作面、采煤工作面及其运输巷、回风巷由瓦检员每班至少巡视检查一次；
** 通风系统发生变化（包括巷道贯通、新建通风设施、主要通风机负压发生变化等异常情况），须及时对相关巷道进行巡视检查。
* 矿井通风系统巡视检查内容应符合下列要求：
** 通风系统巡视检查内容应包括巡视地点、风量、风速、断面、长度、主要影响地点、与上旬相比、巷修情况、以及通风系统存在问题等；
** 矿井主要进、回风巷、硐室等井下所有通风的巷道都应纳入通风系统巡视检查范围。
** 矿井主要进、回风巷及硐室的巡视检查每旬进行一次，并做好记录。
* 通风系统巡视检查领导小组应认真收集、分析、整理各种资料，并建立通风系统巡视检查台帐。
* 盲巷管理必须符合以下规定
** 临时停工的巷道不得停风；否则，必须切断电源、撤出人员、设置栅栏、揭示警标，并设专职瓦检员在栅栏前检查瓦斯、二氧化碳及其他有害气体浓度，当浓度超过《规程》规定，不能立即处理时，必须在24小时内进行封闭。
封闭盲巷时，密闭内至少安设一趟瓦斯抽采管路，管径不得小于100毫米，且瓦斯抽采管路进入密闭段，必须进行绝缘处理。
构筑临时密闭必须经上级部门批准后方可实施，封闭时间超过15天的巷道必须构筑永久密闭。
** 有计划停电、停风前，必须制定专门的通风管理安全技术措施，经矿总工程师审批后实施。
** 采、掘工作面在相距盲巷20米前，生产技术科必须下达过巷警戒通知书，通风科必须制定专门的通风、瓦斯管理安全技术措施，经矿总工程师审批后方可实施等。
* 启封盲巷必须遵守以下规定
** 启封前，必须编制专门的安全技术措施，经矿总工程师批准后，由救护队负责实施。
** 启封前，密闭内、外瓦斯浓度必须降到1.0%以下后，方可进行启封工作。
** 启封工具必须是铜制工具等。
