:PROPERTIES:
:ID:       d2883f7d-32f9-4193-9644-0cd1f83735e2
:END:
#+title: ZDY-4000及ZDY-4600履带式钻机安全操作规程
* 一般要求
** 钻车司机必须经过专门技术培训，掌握机器的一般性保养、维护和故障处理知识，经考试合格并取得上岗证，否则不准操作。
** 钻车司机每班编制2人。1人操作机器，1人照看电缆或更换钻杆的配合工作。
** 机器要保持整洁，各运动机件间不得残留矸石、煤粉等杂物，接班司机要认真检查机器和部件工作情况。机器应每天清理（冲洗）。
** 钻车工作运转时，司机要注意周围情况，注意安全，钻车运转范围内不许站人或放置任何设备、工具。
** 严禁非司机人员驾驶和操作。
* 开车前的准备工作
** 检查油管、操作手柄、电缆、接头、履带行走部件、转盘、推进导轨、动力旋转马达、钻杆、钻头、螺栓、螺帽是否紧固，各运转部件有无卡碰、杂物等。检查两侧履带的张紧度，履带松弛的下垂量在10～20mm之间。检查各软管及接头是否可靠固定，有无渗漏油现象。
** 开机试车：
*** 启动：在操作台上，按启动按钮，给电机送电。
*** 停止：在启动状态下，按停止按钮，主回路失电，而使油泵电动机停止运转。
*** 检查油泵电机转向：当油泵电机转向与油泵转向（油泵转向为顺时针）相反时，应立即停机，以防油泵无油空转干磨，造成液压泵随坏。只要将电机三相进线中任意两相调换，便可改变电机转向。
* 机器的启动和行走
** 电源启动和停止
检查磁力启动器切换手柄应于调整后的位置，并处于锁紧状态，按下操纵台上的启动按钮，机器处于工作状态；按下停止按钮，可切断电源。
** 启动油泵
在总电源启动后，按下启动按钮，油泵电机运转，液压系统处于工作状态。
** 机器的前后行走
当油泵正常工作后，同时轻轻推动左右行走马达控制阀操纵手柄，机器应向前行走，后拉则机器后退。推动左侧手柄，机器右转弯，反之则左转弯。当两个操纵手柄处于中位时，机器停止行走。
* 钻孔作业的操作
** 钻杆、钻头安装到位和对准孔位
*** 主机钻车固定手柄操作：将机器调整到需要作业的位置，将行走马达操作手柄置于零位，停止行走；将安装好钻头的首根钻杆通过前端准星及夹持器放好；再操作回转支撑手柄将导轨旋转到需要打孔的方向；操作底板支撑油缸手柄，使前后底板支撑油缸升起（必要时垫道木）；操作顶板支撑立柱油缸，使立柱升紧顶板。如果顶板空顶或超出支撑高度，可将随机的加长段套在两立柱上，使立柱加长；操作角度调节油缸手柄，调整好要求打孔的仰俯角，并锁紧斜撑抱箍螺栓；如果需要导轨垂直升降，在锁紧斜撑抱箍螺栓的同时，松开立柱抱箍螺栓，操作调角油缸使其升降到指定位置后，在锁紧立柱抱箍螺栓（为了垂直升降负载减小，最好先将动力头推进到前端）。
*** 操作操作台底部的两位换向开关阀，使副泵系统进入工作阀组。
*** 操作推进油缸手柄，使动力头退到尾部，将钻杆（根据环境条件同时加装2-3根）通过动力头内孔及卡盘连接到首根安装好钻头的钻杆。
*** 将通水变头安装在钻杆尾部。把联动阀手柄达到“相反”。操作卡盘手柄至“紧”；再操作马达旋转手柄至“正转”。
*** 操作推进油缸手柄至“前进”，在钻头接近钻孔点时，打开通水阀门，使钻杆匀速推进煤壁。可根据钻进工况任意调节钻进速度。
** 钻进及加接钻杆
*** 第一次加装钻杆钻进至煤壁后，先停止通水，再停止马达旋转，然后将卡盘加紧钻杆反转扭松钻杆，操作推进油缸手柄至“后退”到够一棵钻杆长度时，及时安装下一棵钻杆；把前卡盘手柄放置在“松”；操作推进油缸手柄至“前进”，打开通水阀门，以此类推，直至达到要求深度。
*** 进钻注意事项：
- 钻进前先开水，再旋转推进；停止时先停止推进，再停止旋转，最后停水。
- 钻进时，推进速度要匀速，不可猛推猛拉，根据钻进工况调节钻进速度，注意钻口排屑情况和工作压力表显示，正常情况下随着深度增加，工作压力也不断升高，工作压力在3~12Mpa之间，在工作压力超过12Mpa时要停止推进，在马达旋转情况下排粉，直到工作压力降至正常幅度内在钻进。
** 作业人员要求
*** 开机前必须完成三项检查
*** 电压检查；本机以电动机为源动力，机器在额定工况下作业时，电压的变化值应在额定值的±10℅范围之内。
*** 电缆检查；检查电缆有否破损，悬挂是否可靠，不得将电缆在巷道底板上拖拉摩擦。
*** 机器检查；检查机器各部有无松动，有无损伤。检查软管及接头是否可靠固定，有无渗油现象。检查油箱液面是否在液位计中间位置。
*** 移动机器时司机应坐在司机椅上，严禁横向拽拉多路阀操纵手柄，严禁踩踏液压油管。
*** 司机坐姿要正确，注意力要集中，用左右手分别握住两侧操作手柄，两眼根据机器行进过程，注视前、后方配套设备及人员、电缆等。机器到位时应使行走马达操纵手柄于中位。
*** 钻孔作业前的准备要仔细，对孔位要正确。操纵阀控制人员要与更换钻杆人员密切配合，动力回转装置动作时应注意工作机构和人员的安全。
*** 移动机器时，必须有专人监护电缆，人员位于机器5m以外，带有口哨，发现问题立即发出停机信号。
*** 正确操作机器行走，司机在确认前后两侧无人和其它杂物后方可操作移动机器。应熟练掌握定位、对孔，熟练掌握装、卸钻杆，熟练掌握启停钻机。做到三准确、四注意。（三准确：机器移位要准；对孔定位要准；打孔深度与对应的推进速度要调整准确。四注意：注意周围人员；注意不碰撞其它障碍及设备；注意机器不压电缆及油管；注意根据工作压力表的变化情况调整钻进速度。）
*** 机器行走中如遇大块散落岩石，应停机，将其挪开；严禁机器履带碾压大块岩石。钻孔作业受阻或钻具卡死时，避免长时间憋压操作，使系统溢流发热。
