:PROPERTIES:
:ID:       50031713-c517-4e5f-a9a1-075d26bb32d9
:END:
#+title: 防突技术管理制度
为规范防突技术管理，确保采掘工作面施工期间的安全，特制定此管理制度:
* 生产技术科编制年度、季度、月度生产建设计划时，通风科编制年度、季度、月度防突措施计划，保证抽、掘、采平衡，并 随生产计划一同下发。
* 防突工作必须坚持“区域防突措施先行、局部防突措施补充”的原则，按照“一矿一策、一面一策”的要求；实现“先抽后建、先抽后掘、先抽后采、预抽达标”。突出煤层必须采取两个“四位一体”综合防突措施，做到多措并举、可保必保、应抽尽抽、效果达标，否则严禁采掘活动。
* 根据矿生产接续，由生产技术科编制《[[id:b00dd8d2-63d3-4576-88d7-08e7c36296d9][采掘工作面地质说明书]]》，通风科根据地质说明书编制《[[id:c733a4ce-8474-457d-a3b6-0da0b2e641cf][采掘工作面区域防突请示]]》上报上级部门，上级部门批复后，由施工队组技术员编制《[[id:b2373389-dc09-4d4f-b04a-3fcbd612b65c][采掘工作面作业规程]]》，通风科编制《[[id:6ec20fc9-9e5f-44c7-a5df-64af6f39cc2d][采掘工作面消突评价报告]]》、《[[id:4905db59-9d6f-49f8-86bd-06e16ce7a88f][采掘工作面区域防突措施]]》、《[[id:b28ed70e-c268-4d77-a29c-64a7fbb44755][采掘工作面局部防突措施]]》、《[[id:93851e21-07d2-4bad-bfe3-f4e29cd45c58][采掘工作面专项防突设计]]》，严格按照编制的措施、设计、规程开展防突工作。
* 生产技术科每年进行1次矿井开拓煤量、准备煤量、回采煤量（以下简称“三量”）统计和分析，“三量”可采期的最短时间为：
** 开拓煤量可采期不得少于5年。
** 准备煤量可采期不得少于14个月。
** 回采煤量可采期不得少于5个月。
当“三量”低于上述要求时，应当及时降低煤炭产量，制定相应的灾害治理和采掘调整计划方案。
* 参与防治煤与瓦斯突出管理和施工人员必须经过培训，考试合格后，持证上岗。
* 在新水平的设计中，必须编制防治突出专项设计，专门设计应包括开拓方式、煤层开采顺序、采煤方法、通风方式、支护形式突出危险性预测方法，预抽煤层瓦斯、局部防治突出措施等内容。
* 巷道的布置设计应当满足《[[id:ac297814-dd56-4281-bb19-072895ad4a32][防治煤与瓦斯突出细则]]》第22条规定。
* 通风科负责通风设施构筑、维护及风量调整工作，保证通风系统符合《防治煤与瓦斯突出细则》第31条规定。
* 矿井安全监测系统必须灵敏、可靠，确保断电迅速。
* 生产技术科要密切关注采掘工作面情况，做好煤岩状况描述工作，及时修改图纸，并对前方的地质构造做出准确预测，及时以书面形式通知相关队组及有关矿领导。
* 机运科、队组必须加强电气设备管理，保证正常完好，杜绝失爆。
* 通风科负责防治突出措施的编制，防治突出措施内容必须包括地质资料、突出危险性预测方法、防治突出具体措施及其效果检验的方法、安全防护措施以及执行防治突出措施的责任制。
* 防治突出措施随工作面推进必须及时修改、补充完善。
* 施工队负责向所有人员贯彻、考核已批准的防突措施。
* 通风科负责对残余瓦斯压力、残余瓦斯含量、K1值、钻屑量、抽放量等数据进行测定和整理，形成采掘工作面消突评价报告和抽采达标评价报告，经矿领导和相关科室会审，确保工作面消突后再生产。
* 防突工作严格执行两个“四位一体”综合防突措施，并符合下列规定：
** 地质测量工作必须遵守下列规定：
*** 生产技术科地质测量组与通风部门共同编制矿井瓦斯地质图。图中应当标明采掘进度、被保护范围、煤层赋存条件、地质构造、突出点的位置、突出强度、瓦斯基本参数及绝对瓦斯涌出量和相对瓦斯涌出量等资料，作为区域突出危险性预测和制定防突措施的依据。矿井瓦斯地质图更新周期不得超过1年工作面
瓦斯地质图更新周期不得超过3个月。
*** 地质测量部门在采掘工作面距离未保护区边缘50m前，编制临近未保护区通知单，并报总工程师审批后交有关采掘队组。
*** 在突出煤层顶、底板掘进岩巷时，地质测量部门必须提前进行地质预测，编制巷道剖面图，及时掌握施工动态和围岩变化情况，验证提供的地质资料，并反馈通报给通风科和采掘队组；遇有较大变化时，随时通报。
** 通风系统应当符合下列要求：
*** 井巷揭穿突出煤层前，具有独立的、可靠的通风系统。
*** 突出矿井、有突出煤层的巷道、突出煤层工作面应当有独立的回风系统，并实行分区通风，回风巷和区段回风石门是专用回风巷。突出煤层采掘工作面回风应当直接进入专用回风巷。突出煤层掘进巷道的回风不得经过有人作业的其他回风巷。
*** 开采有瓦斯喷出、有突出危险的煤层，或者在距离突出煤层最小法向距离小于10m的区域掘进施工时，严禁2个工作面之间串联通风。
*** 突出煤层双巷掘进工作面不得同时作业，其他突出煤层区域预测为危险区域的采掘工作面，其进入专用回风巷前的回风严禁切断其他采掘作业地点唯一安全出口。
*** 突出矿井采煤工作面的进、回风巷内，以及煤巷、半煤岩巷和有瓦斯涌出的岩巷掘进工作面回风流中，回风巷及总回风巷，应当安设全量程或者高低浓度甲烷传感器；突出矿井采煤工作面的进风巷内甲烷传感器应当安设在距工作面10m以内的位置。
*** 开采突出煤层时，工作面回风侧不得设置调节风量的设施。
*** 严禁在井下安设辅助通风机。
*** 局部通风机通风必须采用压入式。
** 各项防突措施按照下列要求贯彻实施：
*** 施工前，施工防突措施的队组向本队从业人员讲解并严格组织实施防突措施。
*** 采掘作业时，应当严格执行防突措施的规定并有详细准确的记录。由于地质条件或者其他原因不能执行所规定的防突措施的，施工队组必须立即停止作业并报告矿调度室，经总工程师组织有关人员到现场调查后，由原措施编制部门提出修改或者补充措施，并按原措施的审批程序重新审批后方可继续施工；其他部门或者个人不得改变已批准的防突措施。
*** 矿长和总工程师应当每月至少1次到现场检查各项防突措施的落实情况。
*** 矿安全科、通风科等业务科室应当随时检查综合防突措施的实施情况，并及时将检查结果分别向矿长和总工程师汇报，矿长和总工程师应当对发现的问题立即组织解决。
*** 矿进行安全检查时，必须检查综合防突措施的编制、审批和贯彻执行情况。
** 防突技术资料的管理工作应当符合下列要求：
*** 发生突出后，由矿长组织现场调查，认真填写突出记录卡片，提交专题调查报告，分析突出发生的原因，总结经验教训，制定对策措施。
*** 每年第一季度将上年度发生煤与瓦斯突出矿井的基本情况调查表、煤与瓦斯突出记录卡片、矿井煤与瓦斯突出汇总表连同总结资料报省级煤矿安全监管部门、驻地煤矿安全监察机构煤炭行业管理部门。
*** 所有有关防突工作的资料均存档。
*** 每年对全年的防突技术资料进行系统分析总结，掌握突出规律，完善防突措施。
** 开采保护层区域防突措施应当符合下列要求：
*** 开采保护层时，应当做到连续和规模开采，同时抽采被保护层和邻近层的瓦斯。
*** 开采近距离保护层时，必须采取防止误穿突出煤层和被保护层卸压瓦斯突然涌入保护层工作面的措施。
*** 正在开采的保护层工作面超前于被保护层的掘进工作面，其超前距离不得小于保护层与被保护层层间垂距的3倍，并不得小于100m。保护层的有效保护范围应根据工作面推进，在每个被保护层瓦斯地质图上动态更新。
*** 开采保护层时，应当不留设煤（岩）柱。特殊情况需留煤（岩）柱时，必须将煤（岩）柱的位置和尺寸准确标注在采掘工程平面图和瓦斯地质图上，在瓦斯地质图上还应当标出煤（岩）柱的影响范围。在煤（岩）柱及其影响范围内采掘作业前，必须采取区域预抽煤层瓦斯防突措施。
当保护层留有不规则煤柱时，按照其最外缘的轮廊划出平直轮廓线，并根据保护层与被保护层之间的层间距变化，确定煤柱影响范围。在被保护层进行采掘工作时，还应当根据采掘瓦斯动态及时修改煤柱影响范围。
** 采取井下预抽煤层瓦斯区域防突措施时，应当遵守下列规定：
*** 穿层钻孔或者顺层钻孔预抽区段煤层瓦斯区域防突措施的钻孔应当控制区段内整个回采区域、两侧回采巷道及其外侧如下范围内的煤层：倾斜、急倾斜煤层巷道上帮轮廓线外至少20m（均为沿煤层层面方向的距离，下同），下帮至少10m；其他煤层为巷道两侧轮廓线外至少各15m。
*** 顺层钻孔或者穿层钻孔预抽回采区域煤层瓦斯区域防突措施的钻孔应当控制整个回采区域的煤层。具备条件的，井下预抽煤层瓦斯钻孔应当优先采用定向钻机施工。
*** 穿层钻孔预抽井巷揭煤区域煤层瓦斯区域防突措施的钻孔应当在揭煤工作面距煤层最小法向距离7m以前实施，并用穿层钻孔至少控制以下范围的煤层：石门和立井、斜井揭煤处巷道轮廓线外12m（急倾斜煤层底部或者下帮6m），同时还应当保证控制范围的外边缘到巷道轮廓线（包括预计前方揭煤段巷道的 轮廓线）的最小距离不小于5m。
当区域防突措施难以一次施工完成时，可分段实施，但每一段都应当能保证揭煤工作面到巷道前方至少20m之间的煤层内，区域防突措施控制范围符合上述要求。
*** 穿层钻孔预抽煤巷条带煤层瓦斯区域防突措施的钻孔应当控制整条煤层巷道及其两侧一定范围内的煤层。
*** 顺层钻孔预抽煤巷条带煤层瓦斯区域防突措施的钻孔应当控制煤巷条带前方长度不小于60m，煤巷两侧控制范围与本条第一项中巷道外侧的要求相同。
*** 定向长钻孔预抽煤巷条带煤层瓦斯区域防突措施的钻孔应当采用定向钻进工艺施工预抽钻孔，且钻孔应当控制煤巷条带煤层前方长度不小于300m和煤巷两侧轮廓线外一定范围。
*** 当煤巷掘进和采煤工作面在预抽煤层瓦斯防突效果有效的区域内作业时，工作面距未预抽或者预抽防突效果无效区域 边界的最小距离不得小于20m。
*** 厚煤层分层开采时，预抽钻孔应当一次性穿透全煤层，不能穿透的，应当控制开采分层及其上部法向距离至少20m、下部10m范围内的煤层，当遇有局部煤层增厚时，应当对钻孔布置做相应的调整或者增加钻孔。
*** 对距本煤层法向距离小于5m的平均厚度大于0.3m的邻近突出煤层，预抽钻孔控制范围与本煤层相同。
*** 煤层瓦斯压力达到3MPa的区域应当采用地面井预抽煤层瓦斯，或者开采保护层，或者采用远程操控钻机施工钻孔预抽煤层瓦斯。
*** 不具备按要求实施区域防突措施条件，或者实施区域防突措施时不能满足安全生产要求的突出煤层或者突出危险区，不得进行开采活动，并划定队组。
** 揭煤作业包括从距突出煤层底（顶）板的最小法向距离5m开始，直至揭穿煤层进入顶（底）板2m（最小法向距离）的全过程，应当采取局部综合防突措施。在距煤层底（顶）板最小法向距离5m至2m范围，掘进工作面应当采用远距离爆破。揭煤作业前应当编制井巷揭煤防突专项设计，并报总工程师审批。
揭煤作业应当按照下列程序进行：
*** 探明揭煤工作面和煤层的相对位置。
*** 在与煤层保持适当距离的位置进行工作面预测（或者区域验证）。
*** 工作面预测（或者区域验证）有突出危险时，采取工作面防突措施。
*** 实施工作面措施效果检验。
*** 采用工作面预测方法进行揭煤验证。
*** 采取安全防护措施并采用远距离爆破揭开或者穿过煤层。
** 井巷揭穿突出煤层的专项防突设计至少应当包括下列主要内容：
*** 井巷揭煤区域煤层、瓦斯、地质构造及巷道布置的基本情况。
*** 建立安全可靠的独立通风系统及加强控制通风风流设施的措施。
*** 控制突出煤层层位、准确确定安全岩柱厚度的措施，测定煤层瓦斯压力的钻孔等工程布置、实施方案。
*** 揭煤工作面突出危险性预测及防突措施效果检验的方法、指标，预测及检验钻孔布置等。
*** 井巷揭煤工作面防突措施。
*** 安全防护措施及组织管理措施。
*** 加强过煤层段巷道的支护及其他措施。
** 煤巷掘进和采煤工作面的专项防突设计应当至少包括下列内容：
*** 煤层、瓦斯、地质构造及邻近区域巷道布置的基本情况。
*** 建立安全可靠的独立通风系统及加强控制通风风流设施的措施。
*** 工作面突出危险性预测及防突措施效果检验的方法、指标以及预测、效果检验钻孔布置等。
*** 防突措施的选取及施工设计。
*** 安全防护措施。
*** 组织管理措施。
** 煤巷掘进工作面采用超前钻孔作为工作面防突措施时，应当符合下列要求：
*** 巷道两侧轮廓线外钻孔的最小控制范围：近水平、缓倾斜煤层5m，倾斜、急倾斜煤层上帮7m、下帮3m。当煤层厚度大于巷道高度时，在垂直煤层方向上的巷道上部煤层控制范围不小于7m，巷道下部煤层控制范围不小于3m。
*** 钻孔在控制范围内应当均匀布置，在煤层的软分层中可适当增加钻孔数。预抽钻孔或超前排放钻孔的孔数、孔底间距 等应当根据钻孔的有效抽放或排放半径确定。
*** 钻孔直径应当根据煤层赋存条件、地质构造和瓦斯情况确定，一般为75～120mm，地质条件变化剧烈地带也可采用直径42～75mm 的钻孔。若钻孔直径超过120mm 时，必须采用专门的钻进设备和制定专门的施工安全措施。
*** 煤层赋存状态发生变化时，及时探明情况，再重新确定超前钻孔的参数。
*** 钻孔施工前，加强工作面支护，打好迎面支架，背好工作面煤壁。
