:PROPERTIES:
:ID:       3b91ea5c-b999-4bcb-98c0-4fe9259e8fa1
:END:
#+title: 防灭火管理制度
为认真贯彻落实《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》、《[[id:16c17b43-298e-4015-861c-485b5db3f4fd][矿井防灭火规范]]》及上级有关规定和要求，加强矿井井下防灭火管理工作，杜绝火灾事故，确保矿井安全生产，结合矿实际情况，制定本制度。
* 总则
** 矿井火灾是指：发生在煤矿井下及地面井口附近，威胁到矿井安全生产和人员安全的火灾。
** 矿井火灾事故发生的原因有两种，一是外部火源引起的火灾，称外因火灾；二是煤炭本身的物理化学性质的内在因素引起的火灾，称内因火灾。
** 制定矿防灭火管理制度的依据：《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》、《[[id:16c17b43-298e-4015-861c-485b5db3f4fd][矿井防灭火规范]]》、《[[id:865ea219-2775-401b-95d6-9a3323f4580f][矿井密闭防灭火技术规范]]》、《[[id:c560654d-d53d-453a-95fe-1ef093a9483d][煤矿用氮气防灭火技术规范]]》、《[[id:55e7c87d-c4dd-4e14-9f05-e0f9a9643840][煤矿自然发火束管监测系统通用技术条件]]》、《[[id:8c12cd33-d4ec-492a-bfe9-8b22085c3c7c][矿防灭火管理制度]]》等。
* 组织机构及职责
（责任制统一在岗位安全生产责任制中叙述，建议改为防灭火领导小组，下设工作组，相应职责即可。）
** 成立防灭火领导小组
组  长：矿长
副组长：总工程师
成  员：安全副矿长  生产副矿长  机电副矿长  各专业副总工程师  通风科科长  安全科科长  机运科科长  各队队长
领导小组下设办公室，由通风科科长任办公室主任，负责防灭火相关工作。
** 各岗位职责
1.矿长防灭火职责
（1）认真贯彻执行上级有关防灭火工作的政策、标准、指令，坚持“安全第一、预防为主、综合治理”的方针，对矿井井下防灭火工作负第一责任。
（2）按照上级有关规定配备足够有经验的，工作能力强的管理人员及工作人员保证通风系统的稳定。
（3）保证矿井井下防灭火工作所必须资金投入，并在矿财力所允许的条件下尽量筹措资金应用于防灭火的新技术、新手段，保证矿井井下防灭火治理工作装备现代化。
（4）负责组织领导井下火灾事故的抢救和处理，及时组织追查分析事故的原因和制定今后应队组的预防措施。
2.总工程师防灭火职责
（1）认真贯彻执行上级有关防灭火工作的政策、标准、指令，坚持“安全第一、预防为主、综合治理”的方针直接对井下防灭火工作行使技术管理责任，并向矿长负责。
（2）负责组织领导井下防灭火技术措施的编审工作。
（3）负责组织处理井下防灭火工作中出现的技术问题。
（4）负责领导矿井井下防灭火的科学研究和技术革新工作。
（5）参加和组织矿井重大井下防灭火事故的抢救以及善后处理追查、分析原因、制定防范措施等工作。
3.安全副矿长防灭火职责
（1）认真贯彻执行上级有关防灭火工作的政策、标准、指令，坚持“安全第一、预防为主、综合治理”的方针直接对井下防灭火的安全工作负责，并向矿长负责。
（2）负责每月组织一次井下防灭火检查，对发现的事故隐患及时安排处理。
（3）负责监督检查井下防灭火资金的落实情况。
（4）负责组织和领导重大井下防灭火事故分析、处理工作。
4.生产副矿长防灭火职责
（1）负责分管方面的井下防灭火工作落到实处，对所管方面井下防灭火存在的问题及时制定整改措施，并组织落实。
（2）严格按照井下防灭火的规定组织生产，加强管理，杜绝井下防灭火事故发生，负责保证采掘专业规程措施必须符合井下防灭火专项措施要求。
（3）在安排和布置生产地区的同时必须考虑井下防灭火工作需要。
（4）负责矿主要通风巷道维护管理工作，对严重失修巷道及时组织整修，确保矿井主要通风巷道断面满足通风要求和巷道完好可靠。
5.机电副矿长防灭火职责
（1）组织检查电气设备和电缆的安全情况，保证安全用电，负责井下电焊、气焊工作技术措施的审批按《煤矿安全规程》严格把关。
（2）负责对井下防灭火方面设备到货催办落实。
（3）加强对矿井主要通风机的管理，保证其安全正常运转。
6.各专业副总防灭火职责
（1）认真贯彻执行上级有关防灭火工作的政策、标准、指令，抓好井下防灭火工作的技术革新及时推广先进技术，总结先进经验。
（2）在总工程师的领导下，对井下防灭火技术业务管理工作具体负责。
（3）参加井下防灭火事故的抢救、追查、分析、处理工作，从技术上吸取教训，改进技术管理。
7.通风科科长防灭火职责
（1）负责组织井下防灭火技术方案、通风系统改造及工程计划、技术措施编制审批工作，保证采掘专业规程措施必须符合井下防灭火专项措施要求。
8.安全科科长防灭火职责
（1）负责监督安全规程、技术措施的落实情况，处理好井下防灭火与安全生产的关系。
（2）及时处理井下防灭火工作中出现的安全隐患。
（3）充分发挥安全监督检查的领导职能，及时发现井下防灭火工作中出现的安全问题，并监督有关部门及时解决，严肃处理井下防灭火中出现的“三违”现象。
9.机运科科长防灭火职责
（1）负责矿电气设备的管理，保证井下电气设备合格，杜绝失爆和电气设备失火事故。
（2）负责矿机电运输设备的管理，组织检查，保证机电运输设备完好，杜绝机电运输设备磨损、失火事故。
10.各队队长防灭火职责
（1）负责组织队组从业人员防灭火知识培训，保证从业人员掌握防灭火基本知识，具备基本灭火技能，熟悉矿井火灾避灾路线。
（2）及时解决防灭火问题，重大问题向总工程师、矿长汇报。
（3）负责矿井主要通风巷道维修管理工作，对严重失修巷道及组织整修，确保主要通风巷道断面满足要求和巷道完好可靠。
* 一般规定
** 生产和在建矿井必须制定井上、下防火措施。矿井的所有地面建筑物、煤堆、矸石山、木料场等处的防火措施和制度，必须符合国家有关防火的规定。
** 木料场、矸石山、炉灰场距离进风井不得小于80m。木料场距离矸石山不得小于50m。
** 矿井必须设地面消防水池和井下消防管路系统。井下消防管路系统应当敷设到采掘工作面，每隔100m设置支管和阀门，但在带式输送机巷道中应当每隔50m设置支管和阀门。地面的消防水池必须经常保持不少于200m3的水量。消防用水同生产、生活用水共用同一水池时，应当有确保消防用水的措施。
开采下部水平的矿井，除地面消防水池外，可以利用上部水平或者生产水平的水仓作为消防水池。
** 有自然发火煤层群的开拓、开采必须符合下列规定：
*** 新矿井设计或生产矿井新水平延深时，必须对所有煤层进行煤炭自燃倾向性鉴定，按照鉴定结果制定矿井防灭火管理办法和编制矿井防灭火安全技术措施；
*** 合理选择巷道位置，集中运输大巷和总回风道应布置在岩层或无自然发火煤层内，如果布置在自然发火煤层内，必须砌碹或锚喷，巷道后的空顶处，必须用不燃性材料充填密实，或用无腐蚀性、无毒性的材料进行处理，不得漏风；
*** 合理确定采煤方法。必须采用丢煤少、坑木消耗低，回采速度快的回采方法。
** 严格按设计规范及上级有关规定合理确定生产布局，防范相邻矿井相通。已连通的通道必须设置切实可靠的隔离设施。
** 进风井口应装设防火铁门，防火铁门必须严密并易于关闭，打开时不妨碍提升、运输和人员通行，加强检查维修；如果不设防火铁门，必须有防止烟火进入矿井的安全措施。
** 井上、下每一生产水平均要按规定设立消防材料库。
** 在所有运输转载点设置消防洒水灭尘喷雾。
** 矿井每季度应对井上、下消防管路系统、防火门、消防材料库和消防器材等的设置情况进行1次检查，发现问题，及时解决。
** 井下工作人员必须熟悉灭火器材的使用方法，并熟悉本职工作区域内灭火器材的存放地点。
** 矿井必须配备气体分析装置，完善气体分析制度，随时开展气体分析工作，为防灭火工作提供可靠依据。
** 强化防灭火安全培训和教育，排查治理火灾隐患，开展火灾事故应急救援演练。
* 井下火灾的防治
** 外因火灾的预防
1.井下爆破材料库、机电设备硐室、检修硐室、材料库、井底车场、使用皮带运输机或液力偶合器的巷道以及采掘工作面附近（皮带及刮板运输机包括机头机尾），必须备有灭火器材，其数量、规格和存放地点，应在应急救援预案及采掘作业规程中作出规定，保证灭火器材完好。
井下工作人员必须熟悉灭火器材的使用方法，并熟悉工作区域内灭火器材的存放地点。
2.井下硐室防火
（1）井下硐室（包括变电所、机电硐室、绞车硐室、炸药库）必须设在通风良好的进风巷道中，并有单独直通矿井总回风的回风系统；
（2）硐室必须使用不燃性材料构筑；
（3）硐室的进出口要装设向外开启的铁板防火门（每组不少于两道），防火门内要设置向外开启的铁栅栏并加锁，平时敞开；
（4）在硐室的入口要备有灭火器、砂箱等灭火器材；
（5）硐室的防爆设备，高压配电开关要选择灵敏可靠的保护装置，并按规定试验维修。当电路发生漏电或短路时，能自动切断电源。
3.预防电气火源
（1）井下所有电气设备都不能超负荷运行，及时检查维护；低压网路的每条支线都必须按负荷大小装设分支保险或自动跳闸装置。为避免电气设备及电缆漏电，低压网路装置必须安装漏电继电器；使用调整好的电流继电器和热力继电器，在电流增大或发热时，能自动切断电源；
（2）井下电缆的选用、敷设、连接和使用必须符合《煤矿安全规程》（以下简称“规程”）的规定，电缆要悬挂好，防止撞击、挤压、坠落。电缆接头不论高、低电压或信号线都必须用冷补方法或接线盒，消灭鸡爪子、羊尾巴、明接头，杜绝电气失爆；
（3）井下空气压缩机必须安装使用合格的压力表、安全阀、断油（或断水）保护、过流保护、超温保护等装置，必须使用闪点不低于215℃的压缩机油，必须安设专人看管，落实压缩机操作规程、检修等管理制度和措施，防止发生火灾事故。
（4）矿灯应保持完好，出现电池漏液、亮度不够、电缆破损、灯锁失效、灯头密封不严、灯头圈松动、玻璃破裂等情况时，严禁发放；严禁在井下拆开、敲打、撞击矿灯；矿灯必须有可靠的短路保护装置；
（5）加强井下电气设备检修和维护的管理，严禁带电作业，防止电火花，必须采用矿用本质安全型、防爆型的电气设备。按规定检查电气设备的防爆性能，不符合要求的要及时更换和修理，否则不准使用。井口和井下电气设备必须有防雷电和短路装置，防止井下杂散电流。局部通风机开关必须设风电闭锁、瓦斯电闭锁、检漏装置；
（6）加强瓦斯抽采站避雷装置、抽采管路防雷保护接地装置、泵站防回火、供水等安全设施的检查和维护，确保设施安全功能的实现；
（7）对目前仍需使用的留管应采取抗静电、防雷电、防火等安全措施，如在采面留管中接一根PVC管材等能阻燃、不导电的抽采管等。
4.井下焊接防火
井下和井口房内不得从事电焊、气焊和喷灯焊接等工作。如果必须在井下主要硐室，主要进风井，井口房或其它地点进行电焊、气焊、喷灯焊接等工作时，每次必须制定安全措施，由矿长批准，并遵守下列规定：
（1）指定专人在场检查和监督。
（2）电焊、气焊和喷灯焊接等工作地点的前后两端各10米的井巷范围内，井巷应当是不燃性材料支护，并有供水管路，有专人负责喷水，焊接前应当清理或者隔离焊碴飞溅区域内的可燃物。上述工作地点应当至少备有2个灭火器。
（3）焊接时必须有专职瓦检员检查瓦斯，必须还要有安全员，以及救护队员在现场监护，且焊接地点20米内风流瓦斯浓度不超过0.5%，只有在检查证明作业地点附近20米范围内巷道顶部和支护背板后无瓦斯积存时，方可进行作业。
（4）在井口房、井筒和倾斜巷道内进行电焊、气焊和喷灯焊接等工作时，必须在工作地点的下方用不燃性材料设施接受火星。
（5）电焊、气焊和喷灯焊接等作业完毕后，作业地点应当再次用水喷洒，并有专人在作业地点检查1h，发现异常，立即处理。
（6）突出矿井井下进行电焊、气焊和喷灯焊接时，必须停止突出煤层的掘进、回采、施钻、支护以及其他所有扰动突出煤层的作业。
煤层中未采用砌碹或者喷浆封闭的主要硐室和主要进风大巷中，不得进行电焊、气焊和喷灯焊接等工作。
5.预防摩擦火源
（1）机械传动的皮带和皮带轮，必须保持正常转动，防止发热燃烧；
（2）急倾斜煤层溜煤筒溜煤时，要做好槽头洒水、润湿煤炭，才准进入溜煤筒；
（3）在掘进工作面迎头施工前探钻孔、瓦斯抽采钻孔等钻孔时，必须将工作面的一氧化碳传感器安设在打钻地点的回风侧5-10米位置；在其它未安设一氧化碳传感器的打钻地点的回风侧5-10米位置，打钻负责人必须悬挂一氧化碳测定器；
若使用压风排渣，现场负责人必须在施工地点下风侧5-10米范围内安设一氧化碳传感器（便携式检测仪），必须使用好风水切换装置，并在钻孔口使用喷雾或除尘装置除尘。无一氧化碳检（监）测仪器，使用好水、风水切换装置。发现钻孔着火、出现烟雾或一氧化碳异常等情况，必须立即停止钻进，快速往钻孔里注水，并封堵孔口。水、风水切换装置不完好或不能正常使用时，严禁施工钻孔；严禁打钻，并追究相关人员的责任。
（4）强化打钻应急教育和管理工作，打钻过程中出现有刺激性气味、高温、冒烟等异常现象时，现场施工人员必须立即关闭压风阀门，开启供水阀门对钻孔注水，并用湿棉纱或其它不燃性材料将孔口堵严、堵实等应急措施进行处理；
（5）在富含磷铁矿结核、石英等物质的煤层进行机采时，应保证足够的风量和良好的通风系统；
（6）斜井提升、无极绳运输、回柱绞车、耙斗机等机械的地滚、导向轮必须保持良好动作。加强提升运输的管理，防止钢丝绳与各种金属产生摩擦和跑车事故的发生；
（7）局扇外壳变形，应停止运转；
（8）使用底封式刮板运输机（转载机），应加强链轮和机尾轴的管理，保证正常运转。加强综掘机铲煤板及胶带运输机机头机尾的管理，杜绝摩擦火源；
（9）刮板输送机机尾滚筒轴必须有卡板固定，防止轴承损坏时随滚筒旋转产生机械火花。刮板输送机、皮带机头、机尾下部要清空浮煤，保证空气流畅，防止瓦斯聚积，防止机械摩擦产生火花后点燃瓦斯引起火灾；
（10）加强掘进巷道的支护质量和支护强度，杜绝支护失效时产生的摩擦火源。采煤工作面上下巷要及时替棚，不得将金属棚、锚杆等支护材料留在采空区内，避免产生摩擦火源。
（11）风筒、隔爆水槽、隔爆水袋等必须采用防静电、阻燃且已取得煤矿矿用安全标志的产品。
（12）风筒必须采用防止摩擦起火的材料进行吊挂。
6.预防放炮火源
（1）放炮工作必须严格遵守规程，严禁采用糊炮、隔炮和挑杆炮等易产生火焰的爆炸器材和爆破工艺；
（2）严禁采用放炮方式崩落卡在溜煤眼中的煤矸；
（3）炮眼必须使用水炮泥和黄泥封堵，严禁使用粉煤或易燃物代替炮泥，炮眼的封泥量和装药量应严格遵守规程规定，未按规定装水炮泥不准放炮；
（4）严禁使用失效的火药和雷管；
（5）雷管脚线与联接线、联接线与放炮母线接头必须分别用绝缘胶布包裹并悬空；
（6）放炮时必须严格执行“一炮三检查”制度。
7.井下使用的煤油、汽油和变压器油必须装入盖严的铁桶内，由专人押运送至使用地点，剩余的煤油、汽油和变压器油必须运回地面，严禁在井下存放。
8.井下使用的润滑油、棉纱、布头和纸等，必须存放在盖严的铁桶内。用过的棉纱、布头和纸，也必须放在盖严的铁桶内，并由专人送到地面处理，不得乱扔乱放。严禁将剩油、废油泼洒在井巷或硐室内。
9.严格执行井口检身制度。禁止携带香烟、火柴、打火机、汽油等易燃物品入井，井口房和通风机房附近20米内，禁止烟火和用火炉、电炉取暖。
** 内因火灾的预防
1.开采容易自燃和自燃的煤层时，在开采设计中，必须明确选定自然发火观测站或观测点的位置并挂牌管理，站点间距一般为40米，断层及高冒区等特殊地点不受此限。
凡有自燃煤层的矿井，应建立监测系统，确定煤层自然发火的标志气体和建立自然发火预测预报制度。所有自燃煤层采、掘工作面均应按规定安设一氧化碳传感器。
所有检测分析结果必须记录在专用的防火记录簿内，发现自然发火指标超过或达到临界值等异常变化时，立即发出自然发火预报，采取措施进行处理。
2.矿井每天至少测定一次采煤工作面采空区抽采管内的瓦斯浓度、一氧化碳浓度和温度，每周必须至少分析一次抽采管内的气体组分；矿井每天至少测定一次密闭内的瓦斯浓度、一氧化碳浓度和温度，每周必须分析密闭内的气体组分，并作好详细记录。
发现异常情况，必须及时向矿总工程师汇报，由矿总工程师组织查明原因，采取有效措施进行处理。同时汇报上级部门信息中心及有关领导。
3.救护队每周至少测定、分析一次采煤工作面及密闭抽采管内的气体组分，并将分析结果及时报送上级部门。
发现异常情况，必须及时向矿总工程师汇报，由矿总工程师组织查明原因，采取有效措施进行处理，同时，汇报上级部门信息中心及有关领导。
4.井下作业地点严禁一氧化碳浓度超限作业，当发现作业地点或井巷一氧化碳浓度超过24ppm或自燃发火征兆（巷道温度、湿度增高,出现雾气、煤壁挂汗、有煤油味、汽油味等）时，必须停止工作、切断电源、撤出人员，采取有效措施进行处理。
5.采煤工作面内因火灾预防
开采有自燃发火危险的煤层，必须做到下列要求：
（1）采煤工作面必须采用后退式开采，并在煤层的发火期内采完。否则必须对采空区、突出和冒落孔洞等空隙喷洒阻化剂、注惰性气体、均压等措施，编制相应的防灭火设计，防止自然发火。
（2）注氮管必须敷设到切眼下口，经矿验收合格后，采面方可调试、回采。注氮管路三通必须一次安设齐全，严禁在回采过程中拆主管增加三通；
（3）采煤工作面开始回采前，应完善采空区注水系统；
（4）采煤工作面开始回采前，完善束管监测系统，并按规定安设一氧化碳传感器；
（5）当采煤工作面投产和通风系统形成后，必须按设计的防火门位置构筑好防火门墙，并储备足够数量的封闭防火门的材料；
（6）采煤工作面上、下巷必须采取替棚措施，采面上下巷（下巷下帮除外）的金属棚、托板、金属网、螺帽等金属材料必须全部回收，确保采空内无金属材料（抽采留管除外）。此项工作由采煤队长负责组织实施，由生产技术科、安全科、通风科责监督落实责任，发现没严格执行此项规定的，按重大隐患追查责任者责任。
（7）加强采煤工作面的管理，确保推进度不少于采长的一半；
（8）采煤工作面回采过程中（特别是过断层期间）要严格控制采高，确保采空区内减少或不留顶、底煤，并将采空区内浮煤清理干净，做到不丢或少丢浮煤；
（9）采空区内出现CO或CO呈上升趋势，必须采取施工注水钻孔注水的防灭火措施，注水钻孔处于采空区裂隙带。
（10）在采面安设束管对采空区内CO进行测定和取样分析，确定采空区自燃发火三带。
（11）采煤工作面采到停采线时，必须采取措施使顶板冒落严实，并施工注水钻孔对采空区进行注水；
（12）采煤工作面回采结束后，必须在45天内永久封闭结束。
6.掘进工作面内因火灾预防
在有自燃发火危险的煤层中掘进：
（1）掘进工作面开始施工前，按规定安设一氧化碳传感器；
（2）禁止空帮空顶，禁止堆积浮煤。较大的冒落空洞（冒高超过2米或空洞体积超过6立方米的）和突出空洞应采用阻燃剂将其充填；
（3）加强过断层期间的管理工作，严格控制顶板，杜绝出现高冒区。
7.密闭的采空区内因火灾预防，必须做到下列要求：
（1）严格落实密闭施工要求，尽可能减少采空区漏风；
（2）现有密闭质量不符合相关要求的，必须制定整改计划，采取有效措施进行处理，提高气密程度，确保密闭内的氧气浓度不大于12%；
（3）密闭前的杂物应清理干净，严禁将闭前的巷道用煤矸充填，确需充填的应有防止煤层或其它物品氧化聚热的措施；
（4）加强密闭内气体监测工作，每天对密闭内气体的瓦斯、氧气、一氧化碳和温度至少检测一次，每周对密闭内气体的组分分析一次；
（5）完善注氮系统，对密闭内氧气浓度大于12%或有一氧化碳的密闭，必须采取有效措施进行处理。
8.抽采钻孔内因火灾预防，必须做到下列要求：
（1）严格按矿相关要求进行封孔，确保钻孔不漏气；
（2）加强抽采钻孔内气体监测工作，每天对抽采钻孔主管内气体的瓦斯、氧气、一氧化碳和温度至少检测一次，每周对单个抽采钻孔内气体的组分检测一次；
（3）对检测出一氧化碳的钻孔，必须立即采样进行气体组分分析。
** 防灭火措施及其规定
1.采用阻化剂防灭火时，应遵守下列规定：
（1）选用的阻化剂材料不得污染井下空气和危害人体健康；
（2）必须在设计中对阻化剂的种类和数量、阻化效果等主要参数作出明确规定；
（3）应采取防止阻化剂腐蚀机械设备、支架等金属构件的措施。
2.采用氮气防灭火时，必须遵守下列规定：
（1）氮气源稳定可靠；
（2）注入的氮气浓度不小于97%；
（3）地面、井下制氮设备的供氮压力，可按《煤矿用氮气防灭火技术规范》的供氮压力公式计算，其管路末端的绝对压力应不低于0.2Mpa；
（4）从地面供氮时，当供氮压力小于1.6MPa时，输氮管路应选用无缝钢管。从井下供氮时，除应采用钢管外，在满足输氮压力的情况下，可选用耐压橡胶软管。但进人采空区或火区的管路必须采用无缝钢管；至少有1套专用的氮气输送管路系统及其附属安全设施；
（5）有能连续监测采空区气体成分变化的监测系统；
（6）有固定或移动的温度观测站（点）和监测手段；
（7）安排专人进行检测、分析和整理有关记录、发现问题及时报告处理等规章制度。
* 井下火灾处理与灭火
** 钻孔防火。向远离巷道的高温度点以及有发火危险的地点打钻，然后向其内注水降温，如空隙较大则可只注沙浆，将空隙堵满，然后再注入泥浆或其它阻燃剂。
** 挖出热源防火法。直接将火源或高温炽热物挖出来，以根除火灾隐患。
** 当掘进工作面、回采工作面风流系统中（除采面上偶角）发生火灾时，所有作业人员不得惊慌，必须听从当班班（队）长的统一指挥。当班瓦检员必须迅速检查着火点及其周边的瓦斯情况，若瓦斯不超限、风流稳定，班（队）长必须立即组织当班人员，采取一切可能的方法进行直接灭火，控制和消灭火灾。若瓦斯超限、风流不稳定时，班（队）长则应迅速带领所有作业人员沿避灾路线撤到地面。采面上偶角发现火灾时，不得直接灭火，必须立即撤出人员切断电源。当班班（队）长对现场灭火直接负责，是第一责任人，班（队）长在组织直接灭火的同时，必须迅速向矿调度室汇报，矿调度室接到井下火灾报告后，立即启动火灾事故应急救援预案，组织抢救灾区人员和实施灭火工作。
** 应急救援总指挥、副总指挥代表指挥部行使指挥权。现场灭火工作由矿应急救援总指挥任命有关人员全权指挥。应急救援总指挥、副总指挥是救灾工作的决策人员、对救灾工作全面负责，其他任何人员、包括上级派到救灾现场的代表人员，不得干预他们的决策指令，只能作为决策人的参谋。
** 抢救人员和灭火时，必须指定专人负责检测矿井空气成份和井下风流的变化状态，并定时定点将检测结果报告救灾指挥部和现场总指挥。
** 井下电气设备（电气设备硐室、井巷中的电气设备）着火时应先切断电源，未切断电源前，只准使用不导电的灭火器材，如：干粉灭火器、二氧化碳灭火器等进行灭火，禁止使用水等导电物质扑灭电气火灾。
** 井下处理火灾时，工作地点空气中的各种气体成份必须符合《煤矿安全规程》的规定，当瓦斯浓度在2%以下或在进风侧工作时，可由非救护队进行。
** 直接灭火人员应在进风侧进行灭火，如果必须在回风侧灭火时，在确保人身安全的情况下，采取必要的安全措施进行灭火工作。否则，应由救护队进行。
** 火灾处理过程中，严禁改变风量、风流方向和采取调压等方法，只能在保证安全的情况下，采取措施降低或减少某一处烟流而设的临时通风设施时，也要严加监视瓦斯的变化。当瓦斯超过2%时，必须解除通风设施。
** 高瓦斯矿井处理火灾时，对灾区进行合理的通风，对防止瓦斯爆炸有决定性的作用。在火灾处理过程中，必须掌握瓦斯的变化，合理调节风流。原则是有助于控制火势，又能冲淡瓦斯，及时排走瓦斯。不能随意减少或中断灾区的供风，必要时（瓦斯浓度上升）还应增加火区供风量；加强巷道维护，防止冒顶堵塞巷道，以免瓦斯积聚而产生爆炸。
** 上下山和运输平巷发火时，如果在火源的上风侧有掘进头和废巷，应将积存瓦斯的巷道严密封堵。在火源的下风侧有冒顶、废巷和掘进头积聚瓦斯时，对灭火人员威胁最大，为防止瓦斯爆炸应果断封闭火区，或者进行局部反风，将这些瓦斯封闭后，再组织人员灭火。
** 独头巷道发生火灾时，不能停风，要在保持正常通风或加大风量的条件下处理火灾。特别是上山独头煤巷发火，如果风机已停转，在无需救人的情况下，严禁进入侦察或灭火，应立即在远距离封闭。对于下山掘进煤巷迎头发火，在通风条件下，瓦斯浓度不超过2%时可直接灭火。若在下山中段发火时，无论通风与否，都不得直接灭火，要远距离封闭。
** 当直接灭火无效或不可能时，应封闭火区。在任何情况下（无论是高瓦斯矿井还是低瓦斯矿井），不准先封闭回风、后封闭进风。否则会造成火烟逆退或发生瓦斯爆炸。
** 当火灾发生在巷道中部时，设法直接灭火。采用水灭火时，水量要充足，要防止水蒸气伤人和水煤气爆炸。火源点以里有遇险人员待救时，灭火的同时，可打开压风管阀门加大压风量或将水管改送压风，以延长遇险人员待救时间，降低瓦斯浓度。但供气量不能过大，以免把高浓度瓦斯吹向火源点引爆。因人力、物力不足或火势太大，在短期内不能扑灭火灾或火区瓦斯浓度已超过2%并继续上升，火源以里瓦斯情况不明时，应在巷道口附近封闭火区。
** 井下火灾不能直接扑灭时，应及时予以封闭，封闭火区时，应就地取材、水泥砂浆作临时快速封闭，尔后再砌筑不燃性材料的永久密闭。
** 封闭火区时，先封闭与火区相关连而火区供风系统不受直接破坏的密闭，撤出灾区全部人员，然后再由救护队同时封闭进回风巷的密闭，并迅速撤离灾区。
** 火区封闭的全过程必须有救护待机，单独由救护队员施工抢救时，必须一个小队工作，一个小队待机，一个小队在地面待命，即三个小队。
* 火区防爆
** 灭火时，要采取有效措施严防瓦斯积聚、防止风流逆转，并把瓦斯控制在爆炸限度以外，才准进行火灾的扑灭工作。
** 尽量减少处理火区的人数，运料人员运完料后，要迅速撤离灾区。各调度室要协助防灭火领导小组将灾区工作人员登记清楚。井下撤离人员时，要指定专人负责清点人数向调度汇报，并做到有次序的撤离灾区。
** 当火势较大，用水直接灭火时，先从火源周围慢慢向火源中心浇水，切不可直接用水浇注火源中心，以免引起火灾气体散发和水煤气爆炸。
** 火区封闭后，24小时以内禁止人员进入灾区工作或检查。只有在24小时后由救护人员沿进风侧至回风侧依次对火区进行检查，在确保安全的情况下，再制定恢复工作的计划。
** 火区有爆炸危险时，必须先采取防爆措施，先用板闭隔断进风流或进回风流一起隔断的办法或设立防爆砂墙（防爆砂墙的长度不小于5米）等综合措施，防爆工作实施24小时后方能进行永久设施的施工。设置防爆砂墙时要在其保护下同时施工永久密闭。
** 永久设施的设置必须由救护队进行。永久设施必须安装有取样管、注浆管、放水管和反水池。取样管、注浆管在密闭的上部，放水管和反水池在密闭的下部。
* 火区管理
** 矿井的每一个火区，都要建立火区管理卡片，绘制火区位置关系图，由矿井通风科永久保存，此卡片在发生火灾后10日内报上级部门，每季末进行一次交换。
*** 火区卡片上应详细记录发火日期、原因、位置、范围、防火墙厚度，建筑材料、灭火处理过程、灌浆量以及空气成分、温度、气压变化等情况，并且要附有火区关系位置图，由矿通风科永久保存。
*** 火区位置关系图以通风系统图为基础绘制，即在通风系统图上标明所有火区的边界、防火墙位置、火源点位置、漏风路线。同时在图上注明火区编号、名称、发火时间，图中还应标明历次发火点的位置和发火时间。
** 火区封闭后，矿井防灭火领导小组要制定出火区密闭的观测检查措施并采取积极的措施继续灭火工作，如漏风检查、通风压力观测、气体取样分析检查、对火区进行风压平衡、惰气灭火、注浆灭火等等，并作好记录。
** 火区封闭面积过大，不便工作时，可以进行火区的锁封，火区的锁封工作，只能在火区处于稳定的状况下进行。但必须在锁封密闭的外侧设置严密的锁封风门（不少于两道）并将封闭的材料，工具备齐堆放在锁封风门以里，人员往来不得影响风流流动，只有当锁封密闭一次性建完以后，人员才准出来。
** 井下永久性火区密闭的管理必须符合下列规定：
*** 每个火区密闭前必须设置栅栏、揭示警标，禁止人员入内，并悬挂说明牌。记明密闭内外的沼气浓度、温度、测定日期、测定姓名。
*** 每班必须由矿山救护队检查通风工作，并测定水温、空气温度和空气成分。只有在确认火区完全熄灭、通风等情况良好后，方可进行生产工作。
*** 检查火区密闭外的空气温度、瓦斯浓度，火区密闭内外空气压差及其墙体。发现封闭不严或有其他缺陷或火区有异常变化时，必须采取措施及时处理。
*** 所有测定和检查结果，必须记入防火记录簿。
*** 矿井进行大的风量调整时，应测定火区密闭内的气体成分和空气温度。
*** 井下所有永久性火区密闭都应编号，并在火区位置关系图中注明。
** 火区同时具备下列条件时，方可认为火已熄灭：
*** 火区内的空气温度下降到30℃以下，或与火灾发生前该区的日常空气温度相同。
*** 火区内空气中的氧气浓度降到5.0%以下。
*** 火区内空气中不含有乙烯、乙炔，一氧化碳浓度在封闭期间内逐渐下降，并稳定在0.001%以下。
*** 火区的出水温度低于25℃，或与火灾发生前该区的日常出水温度相同。
*** 上述4项指标持续稳定的时间在１个月以上。
** 火区经过处理后，矿总工程师组织有关部门鉴定，通过取样分析，判断火区是否熄灭，符合熄灭条件时，才可写出火区注销报告（一式四份）报上级部门批准，火区没有注销前，应按有关规定对其进行管理。
火区注销报告应包括：火区基本情况；灭火总结（包括灭火过程、灭火费用和灭火效果等）；火区注销依据与鉴定结果；附图。
** 封闭的火区，必须经过取样化验分析，证明火区确已熄灭，才准启封。启封已熄灭的火区，必须先制定启封火区报告书（一式四份），经上级部门批准后方可启封。
启封火区报告书应包括：火区基本情况与灭火、注销情况；火区侦察顺序与防火墙启封顺序；启封时防止人员中毒、防止火区复燃和防止爆炸的通风安全措施；附图。
** 火区启封前，应在需要启封的密封外侧设置严密的锁封风门，组织救护队员在保持封闭区完好封闭状态下，进入封闭区内检查一氧化碳 、二氧化碳 、瓦斯、氧气等的含量情况以及巷道支护的完好情况。在确保安全的情况下启封火区。
** 锁封风门内应备足巷道支护材料，同时测定回风流中的一氧化碳，如果发现一氧化碳变化异常且有复燃的迹象时，必须停止启封工作并重新封闭火区。
** 启封火区由救护队员佩戴呼吸器在锁封风门内进行，并先将入排风巷道的密闭同时打开一个能进人的小口，打开锁封风门并对火区进行初期供风。在启封火区密闭时，必须由矿山救护队负责进行，火区回风风流所经过巷道中的人员必须全部撤出。
** 火区通风后，由救护队员进入灾区进行检查，只有在确保安全的情况下，才准扩大密闭口，摘除锁封风门，恢复正常通风，若发现巷道有充填物堵塞时，可利用锁封风门逐段恢复火区通风。
** 在启封火区工作完毕后的3天内，每班必须由矿山救护队检查通风工作，并测定水温、空气温度和空气成分。只有在确认火区完全熄灭、通风等情况良好后，方可进行生产工作。
在对熄灭火区内及其下水平或下面的煤层进行开采时，必须编制专门的设计经上级部门批准。
** 火区启封后应进行启封总结，编写启封报告，其内容应包括：
*** 启封经过；
*** 火区火源位置及发火原因分析；
*** 火区破坏情况及火灾后果分析；
*** 经验与教训。
