:PROPERTIES:
:ID:       3f0da7b7-1cbb-47a3-a338-e1016bd5bc85
:END:
#+title: 瓦斯超限管理制度
为了保证瓦斯超限信息监控系统正常运行，及时有效处理瓦斯隐患，确保安全生产，结合矿实际，制定本制度。
* 岗位责任制
** 成立瓦斯超限事故分级责任追究处理小组
组  长：矿 长
副组长：总工程师  安全副矿长
成  员：通风副总工程师  矿调度主任  通风科科长 安全科科长  队长  生产技术科科长
** 通风科是瓦斯管理的业务科室，通风科、队组都是瓦斯超限事故的责任科室，安全科是瓦斯管理的监督检查科室。
* “瓦斯超限”范围界定
** 矿井总回风巷CH4≥0.75%。
** 采煤工作面、采煤工作面上隅角、采掘工作面及回风流、风流经过地点及密闭墙外CH4≥1.0%。
** 采煤工作面进风巷、掘进工作面局部通风机前、井下各煤仓上、下口及其他扩散通风巷道和硐室风流中的CH4≥0.5%。
** 排放瓦斯期间，第一交汇点往外风流CH4≥1.5%。
** 采掘工作面及其他巷道内，体积大于0.5m³的空间内CH4≥2.0%。
* 瓦斯超限分类
** 对于管理工作不到位，未配足专职瓦检员或不按规定检查瓦斯、抽采不达标、通风系统不合理、风量配备不充足或无计划停电停风、设备维修调校不及时出现故障及生产作业过程中放炮、割煤等人为原因造成的瓦斯浓度超过规定值，界定为“瓦斯超限事故”。
** 对于矿井生产安全的需要进行有计划的停风、停电、瓦斯排放、反风演习、瓦斯测试、设备检修等认为原因造成的瓦斯超限原则上不作为瓦斯超限事故处理，但矿必须记录在案。
** 对于非瓦斯浓度引起的瓦斯传感器数值超过规定值而发生的误报警，认定为瓦斯异常信息，原则上可不做为瓦斯超限事故处理，但必须查明原因，采取措施，确保正常运行。
* 煤矿瓦斯超限报告及应急处置程序
** 瓦斯超限汇报程序
*** 煤矿监控中心值班人员要随时监测各作业场所瓦斯变化情况，发现瓦斯超限立即向矿调度室汇报，矿调度室立即采取停电、撤人等安全技术措施。
*** 班组长、瓦检员、安全员现场发现瓦斯超限，必须立即责令现场作业人员停止作业、切断电源、撤出人员、设置栅栏、警示警标，并向矿调度室汇报。
*** 矿调度室接到瓦斯超限汇报后，要立即下令现场作业人员停止作业、切断电源、撤出人员。并迅速向值班领导、主要负责人、总工程师和分管生产、安全、机电的矿领导，以及相关业务科室通报。
*** 煤矿信息中心接到所属煤矿瓦斯超限汇报后，必须立即向上级领导、总工程师、生产副总经理、安全副总经理，以及相关业务科室汇报。高浓度及大面积高浓度瓦斯超限还必须向上级领导汇报。
** 煤矿瓦斯超限应急处置程序
*** 瓦斯超限10min之内，矿长、总工程师以及分管安全、生产、机电的矿领导至少有一人必须到矿调度室组织处理。
*** 接到瓦斯超限汇报后，由矿总工程师详细了解瓦斯超限事故的时间、地点、性质、级别、超限情况和原因等。并做出处理决定。若接到汇报后10min之内瓦斯浓度仍未降到1%以下时，必须立即赶到矿调度室组织处理。
* 瓦斯超限事故分级分析处理
** 井下瓦斯一旦超限，严格按照“四不放过”的原则进行事故分析，并编制瓦斯超限事故分析报告，并详细注明事故经过、事故原因、整改措施及责任落实。
** 采掘工作面、上隅角、采掘工作面回风流CH4≥1.0%；局部通风机前CH4≥0.5%；矿井总回风巷CH4≥0.75%；局部瓦斯≥2.0%；一氧化碳CO≥24ppm时，由通风副总工程师牵头组织相关科室人员进行事故追查处理，并对责任人员进行处罚和落实，并将处理结果上报上级部门。
** 采掘工作面、上隅角、回风流CH4≥1.5%；局部通风机前CH4≥0.7%；矿井总回风巷CH4≥0.9%；一氧化碳CO≥50ppm时；由矿总工程师、矿安全副矿长牵头组织相关科室人员进行事故追查处理，按照矿规定对责任人员进行处罚和落实，并将处理结果上报上级部门。
** 采掘工作面及回风流CH4≥2.0%；局部通风机前CH4≥0.9%；矿井总回风巷CH4≥1.0%；一氧化碳CO≥75ppm以上，持续时间在5分钟以上或者在日常检查中发现煤矿瓦斯长时间超限、浓度值较高的，由上级部门组织相关人员进行分析处理。同时，在分析处理完毕后应及时总结形成书面材料并向县级煤矿安全监管部门和驻地分局报告。
** 煤矿井上、井下采掘工作面以外的其它生产作业场所超过“瓦斯超限”规定浓度，对超限频繁、持续时间长和超值浓度较大的按照上述查处程序查处。
** 对擅自移动、故意弃用、人为封堵、损毁瓦斯传感器或者改变瓦斯监控系统设施造成瓦斯数据失真或上传中断的，一经查实，移送公安机关，根据《中华人民共和国治安管理处罚法》的相关规定处理，构成犯罪的，依法追究刑事责任。
应急处置及分析处理完毕后，煤矿还应及时向县级煤矿安全监管部门及驻地煤监分局作出书面报告。
* 瓦斯信息传输制度
** 监测室值班员只要发现系统有瓦斯超限报警，包括瓦斯超限，瓦斯误报警等情况，均应及时向调度报告，调度汇报通风科科长，并组织人员处理。
** 矿调度接到瓦斯超限信息后，及时将超限信息报送总工程师、安全副矿长。
** 通风科科长要对瓦斯超限处理全程参与并及时上报上级部门备案。
** 超限原因查清后，认真填写记录，并保证系统数据上传无误。
** 监测工在维护和处理超限情况时，不得弄虚作假，必须保证井下各测点、各个传感器正常工作，能准确传输真实、可靠的实时数据。
** 井下实时数据逐级上传到县、市、省局监控中心或调度值班室。
** 对实时数据上传过程中的报警，系统故障，上传中断等情况，通风科要及时组织相关人员或厂家积极处理。
** 监测室必须坚持24小时值班制度，如发现数据无故不能及时上传，追究相关人员责任。
** 对各种信息传输不正常情况应及时认真记录，以备查考。
* 瓦斯传感器报警追究制度
因传感器的校验不及时，误差偏大而引起报警；因井下人员故意破坏传感器而引起的报警；因报警浓度设置太低而引起的报警，按矿相关规定对责任人进行相应的处罚。
