:PROPERTIES:
:ID:       29a8945a-1946-4ad5-a053-4221c9f244fb
:END:
#+title: 阻燃胶带管理制度
为切实加强矿阻燃钢绳芯强力胶带输送机安全使用管理，杜绝断带事故的发生，确保阻燃钢绳芯强力胶带的安全运行，特制定了管理制度。
一、矿成立阻燃钢绳芯强力胶带管理组。
二、阻燃钢绳芯强力胶带的使用做到有计划、有目的，并根据井下实际生产的需要进行合理投入。
三、新进的每卷阻燃钢绳芯强力胶带必须经上级部门试验，试验合格后出据试验报告，同时阻燃胶带管理组把试验报告和试验日期、试验编号、胶带长度及型号记入阻燃胶带管理台帐，采购、使用严格执行《井下阻燃胶带阻燃性能试验管理办发》。
四、新胶带的发放：各使用队组在支领新胶带前必须开领料单，经相关领导批准后，再到管理组去领取，管理台帐注明发放的日期、胶带编号、试验编号、支领队组使用地点登记清楚。
五、各队组使用后旧胶带的回收：各队组更换下来的旧胶带要及时回收到地面交回管理组，管理组根据回收胶带的型号、长度、质量情况分类摆放，并做好台帐登记，以便下次发放使用。
六、做好已发放阻燃钢绳芯强力胶带的跟踪管理工作，对有损阻燃钢绳芯强力胶带的行为给予严重处罚。
七、更换阻燃钢绳芯强力胶带，严禁丢失或挪作他用，如经查实后照价赔偿。
八、各队组支领的新胶带严禁断成几段使用，发现后严处。
九、为正确使用钢绳芯清理胶带输送机（以下简称强力皮带机）保证矿井安全生产特制定本办法。
十、队（组）长是强力皮带机使用队组的安全责任人，负责强力皮带机安全运行的现场管理工作。
十一、使用队组的管理人员要熟悉强力皮带机的技术性能、使用条件、设备完好标准，并编制符合《煤矿安全规程》要求的各种规章制度和操作规程，用时要监督各种规章制度和操作规程的落实情况。
十二、使用队组应根据规章制度和操作规程的要求，对强力皮带机进行正确使用、维护、保养；同时要编制年、月、旬检修计划和日检项目，从而保证强力皮带机安全、高效运行，不得无故取消检修计划和日检项目。
十三、使用队组要建立健全巡回检查制度，明确规定巡回检查责任，内容和巡回检查周期，以及发现问题的处理程序，并对每次巡查工作做好记录。
十四、使用队组应根据强力皮带机的技术性能、使用条件、设备完好标准，编制培训教材，对操作人员，维修人员进行岗位技术培训，提高培训质量，严格考核制度，考试合格后，持证上岗。
十五、强力皮带机在使用中要保证驱动滚筒上的包胶的完整性，避免局部脱胶造成给滚筒圆周长度不同，引起部分钢丝绳芯拉应力长期超负荷而导致胶带断裂；在运转中发现脱胶现象要及时处理。
十六、切实做好强力皮带机卸载点、转载点的管理工作，增设缓冲装置，杜绝各种物料和大块砸伤强力皮带；严禁机尾滚筒卷进煤矸；严禁使用延燃材料制作接煤槽、挡煤板，要采取措施，防止强力皮带机拉水煤。
十七、强力皮带机的电控系统应按照原煤炭部制定《煤矿井下保护接地装置的安装、检查、测定工作细则》、《煤矿井下低压捡漏保护装置的安装、运行、维护与检修工作细则》和《煤矿井下低压电网短路保护装置的整定细则》的要求对电动机所需要运行参数进行计算后准确整定，保证电器保护装置齐全、可靠。
十八、使用队组要根据强力皮带机的工作特性，制定有针对性且可操作性强的事故应急措施和救援预案。
十九、使用队组要对其管辖的强力皮带机建立安全技术档案，切实做到一机一档，安全技术档案应包括以下内容：
（一）强力皮带机的设计文件，强力皮带机及阻燃胶带制造区队的资质证明，产品质量合格证，使用维护说明书以及其他各类技术文件。
（二）以强力皮带机配套使用的电器设备的防爆合格证，煤安标志，电控系统接线图及原理图，生产厂家的资质证明，使用维护说明书。
（三）强力皮带机历年的运行记录。
（四）强力皮带机历年的检修记录。
（五）强力皮带机历年的事故记录。
（六）强力皮带机各种安全保护装置日常维护、试验、检修记录。
（七）认真做好强力皮胶带硫化接头的管理工作，使用队组要对每一个钢丝绳芯胶带硫化接头进行编号建档登记管理，并对每个硫化接头的长度作原始标定，派专人测量，然后逐一比对，确定接头内钢丝绳芯是否有拉脱、伸长趋势，切实做到防患于未然。
（八）各级管理人员上岗记录。
（九）操作规程及相关人员的岗位责任制。
（十）建立健全各种规章制度和管理办法（且应现场张挂）。
二十、使用中的强力皮带机必须按《煤矿安全规程》有关规定，设置下列保护装置：
（一）驱动滚筒防滑保护、堆煤保护和防跑偏装置。
（二）温度保护（是指当皮带机因低速打滑导致驱动滚筒发热时能及时停车并发出声光报警的装置）烟雾保护和自动洒水装置。
（三）输送带张紧力下降保护装置和防撕裂保护装置。
（四）在机头和机尾设置防止人员与驱动滚筒和导向滚筒相接触的防护栏。
（五）倾斜巷井中使用的钢绳芯强力胶带输送机，上运时，必须同时装设防逆转装置和制动装置，下运时，必须装设制动装置。
（六）强力胶带机的小绞车液压联动胶带张紧装置应具备张紧力下降后自动补压功能，如自动补压功能失效应即时停机，并发出声光警报；胶带机的自重式张紧小车应装设防止自重式张紧小车因异常上移或下滑的限位停车装置强力皮带机沿途须装设急、停拉线开关。
（七）对于上述保护作如下规定:
1.烟雾保护的烟雾传感器应每月升井做一次烟雾灵敏度试验，合格后入井使用，在使用中每班做一次模拟试验能够有足够的水压、水量立即喷雾洒水且水量必须覆盖滚筒全长度为合格。
2.温度保护每月可用沸水在井下或升井试验，能够喷雾活水，且水量必须覆盖滚筒全长度为合格。
3.防滑保护：发生低速打滑时立即报警并停车，严禁只报警不停车现象发生。其余保护装置每班做一次手动试验（除防逆转装置和制动装置）。
4.在用强力皮带机应适量装设断带抓捕器，并每50米装设一组牢固的防止断带后下滑的龙门架（或过桥）装置，龙门架高度与煤的间距不高于0.3米。
5.使用队组要根据上述要求，建立检查、试验、维护制度，并责成专人负责此项工作，各级管理人员上岗时要将此项工作作为重点进行检查。
二十一、对使用中的胶带管理要做好以下几方面的工作：
要选用带强满足设计运行条件的胶带。
（一）必须购置有生产资质如名厂家的阻燃胶带，且要有该批次产品合格证明书，煤安标志及胶带阻燃试验报告。
（二）建立胶带损伤记录，实行定点跟踪，查找原因及时处理。
（三）认真执行钢绳芯胶带机头硫化工艺，剥离打磨时严禁破坏镀锌层，清洗刷胶时严格执行防尘防潮措施，接头升温硫化时严格控制时间、温度、压力三要素。
（四）为准确掌握钢丝绳芯胶带内钢丝绳芯的情况，各队组应按规定对强力皮带机进行钢丝绳芯胶带探伤检测。
二十二、强力皮带机在使用中要保证驱动滚筒上的包胶的完整性，避免局部脱胶造成给滚筒圆周长度不同，引起部分钢丝绳芯拉应力长期超负荷而导致胶带断裂；在运转中发现脱胶现象要及时处理。
二十三、切实做好强力皮带机卸载点、转载点的管理工作，增设缓冲装置，杜绝各种物料和大块砸伤强力皮带；严禁机尾滚筒卷进煤矸；严禁使用延燃材料制作接煤槽、挡煤板，要采取措施，防止强力皮带机拉水煤。
二十四、强力皮带机的电控系统应按照原煤炭部制定《煤矿井下保护接地装置的安装、检查、测定工作细则》、《煤矿井下低压捡漏保护装置的安装、运行、维护与检修工作细则》和《煤矿井下低压电网短路保护装置的整定细则》的要求对电动机所需要运行参数进行计算后准确整定，保证电器保护装置齐全、可靠。
二十五、为防止火灾，强力皮带机电控硐室内应设置不少于0.2㎡消防砂和不少于两只便携式灭火器、钢绳芯强力皮带输送机沿途须设置消防水管，且保证50米处有一个分接头，每个分接头处配置一条长度不小25米的胶管，确保发生火灾时，消防水能覆盖整条输送机。
二十六、各生产队组在用的普通胶带输送机需参照执行本办法。
