:PROPERTIES:
:ID:       f3d3c1dc-b191-4d0d-8122-c2cef07072e2
:END:
#+title: 矿图审查制度
为贯彻落实“安全第一，预防为主，综合治理”的安全生产方针，根据《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》第十四条规定，井工煤矿必须填绘反映实际情况图纸要求，特制定本制度。
* 组织机构
为确保矿图审查工作正常开展，成立矿图审查领导小组，负责组织审图工作。
组  长：[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]
副组长：副矿长、各专业副总工程师、生产技术科科长、通风科科长、安全科科长、机运科科长。
成 员：[[id:20bd34bb-4ce1-44e3-bb8a-3fe174f78626][生产技术科]]、[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]、[[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]、[[id:4dc9831c-ee21-49a1-bf97-37e58258b106][机运科]]。
领导小组下设办公室，办公室设在[[id:20bd34bb-4ce1-44e3-bb8a-3fe174f78626][生产技术科]]，生产技术科科长任办公室主任，负责日常工作。
* 矿图审查时间
矿图审查，每月进行一次，原则上安排在每月上旬进行，特殊情况由生产技术科另行通知。
* 矿图审查内容
** 汇报近期生产接续情况。
** 巷道失修情况。
** 采掘工程设计、技术措施，瓦斯治理工程自查致灾因素排查情况及采取的措施。
** 必备图纸资料：
*** 矿井地质图和水文地质图。
*** 井上对照图。
*** 巷道布置图（含井筒剖面图）。
*** 采掘工程平面图（分层图、综合图）。
*** 通风系统图（按综合煤层、分层分别绘制）。
*** 井下运输系统图。
*** 安全监控布置图和断电控制图、人员位置监控系统图。
*** 压风、排水、防尘、防火注浆、抽采瓦斯等管路系统图。
*** 井下通信系统图。
*** 井上下配电系统图和井下电气设备布置图。
*** 井下避灾路线图。
*** 瓦斯地质图。
*** 先探后掘钻孔成果图。
*** 支撑探放水、先探后掘、瓦斯抽采等实施情况资料。
* 矿图审查要求
** 在进行矿图审查前，由各科室负责人如实汇报上月矿图审查时提出的问题的整改落实情况（有书面材料）。
** 提供审查的图纸必须遵照相关规范要求绘制图件，确保图纸质量。
** 提供的图纸资料必须客观真实反映实际情况。
** 查验图纸、资料是否齐全。
** 检查图纸是否遵照相关规范绘制。
** 排查致灾因素及存在风险，提出建议措施。
** 矿图审查查出的问题及建议由矿生产技术科汇总，形成矿图审查会议纪要进行整改落实。
** 各科室对存在的问题编制针对性的安全技术措施，报矿总工程师进行审批进行使用。
** 参与矿图审查人员须加强法律法规、标准、规范及矿有关规定的学习，不断提高审图工作水平。
