:PROPERTIES:
:ID:       a2b71c41-9935-4532-9139-8e1fdd887348
:END:
#+title: 水害应急处置制度
为了加强矿水害应急处理能力，在矿井发生水害事故时，能够最大限度的减小人员伤亡及国家财产损失。根据《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程2022版]]》及《[[id:c3c897d4-b900-4119-8034-e51f6b312c80][煤矿防治水细则]]》要求制定了水害应急处置制度。
* 当井下工作人员发现水情时，应当立即向调度室报告有关突水地点及水情，并通知周围有关人员撤离到安全地点或升井。采取有效安全措施，分析查找透水原因。
* 调度室接到水情报告后，应当立即启动矿井水害应急预案，根据来水方向、地点、水量等因素，确定人员安全撤离的路径，通知井下受水患影响地点的人员马上撤离到安全地点或者升井，向值班负责人和矿井主要负责人汇报。
* 调度室根据水害程度确定应急响应级别，并立即将事故汇报应急救援指挥部总指挥和副总指挥，由总指挥启动应救援预案，并立即向能源调度室汇报。同时组织召开首次应急会议，采取有效处置措施，控制事态的扩大。
* 召开首次应急救援会议，根据应急救援指挥部的命令，传递并下达救灾命令。应急救援指挥包括：应急救援准备、通讯、事故点快速定位、现场信息掌握、资源获取、救援力量集结等。
* 应急救援过程中，指挥部随时掌握救灾进展情况。
* 救援过程中，应急救援总指挥随时了解救援过程的情况，必要时召开后续应急会议，修改救援方案，研究解决应急救援处置中遇到的有关问题；根据事故救援进展情况，召集各应急救援小组人员联席会议，沟通传达相关信息，下达通知和命令。
* 救护队、现场救援人员、各专业组按照各自的职能，在现场指挥部的指挥下，按制定的救援方案、安全措施，积极地、能动地进行抢险救援。
* 各救援组组长指挥抢险救援事宜并及时向指挥部汇报救援进展情况。
* 抢险救援组和技术组根据现场情况，协同现场指挥部进行事故初始评估，划分出危险区、缓冲区、安全区，研究制定抢险救援方案和安全措施。
* 在抢险救援中，要贯彻本预案的优先原则，首先进行人员救助，然后进行现场监控等工作。
* 扩大应急：在事故抢险救援过程中，若事态扩大，抢救力量不足，事故无法得到有效控制，现场抢险指挥部要立即向上级应急救援指挥部汇报；根据灾情情况，如工作难度大，要请求地方政府予以协助。
