:PROPERTIES:
:ID:       64f8ce1c-a505-4ccf-b467-8b973a507b6b
:END:
#+title: 矿井瓦斯治理管理制度
为认真落实通风可靠、抽采达标、监控有效、管理到位、隐患排除、综合利用的瓦斯综合治理管理体系，防止煤与瓦斯突出事故和瓦斯爆炸事故的发生，特制定矿井瓦斯综合治理管理制度。 
* 加强矿井通风管理，确保矿井通风安全、合理、可靠。
** 矿井已按规定要求安装了两套同等能力的主要通风机，其中一套备用，所选用的风机能满足矿井通风需求。必须加强供电管理，实行双电源供电，保证供电安全可靠，保持扇风机连续运转，加强对主要通风机及其附属装置的检查与维护，确保备用风机能在10分钟内启动。 
** 合理设置风门、调节风窗和密闭等通风构筑物，按标准要求施工，做到牢固可靠。 
** 采掘工作面，机电硐室和其它用风地点的风量必须满足要求，风速符合规定要求，不用的巷道和已采的采空区必须及时进行封闭。 
** 供掘进工作面通风的局扇必须使用双风机、双电源，双风机能自动切换，双电源都应实现三专供电，确保通风可靠，风机的安装和使用必须符合煤矿安全规程规定，按规定设置风、电和瓦斯电闭锁。
** 矿井必须设置专用回风巷，进回风巷必须贯穿整个巷道 ，严禁一段为进风巷、一段为回风巷。 
** 采掘工作面实行独立通风，严禁设置风桥，必须使用回风绕道来实现独立的回风系统。 
* 加强防突管理，做到不采突出煤，不掘突出头。 
** 按规定编制防突设计，按设计开展防突工作。 
** 防突工作坚持区域防突措施先行，局部防突措施补充的原则，区域防突工作应当做到多措并举，可保必保，应抽尽抽，效果达标。
*** 成立矿井防突管理机构，设置专门防突队伍，配齐防突人员，落实防突责任制，合理组织开展工作。 
*** 按开采设计要求合理开采保护层，并认真检测保护层开采后对被保护层的解放效果。 
*** 充分发挥瓦斯抽放系统的作用，采取措施提高抽放效果，扩大抽放范围和提高抽放量。高负压瓦斯抽放系统合理用于本煤层预抽和邻近层预抽，预抽效果必须符合“防治煤与瓦斯突出细则”的要求，低负压抽放系统用于采煤工作面上隅角抽放和采空区抽放，合理调控，有效解决采面上隅角瓦斯时常超限而严重威胁安全生产的隐患。 
*** 突出煤层采掘工作面必须编制“四位一体”综合防突措施，认真落实预测预报、防治突出措施，防突措施效果检验和安全防护措施，没有编制或没有落实防突措施的突出煤层采掘工作面，严禁生产或施工。 
* 加强日常瓦斯管理，消除瓦斯隐患。 
** 采煤工作面必须按综合防突措施要求实施抽放钻孔，完善采煤工作面抽放瓦斯管路系统，认真开展工作面预抽和随采随抽。
** 掘进工作面必须按综合防突措施要求实施超前钻孔预抽煤巷掘进条带的瓦斯，钻孔控制范围和超前保护范围必须符合“防治煤与瓦斯突出细则”的要求。 
** 加强瓦斯抽放系统的检查维护管理，防止管路积水，漏气和损坏，发现问题及时采取措施处理。保持抽放系统的正常运行。 
** 加强对瓦斯抽放系统抽放效果的检查，检测抽放管道中瓦斯流量、抽放负压、瓦斯浓度、温度等参数，及时分析和处理存在的问题，做到有记录可查。 
** 加强采空区的管理，检查采空区密闭完好情况，对密闭漏风、密闭前支护不良等隐患，及时采取措施进行处理，减少采空区瓦斯渗漏隐患，采空区进风密闭要设放水管或反水池，回风密闭要设观测管和措施管并设闸阀，以利对采空区的水，火、瓦斯的治理。 
** 加强队组顶板管理，工作面初次来压、周期来压以及过断层和地质破碎带期间，要密切注意采空区涌出瓦斯的变化，及时采取有效措施控制和处理瓦斯。 
** 充分发挥监控系统的作用，按煤矿安全规程要求装备并配齐各种类传感器，安全监测设备和各种传感器的检测调试、维护和使用必须符合规定要求，发现不安全因素，及时采取措施进行处理 
** 矿井因检修主要通风机或因供电质量问题造成主要通风机停止运转，必须及时撒出井下所有人员，切断井下电源，打开风井井口防爆门，利用自然通风。恢复主要通风运转必须制定恢复通风排放瓦斯的专门措施，经矿技术负责人审批后由矿长或值班矿长指挥，通风  安全和机运负责人参加，严格按排放措施进行瓦斯排放。 
** 掘进工作面因故停止局部通风机运转，必须切断掘进工作面内及其回风侧一切非本质安全型电气设备的电源，设置栅栏，揭示警标，禁止人员入内，严禁在停风或瓦斯超限区域内作业。恢复通风排除瓦斯，必须首先检查瓦斯，只有在停风区中最高瓦斯浓度不超过1%和二氧化碳浓度不超过1.5%且局部通风机及其开关附近10米范围内瓦斯浓度不超过0.5%时，方可由指定人员开启风机。停风区中瓦斯浓度超过1%或二氧化碳涌度超过1.5%，最高瓦斯浓度和二氧化碳浓度不超过5%，必须采取措施由专职瓦检员负责控制风流排放瓦斯，只有在恢复通风的巷道及其回风流中的瓦斯浓度低于1%，二氧化碳浓度低于1.5%的情况下才能送电恢复作业；当停风区中瓦斯浓度或二氧化碳浓度超过3%时，必须制定安全排放瓦斯措施，报矿技术负责人审批，落实措施进行安全排放瓦斯。 
** 严格执行一炮三检和三人连锁放炮制度，落实安全放炮管理规定。
** 认真落实矿井瓦斯巡回检查制度，按规定配齐瓦检员，所有采掘工作面、硐室、进回风巷道使用中的机电设备设置地点、回风巷道有人作业的地点都应纳入检查范围。 
*** 采掘工作面瓦斯浓度检查次数每班不少于3次，突出煤层采掘工作面，有瓦斯突出危险和瓦斯涌出较大，变化异常的采掘工作面，必须设专人经常检查瓦斯和二氧化碳。本班未进行工作的采掘工作面瓦斯和二氧化碳浓度每班至少检查一次。可能涌出或积聚瓦斯或二氧化碳的硐室和巷道每班至少检查一次。井下停风地点栅栏外风流中的瓦斯浓度每天至少检查一次。挡风墙或密闭处的瓦斯和二氧化碳浓度每周至少检查一次。 
*** 瓦检员必须执行瓦斯巡回检查制度和请求报告制度，每次检查结果必须记入瓦检手册和检查地点的记录牌上并通知现场人员，瓦斯浓度超过煤矿安全规程有关规定时，瓦检员有权责令现场人员停止作业，并撤至安全地点，同时向矿调度室汇报，严禁瓦斯超限作业。
** 采掘进工作面应设置隔爆水棚，检查并补充水量，保证水袋的水量满足要求。
** 瓦斯日报和安全监控日报表必须送矿长、矿技术负责人审阅，对重大的通风瓦斯问题应制定措施进行处理。
