:PROPERTIES:
:ID:       d6b845f7-611a-4a5e-982f-8f58e3457e85
:END:
#+title: 入井安全宣誓制度
为推动全矿进一步营造浓厚安全氛围，全力提升全员安全意识，增强全矿职工自觉遵法守纪、按章作业，根据《省能源局贵州煤矿安监局关于全面推行煤矿人井安全宣誓制度与“手指口述”安全确认作业法的通知》（黔能源煤安〔2019〕176 号）文件及相关要求，结合矿实际，制定本制度。
* 宣誓人员。矿所有入井作业人员，入井前必须进行安全宣誓。
* 宣誓地点。各队组在井口附近显著位置设集中宣誓点，同时在队组会议室也设置宣誓点，便于入井作业人员进行安全宣誓。
* 宣誓形式。可采取单独宣誓或者集体宣誓的形式。原则上3 人以下(不含3 人)可单独宣誓，宣誓人应当右手举拳，诵读誓词。3 人以上应集体宣誓，由一人领誓，领誓人右手举拳，领诵誓词，其他宣誓人整齐排列，右手举拳，跟诵誓词。宣誓时，必须全体起立，面向誓词牌板，要声音洪亮，精神振奋、言词清晰、节奏感强，体现煤矿职工艰苦作业的精神面貌。宣誓完毕后入井，对于当班中途出井又再次入井人员，也要再次进行安全宣誓。
* 宣誓誓词。矿属各队组参照以下誓词明确入井誓词内容，誓词要上墙或单独设置展板。参照的誓词内容“为了煤矿发展，为了家庭幸福，为了个人安康，我坚决做到，坚持安全第一，搞好自主保安，决不违章作业，平安完成当班任务。”
* 宣誓组织。原则上每班由当班现场负责人组织进行宣誓，也可由队长（主任）、技术员、验收员等管理人员组织进行，零散入井作业人员自行在井口宣誓点宣誓入井。
* 安全宣誓地点要确保挡风遮雨、集体宣誓时应有的空间面积、照明等基本条件；所有宣誓地点必须实现煤矿工业视频系统全过程监控，且监控视频数据保存期限不低于30天。
* 安全宣誓纳入班组建设进行考核，每月开展班组建设检查期间对班组进行安全宣誓情况查阅视频系统进行抽查，凡发现班组存在入井作业未按规定进行安全宣誓的取消当月班组评优资格。
* 当班负责人未组织入井作业人员进行安全宣誓或宣誓时不符上述第三、四条规定的，对当班负责人给予一次XX元处罚；零散入井作业人员未按规定进行宣誓入井，一次给予XX元罚款；一个圆班内出现5人次以上入井作业人员未进行安全宣誓的，给予负责人一次XX元罚款。
* 工业视频系统必须保证运行可靠，不按规定维护出现故障或监控数据不按规定保存导致不能查阅入井宣誓情况对责任人一次给予XX元罚款。视频系统出现故障时，必须有其他设备视频进行记录，否则出现一个班组未记录一次安全宣誓给予队组XX元罚款，累加计算。
* 安全科将作业人员入井安全宣誓纳入日常安全监督内容，对入井作业人员入井安全宣誓进行监督查处。
