:PROPERTIES:
:ID:       6b792616-e751-4a45-bd95-ecbe71628fbc
:END:
#+title: 矿井通风管理制度
* 风量计算基本要求
** 建立“系统合理、设施完好、风量充足、风流稳定”的通风系统，确保通风可靠。
** 每年安排采掘作业计划前必须核定矿井通风能力，严格按实际供风量核定矿井产量，严禁超通风能力生产。
** 按实际需要计算矿井风量时，采用由里向外的方法进行计算，即先计算采掘工作面、硐室及其他用风地点的需要风量，然后计算矿井独立通风系统的需要风量。
** 矿分别计算每个主要通风机系统担负的总进风量和总回风量。
** 各用风地点的需要风量，必须依照下列要求分别计算，并取其最大值。
*** 按用风地点同时工作最多人数计算，每人每分钟不得少于4m３。
*** 按采煤、掘进、硐室及其它地点实际需要风量的总和进行计算。各地点的实际需要风量，必须使该地点的风流中的瓦斯、二氧化碳、氢气和其它有害气体的浓度，风速、温度以及每人供风量必须符合《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》（以下简称“规程”）的有关规定。
** 配给各用风地点的风量必须符合规程中关于瓦斯和二氧化碳浓度的规定、最高风速和最低风速的规定、采掘工作面和机电硐室最高温度的规定。配风时，选择适宜的采煤工作面风速，创造良好的气候条件。
** 总工程师每月至少组织一次通风系统审查，确保通风可靠。每月对各用风地点的需要风量进行一次计算，并报上级部门审批。
** 新安装的主要通风机投入使用前，进行1次通风机性能测定和试运转工作，投入使用后每5年至少进行1次性能测定；矿井通风阻力测定符合《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》规定。
** 矿井有效风量率不低于85%矿井外部漏风率每年至少测定1次，外部漏风率不得超过5%（无提升设备）。
** 矿井每10天进行1次井下全面测风。对采掘工作面和其他用风地点应根据实际需要随时测风，测风结果均须填写在测风管理牌板上。
** 矿井使用局部风机通风时，压入式风筒出风口距工作面的距离必须在作业规程中明确规定。岩巷不得大于8米，煤巷、半煤岩巷不得大于5米。
** 矿井风量计算方法解释权属矿。
** 矿井主要通风机安设监测系统，能够实时准确监测风机运行状态、风量、风压等参数。
* 矿井风量计算
** 生产矿井需要风量按各采掘工作面、硐室及其他巷道等用风地点分别进行计算，包括按规定配备的备用工作面。现有通风系统必须保证各用风地点供风稳定可靠。
Qra≥(∑Qcfi＋∑Qhfi＋∑Quri＋∑Qsci＋∑Qrli)×kaq
式中  Qra—矿井需要风量, m³ / min；
Qcfi—第i个采煤工作面实际需要风量，m³ / min；
Qhfi—第i个掘进工作面实际需要风量，m³ / min；
Quri—第i个硐室实际需要风量，m³ / min；
Qsci—第i个备用工作面实际需要风量，m³ / min；
Qrli—第i个其他用风巷道实际需要风量，m³ / min；
kaq—矿井通风需风系数，取1.15～1.20。
** 采煤工作面需风量计算。每个采煤工作面实际需要风量，应按工作面气象条件、瓦斯涌出量、二氧化碳涌出量、工作人员和爆破后的有害气体产生量等规定分别进行计算，然后取其中最大值。
*** 按气象条件计算：
Qcfi=60×70%×vcfi×Scfi×kchi×kcli（m³/min）
式中 vcfi—第i个采煤工作面的风速，m/s，煤矿采掘工作面温度均小于20℃，故vcfi取1.0；
Scfi—第i个采煤工作面的平均有效断面积，按最大和最小控顶有效断面的平均值计算，㎡；
kchi—第i个采煤工作面采高调整系数，具体按表8-2取值；
kcli—第i个采煤工作面长度调整系数，具体按表8-2取值；
70%—有效通风断面系数；
60—单位换算产生的系数。
表1.1  采煤工作面采高及采长风量调整系数
| 采高／m             | 系数（kch） | 采煤工作面长度／m	系数（kcl） |     |
| ＜2.0               |         1.0 | 80～120                              | 1.0 |
| 2.0～2.5            |         1.1 | 120～150                             | 1.1 |
| ＞2.5及放顶煤工作面 |         1.2 | 150～180                             | 1.2 |
| ＞180               |  1.30～1.40 |                                      |     |
*** 按照瓦斯涌出量计算：
Qcfi=100×qcgi×Kcgi（m³/min）
式中qcgi—第i个采煤工作面回风巷风流中平均绝对瓦斯涌出量，m³/min。抽采矿井的瓦斯涌出量，应扣除瓦斯抽采量进行计算；
Kcgi—第i个采煤工作面瓦斯涌出不均匀的备用风量系数。正常生产时连续观测1个月，最大绝对瓦斯涌出量和月平均绝对瓦斯涌出量的比值；
100—按采煤工作面回风流中瓦斯的浓度不应超过1.0%的换算系数。
*** 按照二氧化碳涌出量计算：
Qcfi=67×qcci×kcci（m³/min）
式中qcci—第i个采煤工作面回风巷风流中平均绝对二氧化碳涌出量，m³/min；
kcci—第i个采煤工作面二氧化碳涌出不均匀的备用风量系数。正常生产时连续观测1个月，最大绝对二氧化碳涌出量和月平均绝对二氧化碳涌出量的比值。
67—按采煤工作面回风流中二氧化碳的浓度不应超过1.5%的换算系数。
*** 按工作人员数量验算：
Qcfi≥4Ncfi
式中  Ncfi—第i个采煤工作面同时工作的最多人数；
4—每人需风量，m³/min。
*** 按风速进行验算：
（1）验算最小风量：
Qcfi≥60×0.25Scbi（m³/min）
Scbi =lcbi×hcfi×70%（㎡）
（2）验算最大风量：
Qcfi≤60×4.0Scsi（m³/min）
Scsi=lcsi×hcfi×70%（㎡）
（3）综合机械化采煤工作面，在采取煤层注水和采煤机喷雾降尘等措施后，验算最大风量：
Qcfi≤60×5.0Scsi（m³/min）
式中  Scbi—第i个采煤工作面最大控顶有效断面积，㎡；
lcbi—第i个采煤工作面最大控顶距， m；
hcfi—第i个采煤工作面实际采高， m；
Scsi—第i个采煤工作面最小控顶有效断面积，㎡；
lcsi—第i个采煤工作面最小控顶距，m；
0.25—采煤工作面允许的最小风速，m/s；
70%—有效通风断面系数；
4.0—采煤工作面允许的最大风速，m/s；
5.0—综合机械化采煤工作面，在采取煤层注水和采煤机喷雾降尘等措施后允许的最大风速，m/s。
*** 备用工作面实际需要风量，应满足瓦斯、二氧化碳、气象条件等规定计算的风量，且最少不应低于采煤工作面实际需要风量的50%。
** 掘进工作面需风量计算。
每个掘进工作面实际需要风量，应按瓦斯涌出量、二氧化碳涌出量、工作人员、爆破后的有害气体产生量以及局部通风机的实际吸风量等规定分别进行计算，然后取其最大值。
1.按照瓦斯涌出量计算：
Qhfi=100×qhgi×khgi
式中 qhgi—第i个掘进工作面回风流中平均绝对瓦斯涌出量，m³/min。
抽放矿井的瓦斯涌出量，应扣除瓦斯抽放量进行计算；
khgi—第i个掘进工作面瓦斯涌出不均匀的备用风量系数。正常生产条件下，连续观测1个月，最大绝对瓦斯涌出量与月平均绝对瓦斯涌出量的比值（实测前机掘工作面取1.5-2，炮掘工作面取1.8-2）；
100—按掘进工作面回风流中瓦斯的浓度不应超过1%的换算
2.按照二氧化碳涌出量计算：
Qhfi=67×qhci×khci
式中qhci—第i个掘进工作面回风流中平均绝对二氧化碳涌出量，m³/min；
khci—第i个掘进工作面二氧化碳涌出不均匀的备用风量系数。正常生产条件下，连续观测1个月，最大绝对二氧化碳涌出量与月平均绝对二氧化碳涌出量的比值；
67—按掘进工作面回风流中二氧化碳的浓度不应超过1.5%的换算系数。
3.按炸药量计算：
（1）一级煤矿许用炸药：
Qhfi=25Ahfi（m³/min）
（2）二、三级煤矿许用炸药：
Qhfi=10Ahfi（m³/min）
式中 Ahfi—第i个掘进工作面1次爆破所用的最大炸药量，kg。
按上述条件计算的最大值，确定局部通风机吸风量。
4.按局部通风机实际吸风量计算：
（1）无瓦斯涌出的岩巷：
Qhfi=∑Qafi+60×0.15Shdi（m³/min）
（2）有瓦斯涌出的岩巷、半煤岩巷和煤巷：
Qhfi=∑Qafi+60×0.25Shdi（m³/min）
式中 ∑Qafi—第i个掘进工作面同时运转的局部通风机实际吸风量的总和，m³/min；
0.15—无瓦斯涌出岩巷的允许最低风速；
0.25—有瓦斯涌出的岩巷，半煤岩巷和煤巷允许的最低风速；
Shdi—局部通风机安装地点到回风口间的巷道最大断面积，㎡。
表1.2   煤矿常用压入式对旋轴流局部通风机主要技术参数表
| 序号 | 型号规格     | 功率(kW) | 风量(m³/min) | 全压(Pa)   |
|    1 | YBTYYBTBT    | 28       | 360          |            |
|    2 | №6.3/2×30  | 2×30    | 630～420     | 1000～5800 |
|    3 | №7.1/2×45  | 2×45    | 800～500     | 1200～6800 |
|    4 | №7.5/2×45  | 2×45    | 840～600     | 1500～8700 |
|    5 | №7.5/2×55  | 2×55    | 990～750     | 170～10700 |
|    3 | №8.0/2×55  | 2×55    | 950～700     | 1500～7000 |
|    4 | №8.5/2×75  | 2×75    | 920～600     | 1700～8500 |
|    5 | №11.2/2×90 | 2×90    | 1800～1000   | 1200～6000 |
*** 按工作人员数量验算：
∑Qafi≥4Nhfi（m³/min）
式中  Nhfi—第i个掘进工作面同时工作的最多人数。
*** 按风速进行验算：
（1）验算最小风量：
无瓦斯涌出的岩巷：
∑Qafi≥60×0.15Shfi（m³/min）
有瓦斯涌出的岩巷，半煤岩巷和煤巷：
∑Qafi≥60×0.25Shfi（m³/min）
（2）验算最大风量：
∑Qafi≤60×4.0Shfi（m³/min）
式中  Shfi—第i个掘进工作面巷道的净断面积，㎡。
** 各个独立通风硐室的需要风量，应根据不同类型的硐室分别进行计算。
1.爆炸材料库需要风量计算：
Quri=4Vi/60  （m³/min）
式中  Vi—第i个井下爆炸材料库的体积，m³；
4—井下爆炸材料库内空气每小时更换次数。
但大型爆炸材料库不应小于100 m³/min，中、小型爆炸材料库不应小于60 m³/min。
2.充电硐室需要风量计算：
Quri = 200qhyi  （m³/min）
式中  qhyi—第i个充电硐室在充电时产生的氢气量，m³/min；
200—按其回风流中氢气浓度不大于0.5%的换算系数。
但充电硐室的供风量不应小于100 m³/min。
3.机电硐室需要风量计算：
发热量大的机电硐室，应按照硐室中运行的机电设备发热量进行计算：
（m³/min）
式中   —第i个机电硐室中运转的电动机（或变压器）总功率（按全年中最大值计算），kW；
—机电硐室发热系数。按表1.3取值；
—空气密度。一般取 =1.20kg/m³；
—空气的定压比热。一般可取 =1.0006KJ/(kg·K)；
—第i个机电硐室的进、回风流的温度差，K。
机电硐室需要风量应根据不同硐室内设备的降温要求进行配风；小型机电硐室，按经验值确定需要风量或取60～80m³/min；选取的硐室风量，应保证机电硐室温度不超过30℃，其他硐室温度不超过26℃。
表1.3  机电硐室发热系数（ ）取值
机电硐室名称	发热系数
空气压缩机房	0.20～0.23
水泵房	0.01～0.03
变电所、绞车房	0.02～0.04
** 其他用风巷道的需要风量，应根据瓦斯涌出量和风速分别进行计算，取其最大值。
1.按瓦斯涌出量计算：
Qrli=133qrgi·krgi（m³/min）
式中  qrgi—第i个其他用风巷道平均绝对瓦斯涌出量，m³/min；
krgi—第i个其他用风巷道瓦斯涌出不均匀的备用风量系数，取1.2～1.3；
133—其他用风巷道中风流瓦斯浓度不超过0.75%所换算的常数。
2.按风速验算：
Qrli≥60×0.15Srci（m³/min）
Srci—其它巷道的净断面积， ㎡；
** 对使用防爆型柴油动力装置机车运输的巷道，行驶车辆巷道的供风量还应当按同时运行的最多车辆数增加巷道配风量，巷道配风量不小于4m³/min×kW。
* 主要通风参数计算
** 空气密度的计算
1.空气密度的计算公式

式中     ——空气密度，kg/m³；
P0——测点的大气压力，pa；
——空气相对湿度，%；
P饱——测点温度为t时，饱和水蒸气压力，pa；
t——空气的温度，℃。
** 标准状态下风量的计算

式中：
Q标——标准状态下的风量， m³/s；
Q测——测定地点的风量，m³/s；
ρ测——测定地点风流的空气密度，kg/ m³；
1.2——为矿井标准状态下空气密度，即大气压力为105 Pa、气温20℃时的空气密度，kg/ m³。
** 矿井有效风量的计算
1.矿井有效风量：是指独立通风的采煤工作面、掘进工作面、硐室和其它用风巷道的实际配风量之和；采、掘工作面有串联通风时，该系统有效风量只能以最大一个工作面的实测风量为准。
Q有效 =∑Q采i+∑Q备用采煤工作面i +∑Q掘i +∑Q硐i +∑Q其他i
式中：
Q有效——矿井有效风量，m³/min；
∑Q采i、∑Q备用采煤工作面i 、∑Q掘i、∑Q硐i 、∑Q其他i——采煤工作面、备用采煤工作面、掘进工作面、硐室和其他用风地点进风流中实测风量，m³/min。
2.矿井有效风量率的计算
矿井有效风量率：是指矿井有效风量与矿井总进风量的百分比。按下式计算：

式中 C——矿井有效风量率，%；
Q有效——矿井有效风量，m³/min；
Q进——矿井总进风量，m³/min。
** 矿井漏风量的计算
矿井漏风量：是指矿井外部漏风量和矿井内部漏风量之和。
1.矿井外部漏风量：是指直接从主要通风机装置及风井附近地表（包括安全出口风门、防爆门等）漏失的风量总和。可用各台主要通风机的风量总和减去矿井总回风量来计算：
矿井外部漏风量的计算
Q外漏=Q机-Q总回
式中：
Q外漏——矿井的外部漏风量，m³/min；
Q机——主要通风机的工作风量，m³/min；
Q总回——矿井总回风量，m³/min。
2.矿井内部漏风量：是指井下通风构筑物、采空区等地点的漏风量之和。可用矿井总回风量减去矿井有效风量来计算：
矿井内部漏风量的计算
Q内漏=Q总进-Q有效
式中：
Q风漏——矿井的内部漏风量，m³/min；
Q总进——矿井总进风量，m³/min；
Q有效——矿井总有效风量，m³/min。
** 矿井漏风率
1.矿井外部漏风率的计算

式中：
L外漏——矿井外部漏风率，%；
Q外漏——矿井外部漏风量之和，m³/min；
Q机——矿井各主要通风机工作风量之和，m³/min。
2.矿井内部漏风率的计算

式中：
L内漏——矿井内部漏风率，%；
Q内漏——矿井内部漏风量之和，m³/min；
Q总回——矿井主要通风机工作风量之和，m³/min；
Q总回、Q有效符号意义同前。
** 矿井风量比的计算

式中：B——矿井风量比，%；
Q矿实——矿井实际总进风量，m³/min；
Q矿需——矿井需要总进风量，m³/min。
** 矿井等积孔的计算
（1）单台主要通风机供风的矿井等积孔：

式中：
A单——矿井等积孔，㎡；
Q总回——矿井总回风量，m³/s；
h——通风机负压，Pa。
（2）两台主要通风机供风的矿井等积孔：

式中：
A1.A2——分别为第一台、第二台通风机担负系统的等积孔，㎡；
Q1.Q2——分别为第一台、第二台通风机的风量，m³/s；
h1.h2——第一台、第二台通风机的通风阻力，Pa；
A双——两台通风机联合工作的矿井等积孔，㎡。
（3）多台主要通风机供风的等积孔A总：

式中：A总——多台主要通风机供风的矿井等积孔，㎡；
Qi——第i台主要通风机的风量，m³/s；
hi ——第i台主要通风机的负压，Pa。
** 主通风机电机实际输入功率的计算
1.同步电机输入功率：

式中：
N同步——同步电机输入功率，kw；
I——同步电机输入的交流电流，A；
U——同步电机输入的交流电压，V；
cosφ——电机功率因数；
A——同步电机砺磁电流（直流电流），A；
V——同步电机砺磁电压（直流电压），V。
2.异步电机输入功率

式中：N异步——异步电机输入功率，kw；
I——异步电机输入的交流电流，A；
U——异步电机输入的交流电压，V；
cosφ——电机功率因数。
** 主要通风机轴功率（输入功率）的计算
1.使用异步电机时

式中：N异轴——通风机轴功率，kw；
η电——主要通风机电机效率，一般取0.9～0.95；
η传——电机传动效率，直接传动取1.0，间接传动取0.95；
I、U 、cosφ符号意义同前。
2.使用同步电机时

式中：各符号意义同前。
** 主要通风机输出功率计算
1.主要通风机静压输出功率

式中：h静——主要通风机静压，Pa。；
Q主——主要通风机工作风量，m³/s；
N静出——主要通风机静压输出功率，kw；
2.主要通风机全压输出功率


式中：h全——主要通风机全压，Pa。；
Q主——主要通风机工作风量，m³/s；
N全出——主要通风机全压输出功率，kw；
** 主要通风机效率的计算
1.主要通风机静压效率

式中：  ——主要通风机的静压效率，%；
N静出——主要通风机静压输出功率，kw；
N入 ——主要通风机输入功率，kw
2.主要通风机全压效率


式中： ——主要通风机的全压效率，%；
N全出——主要主通风机全压输出功率，kw；
N入 ——主要通风机输入功率，kw；
