:PROPERTIES:
:ID:       3eaefb04-1c7c-4969-aa65-c3076f3f5afa
:END:
#+title: 综采工作面端头支护工安全操作规程
* 一般规定
** 端头维护工必须熟悉本工作面煤层、顶板特征，顶板管理方式、矿压显现规律和所采用支柱的性能、结构原理、完好标准及使用维护方法，严格按“作业规程”及本规程的规定进行操作，考试合格后方可持证上岗。
** 进入作业地点后要全面检查顶帮完好情况及支护用品完好情况，发现隐患及时处理。
** 作业过程中要认真执行先支后回、敲帮问顶制度，在敲帮问顶时按下列规定执行：
*** 用镐或长钎杆敲帮，听其声音，判断岩体有无松动或离层等，发现煤帮出现伞檐或松动点，必须立即处理。
*** 问顶时要站在斜上方安全地点，一手持镐一手托顶，先轻敲顶板，无掉渣或离层剥落时，再重敲，听其声音，判断顶板深部是否离层。对松动顶板岩石找“掉”前要对上下人员打招呼，并看好退路，在安全情况下，再用镐自上而下由外向里逐渐轻轻找“掉”。
*** 坚持使用长柄工具，人员站在敲击点以外安全地点，听其声音，观察变化，判断岩体是否松动，深部是否有离层跨落迹象。
** 随时注意（听和看）顶板的动态，若发现异常现象，立即撤离所有人员到安全地点，待顶板稳定后，再进行处理。
** 金属磨擦支柱和单体液压支柱的支设最大高度应小于支柱设计最大高度的0.1m，最小高度应大于支柱设计最小高度的0.2m，当高度发生变化时，应及时更换相应型号的支柱。支设的支柱要确保迎山有力，其初撑力达到规定要求，并拴绳防倒。
** 不同性能的支柱不能混用，特殊情况下需使用时，必须制定专门措施。
** 端头维护工作业时，要和液压支架工、刮板输送机司机、转载机司机、采煤机司机等相关工种人员协调配合，并注意以下事项：
*** 顺槽靠工作面一侧的单体液压支柱如影响推移刮板输送机时，必须在推移刮板输送机前撤除。
*** 端头支护空间必须满足机头机尾与其整体的“平”、“直”，移动机头、机尾时注意输送机与转载机搭接及过渡槽过渡情况，以保证其不上翘、不下陷，运转平稳。
*** 机头、机尾移过后应及时支护顶板，否则不许开机，并要清理干净安全出口的一切杂物，保证出口畅通。
** 架设支柱时，其下方不得有人逗留或通过，防止挂梁时脱落或倒柱伤人。
* 工作前的准备、检查及处理
** 准备。备齐注液枪、锤、铁锹、尖镐、撬棍、铁丝、卸载手把、液压升柱器、斧子、锯、量具等工具。所用工具应牢固可靠。
** 检查与处理：
*** 检查工作地点的顶板、煤帮和支护是否符合质量要求，发现问题应及时进行处理。
*** 检查单体液压支柱时，发现三用阀失效、漏液、变形、弯曲、活柱表面锈蚀、顶盖缺少两个以上小爪或手柄损坏时，应及时更换；新下井或修复后第一次使用的支柱，必须内腔排气。
*** 检查金属磨擦支柱时，发现锁体部件不齐全，水平楔不起作用，断裂、无底、变形、弯曲，顶盖缺少两个（包括两个）以上小爪，不能伸缩，垫圈和托板接触不严密，焊缝裂开或柱体内煤粉影响活柱下缩时，必须处理或更换。
*** 检查金属铰接顶梁时，发现损伤裂纹，焊缝开裂，弯曲，变形，连续缺“牙”不能卡住支柱，销子弯曲或无销时，应立即更换。
*** 检查注液枪时，发现漏液、损坏、变形，无密封圈或出液不正常时，应立即配合有关人员修补或更换。
*** 操作规程中，应时刻观察顶帮，坚持敲帮问顶，发现活煤矸，伞檐，顶板离层，顶板破碎，冒顶或片帮危险时，人员要站在斜上方用长把工具撬落或及时架设临时支护进行维护。
* 基本支护操作程序
** 端头三角区支护操作：
*** 端头三角区靠工作面煤壁侧的柱梁，应在采煤机到达前回撤。一次回撤一个截深的距离，顶帮破碎时，不得提前回撤。顺槽采用锚网支护时，应提前将金属网及锚杆的金属端盘拆掉。
*** 三角区回撤柱梁作业时，至少2人协同作业，一人作业，一人监护；应先清理好退路，用长把工具将单体液压支柱放液，拉出；然后再回铰接顶梁，人员要站在顶梁掉落波及不到的安全地点。
*** 人员进入三角区作业时要将转载机与刮板输送机停机闭锁。
*** 严禁用回柱绞车强行回撤单体柱。
*** 当压力大，端头三角煤顶板严重破碎时，可增加临时支护或支设过渡抬棚，支设抬棚梁时，梁头要互相错开，抬棚腿要打在棚梁与抬棚梁的接触点上，迎山有劲。
*** 顺槽采用锚网支护的工作面，煤机割出巷帮锚杆时，前部刮板输送机因提前停机，煤机要停电闭锁，拣出锚杆，如果煤机在刮板输送机机头，要同时停止转载机。
*** 煤机周围3m及巷道5m范围内严禁有人，防止割出的杂物溅起伤人。
** 端头切顶线处支护操作
*** 按规定的间距和质量要求，支设新的切顶密集支柱及其他特殊支护后，撤除原有密集支柱及金属顶梁。
*** 回撤端头切顶密集柱梁作业时，至少需要3人，两人作业，一人监护；应先清理好退路，用长把工具将单体柱放液后用葫芦拉出，然后再回铰接顶梁，回梁时严禁人员进入老塘作业；退销撤梁，人员站在安全地点。
*** 端头切顶线处回柱放顶遇到“死柱”时，必须采取卧底和其他有效措施进行处理，禁止放炮崩或用绞车硬拉。
*** 切顶线后出现悬顶时，应制定加强支护或强制放顶措施。
** 超前支护操作：
*** 超前支护的形式和支护质量必须符合“作业规程”中的规定。
*** 在采取金属支架棚支护的顺槽内超前回撤金属棚时按以下规定执行：
**** 回撤工字钢棚必须用“作业规程”规定的专用慢速回柱绞车，并使用专用绞车及专用钩头，回柱绞车按钮、信号应灵敏可靠。
**** 用回柱绞车回棚时，有专人站在安全地点监视顶板，并在作业地点两头专人站岗，防止人员进入；操作人员要站在离绞车5m以外的安全地点。
**** 回柱绞车使用前应仔细检查，回柱绞车的固定方式要符合“作业规程”的规定并确保固定可靠，设备完好。
**** 回撤金属支架棚时，施工顺序为由里向外逐一回棚，一次一棚。要先对邻近金属支架棚进行加固，用长柄工具处理挂钩头部位的混凝土块，确保钩头与钢梁结合紧密，并拆掉所有撑木，采用松动棚腿附近巷道底板、适当松动棚腿等措施后再进行回棚作业，作业时先拉棚腿再拉棚梁。
**** 回撤棚梁时绞车应点动作业，司机集中精力，开车时手不离按钮，并严密注视绞车运行情况，阻力过大时，不得强拉硬拽，防止断绳。发现异常情况及时处理。
**** 在回柱、换棚时，严禁人员正对支柱或工字钢歪倒及片帮可能波及的地点，所有人员要躲至安全地点，并要有专人观察顶板。坚持回一棚、换一棚，严禁大拉大放，顶板破碎时要用木料背顶或下套棚。
**** 利用脚手架作业时，脚手架必须垫平，保证牢固可靠。
**** 顶板未稳定前，不得进行摘、挂钩头和外运钢梁工作。
**** 回柱绞车用完后要可靠停电，并将开关按钮放在安全地点。
** 单体液压支柱操作：
*** 带帽点柱操作及注意事项：
**** 操作顺序：量好排、柱距→清理柱位→（放置柱鞋→）竖立点柱→用注液枪洗注液阀煤粉→将注液枪卡套卡紧注液阀→给柱带帽→供液升柱。
**** 注意事项：每根柱只准带一个柱帽，严禁带双柱帽；底板松软时必须穿柱鞋。
*** 铰接顶梁与单体液压支柱的操作及其注意事项：
**** 操作顺序：挂梁→插调角楔→背顶→清理和定柱位→（放置柱鞋→）立柱→供液升柱（使用顶网时应先挂网，再按其顺序进行操作）。
挂梁。一人站在支架完整处两手抓住铰接顶梁将之插入已安设好的顶梁两耳中，另一人站在人行道，插上顶梁圆销并用锤将圆销打到位。插调角楔。将顶梁托起，由下向上插入调角楔，使梁与顶板留有0.1～0.15mm的间隙。背顶。按规定数量与上架棚子背顶材料交叉背好，并用锤打紧水平楔。清理柱窝。根据"作业规程"的规定确定柱位，清扫柱位浮煤，凿柱窝或麻面，需穿鞋时，将鞋平放在柱位上。立柱与升柱。至少一人扶柱，一人供液，先徐徐供液，待支柱见力后（以不倒柱为限），人员要躲到安全地点，实行远距离供液达到规定初撑力，退下注液枪并挂在支柱手把上，支柱及时拴绳防倒。
**** 注意事项：支护必须符合“作业规程”的规定；支设顶梁时，顶梁应摆平并垂直于巷帮煤壁；调角水平楔子必须水平插入顶梁牙口内，不允许垂直插入，正常情况下的插入方向是小头朝工作面上方，禁止用木楔或其他物品代替调角楔；升柱时，应用手托住调角楔并随升柱而及时插紧，当支柱升紧后，必须用锤将调角楔打紧；支护时要注意附近工作人员的安全和各种管线。
*** 金属摩擦支柱支护操作程序：
**** 带帽点柱操作及注意事项：
- 操作顺序：量好排、柱距→清理柱位→凿柱窝或麻面→竖立点柱距顶0.03m→用锤将点柱水平楔打紧→将点柱和木楔（柱帽）朝倾斜上方斜立→用锤将木楔向下由轻到重采结实→预紧至柱不移动→用液压升柱器升紧，达到初撑力。
- 注意事项：每根柱只准带一个柱帽，严禁带双柱帽。
*** 铰接顶梁与金属摩擦支柱的操作及注意事项：
**** 操作顺序：挂梁→插调角楔→背顶→清理和定位柱（以上操作均按第14条操作方法进行）→立柱→挂液压升柱器→升柱。
**** 升柱操作：将活柱抽出与铰接顶梁接触→轻敲支柱水平楔→将液压升柱器底座平放在锁体上→将U形夹卡紧活柱→用锤将U形夹扁楔打紧→松开点柱水平楔→关闭液压升柱器放油阀→上、下摇动手柄进行紧柱（使柱爪卡住梁牙，升紧并达到初撑力）→用锤打紧支柱水平楔→打开放油阀→一手拿锤轻打U形夹→升柱器扁楔松动后，取下升柱器。
**** 注意事项：同单体液压支柱操作注意事项。
*** 工作面端头联网操作程序：
**** 初次上网操作。
- 操作顺序：支护好上网空间→刮板输送机停电闭锁（在机头时转载机同时停电闭锁）→布网→降支架前梁→压网→逐架上齐并把各片网联成一体。
- 注意事项：加强支护或增加临时支护保证端头顶帮稳定；上网人员与支架操作人员要听从指挥，配合协调；刮板输送机、转载机停机闭锁，工作段上下各10m范围内不准进行回柱和支架操作；可以配合长料压网或预先把网边连结在长料上，一同上到支架前梁；一次降一架上一架，逐架上齐，相邻支架迈步前移吃网；人体高度不够时，可以架设牢固的脚手架，但必须有专人扶持监护；顶板破碎或煤体松软时要制定专门措施。
**** 正常联网操作。
- 操作顺序：支护好联网空间→布网挂网→联网→吊网保证煤机通行空间。
- 注意事项：联网时停止相关支架操作；敲掉不稳定的煤帮或临时支护防止掉顶片帮；人员要站在支架与刮板输送机之间操作，严禁站在网与煤壁间或在刮板输送机内挂、联网；人体高度不够时，可以设架牢固的脚手架，但必须有专人扶持监护；时刻保证退路安全畅通；联网标准和质量要符合“作业规程”的规定。
*** 端头支架操作
**** 端头支架拉移前必须先检查临近支架及端头支护的支护质量，确认无误后方可拉移端头支架。
**** 端头支架移架时应先移第三架，再移第一架，最后移第二架。移架操作按照“液压支架工技术操作规程”的有关内容执行。
**** 和溜头、溜尾相连的两组支架必须两人配合操作，拉过后，架前第1组十字梁距支架前端不大于1个循环步距的距离。
**** 当工作面因上窜下滑造成端头支架与顺槽内的金属枯梁之间距离超过500mm时，增加特殊支护。如在端头支架外侧支设走向抬棚等。
*** 过特殊地质构造区域等特殊支护方式的操作应按专门规定的安全措施执行。
* 收尾工作
** 将剩余的支柱、梁或背顶材料等，码放在规定位置，将失效和损坏的柱或梁，运到指定地点，码放整齐。
** 经班长或质量验收员验收合格后，与下一班端头维护工现场交接班后，方可收工。
