:PROPERTIES:
:ID:       e4463d00-ed39-4456-815f-bd662e0c24f4
:END:
#+title: 煤矿企业法定代表人安全生产岗位责任制
* 岗位职责
** 煤矿企业法定代表人（董事长、实际控制人）是煤矿安全生产第一责任人，对煤矿安全生产工作全面负责。
** 负责建立、健全本单位安全生产责任制；组织制定本单位安全生产规章制度和操作规程；保证本单位安全生产投入的有效实施；督促、检查本单位的安全生产工作，及时消除生产安全事故隐患；组织制定并实施本单位的生产安全事故应急救援预案；及时、如实报告生产安全事故。
** 承担安全生产第一责任人责任。加强全员、全过程、全方位安全生产管理，形成管理台账，支持、指导和督促矿领导班子落实安全生产责任。强化风险管控和重大灾害治理，每年不少于1次向煤矿安全监管监察部门报告重大风险管控、重大灾害治理情况。
* 到位标准
** 组织制定并督促落实安全生产规章制度、安全生产岗位责任制、安全技术操作规程，建立健全内部生产标准化管理体系。
** 组织制定安全费用提取及使用管理制度，并组织制定落实年度安全费用提取和使用计划。保证安全生产投入的有效实施。按规定足额提取和使用安全生产费用。为从业人员购买工伤保险等。
** 督促、检查安全生产工作，切实做到整改措施、责任、资金、时限和预案“五到位”，及时消除生产安全事故隐患。
** 监督检查安全生产风险防控和事故隐患排查治理责任体系。
** 组织制定企业安全生产规划，确定企业年度安全生产目标。
** 组织制定并实施安全生产教育和培训计划，保证从业人员具备必要的安全生产知识，掌握本岗位的安全操作技能。
** 建立健全职业病防治责任制，加强职业危害的防治与管理，按规定组织从业人员进行职业健康检查和建立职业健康档案。
** 主动接受并积极配合安全生产执法检查，督促落实安全生产监管监察指令，建立和维护企业安全生产诚信。
** 每季度至少组织一次安全生产办公会议，专门研究解决安全生产中存在的问题，向董事会，安全生产委员会汇报安全生产情况，并向职工公示。接受从业人员对安全生产工作的监督。
** 组织制定并实施的年度灾害预防和处理计划、生产安全事故应急救援预案，完善应急救援条件，开展应急救援演练，并按规定报送有关部门备案。
** 组织开展煤矿隐蔽致灾因素排查治理工作。
** 煤矿发生事故时，立即启动事故应急救援预案，及时如实向有关部门报告事故情况。主动配合事故调查和处理善后工作，落实事故处理决定。
** 建立健全安全风险分级管控工作责任体系，安全风险分级管控工作制度。每年组织开展一次年度安全风险辨识评估工作，制定各类安全风险管控措施，并每月组织开展重大安全风险管控措施落实情况和管控效果检查分析工作。
* 考核标准
根据《XX公司安全生产岗位责任考核办法》、《XX公司工资管理办法》等相关文件规定，煤矿企业法定代表人安全生产责任制到位标准一项不达标考核XX元。
