:PROPERTIES:
:ID:       1939c27a-292b-4977-ae2d-65f7abbb5fe2
:END:
#+title: 调度紧急撤人制度
煤矿生产作为一种特殊行业，主要是地下作业，作业地点受到水、火、瓦斯、有毒有害气体及顶板等的威胁，作业环境条件恶劣，地质条件常有变化，不安因素很多，为了保障煤矿安全生产和职工人身安全，杜绝伤亡事故发生，根据《[[id:544aac27-457c-4dfa-8ad5-33836bfb05fc][国务院关于进一步加强企业安全生产的通知]]》及上级政府的文件精神，特制定矿重大隐患停产撤人制度：
* 值班人员及井下各级管理人员在井下发现可能出现的灾害时，生产现场带班人员、班组长和调度人员有第一时间下达停产撤人避险命令的直接决策权和指挥权，必须采取先撤人再汇报处置的措施。
* 矿井发生灾害事故，现场人员无力抢救时，现场带班领导要迅速组织人员进行自救和沿避灾路线安全撤离，并利用最快的通讯方式汇报调度室，在指挥人员没有到达指挥部之前，由调度室值班领导全权负责指挥工作。调度室值班领导在行使以上权利时，不论现场是否发生灾害导致财产损失，事后，任何领导不得追究调度室值班人员责任。
* 如果发现隐患值班领导有特殊情况不在工作地点时，班组长应立即停止作业，不得冒险作业，能立即处理的一般事故隐患采取措施消除后再恢复作业；威胁作业人员生命安全的重大事故隐患立即撤出作业人员至安全区域，查明原因，制定整改方案整改完毕，消除事故隐患后再恢复作业。
* 如发现以下突发情况之一，井下任何人员必须立即停止一切作业，并组织撤人：
** 汛期本地区气象预报为降雨橙色预报天气或24小时以内连续观测降雨量达到50mm以上，或受上游水库、河流等泄洪威胁时，或发现地面向井下溃水的。
** 井下发生突水，或井下涌水量出现突增，有异常情况，危及职工生命及矿井安全的。
** 井下发生瓦斯、煤尘、火灾、冲击地压等事故的。
** 供电系统发生故障，不能保证安全供电的。
** 主要通风机发生故障，或通风系统遭到破坏，不能保证矿井正常通风的。
** 安全监测监控系统出现报警，情况不明的。
** 煤层自燃发火有害气体指标超限或发生明火的。
*** 发现煤层自燃发火征兆，组织撤出受威胁区域的人员，报告调度室采取措施处理；
*** 发生明火，具备直接灭火条件的，组织人员尽快将明火扑灭，不具备直接灭火条件的，组织撤出受威胁区域的人员，报告调度室采取措施处理。
** 井下工作地点瓦斯浓度超过规定的。
** 采掘工作面冒顶征兆，采取措施不能有效控制，或采掘工作面受冲击地压威胁，采取防冲措施后，仍未解除冲击地压危险的。
** 有其他危及井下人员安全险情的。
* 人员在撤离途中必须保持沉着冷静，听从现场带班领导的统一指挥，积极避灾，不得个人擅自行动。
* 矿调度室是发出预警通报的责任队组，当调度室接到井下灾害事故汇报后，要立即启动应急措施。
* 现场带班领导要立即带领作业人员根据灾害类别按避灾路线，以最快的速度撤人，在撤到全风压地点后，由当班队长负责清点人数。
* 矿井应急预案要与国家以及地方政府应急预案保持衔接，按年度应急演练计划进行演练，不断提高职工在发生事故时的紧急避险撤离意识和自我保护能力。
* 因撤离不及时造成人身伤亡事故的，要从重追究相关人员的法律责任。
* 必须每年编制符合矿井实际情况的应急预案及矿井灾害预防处理计划，并组织全矿职工学习，让每个下井职工熟悉避灾路线。井下条件和生产系统发生重大变化，及时修改应急预案及矿井灾害预防处理计划，并组织全矿职工学习熟悉避灾路线。
