:PROPERTIES:
:ID:       0dd12257-24e0-4576-97bc-44dada233fdc
:END:
#+title: 电缆工安全操作规程
* 一般规定
** 电缆工必须熟悉工作面的作业规程，懂得基本工艺，掌握本岗位及工作面危险源辨识和管控措施，熟悉井下各种事故的自救、互救知识和煤矿井下避灾路线，必须经过专业技术培训，并经考试合格后，方可上岗。
* 岗位标准操作工序
** 到达工作面后，应按照以下顺序进行安全操作：
*** 交接班；
*** 作业前安全检查；
*** 看护链带；
*** 文明生产。
* 安全操作标准
** 现场交接班
*** 佩戴好防尘口罩，进入作业地点。
- 准时进入工作面，认真检查链带情况。
- 在工作面同上一班链带工进行现场交底。
*** 询问上一班工作情况。
*** 问题的移交处理。检查完毕后，把发现的问题落实处理。
** 作业前安全检查
*** 作业环境安全检查
- 检查架前钢丝绳防护网吊挂及连接情况：工作面钢丝绳防护网使用40T链或φ18.5mm绳扣将钢丝绳与每台支架顶梁耳子吊挂，防护网上边使用8#铅丝与支架顶梁侧钢丝绳联接，下边与电缆槽连接；短边搭接长度不得小于100mm，防护网距离支架顶梁间距不得超过300mm。联网丝用8#铅丝，扣扣相连。发现有联网不合格及损坏的防护网要及时更换。
- 巡查工作面，注意煤壁片帮、漏冒顶。
*** 作业前链带检查
清理电缆槽内煤块、矸石，确保链带不刮卡、没有变形或缺失，能正常下滑，管路敷设平整无挤压。
** 看护链带操作标准
*** 从上往下清理电缆槽内煤块。
*** 站在架内人行道监视电缆、水管的运行情况，电缆滑出电缆槽时要及时扶进，电缆、水管滑出电缆槽掉入刮板机、卡拌或发生其它异常情况时，首先闭锁刮板机，再通知采煤机司机停机，然后方可处理，严禁在采煤机运行过程中处理故障，严禁在刮板机运行过程中人员站在挡煤板或齿条上处理故障。
*** 采煤机行走时随电缆折返点下移而下移防止电缆卡刮。确保电缆槽内无煤矸。
*** 要密切注意观察工作地点及周围顶帮动向，刮板机运煤情况，防止片帮或顶板掉矸伤人。
*** 采煤机在机头（尾）吃刀时，电缆工要与拉架工配合好，以防掉矸、片帮及采煤机滚筒甩煤伤人。
*** 链带不下滑时，使用1.5m绝缘撬棍站在架间翘动链带，使链带下滑。
** 文明生产
清理电缆槽内煤块、矸石，确保链带不刮卡、没有变形或缺失，能正常下滑，管路敷设平整无挤压。
* 特殊安全操作规定
** 当电缆槽内有煤矸导致链带不下滑时，需要进入架前清理煤矸时，必须按下列规定操作：
*** 工作面三机运转期间，严禁人员进入架前或煤帮作业。人员进入煤帮侧前必须将采煤机滚筒全部落至底板，通知控制台电工将三机断电、闭锁，无施工人员亲自通知不得送电。解闭锁必须坚持“谁闭锁，谁解锁”的原则，其他人员严禁擅自解锁，严禁任何人员打开采煤机、刮板输送机的闭锁按钮、支架截止阀或组合开关的隔离刀闸。
*** 人员进入架前必须认真检查作业地点及作业地点上方支架的支护情况，将作业地点上方支架升平升紧，确保支架伸缩梁打出支护顶板，护帮板紧贴煤壁，将支架进液截止阀关闭。同时，确保支架初撑力符合规定。
*** 人员进入架前，必须用工作面通讯电话通知上方人员禁止操作支架，等到上方人员回话后方可进入架前进行作业。
*** 当班负责人要严格控制进入架前作业时间和人员数量。
*** 作业时，必须安排专人时刻观察煤壁及支架架缝情况，发现煤壁松动或支架架缝夹石、飞矸等情况时必须立即通知作业人员撤至架间安全地方。
*** 作业完毕后必须确保防护网捆绑在刮板机电缆槽导向杆上。检查防护网，将吊挂时破损的防护网重新连上。
