:PROPERTIES:
:ID:       fbbc3fff-b480-4f1d-a406-a5f65edb8845
:END:
#+title: 地质灾害防治技术管理制度
* 地质技术管理
** 矿井地质必须坚持现场观测和综合分析并重的原则，实际观测资料必须准确、完整；预测资料必须有理有据，并在实践中不断检验、修正和完善。
** 严格按《[[id:2ddc3ace-958e-4b8c-a405-229946a75093][煤矿地质工作规定]]》的内容观测煤层、断层、褶曲、岩浆岩及岩溶陷落柱等。
** 工作面掘进施工前应认真分析附近井巷(钻孔)工程揭露地质资料及物探成果，掌握区域及工作面煤层厚度变化、地质构造情况、掘进层位、煤层与上下相邻煤层间距、顶底板岩性及其变化趋势，按时编制提交掘进地质说明书。
** 掘进过程中应及时填图分析，及时修改填绘断层、各个采煤层底板等高线图、区域地质图及巷道素描图，并及时收集工作面内的煤厚资料，预测前方地质情况变化，及时提交各种地质预报。规定综采工作面必须进行物探，查清工作面内隐藏地质构造、岩浆岩、陷落柱等，获得结果后10天内按《煤矿地质工作规定》的要求编制并提交回采地质说明书，经矿总工程师审批后交队组使用。
** 充分分析回采地质说明书及已开采的相邻工作面地质规律；对回采面进行动态跟踪、动态分析、动态预报，认真观测。记录已知的地质构造、物探异常区的地质变化情况，做好回采面地质素描，分析预测隐伏构造及薄煤层延展变化趋势，验证物探结果，做好地质预报工作。按要求及时编制提交采后总结。
** 生产中遇重大地质构造时，生产技术科地质负责人应立即组织地质人员深入现场进行会审，上井后根据观测及调查资料综合分析及时编制相关图件，及时向总工程师汇报，研究处理。
** 各种图纸，必须按标准化要求使用统一正确的图例、图示作图，按细则要求的时间填绘井巷工程、煤厚、断层等高线等及各种注记。地质工作用图(包括采掘工程平面图、日常手头用图等)要求随工程进度，在日常整理资料的同时随时修改填绘，并至少每月应全面分析修改一次。生产区域地质图(1：2000生产区各煤层底板等高线图、生产水平地质平面图及相应的地质剖面图等)要求每月全面填绘修改一次。基本地质图(1：5000矿井各煤层底等高线图、剖面图、各水平地质平面图等)要求每季修改填绘一次。要求图纸内容齐全，资料推测有理有据，并保证相关图件一致性。
** 各种地质资料包括图纸、原始记录本、说明书、各种台账卡片等要求内容齐全，有目录索引，做到查找方便，实现档案化管理。
** 各种物探仪器必须按使用说明书进行使用、保管与维护，指定专人负责，做到各种仪器设备齐全、完好、无损，保证物探工作能正常开展。
** 加强地质资料的发放管理，任何人不得随意对外提供地质资料及图纸，地质测量科室向外提供的一切资料、图纸、报表等，均须经技术负责人严格把关，经矿总工程师批准后方可提供或报出。
** 积极引用先进技术，不断提高矿井地质工作的技术水平，解决矿井生产建设中的各种地质问题。
* 水文地质技术管理
** 矿井水文地质工作是保证煤矿安全正常生产建设的一项重要技术基础工作、为贯彻执行安全生产方针,防止重大水患事故发生,必须认真执行《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》、《[[id:c3c897d4-b900-4119-8034-e51f6b312c80][煤矿防治水细则]]》等有关规定要求。
** 各生产队组负责人对所在矿井防治水工作负领导责任,实行全面领导,分析研究解决防治水工作中的问题,检查各项防治水工作进展情况,在人力、物力、资金等方面给予保证，总工程师对矿井防治水工作负技术责任，直接领导矿井防治水工作，为防治水患提供保证；生产技术科是矿井防治水业务科室，必须按照有关规程规定有计划地开展水文地质工作，为矿井防治水预防重大水患事故负业务责任；设计部门要将防治水工作列入设计内容；各采掘(队)长对防治水安全措施的落实同第一责任，班组长对本班组的防治水安全措施的落实负直接责任；安全科对防治水的安全技术措施的落实进行监督检查。
** 矿井水文地质工作是防治水工作的基础。为此，必须依据矿井水文地质规程的要求，有计划、有针对性地开展矿区(井)水文地质调查、勘察的观测工作，查明矿井的各种充水因素，分析研究地下水的规律，为防治水工作提供技术依据，并根据生产计划安排的需要，不间断地提供水情资料、水害情况预报，井巷接近危险地段或水情发生变化要根据有关规定提供临时水害通知单。各种水情资料、水患预报要详实、具体，要有超前性；措施要有针对性，可操作性要强，经总工程师审查批准后发送至相关队组。
** 必须认真分析研究水患预测预报资料的有关的水文资料，在编制采掘工程设计时充分考虑水害因素，从工程设计开始，为防止重大水患和探放水工作创造必要的条件，并将探放水工程纳入采掘工程设计和工作面计划时间表内。
** 生产矿井必须坚持预测预报、有疑必探，先探后掘、先治后采的探放水原则。在受水害威胁地区进行采掘施工前，必须首先查清水文地质条件，写出水文地质情况分析意见，并提出防范措施。防范措施经矿总工程师批准后实施，采掘工程待确认水患排除后方可施工。
** 探放水设计经批准后，编制施工安全技术措施。经总工程师审批后方可施工。
** 在存在老空区积水威胁的地区施工探放水工程前，都必须确定积水线，并将积水线、探水线、警戒线、积水范围和积水量填绘在采掘工程平面图上。
** 各类井巷工程贯通前，被贯通巷道有积水淤泥或水文情况不清时，必须在距贯通点30米(煤巷)或20米(岩巷)前，查清条件，待排除积水或淤泥后方可贯通。
** 矿井之间的隔离煤柱必须按有关要求留设。所有防水煤柱内不得进行任何采掘活动，以保证煤柱的完整性与隔水的可靠性。如因工程需要不得不开掘巷道时必须提出专门报告和相应的有效措施，经批准后方可施工。
** 坚持水害隐患定期排查制度，由总工程师组织每月进行一次，对重点水害问题地测组应随时组织会商，每次会商结果均要有正规记录，内容要齐全、规范。
** 当井下工作面出水或出现水文地质异常情况时，要求主管领导和有关技术人员立即赶到现场，根据现场实际情况采取相应的应急措施，对收集到的数据及时地进行分析、整理，提出结论性意见。
** 坚持质量标准化与安全生产一体化管理，杜绝防治水工作中的随意性和侥幸思想，规范矿防治水安全技术工作，以高质量的矿井防治水工作保证矿井的安全生产。
** 对地表水一般情况每月观测一次，在雨季或暴雨后根据需要增加观测次数。
** 为加强矿井防治水工作、预防重大水患事故发生，应制定防治水管理工作五不准：
*** 各类防隔水煤柱内不准随意布设巷道。
*** 当采掘工程施工中出现突水征兆时，不准继续施工。
*** 被贯通巷道有积水、淤泥或水文地质情况时，不准贯通。
*** 回采工作面波及范围内的水文钻孔或封闭不良钻孔，未经处理前，不准回采。
*** 探放水工程施工安全技术措施未经总工程师批准时，不准施工。
* 地面地质灾害技术管理
** 为了防治地质灾害，避免和减轻地质灾害造成的损失，切实履行好企业的责任，维护人民生命和财产安全，促进矿经济和社会的科学发展，根据《地质灾害防治条例》规定，结合矿实际情况，特制定本办法。
** 地质灾害是指自然因素或人为活动引发的危害人民生命和财产安全的山体崩塌、地面塌陷、地表裂缝、地面沉降、矸石山（尾矿库）溃坝等与地质作用有关的灾害。本办法所指的地质灾害是指采矿、排矸、排水、建筑、施工工业设施或构筑物和其他生产活动引发的地质灾害。
** 矿范围内办法二、规定以外的其他原因所致地质灾害按照各级政府及地质灾害管理部门的规定和治理规划、防治方案进行治理。对矿安全生产、工业设施及构筑物、职工家属生活等构成威胁的，要高度关注，加强调查，及时汇报，必要时要积极治理。对引发原因不明或有争议的地质灾害，由中介机构鉴定明确责任主体后，按谁引发谁治理的原则进行治理。
** 要高度重视地质灾害防治工作，制定完善地质灾害防治工作管理办法，落实工作责任制，建立主要负责人、分管人员具体抓的工作体系，层层抓好落实和分解，将责任明确到个人，因工作失职、渎职导致人民群众生命财产蒙受损失的，将严肃追究相关人员的责任。
** 要做好地质灾害调查监控工作，雨季前在矿井范围内开展地质灾害调查，汛期要增加调查次数和加大调查力度，特别是对危及人民群众生命财产安全和安全生产的地质灾害应设点观测，重点监测监控。
** 要建立地质灾害隐患排查治理制度，排查出的隐患要分级管理、建立台帐、整改消号，做到：
*** 一般隐患立即整改排除；
*** 较大、重大隐患挂牌督办，明确整改方案、整改措施、整改责任人、整改完成时间，落实整改资金。
** 生产技术科要做好地质灾害危险性评估工作，经评估认为可能发生地质灾害或者可能遭受地质灾害危害的建设工程，应当配套建设地质灾害治理工程。地质灾害治理工程的设计、施工和验收应当与主体工程的设计、施工、验收同时进行。
** 矿区范围内出现地质灾害前兆、可能造成人员伤亡或重大财产损失的区域和地段，要设置警戒线和警示标志，禁止人员进入。
** 要积极与地方政府和地质灾害防治管理部门沟通协作，开展地质灾害防治知识的宣传教育，增强公众的地质灾害防灾、抗灾意识和互救能力。要发动群众积极参与，构建群测群防网络。
** 地质灾害要建立管理档案，明确专人收集整理灾害相关图纸、灾害发生地点、灾害发生时间、灾害评估文件、灾害治理方案、灾害日常观察观测记录、灾害防治工程竣工验收文件等资料。
** 坚持汛期领导值班制度。汛期为地质灾害易发期，要抓好领导值班工作，搞好调度，确保地质灾害信息收报畅通，灾情、灾害处理及时。
* 测量技术管理
** 测量外业管理
*** 外业（下井）前应对设计图纸、业务技术联系单等的标定数据进行验算，二人对算，认真的计算在对算本上，要做到正、副本一致，并校对签名。
*** 小组工作要在前一天下午安排，组长把工作任务及安排向组员交待清楚。下井前做好工具、仪器的检校、准备，乘车时要把仪器抱在怀里。外业工作时，加强与施工队组的安全联系，保证人身及仪器的安全。
*** 井下测点按规定进行编号，必须明确同一个工作面内点位的编号不能有重复。
*** 井下点位的编号与原始记录本上同一点位的编号要保持一致。
*** 外业必须严格坚持二次以上的复测复算制度，检查制度。在延长经纬仪导线之前，必须对上次测量的最后一个水平角按相应的测角精度进行检查，两次观测水平角的不符值15″级导线不得超过40″、30″级导线不得超过80″，边长小于15m和倾角大于30°斜巷可放宽至1.5倍。对于检查角超限必须后退检查，直至检查角符合规定要求后方可延长导线，直线巷道除检核检查角外，还必须检测边长方可延长导线。
*** 外业测量数据必须按要求采集齐全，外业必须采集点到左右帮距离和顶底距离，以及零星工程的碎部数据，月底必须测出月末工作面的位置，严禁接收队组口报数据。
*** 测量外业观测严格按测回法“后-前-前-后”的顺序，后视度盘归零时，归完后，再次瞄准目标，然后读数。标定放线过程中发现仪器动时，必须重整仪器，重新瞄准后视再放线，放线后必须检查所放中线是否在同一直线上，并现场交接给掘进队组技术员。
*** 激光指向岩石巷道每100m设置一个控制点，每月对激光校正一次，对中腰线进行检查。
*** 测量原始记录的要求
- 每项工程测量，必须使用专用记录本，用钢笔或中性笔，按规定格式准确记录，记录项目应填写工整、齐全，以便长期保存和使用。每个测点均标注草图。
- 记录出错或观测成果超限，应用钢笔自记录本格内的左上角向右下角用直线整齐的划去错误值，重写正确值。同一点正、倒镜不得同时划改，更不允许涂改现象。对于漏测漏记项目，不能凭记忆补数，要补测、补记。
- 井下导线测量记录本上，凡是在成巷巷道里的测点要量记测点至巷道底板的铅垂距离，同时量记测点至左右帮的水平距离，取位至cm。对于无导线控制的硐室等临时工程（如躲避硐室、绞车窝、钻场、临时水仓等）都必须及时记录在导线测量记录薄上，并附示意图。
- 下井时记录本要存放好，避免弄污弄脏，不能在记录本后面作草稿纸或乱写乱画，要保证记录本的整洁完整。
- 记录本分年度按规定统一编号，年度内分组存放，年终统一整理，集中、分类归档。
** 测量内业及成果计算管理
*** 各种计算薄及成果台账封面必须填写名称、编号，目录应有标题和所在页数，要有示意图，示意图上巷道名称及点位等注记必须明了。
*** 测量内业计算要及时，外业工作结束必须在当日（特殊情况下也不能超过次日）由组长、技术员独立计算二份成果，校对、签名后作为下业务联系单等的依据，备注栏内必须有导线或水准路线示意图，还应将所有临时工程、特殊硐室、迎头位置、中腰线数据、贯通点、激光仪安装控制数据等在备注栏标记清楚。后期施工的零星工程应及时补测填绘。正副本数据要保持完全一致。
*** 测量计算起算数据统一取最近一次的复测成果。二次复测不超限时，取二次复测的算术平均值。
*** 对于联测的测量资料必须进行精度评定，检查、分析系统测量资料，及时进行闭合差计算、分配。
*** 对于作废的计算资料要及时用斜线划去，并注明原因，重新计算部分要加以说明。
*** 计算薄上和台账上要求填写项目，必须齐全、字迹工整、清晰、不得了草，示意图要布局美观、明了，及时校对、签名。待一个工作面结束后，统一整理资料，分类归档存放。
*** 对测量数据和成果未经相关领导同意，严禁外泄。
** 测量图纸管理
*** 及时制作《[[id:56654d7a-75ac-405f-b5a5-d06bde216844][煤矿测量规程]]》规定的测量图纸；
*** 不常用的图纸每半年填绘进度，常用图纸按照工程进度及时进行填绘。填绘精度满足《[[id:56654d7a-75ac-405f-b5a5-d06bde216844][煤矿测量规程]]》的要求。
*** 对图纸的使用、发放和销毁做好登记管理。
** 验收管理
*** 每旬、每月底对矿的采掘工作面进行验收；
*** 每次验收必须做好验收记录：掘进和回采工作面长度验收数据保留一个小数；高度或厚度保留二个小数。对中腰线不合格或不按相关《措施》进行支护的掘进巷道不予验收。验收原始记录必须有验收人员签字，并做好验收记录。
*** 按照原始验收记录做好验收表，经相关领导签字后，及时发放给相关领导和部门。同时验收人对相关图纸按照验收进度进行填绘。
*** 严禁在在验收工作中弄虚作假，一经发现，情节轻微者按照责任大小由科内进行经济处罚，情节严重交矿进行处理。
** 测量其它管理
*** 中腰线标定及时、准确、无责任工程事故。
- 巷道开工通知单要提前3天发送地测组。
- 重要巷道的开门应有标定工作设计图。
- 巷道开门时须对作为起算数据的上一级导线（点）进行检测。
*** 3000米以上贯通测量应有设计、审批、总结，贯通测量精度符合规程规定或工程要求。
*** 坚持巷道开工、贯通、停头、复工、停采及工程进度等通知单制度。
***  贯通通知单应提前（单向贯通时，炮掘岩巷不小于20米，煤巷不小于60米；综合机械化掘进不小于50米。两头相向贯通时，炮掘岩巷大于40米，煤巷大于60米；综合机械化掘进大于70米、未保护区贯通不小于60米。）发送施工队组、矿分管领导及安全科、调度室、通风科。
* 考核办法
对技术管理出现失误造成损失或者严重后果的追究其责任，并按矿相关制度核减责任人一定比例的薪酬或其他处分。
