:PROPERTIES:
:ID:       592d6b07-f1e6-4424-b5ec-11deadde5bf2
:END:
#+title: 巷道贯通管理制度
* 巷道贯通前应当制定贯通专项措施。综合机械化掘进巷道在相距50m前、其他巷道在相距20m前（突出煤层掘进工作面在相距60米前），必须停止一个工作面作业，停掘工作面必须保持正常通风，做好调整通风系统的准备工作。
停掘的工作面必须保持正常通风，设置栅栏及警标，每班必须检查风筒的完好状况和工作面及其回风流中的瓦斯浓度，瓦斯浓度超限时，必须立即停电撤人并采取措施进行处理。
掘进工作面每次爆破前，必须派安全员、瓦检员和班队长共同到停掘的工作面检查工作面及其回风流中的瓦斯浓度，瓦斯浓度超限时，必须先停止在掘工作面的工作，然后处理瓦斯，只有在2个工作面及其回风流中的瓦斯浓度都在1.0%以下时，掘进的工作面方可爆破。每次爆破前，2个工作面入口必须有专人警戒。
贯通时，必须由专人在现场统一指挥。
贯通后，必须停止矿井内的一切工作，立即调整通风系统，风流稳定后，方可恢复工作。
间距小于20m的平行巷道的联络巷贯通，必须遵守上款各项规定。
* 掘进工作面与煤层巷道交叉贯通时，被贯通的煤层巷道必须超过贯通位置，其超前距不得小于5m，并且贯通点周围10m范围内的巷道应加强支护。在掘进工作面与被贯通巷道距离小于60m的作业期间，被贯通巷道内不得安排作业，并保持正常通风，且在爆破时按规定停电撤人。
* 巷道贯通工作由矿[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]统一指挥。[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]对巷道贯通工作的生产组织、现场管理等工作负责。安全副矿长对巷道贯通工作的监督管理负责。
* [[id:20bd34bb-4ce1-44e3-bb8a-3fe174f78626][生产技术科]]要随时掌握巷道掘进进度，综合机械化掘进巷道在相距50m前、其他巷道在相距20m前（突出煤层掘进工作面在相距60米前），必须向[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]汇报，同时下达贯通通知书。
贯通通知书应包括：待贯通巷道长度、贯通巷道与被贯通点20米范围内的巷道相对位置、通风、瓦斯、积水区、采空区及小窑等内容。
贯通通知书须经矿[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]审核签字后，送[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]、[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]和[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]、生产队组、[[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]及[[id:8b3b7f54-5496-480a-9d1a-a4b33629d2cd][矿调度室]]。
* 接到贯通通知书后，[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]立即组织编制巷道贯通安全技术措施，并报相关队组及[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]进行审批。
安全技术措施应包括：通风系统调整方案、贯通前后通风系统示意图、放炮设岗警戒示意图（炮掘工作面）和防范通风、瓦斯、煤尘事故及现场组织措施等内容。
经[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]审批后的安全技术措施须报上级部门备案。
* [[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]在接到贯通通知书后，必须对贯通前后的通风系统进行分析，提出合理的调整方案，经矿[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]批准（改变矿井通风系统时，须报上级总工程师审批）后实施。[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]提前做好通风系统调整的准备工作。
* 施工队组必须严格落实通风科编制的[[id:97018547-b054-4ad5-abec-81d857b67708][安全技术措施]]。每班向矿调度汇报施工进度，差5米贯通时，由矿调度向矿[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]、[[id:6479eb8b-5a74-436f-9eda-2e66ec777626][生产副矿长]]及矿值班领导汇报，并通知[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]。必须边探边掘（原则上必须探透），防止误贯通。
* [[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]接到贯通通知书后，负责监督、落实相关安全技术措施。
* 停掘的工作面必须设专职瓦检员经常检查风筒的完好状况和工作面及其回风流中的瓦斯浓度。瓦斯浓度超限时，必须停止贯通工作面的掘进，立即采取措施进行处理。
* 进入贯通警戒范围，掘进工作面每次装药放炮前，必须检查停掘工作面的通风、瓦斯情况，只有在2个工作面及其回风流中的瓦斯浓度都在1.0%以下时，确认瓦斯、通风正常，两个工作面的瓦检员分别向矿调度汇报，由矿调度下达放炮命令，并做好记录。
每次爆破前，2个工作面入口必须有专人警戒。只有接到矿调度下达的放炮命令后，方可起爆。
* 每次放炮后，安全员、放炮员、掘进工作面班队长和瓦检员必须检查通风、瓦斯、煤尘、顶板、支护和瞎炮等情况。只有两工作面检查完毕，确认无异常后，方可恢复正常作业。如发现异常情况，必须立即采取措施进行处理。
* 相距2米贯通时，必须停止掘进，矿必须安排一名副总工程师或以上管理管理人员到现场统一指挥，[[id:c9eccf15-5e95-4c88-b767-956a2a9b9e2f][通风科]]、[[id:23586232-f38d-4117-9460-d4428f1448e8][安全科]]指派一名副科级及以上管理人员到现场负责贯通的具体工作。
* 贯通时，停止矿井内的一切工作，两个工作面及其回风系统必须切断电源、撤出人员，并在与其相连巷道内设岗警戒。
* 贯通放炮时，严格执行“一炮三检”和“三人连锁放炮制”。
* 贯通时，被贯通巷道迎头安设监测探头，[[id:8b3b7f54-5496-480a-9d1a-a4b33629d2cd][矿调度室]]要随时观察瓦斯浓度变化情况。
* 贯通后，立即进行通风系统调整，实现全风压通风，待通风系统稳定后，对系统的风量、瓦斯及二氧化碳等参数进行检测，检测参数符合《[[id:b71952b6-3391-434f-a727-1a41ed3d8883][煤矿安全规程]]》规定后，汇报[[id:8b3b7f54-5496-480a-9d1a-a4b33629d2cd][矿调度室]]，[[id:8b3b7f54-5496-480a-9d1a-a4b33629d2cd][矿调度室]]汇报[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]，由[[id:cd13b47d-88cf-4415-a6c8-b40db130472b][总工程师]]下令恢复正常工作。
* 贯通后，矿调度要及时汇报上级部门。
* 贯通巷道和被贯通巷道都必须安设电话。
* 间距小于20m的平行巷道的联络巷贯通，必须严格执行本制度的有关规定。
* 与采空区（包括联通采空区的巷道）、老窑和情况不明的巷道贯通，必须先采取钻探方法探明贯通距离、贯通地点的瓦斯等有毒有害气体、积水及其它情况，并编制专门的安全技术措施经矿总工程师审批后实施。
* 掘进巷道与老巷，硐室等贯通后，根据现场情况，需要对老巷、硐室等进行封闭的，必须及时按密闭施工要求提报设计，并组织密闭施工。密闭施工结束后必须建立密闭管理台账，并严格按设施管理要求进行挂牌管理。
* 通风科要认真做好贯通台帐，记录贯通时间、贯通前后的风流方向、风量、瓦斯浓度及异常情况等。
