:PROPERTIES:
:ID:       35035e9e-7caa-4215-8a3f-a96cc206b366
:END:
#+title: 巷道维修工安全操作规程
* 相关规定
** 各种巷道的维修、修复工作必须编制专门安全措施，并报矿相关业务科室批准后实施。
** 煤矿井下各类巷道高度不得低于《煤矿安全规程》第21.22条规定，支护应完好。不符合上述要求的要进行维修。
** 修复旧巷道时，必须首先进行瓦斯检查和通风，各类气体的浓度符合《煤矿安全规程》规定后，方可操作。
** 在有车辆运输的巷道中进行巷修工作时，要设置警示标志，注意来往车辆。
** 对支架进行维修和更换时，要事先对该地点进行加固，可靠安全长度不低于10米。
** 更换支架时，新的支架支护强度不得低于原有支架（完好状态时）的支护强度。
** 在维修巷道中需要放炮时，必须按照爆破工操作规程操作。
** 在维修巷道中，要保证安全出口，由外向里施工。
** 备齐所需工具，如风镐、风钻、电钻、锯、铁锨等，长把工具的携带要遵守有关规定。
** 根据“安全规定”中的要求，检查是否具有正常操作的条件。
* 相关操作
** 本工种操作应遵照下列顺序进行：安全检查→维修支架→清理现场。
** 梯形棚（铁、木）支架的维修：
1.梯形棚（铁、木）支架的维修一般有换1条腿、2条腿、棚梁和全部更换几种施工。
2.换1条腿时：
（1）先在断腿的邻近处打1根临时支柱，替换已经损坏的棚腿支撑原来的棚梁。
（2）在顶梁上要设拉木，刹满刹牢，以防止顶梁滑动。
（3）小心的处理大块的浮石、浮煤。
（4）开挖巷道帮（如果未变形，可以不进行此项工作）。
（5）挖柱窝，更换新的棚腿。
（6）在更换完后，支架与顶帮之间的空隙，必须刹紧、背实。
（7）在支架间，安设牢固的撑木或拉杆。
3.换2条腿时：
（1）先在两帮的原来棚腿邻近处各打1根临时支柱，替换已经损坏的棚腿，或采用抬棚托住顶梁。
（2）其余方法与更换1条腿时的操作一样，但要先换1条腿后，再换另外1条腿。
（3）如果巷道高度不够，可以参照“换全部支架”和“支护工”等的操作方法。
（4）在更换完后，支架与顶帮之间的空隙，必须刹紧、背实。
（5）在支架间，安设牢固的撑木或拉杆。
4.换顶梁时：
（1）如原来的支架棚腿未动、未损坏的，可以不更换棚腿。
（2）用拉条、撑杆加固棚腿。
（3）用几排串钎贯穿于两架完好的顶梁之上，挡住上部浮石。
（4）更换顶梁，保证做到亲口吻合。
（5）在更换完后，支架与顶帮之间的空隙，必须刹紧、背实。
（6）在支架间，安设牢固的撑木或拉杆。
5.换全部支架时：
（1）加固临近的完好的支架，留好退路。
（2）如果维修棚梁上部冒落较高，浮石较大，应在施工地点设置小型木垛，并进行瓦斯检查。
（3）然后按照换棚腿、换顶梁的方法，逐项操作。
6.换金属支架时，要防止金属撞击产生火花。
7.U型钢拱型支架巷道维修：
（1）U型钢拱型支架的更换：
①在坏棚处，打1根支柱，支撑到拱形的最高点的顶梁上。如果连续几架棚子损坏，应架设抬棚，并将所有损坏棚子的顶梁托住。
②用手镐掏空棚腿处的煤矸。
③拧松卡缆螺栓，撤下棚腿。
④检查2节U型钢搭接处是否有劈裂、变形，如有需要更换整个支架。
⑤换上新的卡缆螺栓，接上棚腿。
⑥确认卡缆螺栓拧紧后，撤下先前安设的支柱。
⑦棚腿与梁搭接处的曲率半径要一致，如果不一，需要重新调整。
⑧在更换完后，支架与顶帮之间的空隙，必须刹紧、背实。
⑨在支架间，安设牢固的撑木或拉杆。
（2）U型钢拱型支架其他部位的更换，应参考上面的规定进行。
8.砌碹巷道的维修：
（1）按规定准备好材料，并停电、保护好电缆、水沟、管路等。
（2）加固临近巷道，确保安全出口。
（3）倾斜巷道施工前，在施工地点的上下两头必须分别设置临时保护挡板，以防矸石、料石等物滚动伤人。
（4）砌碹巷道维修方法有3种：
第1种：拆除旧碹体，浇注新碹体。当有较大区段砌碹巷道遭破坏而需翻修时，采用该方法。按下列顺序进行操作：
①拆除旧碹体应自拱顶开始向两侧拱基和碹墙进行，直至墙基。
②及时清掉顶帮的浮矸。
③打临时木柱或架木支架（当顶压大时，可架工字梁或槽梁金属支架）。
④如拆除碹体后，巷道断面不足，需刷帮处理至巷道轮廓基本符合要求。
⑤拆除一定距离后，可以按照正常的砌碹巷道施工操作规程进行。
⑥不回收的临时支架与顶帮的空隙要用碎石或低标号混凝土填塞充满。
⑦当碹墙完好而碹拱遭破坏需翻修时，应先自拱顶向两侧拆除拱顶至拱基，并在碹墙上架设临时木支架，至一段距离后，即可架设模板按照普通砌碹巷道方法进行浇注。
第2种：裂缝修补法：
①加固支护。
②将裂缝扩大、加深。
③填充水泥浆（1 ：1）。
第3种：局部修补法。
①加固支护。
②将原来的碹体挖出。
③清理、冲洗处理部位。
④加钢筋网，浇筑混凝土。
9.锚喷巷道的维修：
（1）拱顶、两帮小面积脱皮，可以采用补喷的办法。
（2）拱顶、两帮脱皮面积超过2平方米，脱深为0.3～0.5米时，可以采用补打加长锚杆挂网联合补喷的办法。
（3）大面积冒落，连续失修巷道长度超过5米、冒落高度超过0.5米、锚杆松脱的，可以采用拱型支架和砌碹维修或其他联合支护的方式。
（4）塑性变形大、位移量大、原来喷层脱落但未冒顶的，可以采用锚喷网加拱型支架联合支护的方法。
（5）锚喷巷道的维修操作，可以参考掘进锚喷支护的操作规程。
10.大冒顶巷道的维修：
（1）观察分析顶板、瓦斯等情况，制定施工措施。
（2）在冒落区周边打临时支柱，将冒落处的顶板托住。
（3）逐步向冒落区推进，清理冒落矸石（煤）。
（4）依次由一端架设棚子，棚子以上未接顶的地方要用木垛接顶。
（5）进行安全检查，确认无危险后，方可收工。
11.开岔门处抬棚的维修，首先检查维修、加固周边的支架，然后再进行抬棚更换。具体施工操作方法，应按照“支护工”的有关规定和架棚巷道的支护等章节进行。
12.进行木垛盘式反井维修时，应编制专门安全措施，配齐安全装置：
（1）检查维修反井上口的抬棚及垛盘锁口棚。
（2）反井上口安装一个锁口盘，支撑住反井上口梯形支架，防止顶部坍塌。
（3）如果反井不做通风之用，需在锁口盘上放置遮挡物，以便接住上部坠落物。
（4）检查维修井中各垛盘时，应由上向下逐架检查维修。
（5）维修人员操作时，必须佩带保险绳。
13.水沟的维修：
（1）控制水流。
（2）加固水沟临近的柱腿。
（3）加固道基。
（4）清理淤渣。
（5）敷设或砌筑新的水沟。
14.进行检查，清理现场，保持现场整洁，支护完好。
15.带齐工具，上井后填写维修记录台账。
