:PROPERTIES:
:ID:       c92f5f4f-5a6f-4796-a5e6-e96ea1546640
:END:
#+title: 电气试验测试制度
一、电气试验工作的目的
（一）电气试验工作，是为了鉴定电气设备的绝缘状态，测试分析电气设备技术性能，为机电设备安全、可靠运行，提供技术依据。
（二）检验电气设备性能是否符合有关规程标准的技术要求、是否存在缺陷或故障现象，以便确定能否继续投入使用。
（三）对运行中的电气设备进行正常检验；对新投入的电气设备进行必需的试验，以便确认能否投入运行。
（四）检查、测试绝缘导线和电缆绝缘是否完好，是否符合煤矿安全用电要求，确保供电安全。
二、电气试验的责任
（一）电气试验人员对电气试验工作要认真负责，要以科学的态度对待电气试验工作，要消除侥幸、麻痹大意心理，确保人员及设备安全。
（二）重视图纸和技术资料的核查工作，并要根据客观实际情况，安排好试验工作。
（三）进行电气试验工作，至少应有两人参加，操作时应精力集中，以确保安全。
（四）电气试验工作必须按电气试验标准进行，并且不得少做、漏做或随意降低试验标准。
三、电气试验的准备工作
（一）试验工作开始前要办理好停、送电工作票，然后工作人员应根据试验目的，了解试验用电源的接线方式、组别、相序、电压等级及电压对称性等情况。
（二）试验前，工作负责人应讲述安全注意事项，试验负责人应讲明试验目的和内容。
（三）开始试验前，试验负责人应指派一人检查被试设备及其周围有无人工作，在确认无人工作后方可进行试验。
（四）为保证试验质量，试验前必须检验其所使用仪器、仪表以及相关工器具（主要有：电缆试验仪、调压器、试验变压器、电压表）的完好状况，确认完好后方可使用。且仪器、仪表必须在有效检验周期内。
（五）在井下做试验时，凡有可能积聚瓦斯的地方，必须先检查瓦斯浓度，只有当瓦斯浓度在1%以下时，方准进行试验工作。
四、电气试验工作中的安全防范措施及注意事项
（一）电气试验工作应严格遵守《煤矿安全规程》及《煤矿电气设备试验规程》中的有关规定。
（二）电气试验工作至少应有2人及以上参加。且监护人员必须是对此项工作较为熟悉的或者技术职称较高的人员担任。
（三）试验电源的开关，须使用有明显断开的刀闸开关，而且放在靠近试验人员的位置，以便操作。
（四）试验结束后，拉开试验电源，将试验部位进行接地放电。在井下做试验时，凡有可能积聚瓦斯的地方，必须检查其瓦斯浓度，只有当瓦斯浓度在1%以下时，方准放电。
（五）试验工作结束后，应检查其填写的试验记录，如试验记录无误，方可拆线，将被试设备恢复原状态。工作结束后，由试验的安全监护人和现场负责人检查并验收，认为无误后，方可离开现场。
（六）试验用的设备和仪器、仪表，在搬运及存放现场时，要妥善保管，防止灰尘、潮气侵入。仪表的放置位置和墙壁之间要留出0.5m的通道。
五、电气试验工安全技术操作规程
（一）电气试验工作应严格遵守《煤矿安全规程》及《煤矿电气设备试验规程》，执行工作票制度、工作监护制度、停送电制度及现场有关规定。
（二）试验工作不得少于2人，工作负责人应由该设备队组熟知现场情况且具有一定专业水平的合格人员担任。
（三）试验前，工作负责人应讲述与试验工作相关的安全注意事项，试验负责人应讲明试验的目的和内容。
（四）开始试验前，试验负责人应指派一人检查被试设备及其周围有无人工作，在确认无人工作后方可进行试验。
（五）工作负责人应不间断地在工作地点对工作人员及设备的安全进行监护，若发现有不正确的危险行动时，应立即对工作人员提出警告，必要时停止此项工作，监护人因故离开工作地点时，如找不到适当的人员代替监护，必须立即停止此试验工作；若找到适当的人员代替监护，监护人员必须将整个试验工作的安全注意事项和工作全过程向代替监护人员交代清楚，让代替监护人完全清楚整个试验工作的操作程序和安全注意事项，否则严禁继续此项试验工作。一切非工作人员一律不得进入试验场所。
（六）电气试验的停、送电及操作必须由试验负责人发出口令，操作人员应按口令执行。试验完毕应停电、验电、放电，只有得到试验负责人的命令后方可拆除试验接线和试验接地线。
（七）试验过程中，所有参加工作的人员必须严守工作岗位，精力集中，严禁闲谈嘻笑或做其它与试验工作无关的事。
（八）井下进行试验时，工作负责人必须取得有关部门负责人、瓦检员同意，检查瓦斯、派人站岗放哨，加强联系，防止意外发生。
（九）在高压设备上进行电气试验工作应断开电源，在各个可能来电的方向应有明显断开点，对被试设备应验电放电，对大容量的设备放电应不少于5～8min。
（十）为测量准确尽量把与设备的联接线拆除，拆除后接线应做标记号，防止恢复时出现错误。
（十一）试验电压超过1KV的，应装设遮拦或用围绳拦护并悬挂“高压危险”的标志牌。
（十二）试验用的仪表放置地点及操作人员位置必须在高压危险区以外，试验人员应了解试验中所使用的仪器、仪表和设备的结构性能。
（十三）试验用临时接地线、电源专用线、刀闸及开关，应按电流大小选择，要有足够的容量和机械强度。
（十四）试验负责人应检查试验用的电源电压是否正确，以免损坏仪器和设备，试验电源刀闸必须置于操作人近旁，并装有适当保险丝。试验人员离开工作岗位及接线前时，刀闸必须在断开位置。
（十五）电气试验必须按照试验规程中高压、继电保护、仪表的试验项目方法的顺序进行。试验中发现异常，应立即停止试验查明原因方可继续进行试验。
（十六）高压试验完毕，应用专用的放电棒进行放电，对于电容器应采取经过电阻放电后再采取直接放电，大容量的设备，电缆等应不少于3～10min，之后方可进行拆接线的工作。
（十七）绝缘试验应在天气良好、周围温度不低于5℃条件下进行。用摇表测量绝缘电阻时，不得少于2人，测量前应将被试物残余电荷放净后进行。测量线路绝缘时，应通知对方且确认线路上无人工作后方可进行测量。
（十八）带电在二次回路中测量必须防止电压回路短路，电流回路开路，若串接电流回路带电更换电流回路仪表，必须有专门试验端子或专门接线盒，严禁用铜丝缠绕。
（十九）电气试验工作人员的正常活动范围，6～35KV的安全距离为0.7m,小于上述距离,应将该设备停电。
（二十）电气试验耐压升压速度无特殊要求时，一般不应超3KV/S的速度。
