:PROPERTIES:
:ID:       0b1686b0-6551-4547-a50a-623d83d3f380
:END:
#+title: 带班领导带班下井制度
为认真贯彻落实《[[id:544aac27-457c-4dfa-8ad5-33836bfb05fc][国务院关于进一步加强企业安全生产的通知]]》(国发〔2010〕23号)和《[[id:149bc76b-2a8b-4a4a-8e0e-f88f2167b860][煤矿领导带班下井及安全监督检查规定]]》（国家安全生产监督管理总局第33号令），做好领导带班下井工作，结合矿实际情况，制定本制度。
* 一般规定
** 本制度所称带班领导，是矿领导班子成员和副总工程师。
** 矿长对落实领导带班下井制度全面负责，安全副矿长牵头督促落实领导带班下井制度的执行。
** 每班必须有带班领导带班下井，并与工人同时下井、同时升井。没有矿领导带班下井的，职工有权拒绝下井作业，并且不得因此降低职工工资、福利等待遇或者解除与其订立的劳动合同。
** 个人对带班领导未按照规定带班下井或者弄虚作假的，均有权向煤炭行业管理部门、煤矿安全监管部门、煤矿安全监察机构举报和报告。
** 矿长每月带班下井不得少于5次，其余分管井下安全生产的分管领导和副总工程师每月带班下井根据实际生产情况进行安排，每月带班下井不得少于5次。每月底由矿安全副矿长牵头制定下月带班计划，经矿长审核同意后，以文件形式发布执行。矿调度室每月5日前，根据人员定位系统记录、带班记录、交接班记录统计上月带班计划的完成情况，张贴在井口或者其他醒目位置公示，公示内容涵盖带班领导入井时间、行走路线、出井时间等。带班下井不得出现空班，带班领导如因有事不能带班下井时，应由本人商请其他带班领导带班下井，并完善手续报调度室备查。
** 矿领导带班下井时，应当履行下列职责：
*** 加强对重点部位、关键环节的检查巡视，全面掌握当班井下的安全生产状况。
*** 及时发现和组织消除事故隐患和险情，及时制止违章违纪行为，严禁违章指挥，严禁超能力组织生产。
*** 遇到险情时，立即下达停止作业，撤出涉险区域人员的命令，组织涉险区域人员及时、有序撤离到安全地点。
*** 带班领导应及时将井下的安全情况汇报矿调度室。
** 带班领导带班下井时权利：
*** 有权制止“三违”行为，并按照矿相关规定对责任者进行经济处罚、警示教育。
*** 有权制止危及人身安全的不安全行为，并要求责任人及时纠正或限期整改。
*** 特殊情况下，有权调动矿人力、物力资源。
*** 有权代表矿执行上级文件和矿各种安全指令及规章制度。
** 带班领导带班下井时任务：
*** 遵守有关法律、法规，严格执行上级文件和矿有关安全管理制度。
*** 向职工宣传党和国家的安全生产方针、政策、法律、法规、规章制度、上级有关文件精神及矿井安全生产形势等，提高职工安全意识和技能，激发职工树立主人翁意识，增强责任感。
*** 深入职工群众中，经常与职工交流、沟通，全面了解职工思想、工作、生活状况。
*** 对职工提出的建议和意见，应如实向矿班子成员反映。
*** 认真排查隐患，并及时向矿调度汇报，采取有效措施现场跟踪处理。
*** 揭煤、采空区放水、处理冒顶、巷道贯通、启封密闭等重要作业环节，带班领导应现场指挥监督。
*** 认真执行交接班制度，并做好带班下井工作记录。
** 带班下井实行井下现场交接班制度。上一班的带班领导应当在井下向接班的领导详细说明井下安全状况、存在的问题及原因、需要注意的事项等，并认真填写交接班记录簿。因工作需要，当出现当班带班领导和下一班带班领导不在同一个地点带班情况时，交班领导应将井下安全情况向调度室汇报清楚，接班领导应向调度室汇报带班地点，调度室做好领导带班记录（并采用电话进行现场交接班）。
** 矿带班领导升井后，应当及时将下井的时间、地点、经过路线、发现的问题及处理情况、意见等有关情况进行登记，记录簿由矿调度安排专人保管，记录簿用完之后交矿调度存档备查。矿领导带班下井的相关记录和信息保存期不少于一年。
* 领导带班下井公示规定
** 公示载体
在矿井显著位置设立公示栏，应根据实际情况及动态管理、长期置放和清楚方便的要求进行规范。要尽可能独立置放，位置明显，字体端正，实用规范。遇有损坏或字迹不清的，要及时更换、维修或刷新。
** 公示对象
矿领导班子成员和副总工程师。
** 公示范围
由矿制作公示牌，在井口公示当班带班下井的带班领导姓名。
** 公示内容
矿井制订的矿领导带班下井计划，包括下井个数和班次。
** 公示要求
*** 矿领导带班下井计划必须符合上级相关文件的要求，详细制定下井班次和下井个数。
*** 公示工作必须矿调度对矿领导带班下井记录进行认真统计，经矿长审核无误的，进行公示。
*** 公示栏填写内容必须确保真实性，填写人员必须认真核实，严禁出现徇私舞弊，弄虚作假现象。
*** 矿领导带班下井公示接受上级部门、职工及群众监督，如发现公示内容不实，可向有关主管部门检举。
* 领导带班下井考核奖惩规定
** 矿长每月抽查一次带班领导带班完成情况，对不按规定带班的带班领导进行考核，考核结果由矿安全部门报上级安全部门，以便上级安全部门督查。
*** 带班人员无故不带班的，一次罚款XX元。
*** 带班人员未与当班员工同时入井同时升井的，一律按违章处罚，一次罚款XX元。
*** 未填填写交接班记录或填写不规范，罚款责任人XX元/次。
*** 矿调度室未按规定公示带班计划和完成情况的，罚责任人XX元/次
*** 矿领导带班一次奖励XX元，当月兑现。
*** 矿领导下井带班接受职工和社会监督。
** 调度室建立领导入井考核记录，对完不成下井带班作业次数的，当月每少一次下井带班罚XX元。
** 带班下井的矿领导应及时发现和组织消除事故隐患和险情，及时掌握当班入井人数，及时制止违章违纪行为，严禁违章指挥，严禁超能力组织生产和建设；遇到险情时，立即下达停产撤人命令，组织涉险区域人员及时、有序撤离到安全地点。如果带班领导不认真履职，弄虚作假，一经查实，对本人处以XX元的罚款。
** 对应带班下井的领导带班未下井而发生事故的，对该领导依照下列规定处以罚款：
一般轻伤事故，处以医疗费的X%，发生重伤事故和死亡事故的，按规定逐级上报矿和上级主管部门接受处罚。
** 根据矿领导的下井情况，发生每起事故的当班领导履职情况等，每季度进行一次考核评比，对跟班到位无事故的领导予以奖励，对跟班数量不够，工作不到位或因跟班不到位而发生事故的领导视情节予以处罚。
* 领导带班下井举报规定
** 为了进一步落实矿领导带班下井制度，欢迎广大管理人员和职工群众对矿级领导带班下井情况进行监督，对矿级领导当班应下井带班而未下井带班履行职责的，有权向矿或上级主管部门进行举报。
** 举报人
凡在××矿内从事煤炭生产、安全管理的职工，以及关心、关注、支持××矿煤炭生产、安全管理的任何人员均可举报。
** 举报对象
矿规定要求下井带班的管理人员。
** 举报内容
对在矿安全工作上，有下列问题的均可举报：
*** 没有按要求进行下井带班的领导。
*** 没有达到国家规定的下井带班天数。
*** 入井带班领导违章指挥的。
*** 隐瞒事故的。
*** 未严格执行入井带班交接班制度的。
*** 作业范围内存在重大安全隐患强制职工作业的。
*** 员工有“三违”行为而不制止的。
*** 未遂事故发生后未及时汇报、追查和处理的。
*** 不按照法律、法规和国家标准或者行业标准规定而违章生产的。
*** 生产场所存在重大安全隐患，而未有效治理继续生产的。
*** 对举报人员打击报复的。
*** 其它需要举报的内容。
** 举报方式
可受理电话、电子邮箱举报
*** 矿长（办公室）：
*** 矿调度室主任（办公室）：
*** 矿调度室：
*** 上级监督管理部门：
** 奖励办法：
接到举报后，相关部门要认真做好记录，严格执行保密制度，不得将举报人及举报情况泄露。被举报领导不得打击报复举报人，如有泄密或打击报复举报人的，从严查处罚；对举报矿级领导当班应下井带班而未下井带班的，经查实，给予举报人XX元的奖励。
