:PROPERTIES:
:ID:       e33e6461-c342-49ae-8e45-8d1107fe2c2c
:END:
#+title: ZY-2000型钻机安全操作规程
* 钻机的搬运
** 首先对钻机进行解体：将钻机分成四个部分搬运，即泵站、操作台、主机、钻具。
** 在运输钻机时，注意各胶管不要乱扔和过渡弯曲，所有外露孔口要包裹或加帽罩等，防止脏物进入元件和胶管内。
** 拆下的各紧固件应带在相应的零件和部件上，以免丢失或混淆。
** 装卸钻机时人员要相互呼应，设专人负责安全、统一指挥，使用绞车提放时要与矿车或花栏车捆绑牢固。
** 将导链、管钳等应用工具随同运到打钻现场。
* 钻机的安装
** 在钻机运到之前，先准备好场地、电源和水源。
** 钻机运到指定地点后，将各组件按部件进行组装，然后分别将泵站、操作台和主机摆放在既利于安全操作和监视各部工作，又便于搬运的位置，泵站置于钻机的进风侧。
** 泵站油箱内加入46#抗磨液压油，油箱油位应在油位指示器的2/3处以上，接好冷却水管，根据液压系统图连接好各胶管，不能接错位置。
** 根据钻孔的位置、方位角，调整主机的位置和方位，将主机夹持器所连接的两根管状导轨向前拉出（或用推进油缸推出），当管状导轨上的两孔与机身上的两孔对齐时，用插销插入，并用立柱固定钻机。
** 将推进油缸的胶管，与机架后部的调定油缸的快换接头相边接，启动泵站（注意钻机的转向是否与所标箭头相一致），将操作台上的节流阀全部松开，操作推进手把，把钻机调整到设计所需的倾角。
** 将支撑管的一端用销子插入机架底盘合适的孔内，加一端用插在机架上梁的抱箍抱紧，紧固好螺栓。
** 用螺纹调节支撑杆，支在夹持器下的耳槽内，插上销子，转动螺杆调节支撑杆长度到合适的尺寸，将支撑杆下端插入机架底盘前端的槽内再插入定位销。
** 将两根立柱压在钻机底盘上与巷道顶底撑紧。
** 以上所有支撑无误后，将接在调定油缸上的快换接头拆下，装在推进油缸的油管上，其他胶管按正确的方式全部接上。
* 钻机的操作
** 开钻前先检查各油管是否正确；各连接螺栓是否拧紧，立柱是否锚固牢固；检查冷却水是否连通；点动电机，检查电机的旋向是否与齿轮泵所标定的转向一致。
** 操作多路阀和手把，使其置于中位。
** 钻机空运转1分钟，检查钻机各部件是否正常。
** 操作卡盘手把，使卡盘夹紧水变轴或钻杆，开启冷却水。
** 操作旋转手把至正转位，使动力头带动钻杆正转。
** 待孔口见到返水后，操纵前进、后退手把至前进位，使给进油缸以正常速度钻进。
** 在钻进过程中，因切削阻力发生变化时，可调节微调来控制推进速度。
** 当一根钻杆钻完需加接钻杆时，先停止推进，再停止旋转，关闭冷却水，操作夹持器手把，使夹持器夹紧钻杆节流阀开启（右旋），回转器反转，与此同时，后退给进油缸，使水与钻杆旋离，停止旋转，操纵快速进退手把置快退位置使卡盘快速退到位，将要加接的钻杆接在前一根钻杆上，回转器边旋转边前进，当水变轴梯形锥螺纹与新加钻杆锥螺纹旋合接触时，立即操纵夹持器手把，松开夹持器，完成钻杆加接，停止推进，打开冷却水，待见到孔口返水后，调整节流阀使压力增大到合适压力再往前推进。
** 卸钻杆时，夹持器夹紧水变轴前的第一根钻杆，回转器反转，与此同时，推进手把置于后退位置，使水变轴与第一根钻杆分离，松开卡盘，取下水变，打开并推进卡盘，用卡盘夹紧第一根要退出的钻杆，松开夹持器，操纵前进后退手把使钻杆后退到适当位置，即第一根钻杆与第二根钻杆连接处露出在卡盘和夹持器之间，打开微调节流阀（右旋），操纵夹持器手把夹紧钻杆，回转器反转，推进手把置后退位置，松开钻杆之间的螺扣，操作卡盘手把，松开卡盘，卸下一根钻杆。
* 注意事项
** 所有快换接头必须擦干净后方可进行安装。
** 孔内有钻具时，除按规定程序卸钻杆的动作需要外，不允许回转器反转。
** 回转器反转拆卸钻杆时，油缸必须留足卸扣行程，以免损坏钻杆螺纹。
** 钻机工作过程中，应随时注意各运动部件的温度变化，轴承、齿轮、油泵、油马达、电动机等处的温升不得超过45℃，油箱出油口处的温度不得超过60℃，否则应停机检查并加以处理。
** 钻机工作时，注意液压系统的元件，胶管及管接头是否有漏油现象，各机械连接部件、锚固部件是否有松动现象，如有故障应及时处理。
** 钻机工作时，除了因钻进负荷变化而引起的供油压力、旋转速度和推进速度的相应变化外，系统压力突然大幅度升降引起旋转、推进速度巨变，应立即停机，找出原因，处理故障。
** 当钻机停止工作时，所有操作手把应置于中位。
** 钻机运行过程中，要随时注意支撑立柱的变化，发现松动立即用摇把摇紧。
