#+title:贵州润鑫能源有限公司铁厂煤矿汇报材料
#+date:2022年6月23日

* 煤矿基本情况
** 单位名称，状态（基建），建设情况、历史沿革、投产时间。
** 企业性质（私企）、股权结构、投资人、法人、主要负责人基本情况及履职情况。
** 营业执照（有）、采矿许可证（有）、安全生产许可证（无）等证照情况。
** 机构设置及安管人员配备情况，生产、采掘区队设置及人员情况。
** 设计生产能力、核定能力，开拓方式，采煤工艺，开采煤层、实际开采煤层，
** 瓦斯等级、水文地质类型、煤层自燃、冲击地压等灾害情况。
* 组织机构、管理制度和责任制落实情况
** 专门机构建立情况。安全、防突、防冲等专门机构和队伍及配备相应安全、技术管理人员情况，人员素质和能力能否满足煤矿实际需要情况；采掘技术管理、地质测量、抽采队伍等安全技术管理机构设置及专业技术管理人员配备情况。
** 管理制度及落实情况。以总工程师为首的技术管理体系建立及技术管理职责落实情况；主要负责人、实际控制人、分管负责人、安全生产管理人员、职能部门、各工种岗位安全生产责任制，以及安全生产目标管理、投入、奖惩、技术措施审批、培训、安全办公会议制度，安全检查制度，安全风险分级管控制度，隐患排查治理报告制度，矿级领导干部带班下井制度和作业规程、操作规程等制度制定和落实情况。
** “三项岗位人员”培训考核情况。主要负责人、安全生产管理人员、特种作业人员
* 矿井采掘部署情况
** 矿井开拓情况。开拓方式，水平划分，采区划分采，开采水平、现有生产水平，采煤工作面个数、实际生产工作面个数，掘进工作面个数、现在正在掘进工作面个数。
** 采掘接替情况。近3年采掘规划；2021年矿井产量，2022年原煤产量计划、采掘工作面布置及衔接、月度开掘进尺情况及各采掘工作面的相关参数，计划最深开采标高及深度；一、二、三、四季度生产作业计划。
** 建设矿井按一、二、三期工程建设情况。
** 矿井“三量”情况。上年度月末矿井开拓煤量、准备煤量、回采煤量、抽采达标煤量及可采期情况，上年度实际产量、剩余储量、服务年限等。
* 通风系统情况
** 主要通风机安装地点、型号、台数、配套电机功率，各回风井通风阻力及测定时间，主要通风机检测检验情况；矿井实际配风量。
* 瓦斯防治情况
** 瓦斯等级鉴定、测定情况。矿井瓦斯等级鉴定批复时间、机构；高瓦斯、突出矿井上年度测定和计算的矿井、采区瓦斯和二氧化碳涌出量情况。
** 低瓦斯矿井新水平、新采区测定煤层原始瓦斯含量和压力；高瓦斯、突出矿井采区垂深每增加50m测定煤层原始瓦斯含量和压力（提供瓦斯压力、含量测定台账）。
** 防突管理情况。矿井瓦斯治理机构设置及人员配备情况（包括抽采、防突机构相关人员的专业、学历、职称等情况），防突工、瓦斯抽采工（含钻孔施工人员）花名册；高瓦斯、突出矿井可采煤层瓦斯含量、瓦斯压力、瓦斯放散初速度、坚固性系数、破坏类型、透气性系数等参数。
** 突出矿井突出危险性敏感指标及临界值考察、使用情况，抽采半径、排放半径等考察时间、机构、结论、批复情况。
** 预计进行区域预测的地区或非突矿井煤层突出危险性鉴定情况。
** 两个“四位一体”情况。突出矿井坚持区域综合防突措施先行、局部综合防突措施补充原则开展防突工作情况；本年度区域防突措施规划和年度实施计划，矿井的开拓区、抽采区、保护层开采区和被保护层有效区配置情况；矿井、采区、工作面等两个“四位一体”防突设计和措施审批及落实情况；两个“四位一体”综合防突措施的实施全过程管理情况；开采保护层可行性论证情况，有保护层但未开采保护层经上级公司批复情况。
** 瓦斯抽采情况。矿井瓦斯抽放系统建设、使用情况，瓦斯抽放泵台数、能力、管路直径等参数，本年度抽采系统升级改造计划；瓦斯抽采监控系统监测情况及抽采计量安设（包括孔板流量计）情况；现采掘工作面的风量、回风瓦斯浓度、风排瓦斯量、抽采瓦斯量、抽采浓度、瓦斯抽采方法、抽采负压等；现采掘工作面瓦斯抽采设计、抽采达标评判情况；本年度计划抽采工程情况，包括抽采钻孔的施工量、计量方式等内容。
** “一矿一策、一面一策”情况。上年度12月末瓦斯抽采达标煤量情况；本年度瓦斯治理重点地区及治理工作安排情况；“一矿一策、一面一策”制定、审批情况；矿井瓦斯治理“五项指标”情况；石门揭煤计划及揭煤地区瓦斯、地质主要情况；以采掘衔接计划为基础，列出规定时间内完成“五项指标”保障正常衔接的地区、装备、人员、措施。
** 瓦斯管理不到位及责任追究情况。上年度开展瓦斯分析预警，瓦斯涌出异常或出现煤炮声、顶钻、夹钻、喷孔等动力现象，停止作业、撤出作业人员情况；瓦斯超限停电撤人、分析原因、停产整改和追究责任四项措施执行情况。
* 安全监控系统运行情况
** 监控系统型号、生产厂家、安全标志编号及有效期，各类传感器配备型号及数量。
** 甲烷等传感器设置地点，报警、断电、复电浓度和断电范围设置情况；安全监控设备调校、测试周期。
** 上年度系统报警、断电、馈电异常处置情况，矿长和总工程师审阅安全监控日报表，分析变化趋势情况。
** 安全监控系统管理机构设置及人员配备情况。
* 顶板管理情况
** 采掘工作面支护设计（过地质构造带、破碎带、应力集中区加强补充设计）及实施情况，根据采掘衔接计划，分析年度顶板管理困难的时间、地点及需要采取措施。
** 顶板离层仪等矿压观测情况。
* 矿井防治水情况
** 矿井水文地质类型报告编制时间，批复情况。
** 根据《煤矿防治水细则》建立健全各项防治水制度及水害防治岗位责任制情况。
** 矿井防治水机构设置及人员配备情况（包括人员的专业、学历、职称、毕业院校等，机构设立文件，专业技术人员花名册，探放水队伍设立文件及人员花名册），钻探、物探设备的配备情况，水文动态观测系统安设情况，矿井涌水量及排水系统配备情况。
** 年度矿井防治水技术路线与防治水计划。水文地质类型复杂、极复杂矿井编制“一矿一策、一面一策”防治水计划情况，主要包括：工作面概况，水害情况分析，水害治理工程及探放水工程量，施工工期，根据采掘计划列出采前评价预计时间、开采时间节点等。
** 井田范围内及周边区域水害致灾因素排查情况（详细列出排查出的各种水害情况）。
** 矿井防隔水设施的施工、设置及监测情况（包括受老空积水影响的密闭墙、挡水墙等位置、个数、变形情况）。
** 防隔水煤（岩）柱的留设及批复情况。
** 老空水、岩溶水排查治理情况。是否查明矿井及周边老空积水等情况，是否严格落实查全、探清、放净、验准的老空水防治“四步工作法”，是否采取水患区域积水线、警戒线、探水线、停采线等“四线”管理措施。
* 防灭火情况
** 高瓦斯、突出矿井煤层自燃倾向性鉴定情况（注明取样地点），防灭火系统建设及使用情况；消防供水系统设置情况。
** 采煤工作面结束后密闭墙构筑、气样采集及分析情况；采空区、巷道高冒区和煤柱破坏区预防自然发火措施情况；
** 井下电缆、皮带、高分子材料等阻燃性、抗静电性检测检验情况。
** 本年度井下电焊等动火情况。
* 机电运输情况
** 井下防爆电气设备的入井前检查、运行、维护、修理和定期检查体制机制。
** 斜巷运输40Kw以上调度绞车、卡轨车使用情况。
** 立井和倾斜井巷用于升降人员的提升系统、主要通风机、主排水泵、空压机、井下带式输送机等重要装备的各项保护设置及检修、检测检验和更换情况。
** 国家明令淘汰设备、工艺在用情况。
* 爆破管理情况
** 煤矿爆破工数量及管理情况，井下爆破作业制度执行情况；本年度井下预计需要爆破作业的地点情况。
* 应急处置救援情况
** 救护队建立或签订协议情况，日常救护人员到煤矿下井情况；对从业人员进行安全避险、自救互救和应急处置救援培训，组织应急演练情况；自救器是否符合矿井安全要求。
* 矿井劳动定员情况
** 本年度劳动用工情况。煤矿井下用工情况、区（科）设置及人员配备，工伤、养老保险缴纳情况。（本矿职工、劳务派遣工等用工情况，劳务派遣人员要说明劳务派遣公司、所属区队、主要作业地点）。
* 煤矿建设项目基本情况及进展情况
** 建设煤矿项目手续和建设、设计、施工、监理等单位资质情况；安全管理、项目部人员配备情况，人员、能力是否满足需求； 一、二、三期工程建设情况。批复工程量、开工时间、已施工工程、剩余工程量等。
** 主要通风机安装、双回路供电、防排水系统建设情况。
